-- Seed tourist Q&A articles from docs/tourist_qa_codex_prompt_2026_ru.md.

CREATE TEMP TABLE tourist_faq_categories_seed (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

INSERT INTO tourist_faq_categories_seed (id, slug, sort_order)
VALUES
    ('documents_visas_entry', 'documents-visas-entry', 10),
    ('airport_flights_baggage', 'airport-flights-baggage', 20),
    ('booking_accommodation', 'booking-accommodation', 30),
    ('money_cards_connectivity', 'money-cards-connectivity', 40),
    ('health_safety_insurance', 'health-safety-insurance', 50),
    ('local_transport', 'local-transport', 60),
    ('route_budget_planning', 'route-budget-planning', 70),
    ('local_rules_culture_special', 'local-rules-culture-special', 80);

CREATE TEMP TABLE tourist_faq_seed (
    id TEXT PRIMARY KEY,
    category_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    category_tag TEXT NOT NULL,
    title_ru TEXT NOT NULL,
    answer_ru TEXT NOT NULL,
    title_en TEXT NOT NULL,
    answer_en TEXT NOT NULL,
    title_kk TEXT NOT NULL,
    answer_kk TEXT NOT NULL
);

INSERT INTO tourist_faq_seed (
    id,
    category_id,
    slug,
    sort_order,
    category_tag,
    title_ru,
    answer_ru,
    title_en,
    answer_en,
    title_kk,
    answer_kk
)
VALUES
    ('tourist-faq-001', 'documents_visas_entry', 'tourist-faq-001', 1, 'documents', 'Какие документы нужны для поездки за границу?', 'Нужны паспорт, виза или электронное разрешение, если требуется, билеты, подтверждение проживания, страховка, иногда доказательство средств и обратный билет. Для Шенгена у не-граждан ЕС паспорт обычно должен быть выдан менее 10 лет назад и действовать минимум 3 месяца после планируемого выезда; пограничник также может попросить бронь жилья, приглашение, обратный билет и подтверждение средств.', 'What documents do I need for an international trip?', 'You usually need a passport, visa or electronic authorization if required, tickets, accommodation proof, insurance, and sometimes proof of funds and a return ticket. For Schengen, non-EU passports are usually expected to be under 10 years old and valid for at least 3 months after exit.', 'Шетелге сапарға қандай құжаттар керек?', 'Әдетте паспорт, қажет болса виза немесе электрондық рұқсат, билеттер, тұруды растау, сақтандыру және кейде қаражат пен қайту билеті керек. Шенген үшін ЕО азаматы емес паспорт көбіне 10 жылдан жаңа және шығудан кейін кемі 3 ай жарамды болуы тиіс.'),
    ('tourist-faq-002', 'documents_visas_entry', 'tourist-faq-002', 2, 'documents', 'Сколько должен действовать паспорт после поездки?', 'Универсального правила нет. Для Шенгенской зоны действует ориентир: паспорт не старше 10 лет и минимум 3 месяца после выезда; для США часто применяется правило 6 месяцев после планируемого выезда, но есть исключения по странам. Перед покупкой билета проверяйте именно требования страны назначения и транзита, а не только авиакомпании.', 'How long should my passport be valid after travel?', 'There is no single global rule. Schengen commonly requires a passport issued within the last 10 years and valid 3 months after exit; some destinations use a 6-month rule. Check destination and transit rules before buying tickets.', 'Паспорт сапардан кейін қанша уақыт жарамды болуы керек?', 'Бірдей әлемдік ереже жоқ. Шенгенде паспорт 10 жылдан жаңа және шығудан кейін 3 ай жарамды болуы керек, кей елдер 6 ай талап етеді. Билет алар алдында баратын және транзит елдерін тексеріңіз.'),
    ('tourist-faq-003', 'documents_visas_entry', 'tourist-faq-003', 3, 'documents', 'Как понять, нужна ли мне виза?', 'Проверяйте по паспорту, а не по месту проживания. Виза может требоваться из-за гражданства, цели поездки, срока пребывания, транзита, наличия пересадки с выходом из транзитной зоны или отдельных билетов. Самый надежный путь: официальный сайт правительства/консульства страны назначения плюс проверка требований у авиакомпании перед вылетом.', 'How do I know if I need a visa?', 'Check requirements by passport nationality, not residence. Visa rules depend on citizenship, purpose, stay length, transit, separate tickets, and whether you leave the transit zone. Use official government or consulate sites and confirm with the airline.', 'Маған виза керек пе екенін қалай білемін?', 'Талапты тұратын жеріңізге емес, паспорт азаматтығына қарай тексеріңіз. Виза азаматтыққа, мақсатқа, мерзімге, транзитке және бөлек билеттерге байланысты. Ресми үкімет/консулдық сайттарын және авиакомпанияны тексеріңіз.'),
    ('tourist-faq-004', 'documents_visas_entry', 'tourist-faq-004', 4, 'documents', 'Что такое ETA, eTA, ESTA, ETIAS и чем они отличаются от визы?', 'Это электронные разрешения или предварительные авторизации для краткосрочных поездок. Они не всегда являются визой и обычно не гарантируют въезд: окончательное решение принимает пограничная служба. Например, UK ETA стоит £20 и позволяет приезжать в Великобританию обычно до 6 месяцев, ESTA для США нужна участникам Visa Waiver Program, канадская eTA стоит CAN$7, а ETIAS для Европы должен начать работу в последнем квартале 2026 года.', 'What are ETA, eTA, ESTA and ETIAS?', 'They are electronic travel authorizations for short visits. They are not always visas and do not guarantee entry; border officers make the final decision. Fees, validity and launch dates can change, so check the official site before travel.', 'ETA, eTA, ESTA және ETIAS деген не?', 'Бұл қысқа сапарларға арналған электрондық рұқсаттар. Олар әрдайым виза емес және кіруге кепілдік бермейді; соңғы шешімді шекара қызметі қабылдайды. Баға мен мерзім өзгеруі мүмкін, ресми сайтты тексеріңіз.'),
    ('tourist-faq-005', 'documents_visas_entry', 'tourist-faq-005', 5, 'documents', 'Нужна ли страховка для въезда в страну?', 'Иногда да. Некоторые страны требуют туристическую страховку для визы или въезда, а другие настоятельно рекомендуют ее. Проверьте покрытие по датам, стране, экстренной помощи, госпитализации и медицинской эвакуации до подачи на визу или посадки на рейс.', 'Do I need travel insurance to enter a country?', 'Sometimes yes. Some destinations require insurance for visas or entry, and others strongly recommend it. Check medical coverage, dates, destination, emergency care and evacuation before applying for a visa or boarding.', 'Елге кіру үшін туристік сақтандыру керек пе?', 'Кейде керек. Кей елдер виза немесе кіру үшін сақтандыру талап етеді, ал басқалары қатты ұсынады. Визаға дейін медициналық лимитті, күндерді, елді, шұғыл көмек пен эвакуацияны тексеріңіз.'),
    ('tourist-faq-006', 'documents_visas_entry', 'tourist-faq-006', 6, 'documents', 'Как работает правило 90/180 дней в Шенгене?', 'Краткосрочное пребывание обычно ограничено 90 днями в любом скользящем периоде 180 дней. Это не “90 дней с 1 января”, а расчет назад от каждого дня нахождения в Шенгене. День въезда и день выезда считаются днями пребывания. Долгосрочные визы и виды на жительство считаются по другим правилам.', 'How does the Schengen 90/180-day rule work?', 'Short stays are usually limited to 90 days in any rolling 180-day period. It is not 90 days from January 1; count backwards from each day in Schengen. Entry and exit days count. Long-stay visas and residence permits follow different rules.', 'Шенгендегі 90/180 күн ережесі қалай жұмыс істейді?', 'Қысқа болу әдетте кез келген жылжымалы 180 күн ішінде 90 күнмен шектеледі. Бұл 1 қаңтардан бастап есептелмейді; Шенгендегі әр күннен артқа саналады. Кіру және шығу күндері де есептеледі.'),
    ('tourist-faq-007', 'documents_visas_entry', 'tourist-faq-007', 7, 'documents', 'Нужна ли транзитная виза при пересадке?', 'Иногда да, даже если вы не выходите из аэропорта. Риск выше при пересадке в США, Канаде, Великобритании, Шенгене, при смене аэропорта, ночевке, выходе за багажом или отдельных билетах. Проверяйте транзит по всем странам маршрута, включая обратный путь.', 'Do I need a transit visa for a connection?', 'Sometimes yes, even if you stay in the airport. Risk is higher with the US, Canada, UK, Schengen, airport changes, overnight connections, baggage reclaim, or separate tickets. Check every transit country, including the return route.', 'Ауысып мінуге транзиттік виза керек пе?', 'Кейде керек, әуежайдан шықпасаңыз да. АҚШ, Канада, Ұлыбритания, Шенген, әуежай ауыстыру, түндеу, багаж алу немесе бөлек билеттерде тәуекел жоғары. Қайтар жолды қоса барлық транзит елдерін тексеріңіз.'),
    ('tourist-faq-008', 'documents_visas_entry', 'tourist-faq-008', 8, 'documents', 'Могут ли на границе попросить обратный билет, бронь отеля и деньги?', 'Да. Даже при безвизовом въезде пограничник может спросить цель поездки, адрес проживания, обратный билет, страховку, приглашение и подтверждение средств. Держите эти документы офлайн в телефоне и, желательно, в распечатке.', 'Can border control ask for a return ticket, hotel booking and money?', 'Yes. Even visa-free travelers may be asked about purpose, address, return ticket, insurance, invitation, and funds. Keep documents offline on your phone and, when possible, printed.', 'Шекарада қайту билетін, қонақүйді және ақшаны сұрай ала ма?', 'Иә. Визасыз кірсеңіз де, сапар мақсатын, мекенжайды, қайту билетін, сақтандыруды, шақыруды және қаражатты сұрауы мүмкін. Құжаттарды телефонда офлайн және мүмкін болса қағазда сақтаңыз.'),
    ('tourist-faq-009', 'documents_visas_entry', 'tourist-faq-009', 9, 'documents', 'Что делать, если паспорт потерян за границей?', 'Сначала заблокируйте риски: сообщите в полицию, обратитесь в посольство или консульство своей страны, подготовьте фото, копию паспорта или другой ID, маршрут и данные билетов. Для многих стран посольство может выдать временный или emergency travel document для возвращения домой или продолжения маршрута с ограничениями. После официального заявления утерянный паспорт часто становится недействительным, даже если потом нашелся.', 'What should I do if I lose my passport abroad?', 'Report it to the police, contact your embassy or consulate, and prepare photos, passport copies or other ID, itinerary and ticket details. Many countries can issue an emergency travel document, but a reported lost passport may become invalid.', 'Шетелде паспорт жоғалса не істеу керек?', 'Полицияға хабарлаңыз, елшілікке немесе консулдыққа барыңыз, фото, паспорт көшірмесі, басқа ID, маршрут және билет деректерін дайындаңыз. Көп ел уақытша жол жүру құжатын бере алады, ал жоғалған деп тіркелген паспорт жарамсыз болуы мүмкін.'),
    ('tourist-faq-010', 'documents_visas_entry', 'tourist-faq-010', 10, 'documents', 'Что делать, если имя в билете отличается от паспорта?', 'Исправляйте до вылета. Имя, фамилия и порядок написания должны соответствовать паспорту настолько, насколько это требует авиакомпания и страна въезда. Небольшие опечатки иногда исправляют бесплатно, но смена пассажира почти всегда запрещена или стоит дорого.', 'What if the name on my ticket differs from my passport?', 'Fix it before departure. First name, last name and order should match the passport as required by the airline and destination. Small typos may be corrected, but changing the passenger is usually forbidden or expensive.', 'Билеттегі аты-жөнім паспорттан өзгеше болса не істеймін?', 'Ұшуға дейін түзетіңіз. Аты, тегі және жазылу тәртібі авиакомпания мен ел талабына сай паспортпен сәйкес болуы керек. Ұсақ қате кейде түзетіледі, ал жолаушыны ауыстыру көбіне болмайды немесе қымбат.'),
    ('tourist-faq-011', 'documents_visas_entry', 'tourist-faq-011', 11, 'documents', 'Какие документы нужны ребенку для поездки?', 'Ребенку обычно нужен собственный паспорт и, если требуется, виза или электронное разрешение. Если ребенок едет один, с одним родителем, с родственниками, тренером или группой, часто рекомендуют нотариальное согласие отсутствующего родителя/опекунов, иногда с переводом. ЕС, Канада и США советуют проверять такие документы заранее, потому что их могут запросить пограничники или авиакомпания.', 'What documents does a child need to travel?', 'A child usually needs their own passport and, if required, a visa or authorization. If traveling alone, with one parent, relatives or a group, a notarized consent with translation may be recommended or requested.', 'Баламен сапарға қандай құжаттар керек?', 'Балаға әдетте жеке паспорт және қажет болса виза немесе электрондық рұқсат керек. Жалғыз, бір ата-анамен, туыспен немесе топпен барса, нотариалды келісім мен аударма сұралуы мүмкін.'),
    ('tourist-faq-012', 'documents_visas_entry', 'tourist-faq-012', 12, 'documents', 'Можно ли путешествовать с двумя гражданствами?', 'Можно, но важно понимать, каким паспортом вы въезжаете и выезжаете. Некоторые страны требуют, чтобы их граждане въезжали именно по национальному паспорту. Для визы, авиабилета и пограничного контроля используйте согласованную комбинацию документов, чтобы не возникло расхождений в имени, гражданстве и сроках пребывания.', 'Can I travel with dual citizenship?', 'Yes, but plan which passport you use to enter and exit. Some countries require their citizens to use the national passport. Keep visa, ticket and border documents consistent to avoid mismatched name or nationality issues.', 'Екі азаматтықпен саяхаттауға бола ма?', 'Болады, бірақ қай паспортпен кіріп-шығатыныңызды алдын ала жоспарлаңыз. Кей елдер өз азаматтарынан ұлттық паспортты талап етеді. Виза, билет және шекара құжаттары бір-біріне сәйкес болсын.'),
    ('tourist-faq-013', 'documents_visas_entry', 'tourist-faq-013', 13, 'documents', 'Можно ли ехать, если паспорт скоро заканчивается?', 'Не стоит рисковать. Даже если авиакомпания посадит на рейс, страна назначения или транзита может отказать во въезде. Безопасный подход: обновить паспорт до покупки невозвратных билетов, если до окончания действия остается менее 6 месяцев.', 'Can I travel if my passport expires soon?', 'It is risky. Even if the airline lets you board, the destination or transit country may refuse entry. A safer approach is to renew before buying non-refundable tickets if less than 6 months remain.', 'Паспорт мерзімі жақында бітсе, сапарға шығуға бола ма?', 'Бұл тәуекелді. Авиакомпания отырғызса да, баратын немесе транзит елі кіргізбеуі мүмкін. 6 айдан аз қалса, қайтарылмайтын билет алмай тұрып паспортты жаңарту қауіпсіз.'),
    ('tourist-faq-014', 'documents_visas_entry', 'tourist-faq-014', 14, 'documents', 'Можно ли брать с собой лекарства?', 'Да, но держите их в ручной клади, в оригинальной упаковке, с рецептом или справкой врача, особенно если это контролируемые препараты, инъекции, психостимуляторы, снотворные или сильные обезболивающие. Некоторые обычные дома лекарства могут быть запрещены за рубежом, поэтому проверяйте правила страны назначения через официальные источники.', 'Can I take medicines with me?', 'Yes, but keep them in carry-on luggage, original packaging, with a prescription or doctor letter, especially for controlled drugs, injections, stimulants, sleeping pills or strong painkillers. Check destination rules before travel.', 'Дәрілерді алып жүруге бола ма?', 'Иә, бірақ оларды қол жүгінде, түпнұсқа қаптамада, рецептпен немесе дәрігер анықтамасымен ұстаңыз. Бақыланатын препараттар, инъекциялар және күшті дәрілер үшін ел ережесін алдын ала тексеріңіз.'),
    ('tourist-faq-015', 'documents_visas_entry', 'tourist-faq-015', 15, 'documents', 'Что делать, если раньше был отказ в визе или проблемы с законом?', 'Не скрывайте это в анкетах. Многие страны считают ложные сведения более серьезным нарушением, чем сам старый отказ. Подготовьте объяснение, документы, подтверждающие изменения обстоятельств, и при сложной истории обратитесь к профильному визовому специалисту или юристу.', 'What if I had a visa refusal or legal issue before?', 'Do not hide it in applications. False information can be more serious than the old refusal. Prepare an explanation and supporting documents; for complex histories, consult a qualified visa specialist or lawyer.', 'Бұрын виза бас тартуы немесе заң мәселесі болса не істеу керек?', 'Анкетада жасырмаңыз. Жалған ақпарат ескі бас тартудан да ауыр болуы мүмкін. Түсіндірме мен дәлел құжаттарын дайындаңыз, күрделі жағдайда визалық маманға немесе заңгерге жүгініңіз.'),
    ('tourist-faq-016', 'documents_visas_entry', 'tourist-faq-016', 16, 'documents', 'Какие популярные электронные разрешения актуальны на 2026 год?', 'Для Великобритании многим путешественникам нужна UK ETA, стоимость £20; для США по Visa Waiver Program нужна ESTA; для Канады официальная eTA стоит CAN$7; для Австралии ETA оформляется через приложение с сервисным сбором AUD20; для Новой Зеландии NZeTA обычно действует 2 года для путешественников.', 'Which common electronic authorizations are relevant in 2026?', 'Common examples include UK ETA, US ESTA for Visa Waiver travelers, Canada eTA, Australia ETA, and New Zealand NZeTA. Fees and validity can change, so always use official sites before applying.', '2026 жылы қандай электрондық рұқсаттар жиі кездеседі?', 'Жиі кездесетіндері: UK ETA, АҚШ ESTA, Канада eTA, Австралия ETA және Жаңа Зеландия NZeTA. Баға мен жарамдылық өзгеруі мүмкін, өтініш берер алдында ресми сайтты пайдаланыңыз.'),
    ('tourist-faq-017', 'documents_visas_entry', 'tourist-faq-017', 17, 'documents', 'Если виза или ETA одобрена, въезд гарантирован?', 'Нет. Виза или электронное разрешение позволяют прибыть к границе, но пограничник может отказать, если цель поездки неясна, документы противоречат друг другу, недостаточно средств, нарушены сроки пребывания или есть иммиграционные риски.', 'Does an approved visa or ETA guarantee entry?', 'No. A visa or authorization lets you travel to the border, but entry can still be refused if the purpose is unclear, documents conflict, funds are insufficient, stay limits were broken, or immigration risks exist.', 'Виза немесе ETA мақұлданса, кіру кепілдене ме?', 'Жоқ. Виза немесе рұқсат шекараға келуге мүмкіндік береді, бірақ мақсат түсініксіз, құжаттар сәйкес емес, қаражат жеткіліксіз немесе мерзім бұзылған болса, кіргізбеуі мүмкін.'),
    ('tourist-faq-018', 'documents_visas_entry', 'tourist-faq-018', 18, 'documents', 'Нужно ли ждать очередей из-за биометрии и электронных ворот?', 'Да, особенно на первых поездках после запуска новых систем. В Шенгене EES собирает данные въезда/выезда и биометрию для краткосрочных поездок не-граждан ЕС, поэтому закладывайте дополнительное время на паспортный контроль.', 'Should I expect queues because of biometrics and e-gates?', 'Yes, especially when new systems launch or on first trips. Schengen EES records entry/exit and biometrics for short-stay non-EU travelers, so allow extra time at passport control.', 'Биометрия мен электрондық қақпалардан кезек болуы мүмкін бе?', 'Иә, әсіресе жаңа жүйелер іске қосылғанда немесе алғашқы сапарда. Шенген EES қысқа мерзімді ЕО емес саяхатшылардың кіру/шығуын және биометриясын тіркейді, сондықтан паспорт бақылауына қосымша уақыт қалдырыңыз.'),
    ('tourist-faq-019', 'airport_flights_baggage', 'tourist-faq-019', 19, 'flights', 'За сколько приезжать в аэропорт?', 'Практичный ориентир: за 2 часа до внутреннего рейса и за 3 часа до международного. Добавляйте время, если у вас багаж, дети, животное, визовая проверка, спецпомощь, пик сезона, новый аэропорт или страна с дополнительным пограничным контролем.', 'How early should I arrive at the airport?', 'A practical guide is 2 hours before domestic flights and 3 hours before international flights. Add time for baggage, children, pets, visa checks, special assistance, peak season or unfamiliar airports.', 'Әуежайға қанша ерте бару керек?', 'Ішкі рейске шамамен 2 сағат, халықаралық рейске 3 сағат бұрын барған дұрыс. Багаж, балалар, жануар, виза тексеруі, арнайы көмек, маусым қызуы немесе жаңа әуежай болса, қосымша уақыт қосыңыз.'),
    ('tourist-faq-020', 'airport_flights_baggage', 'tourist-faq-020', 20, 'flights', 'Нужно ли делать онлайн-регистрацию?', 'Да, если она доступна. Онлайн-регистрация снижает риск проблем с местами и очередями, а у лоукостеров регистрация в аэропорту может быть платной. Но если требуется проверка визы, паспорта, медицинских документов или разрешения на въезд, авиакомпания может направить вас на стойку.', 'Should I check in online?', 'Yes, when available. Online check-in reduces queues and seat issues, and low-cost airlines may charge for airport check-in. If documents need verification, the airline can still send you to the counter.', 'Онлайн тіркелу керек пе?', 'Иә, қолжетімді болса. Онлайн тіркелу кезек пен орын мәселесін азайтады, ал лоукостерлер әуежайда тіркелуге ақы алуы мүмкін. Құжат тексерілсе, бәрібір стойкаға жіберуі мүмкін.'),
    ('tourist-faq-021', 'airport_flights_baggage', 'tourist-faq-021', 21, 'flights', 'Достаточно ли посадочного талона в телефоне?', 'Чаще всего да, но сохраните его офлайн: в Wallet, PDF и скриншотом. В некоторых аэропортах, при визовой проверке или у отдельных авиакомпаний могут попросить распечатку. Для сложных маршрутов лучше иметь бумажную копию.', 'Is a boarding pass on my phone enough?', 'Usually yes, but save it offline in Wallet, PDF and screenshot. Some airports, visa checks or airlines may require a printed copy. For complex routes, keep paper copies too.', 'Телефондағы отырғызу талоны жеткілікті ме?', 'Көбіне жеткілікті, бірақ оны Wallet, PDF және скриншот ретінде офлайн сақтаңыз. Кей әуежай, виза тексеруі немесе авиакомпания қағаз нұсқаны сұрауы мүмкін.'),
    ('tourist-faq-022', 'airport_flights_baggage', 'tourist-faq-022', 22, 'flights', 'Какие жидкости можно брать в ручную кладь?', 'Стандартное международное правило: жидкости, гели и аэрозоли — в емкостях до 100 мл / 3.4 oz, обычно в одном прозрачном пакете. В некоторых аэропортах новые сканеры позволяют больше, но рассчитывать на это нельзя: при пересадке правила могут снова стать стандартными.', 'What liquids can I take in carry-on luggage?', 'The standard rule is liquids, gels and aerosols in containers up to 100 ml / 3.4 oz, usually in one clear bag. Some airports allow more with new scanners, but transfers may apply standard rules again.', 'Қол жүгінде қандай сұйықтық алуға болады?', 'Стандарт ереже: сұйықтық, гель және аэрозоль 100 мл-ге дейінгі ыдыста, әдетте бір мөлдір пакетте. Кей әуежайда жаңа сканерлер көбірек рұқсат етеді, бірақ транзитте стандарт ереже қайта қолданылуы мүмкін.'),
    ('tourist-faq-023', 'airport_flights_baggage', 'tourist-faq-023', 23, 'flights', 'Можно ли брать power bank в самолет?', 'Да, но только в ручную кладь, не в зарегистрированный багаж. Обычные power bank до 100 Wh обычно разрешены; аккумуляторы 101–160 Wh требуют одобрения авиакомпании и ограничены количеством. Контакты батарей должны быть защищены от короткого замыкания.', 'Can I take a power bank on a plane?', 'Yes, but only in carry-on luggage. Most power banks up to 100 Wh are allowed; 101-160 Wh batteries need airline approval and are limited. Protect battery terminals from short circuits.', 'Power bank ұшаққа алуға бола ма?', 'Иә, бірақ тек қол жүгіне. 100 Wh дейінгі power bank көбіне рұқсат, 101-160 Wh үшін авиакомпания мақұлдауы керек және саны шектеулі. Контактілерін қысқа тұйықталудан қорғаңыз.'),
    ('tourist-faq-024', 'airport_flights_baggage', 'tourist-faq-024', 24, 'flights', 'Что делать со “smart luggage” с батареей?', 'Если чемодан сдается в багаж, литиевую батарею обычно нужно снять и взять в салон. Багаж с несъемной батареей выше малых порогов может быть запрещен к перевозке. Перед покупкой smart-чемодана проверьте, съемная ли батарея.', 'What should I do with smart luggage batteries?', 'If checking smart luggage, the lithium battery usually must be removed and carried in the cabin. Bags with non-removable batteries may be refused. Check whether the battery is removable before buying or flying.', 'Батареясы бар smart-чемоданмен не істеу керек?', 'Егер чемоданды багажға тапсырсаңыз, литий батареясын әдетте шығарып, салонға алу керек. Алынбайтын батареясы бар чемодан қабылданбауы мүмкін. Ұшар алдында батарея алынатынын тексеріңіз.'),
    ('tourist-faq-025', 'airport_flights_baggage', 'tourist-faq-025', 25, 'flights', 'Как провозить лекарства, шприцы и медицинские приборы?', 'Берите жизненно важные лекарства и приборы только в ручную кладь. Держите рецепт, справку врача, оригинальную упаковку и запас на несколько дней сверх поездки. Если препарат нужно охлаждать, заранее уточните правила по хладоэлементам и хранению в полете.', 'How do I carry medicines, syringes and medical devices?', 'Carry essential medicines and devices in hand luggage. Keep prescriptions, a doctor letter, original packaging and extra supply. If medicine must stay cold, check rules for ice packs and in-flight storage.', 'Дәрі, шприц және медициналық құрылғыны қалай алып жүремін?', 'Маңызды дәрі мен құрылғыны қол жүгінде ұстаңыз. Рецепт, дәрігер анықтамасы, түпнұсқа қаптама және қосымша қор алыңыз. Салқын сақтау керек болса, хладоэлемент пен ұшақтағы сақтау ережесін тексеріңіз.'),
    ('tourist-faq-026', 'airport_flights_baggage', 'tourist-faq-026', 26, 'flights', 'Можно ли брать еду в ручную кладь?', 'Твердую еду часто можно, но пасты, соусы, йогурты, мед, варенье, супы и мягкие продукты могут считаться жидкостями. Главная проблема обычно не досмотр, а таможня в стране прибытия: мясо, молочные продукты, растения, семена и фрукты часто ограничены или запрещены.', 'Can I take food in carry-on luggage?', 'Solid food is often allowed, but pastes, sauces, yogurt, honey, jam, soups and soft foods may count as liquids. Customs rules at arrival are usually stricter for meat, dairy, plants, seeds and fruit.', 'Қол жүгінде тамақ алуға бола ма?', 'Қатты тағам жиі рұқсат, бірақ паста, соус, йогурт, бал, тосап, сорпа және жұмсақ өнімдер сұйықтық саналуы мүмкін. Келген елдің кедені ет, сүт, өсімдік, тұқым және жеміске қатаң болуы мүмкін.'),
    ('tourist-faq-027', 'airport_flights_baggage', 'tourist-faq-027', 27, 'flights', 'Как понять, пройдет ли моя ручная кладь по размеру?', 'Смотрите правила конкретной авиакомпании и тарифа, а не “средний размер”. Учитывайте колеса, ручки и внешние карманы. Лоукостеры часто различают personal item под сиденье и полноценную cabin bag — это разные нормы.', 'How do I know if my carry-on size is allowed?', 'Check your airline and fare rules, not an average size. Include wheels, handles and outer pockets. Low-cost airlines often separate a small personal item from a full cabin bag.', 'Қол жүгімнің өлшемі өтетінін қалай білемін?', 'Орташа өлшемге емес, нақты авиакомпания мен тариф ережесіне қараңыз. Дөңгелек, тұтқа және сыртқы қалталарды есептеңіз. Лоукостерлер жеке зат пен толық cabin bag-ті бөлек қарастырады.'),
    ('tourist-faq-028', 'airport_flights_baggage', 'tourist-faq-028', 28, 'flights', 'Что нельзя класть в зарегистрированный багаж?', 'Не кладите паспорта, деньги, банковские карты, лекарства, ноутбуки, ценные вещи, ключи, power bank, запасные литиевые батареи и документы. Зарегистрированный багаж может задержаться, вскрыться или потеряться, а компенсация почти всегда ограничена.', 'What should I never put in checked baggage?', 'Do not pack passports, money, bank cards, medicines, laptops, valuables, keys, power banks, spare lithium batteries or important documents. Checked baggage can be delayed, opened or lost, and compensation is limited.', 'Тіркелген багажға нені салмау керек?', 'Паспорт, ақша, карта, дәрі, ноутбук, құнды зат, кілт, power bank, қосымша литий батарея және маңызды құжаттарды салмаңыз. Багаж кешігуі, ашылуы немесе жоғалуы мүмкін, өтемақы шектеулі.'),
    ('tourist-faq-029', 'airport_flights_baggage', 'tourist-faq-029', 29, 'flights', 'Сколько времени закладывать на пересадку?', 'На одном билете безопаснее, потому что авиакомпания отвечает за стыковку. Для международных пересадок с паспортным контролем и повторным досмотром лучше закладывать 2–3 часа и больше. На отдельных билетах берите большой запас, потому что при опоздании первого рейса второй перевозчик может считать вас no-show.', 'How much time should I allow for a connection?', 'One ticket is safer because the airline handles missed connections. For international transfers with passport control and security, allow 2-3 hours or more. With separate tickets, leave a large buffer or overnight.', 'Ауысып мінуге қанша уақыт қалдыру керек?', 'Бір билет қауіпсіз, себебі стыковкаға авиакомпания жауап береді. Халықаралық паспорт бақылауы мен қайта тексеру болса, 2-3 сағат немесе одан көп қалдырыңыз. Бөлек билеттерде үлкен запас немесе түндеу керек.'),
    ('tourist-faq-030', 'airport_flights_baggage', 'tourist-faq-030', 30, 'flights', 'Можно ли провозить duty free жидкости через пересадку?', 'Можно, если они упакованы в специальный запечатанный пакет с чеком, но пересадочный аэропорт может применить свои правила. Не вскрывайте пакет до конечного пункта и учитывайте, что на отдельных билетах или при повторном досмотре покупку могут изъять.', 'Can duty-free liquids pass through a connection?', 'Yes if sealed in a security bag with receipt, but transfer airports may apply their own rules. Do not open the bag before the final destination; with separate tickets or re-screening, items may be taken away.', 'Duty free сұйықтығын транзиттен өткізуге бола ма?', 'Чекпен арнайы мөрленген пакетте болса болады, бірақ транзит әуежайы өз ережесін қолдануы мүмкін. Соңғы пунктке дейін ашпаңыз; бөлек билеттерде немесе қайта тексеруде алып қоюы мүмкін.'),
    ('tourist-faq-031', 'airport_flights_baggage', 'tourist-faq-031', 31, 'flights', 'Что делать при задержке или отмене рейса?', 'Сразу зафиксируйте время уведомления, причину задержки, фактическое время прибытия, посадочные талоны, чеки на питание/отель/транспорт и переписку. Попросите у авиакомпании письменное подтверждение причины. Не соглашайтесь на ваучер, если хотите денежный возврат и закон дает такое право.', 'What should I do if my flight is delayed or cancelled?', 'Record notification time, reason, actual arrival time, boarding passes, receipts for food/hotel/transport and messages. Ask the airline for written confirmation of the reason. Avoid accepting vouchers if you want a cash refund and the law allows it.', 'Рейс кешіксе немесе тоқтатылса не істеу керек?', 'Хабарлау уақытын, себебін, нақты келу уақытын, отырғызу талондарын, тамақ/қонақүй/көлік чектерін және хаттарды сақтаңыз. Себепті жазбаша сұраңыз. Ақшалай қайтарым қажет болса, ваучерге бірден келіспеңіз.'),
    ('tourist-faq-032', 'airport_flights_baggage', 'tourist-faq-032', 32, 'flights', 'Когда положена компенсация в Европе?', 'Правила ЕС применяются к рейсам внутри ЕС, рейсам из ЕС и к рейсам в ЕС, если их выполняет авиакомпания ЕС. При отмене менее чем за 14 дней, отказе в посадке из-за овербукинга или прибытии с задержкой 3+ часа может быть компенсация 250/400/600 евро в зависимости от расстояния, если причина не относится к исключительным обстоятельствам.', 'When is compensation due in Europe?', 'EU rules cover flights inside the EU, from the EU, and into the EU on EU airlines. Cancellation less than 14 days before departure, denied boarding or arrival delay of 3+ hours may give compensation of 250/400/600 euros unless extraordinary circumstances apply.', 'Еуропада қай кезде өтемақы беріледі?', 'ЕО ережелері ЕО ішіндегі, ЕО-дан шығатын және ЕО әуе компаниясымен ЕО-ға келетін рейстерге қолданылады. 14 күннен аз уақытта тоқтату, овербукинг немесе 3+ сағат кешігу 250/400/600 евро өтемақы беруі мүмкін.'),
    ('tourist-faq-033', 'airport_flights_baggage', 'tourist-faq-033', 33, 'flights', 'Что положено при отмене или сильном изменении рейса в США?', 'Если авиакомпания отменяет или существенно меняет рейс, пассажир имеет право на возврат, если не принимает предложенную альтернативу. В США компенсация за задержку не всегда автоматическая, но возврат за неиспользованный билет и некоторые сборы регулируется отдельно.', 'What is due for cancellation or major schedule changes in the US?', 'If an airline cancels or significantly changes a flight, passengers can get a refund if they do not accept the alternative. Delay compensation is not always automatic, but unused tickets and some fees have separate refund rules.', 'АҚШ-та рейс тоқтаса немесе қатты өзгерсе не беріледі?', 'Авиакомпания рейсті тоқтатса немесе айтарлықтай өзгертсе, ұсынылған баламаны қабылдамасаңыз, қайтарым алуға болады. Кешігу өтемақысы әрдайым автоматты емес, бірақ пайдаланылмаған билет пен кей алымдар бөлек реттеледі.'),
    ('tourist-faq-034', 'airport_flights_baggage', 'tourist-faq-034', 34, 'flights', 'Что делать при овербукинге?', 'Если просят добровольцев, соглашайтесь только после того, как понятны сумма, форма компенсации, новый рейс, питание, отель и срок действия ваучера. Если вас сняли с рейса принудительно, требуйте письменное подтверждение отказа в посадке и проверяйте правила компенсации по стране вылета и перевозчику.', 'What should I do in an overbooking situation?', 'If volunteers are requested, agree only after you understand compensation amount, form, new flight, meals, hotel and voucher validity. If denied boarding involuntarily, ask for written confirmation and check compensation rules.', 'Овербукинг болса не істеу керек?', 'Еріктілер сұралса, өтемақы сомасы, түрі, жаңа рейс, тамақ, қонақүй және ваучер мерзімі анық болғанда ғана келісіңіз. Мәжбүрлі түсірсе, жазбаша растау сұрап, өтемақы ережесін тексеріңіз.'),
    ('tourist-faq-035', 'airport_flights_baggage', 'tourist-faq-035', 35, 'flights', 'Кто отвечает, если я опоздал на стыковку?', 'Если все сегменты в одном билете и опоздание вызвано задержкой авиакомпании, перевозчик обычно должен перебронировать вас. Если билеты отдельные, риск почти всегда на пассажире: второй перевозчик может не пересадить бесплатно. Для отдельных билетов нужен запас, иногда ночевка между рейсами.', 'Who is responsible if I miss a connection?', 'If all segments are on one ticket and the airline delay caused the miss, the carrier usually rebooks you. With separate tickets, the risk is usually yours and the second carrier may mark you no-show.', 'Стыковкаға үлгермесем кім жауапты?', 'Барлық сегмент бір билетте болса және кешігу авиакомпаниядан болса, тасымалдаушы әдетте қайта брондайды. Билеттер бөлек болса, тәуекел көбіне жолаушыда, екінші тасымалдаушы no-show деп санауы мүмкін.'),
    ('tourist-faq-036', 'airport_flights_baggage', 'tourist-faq-036', 36, 'flights', 'Что делать, если багаж потеряли или задержали?', 'Оформите PIR / baggage irregularity report до выхода из зоны прилета, сохраните номер дела, багажную бирку и чеки на необходимые покупки. По Монреальской конвенции лимит ответственности за багаж с 28 декабря 2024 года составляет 1,519 SDR; в США лимит по внутренним рейсам указан DOT как $4,700 на пассажира. Для международных рейсов важно соблюдать сроки претензий, особенно 7 дней для повреждения и 21 день для задержки багажа после получения.', 'What should I do if baggage is lost or delayed?', 'File a PIR or baggage irregularity report before leaving arrivals, keep the case number, bag tag and receipts for essential purchases. International and domestic liability limits and claim deadlines apply, so act quickly.', 'Багаж жоғалса немесе кешіксе не істеу керек?', 'Келу аймағынан шықпай тұрып PIR/baggage report толтырыңыз, іс нөмірін, багаж биркасын және қажет заттар чектерін сақтаңыз. Халықаралық және ішкі лимиттер мен шағым мерзімдері бар, тез әрекет етіңіз.'),
    ('tourist-faq-037', 'airport_flights_baggage', 'tourist-faq-037', 37, 'flights', 'Можно ли лететь с животным?', 'Можно не всегда. У авиакомпаний разные правила по весу, переноске, породам, салону/багажному отсеку и сезонам. Страна назначения может требовать микрочип, прививки, титры антител, ветеринарный сертификат и импортное разрешение. Бронируйте место для животного до покупки невозвратных билетов.', 'Can I fly with a pet?', 'Not always. Airlines differ by weight, carrier, breed, cabin/hold and season. The destination may require microchip, vaccines, antibody titers, veterinary certificate or import permit. Reserve pet space before non-refundable tickets.', 'Жануармен ұшуға бола ма?', 'Әрдайым емес. Авиакомпаниялар салмақ, тасымалдағыш, тұқым, салон/багаж және маусым бойынша ерекшеленеді. Ел микрочип, вакцина, титр, ветеринарлық сертификат немесе импорт рұқсатын талап етуі мүмкін.'),
    ('tourist-faq-038', 'booking_accommodation', 'tourist-faq-038', 38, 'accommodation', 'Как выбрать безопасный отель или апартаменты?', 'Проверяйте свежие отзывы, реальные фото, точный адрес, район, правила отмены, включенные сборы и способ связи. У апартаментов особенно важны отзывы за последние 6–12 месяцев и отсутствие просьб уйти из официального канала бронирования.', 'How do I choose a safe hotel or apartment?', 'Check recent reviews, real photos, exact address, neighborhood, cancellation rules, included fees and official contact method. For apartments, reviews from the last 6-12 months and staying inside the booking platform matter.', 'Қауіпсіз қонақүй немесе пәтерді қалай таңдаймын?', 'Жаңа пікірлерді, нақты фотоларды, мекенжайды, ауданын, бас тарту шартын, қосылған алымдарды және ресми байланыс жолын тексеріңіз. Пәтерде соңғы 6-12 ай пікірлері және платформадан шықпау маңызды.'),
    ('tourist-faq-039', 'booking_accommodation', 'tourist-faq-039', 39, 'accommodation', 'Как распознать мошенническое жилье?', 'Красные флаги: цена сильно ниже рынка, “роскошная вилла” без проверяемых отзывов, давление “платите сейчас”, просьба перевести деньги вне платформы, оплата gift card, crypto, wire transfer или платежным приложением, размытый адрес и отказ дать договор/условия. FTC выделяет такие признаки как типичные для travel scams.', 'How can I spot a fake accommodation listing?', 'Red flags include a price far below market, luxury photos without verified reviews, pressure to pay now, requests to pay outside the platform, gift cards, crypto, wire transfer, vague address or no written terms.', 'Жалған тұрғын үйді қалай тануға болады?', 'Белгілері: нарықтан тым төмен баға, пікірсіз “люкс” фото, “қазір төлеңіз” қысымы, платформадан тыс төлем, gift card, crypto, wire transfer, анық емес мекенжай немесе шарт бермеу.'),
    ('tourist-faq-040', 'booking_accommodation', 'tourist-faq-040', 40, 'accommodation', 'Мне пришло сообщение от отеля с просьбой заново ввести карту. Это нормально?', 'Относитесь как к потенциальному фишингу. Booking.com предупреждает, что мошенники могут присылать сообщения с деталями бронирования и срочными просьбами оплатить или ввести карту; платформа не просит данные карты по email, телефону, SMS или WhatsApp и не просит перевод на другой счет, отличный от подтверждения бронирования.', 'A hotel message asks me to re-enter card details. Is that normal?', 'Treat it as possible phishing. Fraudsters may send booking details and urgent payment links. Do not enter card data through email, SMS, phone or messengers unless it is clearly inside the official booking flow.', 'Қонақүй карта дерегін қайта енгізуді сұрады. Бұл қалыпты ма?', 'Мұны фишинг болуы мүмкін деп қараңыз. Алаяқтар бронь деректерімен шұғыл төлем сілтемесін жібереді. Ресми брондау ағыны екені анық болмаса, email, SMS, телефон немесе мессенджер арқылы карта енгізбеңіз.'),
    ('tourist-faq-041', 'booking_accommodation', 'tourist-faq-041', 41, 'accommodation', 'Что такое депозит в отеле?', 'Это сумма, которую отель блокирует или списывает на случай ущерба, мини-бара, штрафов или неоплаченных услуг. Уточняйте: это pre-authorization или реальное списание, когда разблокируют деньги, в какой валюте и какие условия возврата. Для депозитов кредитная карта часто удобнее дебетовой.', 'What is a hotel deposit?', 'It is an amount blocked or charged for possible damage, minibar, fines or unpaid services. Ask whether it is a pre-authorization or real charge, when it is released, in which currency, and refund conditions.', 'Қонақүй депозиті деген не?', 'Бұл залал, мини-бар, айыппұл немесе төленбеген қызмет үшін бұғатталатын немесе алынатын сома. Pre-authorization ма, нақты списание ма, қашан босатылады, қай валютада және қайтару шарты қандай екенін сұраңыз.'),
    ('tourist-faq-042', 'booking_accommodation', 'tourist-faq-042', 42, 'accommodation', 'Почему цена на сайте одна, а при оплате выше?', 'К цене могут добавляться налоги, resort fee, city tax, cleaning fee, service fee и сборы платформы.', 'Why is the final price higher than the site price?', 'Taxes, resort fees, city taxes, cleaning fees, service fees and platform fees may be added. Always check the final payment screen and booking confirmation, not only the first displayed price.', 'Неге сайттағы баға мен төлем бағасы әртүрлі?', 'Салық, resort fee, city tax, cleaning fee, service fee және платформа алымдары қосылуы мүмкін. Алғашқы бағаға ғана емес, соңғы төлем экраны мен бронь растауына қараңыз.'),
    ('tourist-faq-043', 'booking_accommodation', 'tourist-faq-043', 43, 'accommodation', 'Как читать условия отмены бронирования?', 'Смотрите не только “free cancellation”, а дату и час отмены, часовой пояс, штраф, условия no-show и разницу между “refundable” и “pay at property”. Сделайте скриншот условий на момент бронирования. Невозвратные тарифы обычно дешевле, но страховка покрывает отмену только по прописанным причинам.', 'How should I read cancellation rules?', 'Look beyond “free cancellation”: check date and time, time zone, penalty, no-show terms, and refundable vs pay-at-property differences. Screenshot the rules when booking. Insurance covers cancellation only for listed reasons.', 'Броньды бас тарту шартын қалай оқу керек?', '“Free cancellation” сөзімен шектелмеңіз: күн/сағат, уақыт белдеуі, айыппұл, no-show және refundable/pay at property айырмасын тексеріңіз. Бронь кезіндегі шартты скриншот жасаңыз.'),
    ('tourist-faq-044', 'booking_accommodation', 'tourist-faq-044', 44, 'accommodation', 'Что делать, если отель не заселяет или бронирования нет?', 'Попросите письменное подтверждение отказа, не отменяйте бронирование самостоятельно, свяжитесь с платформой и требуйте эквивалентное или лучшее размещение. Сохраняйте чеки на транспорт, связь и вынужденное новое жилье.', 'What if the hotel refuses check-in or has no booking?', 'Ask for written confirmation, do not cancel the booking yourself, contact the platform and request equivalent or better accommodation. Keep receipts for transport, calls and forced new lodging.', 'Қонақүй кіргізбесе немесе бронь жоқ десе не істеу керек?', 'Жазбаша растау сұраңыз, броньды өзіңіз жоймаңыз, платформамен байланысып, баламалы немесе жақсырақ орналастыруды талап етіңіз. Көлік, байланыс және жаңа тұрғын үй чектерін сақтаңыз.'),
    ('tourist-faq-045', 'booking_accommodation', 'tourist-faq-045', 45, 'accommodation', 'Можно ли отдавать паспорт на ресепшене?', 'Во многих странах отель обязан записать паспортные данные или сделать копию. Но оставлять оригинал “на весь срок” небезопасно, если это не требуется законом. Попросите вернуть документ сразу после регистрации или дать расписку, если его временно удерживают.', 'Can reception keep my passport?', 'Many countries require hotels to record passport details or copy it, but keeping the original for the whole stay is unsafe unless legally required. Ask for it back after registration or request a receipt.', 'Ресепшенге паспортты қалдыруға бола ма?', 'Көп елде қонақүй паспорт дерегін жазуы немесе көшіруі керек, бірақ түпнұсқаны бүкіл мерзімге қалдыру қауіпсіз емес, заң талап етпесе. Тіркеуден кейін қайтаруды немесе қолхат беруді сұраңыз.'),
    ('tourist-faq-046', 'booking_accommodation', 'tourist-faq-046', 46, 'accommodation', 'Где хранить паспорт, деньги и ценности в отеле?', 'Не держите все в одном месте. Паспорт, резервную карту и часть наличных лучше хранить отдельно от повседневного кошелька. Цифровые копии документов сохраните в защищенном облаке и офлайн, но не заменяйте ими оригиналы.', 'Where should I keep passport, money and valuables in a hotel?', 'Do not keep everything in one place. Store passport, backup card and some cash separately from your daily wallet. Keep protected digital copies online and offline, but they do not replace originals.', 'Қонақүйде паспорт, ақша және құнды заттарды қайда сақтаймын?', 'Барлығын бір жерде ұстамаңыз. Паспортты, резерв картаны және қолма-қол ақшаның бір бөлігін күнделікті әмияннан бөлек сақтаңыз. Құжат көшірмелерін қорғалған бұлтта және офлайн ұстаңыз.'),
    ('tourist-faq-047', 'booking_accommodation', 'tourist-faq-047', 47, 'accommodation', 'Что делать, если номер плохой: грязно, шумно, не работает кондиционер?', 'Сообщайте сразу, а не после выезда. Сделайте фото/видео, попросите исправить, переселить или оформить частичный возврат. Чем раньше зафиксирована проблема, тем выше шанс на решение через отель, платформу или банк.', 'What if the room is dirty, noisy or something does not work?', 'Report it immediately, not after checkout. Take photos or video, ask for repair, relocation or partial refund. The earlier the issue is documented, the better the chance of a solution.', 'Нөмір лас, шу немесе кондиционер істемесе не істеу керек?', 'Шыққаннан кейін емес, бірден хабарлаңыз. Фото/видео түсіріп, жөндеу, басқа нөмір немесе ішінара қайтарым сұраңыз. Мәселе ерте тіркелсе, шешілу мүмкіндігі жоғары.'),
    ('tourist-faq-048', 'money_cards_connectivity', 'tourist-faq-048', 48, 'money', 'Что лучше брать: карту или наличные?', 'Оптимально — две банковские карты разных платежных систем плюс небольшая сумма наличных. Одну карту держите отдельно как резерв. Для поездки включите уведомления банка, проверьте лимиты, PIN, возможность снятия наличных и доступ к приложению за рубежом.', 'Should I take cards or cash?', 'Best practice is two bank cards from different networks plus a small amount of cash. Keep one card separate as backup. Before travel, check notifications, limits, PIN, cash withdrawal and app access abroad.', 'Карта ма, қолма-қол ақша ма?', 'Ең дұрысы — әртүрлі төлем жүйесінен екі карта және аз қолма-қол ақша. Бір картаны бөлек резервте ұстаңыз. Сапар алдында хабарлама, лимит, PIN, қолма-қол алу және шетелдегі app қолжетімділігін тексеріңіз.'),
    ('tourist-faq-049', 'money_cards_connectivity', 'tourist-faq-049', 49, 'money', 'Сколько наличных можно ввозить и вывозить?', 'Порог зависит от страны. При въезде или выезде из ЕС суммы от €10,000 наличными подлежат декларированию; в США суммы более $10,000 также нужно сообщать, при этом максимального лимита на перевозку денег нет, но недекларирование может привести к конфискации и штрафам.', 'How much cash can I bring in or take out?', 'Thresholds depend on the country. In the EU, cash of €10,000 or more must be declared; in the US, more than $10,000 must be reported. Not declaring can lead to seizure and fines.', 'Қанша қолма-қол ақшаны кіргізуге немесе шығаруға болады?', 'Шек елге байланысты. ЕО-да €10,000 және одан көп қолма-қол ақша декларацияланады; АҚШ-та $10,000-нан көп соманы хабарлау керек. Декларацияламау тәркілеу мен айыппұлға әкелуі мүмкін.'),
    ('tourist-faq-050', 'money_cards_connectivity', 'tourist-faq-050', 50, 'money', 'Где лучше менять деньги?', 'Обычно выгоднее банкомат крупного банка или обменник с прозрачным курсом и комиссией, чем аэропорт и отель. Избегайте уличных обменов и “нулевой комиссии” без проверки курса. Считайте итог: курс плюс фиксированная комиссия плюс комиссия вашего банка.', 'Where is it better to exchange money?', 'A major bank ATM or transparent exchange office is usually better than airport or hotel exchange. Avoid street exchanges and “zero commission” without checking the rate. Compare total cost: rate plus fixed and bank fees.', 'Ақшаны қай жерде ауыстырған дұрыс?', 'Ірі банк банкоматы немесе ашық бағамы бар айырбастау пункті әуежай мен қонақүйден жиі тиімді. Көшедегі айырбас пен “0 комиссияны” бағамсыз қабылдамаңыз. Жалпы шығынды есептеңіз.'),
    ('tourist-faq-051', 'money_cards_connectivity', 'tourist-faq-051', 51, 'money', 'В какой валюте платить картой: местной или своей?', 'В большинстве случаев выбирайте местную валюту. Dynamic Currency Conversion позволяет терминалу или банкомату сразу пересчитать сумму в вашу валюту, но часто добавляет невыгодный курс и дополнительные сборы. Если терминал не показывает понятные условия или вас торопят, лучше отказаться от DCC.', 'Which currency should I choose when paying by card?', 'Usually choose the local currency. Dynamic Currency Conversion converts immediately into your home currency, but often uses a poor rate and extra fees. If terms are unclear, decline DCC.', 'Картамен төлегенде қай валютаны таңдау керек?', 'Көбіне жергілікті валютаны таңдаңыз. Dynamic Currency Conversion соманы үй валютаңызға бірден аударады, бірақ бағамы тиімсіз және қосымша алым болуы мүмкін. Шарт түсініксіз болса, DCC-ден бас тартыңыз.'),
    ('tourist-faq-052', 'money_cards_connectivity', 'tourist-faq-052', 52, 'money', 'Как безопасно пользоваться банкоматом за границей?', 'Выбирайте банкоматы внутри банков, торговых центров или отелей, прикрывайте PIN, не принимайте помощь посторонних и отказывайтесь от конвертации в домашнюю валюту, если курс невыгоден. Снимайте разумными суммами: слишком часто — много комиссий, слишком много — выше риск кражи.', 'How do I use ATMs safely abroad?', 'Use ATMs inside banks, malls or hotels, cover your PIN, refuse help from strangers, and decline conversion to your home currency if the rate is bad. Withdraw sensible amounts to balance fees and theft risk.', 'Шетелде банкоматты қалай қауіпсіз қолданамын?', 'Банк, сауда орталығы немесе қонақүй ішіндегі банкоматты таңдаңыз, PIN-ді жабыңыз, бейтаныс көмегінен бас тартыңыз және тиімсіз болса үй валютаға конвертацияны қабылдамаңыз.'),
    ('tourist-faq-053', 'money_cards_connectivity', 'tourist-faq-053', 53, 'money', 'Что выбрать: роуминг, eSIM или местную SIM?', 'Для коротких поездок удобна eSIM, если телефон поддерживает eSIM и не заблокирован оператором. Для длительных поездок часто дешевле местная SIM. Проверьте заранее, как будут работать банковские SMS и двухфакторная авторизация, если основной номер временно недоступен.', 'Should I choose roaming, eSIM or local SIM?', 'For short trips, eSIM is convenient if your phone supports it and is unlocked. For long trips, local SIM may be cheaper. Check banking SMS and two-factor login if your main number becomes unavailable.', 'Роуминг, eSIM немесе жергілікті SIM таңдаған дұрыс па?', 'Қысқа сапарға eSIM ыңғайлы, егер телефон қолдаса және операторға байланбаған болса. Ұзақ сапарда жергілікті SIM арзан болуы мүмкін. Банк SMS және 2FA қалай жұмыс істейтінін тексеріңіз.'),
    ('tourist-faq-054', 'money_cards_connectivity', 'tourist-faq-054', 54, 'money', 'Как работает роуминг в ЕС?', 'В ЕС правило “roam like at home” продлено до 2032 года: звонки, SMS и данные в поездках по ЕС обычно тарифицируются как дома, но действуют правила fair use. Судовые, авиационные и спутниковые сети, а также страны вне ЕС не обязательно входят в это правило.', 'How does EU roaming work?', '“Roam like at home” in the EU generally means calls, SMS and data are charged like at home, with fair-use rules. Ship, aircraft, satellite networks and non-EU countries are not necessarily included.', 'ЕО-дағы роуминг қалай жұмыс істейді?', 'ЕО-да “roam like at home” әдетте қоңырау, SMS және интернетті үйдегідей тарифтейді, бірақ fair use ережесі бар. Кеме, ұшақ, спутник желілері және ЕО-дан тыс елдер кірмеуі мүмкін.'),
    ('tourist-faq-055', 'money_cards_connectivity', 'tourist-faq-055', 55, 'money', 'Что делать, если карта заблокировалась за границей?', 'Свяжитесь с банком через приложение, официальный номер или чат. Держите резервную карту и немного наличных отдельно. Никогда не ищите “номер банка” через случайную рекламу в поиске — используйте номер на карте, в приложении или на официальном сайте.', 'What if my card is blocked abroad?', 'Contact your bank through the app, official number or chat. Keep a backup card and some cash separately. Do not search random ads for bank numbers; use the card, app or official site.', 'Шетелде карта бұғатталса не істеу керек?', 'Банк қосымшасы, ресми нөмірі немесе чаты арқылы хабарласыңыз. Резерв карта мен аз қолма-қол ақшаны бөлек сақтаңыз. Банк нөмірін кездейсоқ жарнамадан іздемеңіз.'),
    ('tourist-faq-056', 'money_cards_connectivity', 'tourist-faq-056', 56, 'money', 'Нужно ли оставлять чаевые?', 'Зависит от страны. В США чаевые часто являются ожидаемой частью оплаты сервиса; в Японии они могут быть неуместны; в Европе обычно умеренные и зависят от страны; в некоторых местах сервис уже включен в счет. Для Q&A лучше давать страновые подсказки, а не один универсальный процент.', 'Should I leave tips?', 'It depends on the country. In the US tips are often expected, in Japan they may be inappropriate, and in Europe they vary by country and bill. Use country-specific guidance, not one universal percentage.', 'Шайпұл қалдыру керек пе?', 'Елге байланысты. АҚШ-та шайпұл жиі күтіледі, Жапонияда орынсыз болуы мүмкін, Еуропада ел мен шотқа байланысты. Бір әмбебап пайыз емес, елдік кеңесті қолданыңыз.'),
    ('tourist-faq-057', 'money_cards_connectivity', 'tourist-faq-057', 57, 'money', 'Как получить tax free / VAT refund?', 'Покупайте в магазинах, участвующих в tax free, оформляйте форму на имя путешественника, сохраняйте чек и не используйте товар до вывоза, если это требуется. На выезде поставьте отметку таможни до сдачи багажа, если товар в чемодане. Возврат может занять недели, а оператор удерживает комиссию.', 'How do I get tax free or VAT refund?', 'Buy from participating shops, complete the form in the traveler’s name, keep receipt and do not use goods before export if required. Get customs validation before checking luggage if the item is inside. Refunds may take weeks and include fees.', 'Tax free / VAT refund қалай аламын?', 'Tax free дүкендерден сатып алып, форманы саяхатшы атына толтырыңыз, чекті сақтаңыз және қажет болса тауарды шығарғанға дейін қолданбаңыз. Тауар чемоданда болса, багаж тапсырмай тұрып кеден мөрін алыңыз.'),
    ('tourist-faq-058', 'health_safety_insurance', 'tourist-faq-058', 58, 'safety', 'Нужна ли туристическая страховка?', 'Да, особенно для зарубежной поездки. Государство обычно не оплачивает лечение туристов за границей, а медицинская эвакуация может стоить десятки и сотни тысяч долларов. Страховка должна покрывать страну, даты, экстренную помощь, транспортировку, репатриацию и ваши активности.', 'Do I need travel insurance?', 'Yes, especially abroad. Governments usually do not pay tourist medical costs, and evacuation can be very expensive. Insurance should cover the country, dates, emergency care, transport, repatriation and activities.', 'Туристік сақтандыру керек пе?', 'Иә, әсіресе шетелге. Мемлекет әдетте туристің емін төлемейді, эвакуация өте қымбат болуы мүмкін. Сақтандыру елді, күндерді, шұғыл көмекті, тасымалды, репатриацияны және белсенділіктерді жабуы керек.'),
    ('tourist-faq-059', 'health_safety_insurance', 'tourist-faq-059', 59, 'safety', 'Что проверить в страховке перед покупкой?', 'Проверьте медицинский лимит, эвакуацию, хронические болезни, беременность, спорт, алкогольные исключения, отмену поездки, багаж, франшизу, страны покрытия и номер 24/7 assistance. Если едете в горы, на дайвинг, лыжи, серфинг, сафари или арендуете мотоцикл, обычной страховки может быть недостаточно.', 'What should I check before buying insurance?', 'Check medical limit, evacuation, chronic illness, pregnancy, sports, alcohol exclusions, cancellation, baggage, deductible, covered countries and 24/7 assistance. Mountains, diving, skiing, surfing, safari or motorcycle rental may need extra coverage.', 'Сақтандыру сатып аларда нені тексеру керек?', 'Медициналық лимит, эвакуация, созылмалы ауру, жүктілік, спорт, алкоголь ерекшеліктері, сапарды тоқтату, багаж, франшиза, елдер және 24/7 assistance тексеріңіз. Тау, дайвинг, шаңғы, серфинг, сафари немесе мотоцикл үшін қосымша жабу керек болуы мүмкін.'),
    ('tourist-faq-060', 'health_safety_insurance', 'tourist-faq-060', 60, 'safety', 'Какие прививки нужны перед поездкой?', 'Нужно быть в курсе обычных прививок и проверить рекомендации по стране назначения. CDC советует записываться к врачу или travel health specialist за 4–6 недель до поездки; WHO также отмечает, что некоторые страны требуют доказательство вакцинации для въезда или выезда, например в отдельных случаях по желтой лихорадке.', 'Which vaccines do I need before travel?', 'Keep routine vaccines up to date and check destination recommendations. Visit a doctor or travel health specialist 4-6 weeks before travel. Some countries require vaccination proof for entry or exit, such as yellow fever in specific cases.', 'Сапар алдында қандай екпе керек?', 'Кәдімгі екпелерді жаңартып, баратын елдің ұсыныстарын тексеріңіз. Сапардан 4-6 апта бұрын дәрігерге немесе travel health маманына барыңыз. Кей елдер кіру/шығу үшін вакцина дәлелін талап етеді.'),
    ('tourist-faq-061', 'health_safety_insurance', 'tourist-faq-061', 61, 'safety', 'Как узнать о вспышках болезней и рисках перед поездкой?', 'Проверьте официальные travel health pages своей страны, CDC/WHO и сайт страны назначения. Делайте это дважды: до покупки сложной поездки и за несколько дней до вылета. Риски по малярии, денге, кори, желтой лихорадке и другим инфекциям меняются по регионам и сезонам.', 'How do I learn about disease outbreaks and health risks?', 'Check official travel health pages, CDC/WHO and destination health sources twice: before buying a complex trip and a few days before departure. Risks like malaria, dengue, measles and yellow fever vary by region and season.', 'Ауру ошақтары мен қауіптерді қалай білемін?', 'Ресми travel health беттерін, CDC/WHO және баратын ел деректерін екі рет тексеріңіз: күрделі сапарды сатып алмас бұрын және ұшуға бірнеше күн қалғанда. Малярия, денге, қызылша, сары қызба тәуекелі аймақ пен маусымға байланысты.'),
    ('tourist-faq-062', 'health_safety_insurance', 'tourist-faq-062', 62, 'safety', 'Что положить в аптечку путешественника?', 'Постоянные лекарства с запасом, рецепты, обезболивающее/жаропонижающее, средство от диареи, оральные регидратационные соли, пластыри, антисептик, репеллент, солнцезащиту, средства от аллергии и индивидуальные препараты. Лекарства первой необходимости — только в ручную кладь.', 'What should I put in a travel first-aid kit?', 'Pack regular medicines with extra supply, prescriptions, pain/fever medicine, diarrhea treatment, oral rehydration salts, plasters, antiseptic, repellent, sunscreen, allergy medicine and personal items. Essential medicines stay in carry-on.', 'Саяхат аптечкасына не салу керек?', 'Тұрақты дәрілерді запаспен, рецепттерді, ауырсыну/қызу дәрісін, диареяға дәрі, регидратация тұзын, пластырь, антисептик, репеллент, күннен қорғаныс, аллергия дәрісі және жеке препараттарды салыңыз. Маңызды дәрі қол жүгінде болсын.'),
    ('tourist-faq-063', 'health_safety_insurance', 'tourist-faq-063', 63, 'safety', 'Что делать, если заболел за границей?', 'В экстренной ситуации звоните в местную скорую. В неэкстренной — сначала свяжитесь со страховой assistance, чтобы получить клинику из сети и согласование оплаты. Сохраняйте диагноз, рецепты, чеки, результаты анализов и выписки.', 'What if I get sick abroad?', 'For emergencies, call the local ambulance. For non-emergency care, contact your insurance assistance first to get a network clinic and payment approval. Keep diagnosis, prescriptions, receipts, test results and discharge notes.', 'Шетелде ауырып қалсам не істеу керек?', 'Шұғыл жағдайда жергілікті жедел жәрдемге қоңырау шалыңыз. Шұғыл емес жағдайда алдымен сақтандыру assistance-ке хабарласып, клиника мен төлем келісімін алыңыз. Диагноз, рецепт, чек, талдау және выписка сақтаңыз.'),
    ('tourist-faq-064', 'health_safety_insurance', 'tourist-faq-064', 64, 'safety', 'Можно ли пить воду из-под крана?', 'Зависит от страны и региона. Если сомневаетесь, пейте воду из запечатанных бутылок, кипяченую или надежно фильтрованную; избегайте льда и чистите зубы безопасной водой. В горах и на островах качество воды может отличаться от столицы.', 'Can I drink tap water?', 'It depends on the country and region. If unsure, drink sealed bottled, boiled or reliably filtered water; avoid ice and brush teeth with safe water. Mountain and island water quality can differ from capitals.', 'Кран суын ішуге бола ма?', 'Ел мен аймаққа байланысты. Күмән болса, жабық бөтелке, қайнатылған немесе сенімді сүзілген су ішіңіз; мұздан сақтанып, тісті қауіпсіз сумен тазалаңыз. Тауда немесе аралда су сапасы астанадан өзгеше болуы мүмкін.'),
    ('tourist-faq-065', 'health_safety_insurance', 'tourist-faq-065', 65, 'safety', 'Как снизить риск пищевого отравления?', 'Выбирайте свежеприготовленную горячую еду, места с высокой проходимостью, очищенные фрукты и безопасную воду. Осторожнее с сырыми морепродуктами, молочными продуктами без пастеризации, салатами, льдом и буфетами, где еда долго стоит теплой. При крови в стуле, высокой температуре, обезвоживании или симптомах у ребенка — к врачу.', 'How do I reduce food poisoning risk?', 'Choose freshly cooked hot food, busy places, peeled fruit and safe water. Be careful with raw seafood, unpasteurized dairy, salads, ice and buffets. Seek medical help for blood in stool, high fever, dehydration or child symptoms.', 'Тамақтан улану қаупін қалай азайтамын?', 'Жаңа піскен ыстық тағамды, адам көп орындарды, аршылған жеміс пен қауіпсіз суды таңдаңыз. Шикі теңіз өнімдері, пастерленбеген сүт, салат, мұз және буфетке абай болыңыз. Қан, жоғары қызу, сусыздану немесе балада симптом болса дәрігерге барыңыз.'),
    ('tourist-faq-066', 'health_safety_insurance', 'tourist-faq-066', 66, 'safety', 'Как защититься от комаров, денге и малярии?', 'Используйте репеллент, закрытую одежду, сетки, кондиционер и избегайте стоячей воды рядом с жильем. Если регион малярийный и врач назначил профилактику, принимайте препарат до, во время и после поездки строго по схеме. CDC указывает, что противомалярийные препараты нужно принимать по назначению до, во время и после путешествия.', 'How do I protect against mosquitoes, dengue and malaria?', 'Use repellent, covered clothing, nets, air conditioning and avoid standing water near lodging. If malaria prevention is prescribed, take it before, during and after the trip exactly as instructed.', 'Маса, денге және маляриядан қалай қорғанамын?', 'Репеллент, жабық киім, тор, кондиционер қолданыңыз және тұрған жер жанындағы тұрып қалған судан аулақ болыңыз. Малярия профилактикасы тағайындалса, дәріні сапарға дейін, кезінде және кейін нұсқау бойынша ішіңіз.'),
    ('tourist-faq-067', 'health_safety_insurance', 'tourist-faq-067', 67, 'safety', 'Что делать при жаре, солнце, высоте и море?', 'Пейте воду, избегайте активностей в полуденную жару, используйте SPF, головной убор и постепенно адаптируйтесь к высоте. На море соблюдайте флаги, не плывите против отбойного течения и не заходите в воду после алкоголя. В горах лучше планировать медленный набор высоты и день акклиматизации.', 'What should I do about heat, sun, altitude and the sea?', 'Drink water, avoid midday heat, use SPF and a hat, and adapt to altitude gradually. At sea, follow flags, do not swim against rip currents, and avoid swimming after alcohol. In mountains, plan slow ascent and acclimatization.', 'Ыстық, күн, биіктік және теңізде не істеу керек?', 'Су ішіңіз, түскі ыстықтан қашыңыз, SPF және бас киім қолданыңыз, биіктікке біртіндеп бейімделіңіз. Теңізде жалауларды сақтаңыз, ағысқа қарсы жүзбеңіз, алкогольден кейін суға түспеңіз. Тауда баяу көтерілу мен акклиматизация жоспарлаңыз.'),
    ('tourist-faq-068', 'health_safety_insurance', 'tourist-faq-068', 68, 'safety', 'Как действовать при протестах, землетрясении, пожаре или другой ЧС?', 'Следуйте указаниям местных властей, не снимайте силовые действия вблизи, избегайте толпы и сообщите близким, где вы. Проверьте travel advisories и подпишитесь на оповещения, если ваша страна предоставляет такой сервис. Например, STEP рассылает уведомления от посольства и помогает связаться с гражданином или emergency contact в кризисе для граждан США.', 'What should I do during protests, earthquakes, fires or emergencies?', 'Follow local authorities, avoid crowds, do not film security actions nearby, and tell family where you are. Check travel advisories and sign up for alerts if your country offers them.', 'Наразылық, жер сілкінісі, өрт немесе ТЖ кезінде не істеу керек?', 'Жергілікті билік нұсқауын орындаңыз, көпшіліктен аулақ болыңыз, күштік әрекеттерді жақыннан түсірмеңіз және жақындарыңызға қайда екеніңізді айтыңыз. Travel advisories тексеріп, ел ұсынса ескертулерге жазылыңыз.'),
    ('tourist-faq-069', 'health_safety_insurance', 'tourist-faq-069', 69, 'safety', 'Что делать при краже документов, телефона или карты?', 'Заблокируйте карты и SIM/eSIM, смените пароли, подайте заявление в полицию, обратитесь в посольство по документам и в страховую по возмещению. Не храните единственный доступ к банку, билетам и документам только в украденном телефоне.', 'What if documents, phone or card are stolen?', 'Block cards and SIM/eSIM, change passwords, file a police report, contact the embassy for documents and the insurer for claims. Do not keep your only access to bank, tickets and documents on one phone.', 'Құжат, телефон немесе карта ұрланса не істеу керек?', 'Карталар мен SIM/eSIM-ді бұғаттаңыз, парольдерді өзгертіңіз, полицияға арыз беріңіз, құжат үшін елшілікке және өтем үшін сақтандыруға хабарласыңыз. Банк, билет және құжатқа жалғыз қолжетімділікті бір телефонда ғана сақтамаңыз.'),
    ('tourist-faq-070', 'health_safety_insurance', 'tourist-faq-070', 70, 'safety', 'Какой номер экстренной помощи использовать в Европе?', '112 — единый бесплатный номер экстренной помощи в ЕС для полиции, скорой и пожарных. Он работает с мобильного и стационарного телефона; во многих странах операторы могут ответить на английском или другом европейском языке.', 'What emergency number should I use in Europe?', '112 is the single free emergency number in the EU for police, ambulance and fire services. It works from mobile and landline phones; in many countries operators may answer in English or another European language.', 'Еуропада қандай жедел нөмірді қолданамын?', '112 — ЕО-дағы полиция, жедел жәрдем және өрт қызметіне арналған бірыңғай тегін нөмір. Ол ұялы және стационар телефоннан жұмыс істейді; көп елде операторлар ағылшын немесе басқа еуропалық тілде жауап бере алады.'),
    ('tourist-faq-071', 'health_safety_insurance', 'tourist-faq-071', 71, 'safety', 'Как выбрать клинику за границей?', 'Начните со страховой assistance: они подскажут клинику, язык, оплату и документы. Списки клиник у посольств полезны, но обычно не являются гарантией качества. При серьезном случае добивайтесь письменного диагноза и плана лечения на понятном языке.', 'How do I choose a clinic abroad?', 'Start with insurance assistance: they can suggest clinics, language, payment and documents. Embassy clinic lists can help but are not a quality guarantee. For serious cases, request written diagnosis and treatment plan in a language you understand.', 'Шетелде клиниканы қалай таңдаймын?', 'Алдымен сақтандыру assistance-тен бастаңыз: олар клиника, тіл, төлем және құжат бойынша бағыт береді. Елшілік тізімдері пайдалы, бірақ сапа кепілі емес. Ауыр жағдайда түсінікті тілде жазбаша диагноз және ем жоспарын сұраңыз.'),
    ('tourist-faq-072', 'health_safety_insurance', 'tourist-faq-072', 72, 'safety', 'Как путешествовать при беременности или хроническом заболевании?', 'Перед поездкой обсудите маршрут с врачом, возьмите медицинскую выписку на английском или языке страны, запас лекарств и страховку, которая действительно покрывает беременность или хронические состояния. У авиакомпаний есть ограничения по срокам беременности, а у страховок — по неделям и осложнениям.', 'How do I travel while pregnant or with a chronic condition?', 'Discuss the route with your doctor, take a medical summary in English or destination language, extra medicines, and insurance that truly covers pregnancy or chronic conditions. Airlines and insurers have week and complication limits.', 'Жүктілік немесе созылмалы аурумен қалай саяхаттау керек?', 'Маршрутты дәрігермен талқылаңыз, ағылшын немесе ел тіліндегі медициналық выписка, дәрі запасы және жүктілік/созылмалы жағдайды шынымен жабатын сақтандыру алыңыз. Авиакомпания мен сақтандыруда апта және асқыну шектеулері бар.'),
    ('tourist-faq-073', 'local_transport', 'tourist-faq-073', 73, 'transport', 'Как безопасно добраться из аэропорта?', 'Используйте официальные стойки такси, лицензированные приложения, поезд/метро или трансфер от отеля. До выхода из аэропорта узнайте примерную цену и маршрут. Не соглашайтесь на предложения водителей, которые ловят туристов в зале прилета.', 'How do I get safely from the airport?', 'Use official taxi counters, licensed apps, train/metro or hotel transfer. Before leaving the airport, know the approximate price and route. Avoid drivers approaching tourists in arrivals.', 'Әуежайдан қауіпсіз қалай жетемін?', 'Ресми такси стойкасын, лицензияланған app, пойыз/метро немесе қонақүй трансферін қолданыңыз. Әуежайдан шығар алдында шамамен баға мен маршрутты біліңіз. Келу залында турист ұстайтын жүргізушілерге келіспеңіз.'),
    ('tourist-faq-074', 'local_transport', 'tourist-faq-074', 74, 'transport', 'Как пользоваться общественным транспортом без штрафов?', 'Покупайте билеты в официальных автоматах, приложениях или кассах и обязательно валидируйте их, если это требуется. В некоторых городах штрафуют не за отсутствие билета, а за то, что билет не активирован. Храните билет до конца поездки и выхода со станции.', 'How do I use public transport without fines?', 'Buy tickets from official machines, apps or counters and validate them if required. Some cities fine not for no ticket, but for not activating it. Keep the ticket until the end of the trip and station exit.', 'Қоғамдық көлікте айыппұлсыз қалай жүремін?', 'Билетті ресми автомат, app немесе кассадан алыңыз және қажет болса міндетті түрде валидациялаңыз. Кей қалада билет болмауына емес, іске қосылмауына айыппұл салады. Билетті сапар соңына және станциядан шыққанша сақтаңыз.'),
    ('tourist-faq-075', 'local_transport', 'tourist-faq-075', 75, 'transport', 'Как избежать обмана в такси?', 'Используйте приложение или официальное такси, проверяйте номер машины, маршрут и способ оплаты. Если счетчик не используется, договаривайтесь о цене до посадки. Не отдавайте крупные купюры без необходимости и не оставляйте багаж в машине до окончания оплаты.', 'How do I avoid taxi scams?', 'Use an app or official taxi, check car number, route and payment method. If no meter is used, agree the price before getting in. Avoid handing over large notes unnecessarily and keep luggage until payment is settled.', 'Таксидегі алдаудан қалай сақтанамын?', 'App немесе ресми такси қолданыңыз, көлік нөмірін, маршрутты және төлем әдісін тексеріңіз. Есептегіш жоқ болса, отырар алдында бағаны келісіңіз. Ірі купюраны қажетсіз бермеңіз және төлем аяқталғанша багажды қалдырмаңыз.'),
    ('tourist-faq-076', 'local_transport', 'tourist-faq-076', 76, 'transport', 'Безопасны ли ride-hailing приложения?', 'В целом удобны, но проверяйте номер машины, имя водителя и маршрут. Делитесь поездкой с близкими, садитесь на заднее сиденье и не раскрывайте лишние детали о жилье. Если водитель просит отменить поездку и платить наличными, это повышает риск спора.', 'Are ride-hailing apps safe?', 'Generally convenient, but verify car number, driver name and route. Share the ride with someone, sit in the back, and do not reveal lodging details. If the driver asks to cancel and pay cash, dispute risk rises.', 'Ride-hailing қолданбалары қауіпсіз бе?', 'Жалпы ыңғайлы, бірақ көлік нөмірін, жүргізуші атын және маршрутты тексеріңіз. Сапарды жақынмен бөлісіңіз, артқы орынға отырыңыз, тұратын жер туралы артық айтпаңыз. Жүргізуші сапарды жойып, қолма-қол сұраса, дау тәуекелі артады.'),
    ('tourist-faq-077', 'local_transport', 'tourist-faq-077', 77, 'transport', 'Нужно ли международное водительское удостоверение?', 'Во многих странах нужно или рекомендуется IDP — международное водительское удостоверение, которое переводит данные национальных прав. Его обычно нужно возить вместе с оригинальными правами; само по себе IDP не заменяет водительское удостоверение. Официальные источники США также предупреждают о мошеннических сайтах, продающих недействительные IDP.', 'Do I need an International Driving Permit?', 'In many countries an IDP is required or recommended as a translation of your national license. Carry it together with the original license; it does not replace it. Beware of fake sites selling invalid IDPs.', 'Халықаралық жүргізуші куәлігі керек пе?', 'Көп елде IDP қажет немесе ұсынылады, ол ұлттық куәлікті аударады. Оны түпнұсқа құқықпен бірге алып жүріңіз; өзі құқықты алмастырмайды. Жарамсыз IDP сататын жалған сайттардан сақ болыңыз.'),
    ('tourist-faq-078', 'local_transport', 'tourist-faq-078', 78, 'transport', 'Как не переплатить за аренду автомобиля?', 'До выезда с парковки снимите видео кузова, стекол, шин, салона, уровня топлива и пробега. Проверьте франшизу, депозит, политику топлива, лимит пробега, платные дороги, штрафы, страховку шин/стекол и условия возврата. GOV.UK предупреждает, что стандартная CDW часто не покрывает шины и стекла, а прокатчики могут активно продавать дополнительные страховки.', 'How do I avoid overpaying for car rental?', 'Before leaving, video the body, glass, tires, cabin, fuel level and mileage. Check deductible, deposit, fuel policy, mileage, tolls, fines, insurance for tires/glass and return rules. Do not buy extras under pressure.', 'Автокөлік жалдауда артық төлемнен қалай сақтанамын?', 'Шықпас бұрын кузов, әйнек, шина, салон, жанармай және пробегті видеоға түсіріңіз. Франшиза, депозит, fuel policy, пробег, ақылы жол, айыппұл, шина/әйнек сақтандыруы және қайтару шартын тексеріңіз. Қысыммен қосымша алмаңыз.'),
    ('tourist-faq-079', 'local_transport', 'tourist-faq-079', 79, 'transport', 'Что такое ZTL, congestion charge и e-vignette?', 'Это зоны ограниченного движения, платный въезд или электронные дорожные сборы. В Европе штрафы за ZTL и парковку часто приходят через прокатную компанию, которая добавляет административный сбор. Перед поездкой проверьте правила городов, куда въезжаете на машине.', 'What are ZTL, congestion charge and e-vignette?', 'They are restricted traffic zones, paid entry or electronic road charges. In Europe, fines for ZTL and parking often arrive through rental companies with an admin fee. Check city rules before driving in.', 'ZTL, congestion charge және e-vignette деген не?', 'Бұл шектеулі қозғалыс аймағы, ақылы кіру немесе электрондық жол алымы. Еуропада ZTL және тұрақ айыппұлы прокат компаниясы арқылы әкімшілік алыммен келеді. Қалаға кірмес бұрын ережені тексеріңіз.'),
    ('tourist-faq-080', 'local_transport', 'tourist-faq-080', 80, 'transport', 'Стоит ли арендовать скутер, мопед или ATV?', 'Только если у вас есть опыт, правильная категория прав, шлем и страховка, которая покрывает такой транспорт. В туристических регионах аварии на скутерах — частая причина травм, а езда без нужной категории прав может лишить вас страхового покрытия.', 'Should I rent a scooter, moped or ATV?', 'Only if you have experience, the correct license category, helmet and insurance that covers it. Tourist areas have many scooter injuries, and riding without the proper license can void insurance.', 'Скутер, мопед немесе ATV жалдаған дұрыс па?', 'Тәжірибеңіз, дұрыс құқық категориясы, шлем және оны жабатын сақтандыру болса ғана. Туристік жерлерде скутер апаты жиі, ал дұрыс категориясыз жүру сақтандыруды жарамсыз етуі мүмкін.'),
    ('tourist-faq-081', 'route_budget_planning', 'tourist-faq-081', 81, 'planning', 'Когда лучше ехать в страну?', '“Лучшее время” зависит от цели: погода, пляж, горы, фестивали, цены, толпы, цветение, миграция животных или северное сияние. Часто оптимален shoulder season — период между высоким и низким сезоном: меньше людей и ниже цены, но погода еще приемлемая.', 'When is the best time to visit a country?', 'The best time depends on purpose: weather, beach, mountains, festivals, prices, crowds, blooms, wildlife migration or northern lights. Shoulder season often offers fewer crowds and lower prices with acceptable weather.', 'Елге қай кезде барған дұрыс?', 'Ең жақсы уақыт мақсатқа байланысты: ауа райы, жағажай, тау, фестиваль, баға, адам көптігі, гүлдеу, жануар миграциясы немесе солтүстік шұғыла. Shoulder season жиі адам аз, баға төмен және ауа райы қолайлы болады.'),
    ('tourist-faq-082', 'route_budget_planning', 'tourist-faq-082', 82, 'planning', 'Сколько дней нужно на поездку?', 'Не считайте только ночи — считайте чистое время на месте. Для крупного города обычно нужно минимум 3–4 полных дня, для региона 7–10 дней, для страны с переездами — больше. Добавляйте день на адаптацию, задержки, детей, пожилых путешественников и смену часовых поясов.', 'How many days do I need for a trip?', 'Count real time on location, not just nights. A large city usually needs at least 3-4 full days, a region 7-10 days, and countries with transfers more. Add time for adaptation, delays, children, seniors and jet lag.', 'Сапарға қанша күн керек?', 'Тек түнді емес, орындағы таза уақытты санаңыз. Үлкен қалаға кемі 3-4 толық күн, өңірге 7-10 күн, көп көшетін елге көбірек керек. Бейімделу, кешігу, балалар, егде адамдар және уақыт белдеуі үшін уақыт қосыңыз.'),
    ('tourist-faq-083', 'route_budget_planning', 'tourist-faq-083', 83, 'planning', 'Как не перегрузить маршрут?', 'Планируйте по районам, а не по случайному списку достопримечательностей. Хорошее правило: 2–3 крупных активности в день плюс свободное окно. Оставляйте альтернативы на дождь, жару, забастовки и усталость.', 'How do I avoid overloading the itinerary?', 'Plan by neighborhoods, not random attractions. A good rule is 2-3 major activities per day plus free time. Keep alternatives for rain, heat, strikes and fatigue.', 'Маршрутты қалай ауырлатпауға болады?', 'Кездейсоқ көрікті орын тізімімен емес, аудандар бойынша жоспарлаңыз. Күніне 2-3 ірі белсенділік және бос уақыт жақсы ереже. Жаңбыр, ыстық, ереуіл және шаршауға балама қалдырыңыз.'),
    ('tourist-faq-084', 'route_budget_planning', 'tourist-faq-084', 84, 'planning', 'Как посчитать реальный бюджет поездки?', 'Считайте не только перелет и отель. Добавьте багаж, выбор мест, трансферы, питание, визы/ETA, страховку, связь, городские налоги, чаевые, входные билеты, экскурсии, платные дороги и резерв 10–20%. Для семейных поездок отдельно учитывайте детские кресла, багаж, питание и ранние заселения.', 'How do I calculate the real trip budget?', 'Include more than flight and hotel: baggage, seats, transfers, meals, visas/ETA, insurance, connectivity, city taxes, tips, tickets, tours, tolls and a 10-20% reserve. Families should include child seats, luggage, meals and early check-in.', 'Сапардың нақты бюджетін қалай есептеймін?', 'Ұшу мен қонақүйден бөлек багаж, орын таңдау, трансфер, тамақ, виза/ETA, сақтандыру, байланыс, қала салығы, шайпұл, билеттер, экскурсия, ақылы жол және 10-20% резерв қосыңыз. Отбасылар бала креслосын, багажды, тамақты және ерте кіруді есептесін.'),
    ('tourist-faq-085', 'route_budget_planning', 'tourist-faq-085', 85, 'planning', 'Что бронировать заранее?', 'Заранее лучше бронировать популярные музеи с timed entry, поезда, паромы, национальные парки, рестораны с высоким спросом, сафари, горные хижины, круизы и праздничные даты. Если маршрут еще плавающий, выбирайте refundable или flexible тарифы.', 'What should I book in advance?', 'Book high-demand timed museums, trains, ferries, national parks, popular restaurants, safaris, mountain huts, cruises and holiday dates early. If plans may change, choose refundable or flexible rates.', 'Нені алдын ала брондау керек?', 'Сұранысы жоғары timed entry музейлер, пойыз, паром, ұлттық парк, танымал ресторан, сафари, тау үйшігі, круиз және мереке күндерін ерте брондаңыз. Жоспар өзгеруі мүмкін болса, refundable немесе flexible тариф таңдаңыз.'),
    ('tourist-faq-086', 'route_budget_planning', 'tourist-faq-086', 86, 'planning', 'Как избежать толп и overtourism?', 'Покупайте ранние или вечерние слоты, выбирайте будни, ночуйте рядом с популярным местом, смотрите альтернативные входы и посещайте второстепенные, но качественные локации. Уважайте лимиты, бронирования и правила местных жителей: популярность места не отменяет частную жизнь и экологические ограничения.', 'How do I avoid crowds and overtourism?', 'Use early or evening slots, weekdays, stay near popular places, check alternative entrances and visit secondary but quality locations. Respect limits, bookings and local residents; popularity does not remove privacy or environmental rules.', 'Адам көптігі мен overtourism-нен қалай сақтанамын?', 'Ерте немесе кешкі слот, жұмыс күндері, танымал орынға жақын тұру, балама кіреберіс және сапалы екінші локацияларды таңдаңыз. Лимит, бронь және жергілікті тұрғындарды құрметтеңіз.'),
    ('tourist-faq-087', 'route_budget_planning', 'tourist-faq-087', 87, 'planning', 'Какие приложения скачать до поездки?', 'Карты офлайн, переводчик, приложение авиакомпании, отеля/платформы бронирования, транспорта, страховой, банка, eSIM/оператора и местные такси. Сохраните билеты, страховку, паспортные копии и адреса офлайн — интернет часто пропадает именно в аэропортах и на границе.', 'Which apps should I download before travel?', 'Download offline maps, translator, airline, hotel/booking, transport, insurance, bank, eSIM/operator and local taxi apps. Save tickets, insurance, passport copies and addresses offline because internet often fails at airports and borders.', 'Сапар алдында қандай app жүктеу керек?', 'Офлайн карта, аудармашы, авиакомпания, қонақүй/бронь, көлік, сақтандыру, банк, eSIM/оператор және жергілікті такси app жүктеңіз. Билет, сақтандыру, паспорт көшірмесі және мекенжайларды офлайн сақтаңыз.'),
    ('tourist-faq-088', 'route_budget_planning', 'tourist-faq-088', 88, 'planning', 'Что делать, если прогноз погоды резко изменился?', 'Проверьте не только температуру, но и ветер, осадки, предупреждения, состояние дорог/моря и правила отмены активностей. Имейте план B: музеи, крытые рынки, спа, кулинарные классы, перенос экскурсии. Страховка покрывает отмену из-за погоды только в случаях, прямо указанных в полисе.', 'What if the weather forecast changes sharply?', 'Check more than temperature: wind, rain, alerts, roads/sea and cancellation rules. Have plan B: museums, indoor markets, spa, cooking classes or moving a tour. Insurance covers weather only when the policy says so.', 'Ауа райы күрт өзгерсе не істеу керек?', 'Температурадан бөлек жел, жауын, ескерту, жол/теңіз жағдайы және белсенділік бас тарту шартын тексеріңіз. B жоспары болсын: музей, жабық базар, spa, аспаздық сабақ немесе экскурсияны ауыстыру.'),
    ('tourist-faq-089', 'route_budget_planning', 'tourist-faq-089', 89, 'planning', 'Как путешествовать более экологично и уважительно?', 'Оставайтесь дольше в одном месте, используйте общественный транспорт и поезда, выбирайте локальных гидов, не кормите диких животных, не покупайте сувениры из охраняемых видов, не сходите с троп и экономьте воду там, где ее мало. Хороший туризм оставляет деньги в местной экономике, а не только мусор и шум.', 'How can I travel more responsibly?', 'Stay longer in one place, use public transport and trains, choose local guides, do not feed wildlife, avoid protected-species souvenirs, stay on trails and save water where scarce. Good tourism supports local economy.', 'Қалай экологиялық және құрметпен саяхаттауға болады?', 'Бір жерде ұзағырақ болыңыз, қоғамдық көлік пен пойыз қолданыңыз, жергілікті гид таңдаңыз, жабайы жануарды тамақтандырмаңыз, қорғалатын түр сувенирін алмаңыз, соқпақтан шықпаңыз және су аз жерде үнемдеңіз.'),
    ('tourist-faq-090', 'local_rules_culture_special', 'tourist-faq-090', 90, 'culture', 'Какие местные законы чаще всего удивляют туристов?', 'Запреты на наркотики, вейпы, некоторые лекарства, дроны, съемку военных объектов, публичное употребление алкоголя, дресс-код, поведение в религиозных местах и правила ввоза еды. Незнание закона почти никогда не освобождает от штрафа, депортации или уголовной ответственности.', 'Which local laws often surprise tourists?', 'Common surprises include bans on drugs, vapes, some medicines, drones, filming military sites, public alcohol, dress codes, religious-site behavior and food imports. Not knowing the law rarely prevents fines, deportation or criminal liability.', 'Туристерді қандай жергілікті заңдар жиі таңғалдырады?', 'Есірткі, vape, кей дәрілер, дрон, әскери нысанды түсіру, қоғамдық алкоголь, dress code, діни орын тәртібі және тағам әкелуге тыйым жиі кездеседі. Заңды білмеу айыппұл, депортация немесе қылмыстық жауапкершіліктен босатпайды.'),
    ('tourist-faq-091', 'local_rules_culture_special', 'tourist-faq-091', 91, 'culture', 'Как одеваться в религиозных местах?', 'Заранее проверьте дресс-код. Часто нужно закрыть плечи и колени, снять обувь, покрыть голову или не входить во время службы/молитвы. Возьмите легкий шарф и одежду, которую можно быстро накинуть поверх туристической формы.', 'How should I dress in religious places?', 'Check dress code in advance. Often shoulders and knees must be covered, shoes removed, head covered, or entry avoided during services/prayer. Carry a light scarf and cover-up clothing.', 'Діни орындарда қалай киіну керек?', 'Dress code-ты алдын ала тексеріңіз. Көбіне иық пен тізені жабу, аяқ киімді шешу, басты жабу немесе құлшылық кезінде кірмеу керек. Жеңіл орамал және үстінен киетін киім алыңыз.'),
    ('tourist-faq-092', 'local_rules_culture_special', 'tourist-faq-092', 92, 'culture', 'Можно ли фотографировать людей, полицию, аэропорты и запускать дрон?', 'Людей лучше снимать с разрешения, особенно детей. Военные объекты, границы, аэропорты, полиция и инфраструктура часто запрещены к съемке. Дроны во многих странах требуют регистрации, разрешения, страховки и соблюдения no-fly zones; нарушение может закончиться конфискацией и штрафом.', 'Can I photograph people, police, airports or fly a drone?', 'Ask permission before photographing people, especially children. Military sites, borders, airports, police and infrastructure are often restricted. Drones may require registration, permits, insurance and no-fly-zone compliance.', 'Адамдарды, полицияны, әуежайды түсіруге немесе дрон ұшыруға бола ма?', 'Адамдарды, әсіресе балаларды, рұқсатпен түсіріңіз. Әскери нысан, шекара, әуежай, полиция және инфрақұрылым жиі тыйымда. Дронға тіркеу, рұқсат, сақтандыру және no-fly zone ережесі керек болуы мүмкін.'),
    ('tourist-faq-093', 'local_rules_culture_special', 'tourist-faq-093', 93, 'culture', 'Можно ли ввозить алкоголь, сигареты, еду и сувениры?', 'Нормы зависят от страны и возраста путешественника. Алкоголь и табак обычно имеют лимиты, а мясо, молочные продукты, растения, семена, кораллы, ракушки и изделия из животных могут быть запрещены. Проверяйте правила ввоза и вывоза, особенно после сафари, островов и рынков.', 'Can I bring alcohol, cigarettes, food and souvenirs?', 'Limits depend on country and traveler age. Alcohol and tobacco usually have quotas; meat, dairy, plants, seeds, coral, shells and animal products may be banned. Check import and export rules, especially after markets, islands and safaris.', 'Алкоголь, темекі, тағам және сувенир әкелуге бола ма?', 'Норма елге және жасқа байланысты. Алкоголь мен темекіге лимит бар; ет, сүт, өсімдік, тұқым, коралл, қабыршақ және жануар өнімдері тыйым болуы мүмкін. Әкелу/әкету ережесін тексеріңіз.'),
    ('tourist-faq-094', 'local_rules_culture_special', 'tourist-faq-094', 94, 'culture', 'Как подготовиться к поездке с детьми?', 'Проверьте паспорта, визы, согласия родителей, страховку, детские лекарства, питание, коляску, автокресло и режим сна. На браслете или карточке ребенка укажите имя, телефон взрослого и адрес отеля. В маршруте оставляйте больше пауз и меньше переездов.', 'How do I prepare for travel with children?', 'Check passports, visas, parental consents, insurance, children’s medicines, food, stroller, car seat and sleep schedule. Put the child’s name, adult phone and hotel address on a bracelet or card. Plan more pauses and fewer transfers.', 'Баламен сапарға қалай дайындалу керек?', 'Паспорт, виза, ата-ана келісімі, сақтандыру, балалар дәрісі, тамақ, арба, автокресло және ұйқы режимін тексеріңіз. Бала браслетіне/картасына аты, ересек телефоны және қонақүй мекенжайын жазыңыз. Көбірек үзіліс және аз көшу жоспарлаңыз.'),
    ('tourist-faq-095', 'local_rules_culture_special', 'tourist-faq-095', 95, 'culture', 'Как путешествовать пожилым людям или людям с ограниченной мобильностью?', 'Запрашивайте помощь в аэропорту заранее, выбирайте жилье с лифтом и реальной доступностью, проверяйте расстояния без лестниц и наличие душа без бортика. Лекарства, выписки и страховка должны быть в ручной клади. Планируйте меньше активностей в день и больше времени на пересадки.', 'How can seniors or travelers with limited mobility prepare?', 'Request airport assistance early, choose lodging with elevator and real accessibility, check distances without stairs and shower access. Medicines, medical notes and insurance should stay in carry-on. Plan fewer activities and longer transfers.', 'Егде адамдар немесе қозғалысы шектеулі жандар қалай дайындалады?', 'Әуежай көмегін ерте сұраңыз, лифті және нақты қолжетімділігі бар тұрғын үй таңдаңыз, баспалдақсыз қашықтық пен душты тексеріңіз. Дәрі, выписка және сақтандыру қол жүгінде болсын. Күніне аз белсенділік және ұзақ ауысу жоспарлаңыз.'),
    ('tourist-faq-096', 'local_rules_culture_special', 'tourist-faq-096', 96, 'culture', 'Что важно для solo female travel?', 'Выбирайте безопасный район и понятный поздний трансфер, делитесь маршрутом с близкими, не сообщайте незнакомым номер комнаты и детали одиночного проживания, избегайте изолированных мест ночью и доверяйте ощущениям. Лучше переплатить за безопасный транспорт, чем экономить на рискованной ночной пересадке.', 'What matters for solo female travel?', 'Choose a safe area and clear late transfer, share your route with trusted people, do not reveal room number or that you stay alone, avoid isolated places at night and trust your instincts. Paying more for safe transport is often worth it.', 'Жалғыз әйел саяхатында не маңызды?', 'Қауіпсіз аудан және түсінікті кешкі трансфер таңдаңыз, маршрутты жақындармен бөлісіңіз, бөлме нөмірін немесе жалғыз тұрғаныңызды айтпаңыз, түнде оқшау жерден қашыңыз және сезіміңізге сеніңіз. Қауіпсіз көлікке артық төлеу жиі дұрыс.'),
    ('tourist-faq-097', 'local_rules_culture_special', 'tourist-faq-097', 97, 'culture', 'Что важно для LGBTQ+ путешественников?', 'Проверьте местные законы, социальную ситуацию и риски публичных проявлений привязанности. В некоторых странах правовой риск реален, даже если туристические зоны выглядят расслабленно. Выбирайте inclusive-friendly жилье и аккуратно настройте приватность приложений знакомств и соцсетей.', 'What matters for LGBTQ+ travelers?', 'Check local laws, social climate and risks around public affection. In some countries legal risk is real even if tourist zones seem relaxed. Choose inclusive-friendly lodging and review privacy settings in dating apps and social media.', 'LGBTQ+ саяхатшылар үшін не маңызды?', 'Жергілікті заңды, қоғам ахуалын және қоғамдық сүйіспеншілік тәуекелін тексеріңіз. Кей елдерде туристік аймақ еркін көрінсе де, құқықтық тәуекел нақты. Inclusive-friendly тұрғын үй таңдаңыз және dating app/әлеуметтік желі құпиялығын реттеңіз.'),
    ('tourist-faq-098', 'local_rules_culture_special', 'tourist-faq-098', 98, 'culture', 'Можно ли работать удаленно по туристической визе?', 'Не всегда. Туристический статус обычно не разрешает местную работу, а правила удаленной работы на иностранного работодателя сильно различаются. Для длительного workation проверяйте digital nomad visa, налоговые последствия, лимит дней и условия страховки.', 'Can I work remotely on a tourist visa?', 'Not always. Tourist status usually does not allow local work, and rules for remote work for a foreign employer vary widely. For long workation, check digital nomad visas, tax consequences, day limits and insurance terms.', 'Туристік визамен қашықтан жұмыс істеуге бола ма?', 'Әрдайым емес. Туристік статус әдетте жергілікті жұмысқа рұқсат бермейді, ал шетелдік жұмыс берушіге қашықтан жұмыс ережесі әр елде әртүрлі. Ұзақ workation үшін digital nomad visa, салық, күн лимиті және сақтандыру шартын тексеріңіз.'),
    ('tourist-faq-099', 'local_rules_culture_special', 'tourist-faq-099', 99, 'culture', 'Что делать, если я опоздал на рейс, поезд или экскурсию?', 'Свяжитесь с перевозчиком или оператором до времени отправления, если это возможно: так выше шанс на перенос, standby или частичный возврат. Не все “невозвратные” билеты одинаковы: иногда возвращаются налоги или можно изменить дату за сбор. Страховка поможет только при покрытой причине и с документами.', 'What if I miss a flight, train or tour?', 'Contact the carrier or operator before departure time if possible; this improves chances of rebooking, standby or partial refund. Not all “non-refundable” tickets are the same; taxes or date changes may still be possible.', 'Рейс, пойыз немесе экскурсияға кешіксем не істеу керек?', 'Мүмкін болса, жөнелту уақытына дейін тасымалдаушыға немесе операторға хабарласыңыз; ауыстыру, standby немесе ішінара қайтарым мүмкіндігі артады. “Қайтарылмайтын” билеттер бірдей емес; салықтар немесе күн өзгерту мүмкін болуы ықтимал.'),
    ('tourist-faq-100', 'local_rules_culture_special', 'tourist-faq-100', 100, 'culture', 'Что нужно знать перед круизом?', 'Проверьте паспорт, визы и правила всех портов, даже если вы не планируете сходить на берег: некоторые маршруты требуют документы по странам транзита. Нужна страховка с медицинской эвакуацией, потому что лечение на борту и эвакуация дороги. Следите за “ship time”, временем возвращения на борт и правилами багажа/алкоголя у круизной линии.', 'What should I know before a cruise?', 'Check passport, visas and rules for every port even if you will not go ashore. Some routes require transit-country documents. Insurance should cover medical evacuation, because onboard treatment and evacuation are costly. Watch ship time and boarding deadlines.', 'Круиз алдында нені білу керек?', 'Жағаға түспесеңіз де, барлық порттың паспорт, виза және ережесін тексеріңіз. Кей маршрут транзит ел құжатын талап етеді. Сақтандыру медициналық эвакуацияны жабуы керек, себебі борттағы ем мен эвакуация қымбат. Ship time және бортқа қайту уақытын қадағалаңыз.');

DELETE FROM help_articles
WHERE id LIKE 'fallback-%'
   OR slug LIKE 'fallback-%'
   OR id IN (
       'fallback-support-request',
       'fallback-activity-question',
       'fallback-refund',
       'fallback-currency'
   )
   OR slug IN (
       'fallback-support-request',
       'fallback-activity-question',
       'fallback-refund',
       'fallback-currency'
   );

INSERT INTO help_categories (id, slug, sort_order, status, created_at, updated_at)
SELECT id, slug, sort_order, 'published', now(), now()
FROM tourist_faq_categories_seed
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    sort_order = EXCLUDED.sort_order,
    status = 'published',
    updated_at = now();

INSERT INTO help_articles (
    id,
    category_id,
    slug,
    status,
    version,
    owner_id,
    reviewer_id,
    visibility_rules,
    published_at,
    last_reviewed_at,
    created_at,
    updated_at
)
SELECT
    id,
    category_id,
    slug,
    'published',
    1,
    'system',
    'system',
    '{}'::jsonb,
    now(),
    now(),
    now(),
    now()
FROM tourist_faq_seed
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    slug = EXCLUDED.slug,
    status = 'published',
    version = help_articles.version + 1,
    owner_id = EXCLUDED.owner_id,
    reviewer_id = EXCLUDED.reviewer_id,
    visibility_rules = EXCLUDED.visibility_rules,
    published_at = COALESCE(help_articles.published_at, EXCLUDED.published_at),
    last_reviewed_at = EXCLUDED.last_reviewed_at,
    updated_at = now();

DELETE FROM help_article_translations
WHERE article_id IN (SELECT id FROM tourist_faq_seed);

INSERT INTO help_article_translations (article_id, locale, title, short_answer, body, created_at, updated_at)
SELECT id, 'ru', title_ru, answer_ru, answer_ru, now(), now()
FROM tourist_faq_seed
UNION ALL
SELECT id, 'en', title_en, answer_en, answer_en, now(), now()
FROM tourist_faq_seed
UNION ALL
SELECT id, 'kk', title_kk, answer_kk, answer_kk, now(), now()
FROM tourist_faq_seed;

DELETE FROM help_article_surfaces
WHERE article_id IN (SELECT id FROM tourist_faq_seed);

INSERT INTO help_article_surfaces (article_id, surface)
SELECT id, 'help_center'
FROM tourist_faq_seed
ON CONFLICT DO NOTHING;

DELETE FROM help_article_tags
WHERE article_id IN (SELECT id FROM tourist_faq_seed);

INSERT INTO help_article_tags (article_id, tag)
SELECT id, 'popular'
FROM tourist_faq_seed
UNION
SELECT id, category_tag
FROM tourist_faq_seed;
