-- Seed product-specific Q&A articles for the Inflap Help Center.

CREATE TEMP TABLE app_faq_categories_seed (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    title_ru TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_kk TEXT NOT NULL
);

INSERT INTO app_faq_categories_seed (id, slug, sort_order, title_ru, title_en, title_kk)
VALUES
    ('app_getting_started', 'app-getting-started', 130, 'Приложение Inflap', 'Inflap app', 'Inflap қолданбасы'),
    ('app_account_profile', 'app-account-profile', 140, 'Аккаунт и профиль', 'Account and profile', 'Аккаунт және профиль'),
    ('app_activities_excursions', 'app-activities-excursions', 150, 'Активности и экскурсии', 'Activities and excursions', 'Белсенділіктер және экскурсиялар'),
    ('app_chats_support', 'app-chats-support', 160, 'Чаты и поддержка', 'Chats and support', 'Чаттар және қолдау'),
    ('app_services_notifications', 'app-services-notifications', 170, 'Сервисы и уведомления', 'Services and notifications', 'Сервистер және хабарламалар');

CREATE TEMP TABLE app_faq_seed (
    id TEXT PRIMARY KEY,
    category_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    category_tag TEXT NOT NULL,
    title_ru TEXT NOT NULL,
    short_ru TEXT NOT NULL,
    body_ru TEXT NOT NULL,
    title_en TEXT NOT NULL,
    short_en TEXT NOT NULL,
    body_en TEXT NOT NULL,
    title_kk TEXT NOT NULL,
    short_kk TEXT NOT NULL,
    body_kk TEXT NOT NULL
);

INSERT INTO app_faq_seed (
    id,
    category_id,
    slug,
    sort_order,
    category_tag,
    title_ru,
    short_ru,
    body_ru,
    title_en,
    short_en,
    body_en,
    title_kk,
    short_kk,
    body_kk
)
VALUES
    ('app-faq-001', 'app_getting_started', 'what-is-inflap', 1, 'getting_started',
     $ru$Что можно делать в Inflap?$ru$,
     $ru$Inflap помогает планировать поездку, находить места, активности, экскурсии, пользоваться сервисами и быстро обращаться в поддержку.$ru$,
     $ru$В Inflap можно искать интересные места, смотреть активности и экскурсии, общаться в чатах, пользоваться курсами валют, получать уведомления и открывать Центр помощи. Если ответа нет в Q&A, создайте чат поддержки: сотрудник увидит контекст обращения и сможет продолжить переписку.$ru$,
     $en$What can I do in Inflap?$en$,
     $en$Inflap helps you plan trips, find places, activities and excursions, use travel services and contact support quickly.$en$,
     $en$In Inflap you can discover places, browse activities and excursions, chat, use currency rates, receive notifications and open the Help Center. If Q&A does not answer your question, start a support chat so the team can see the context and continue the conversation.$en$,
     $kk$Inflap-та не істеуге болады?$kk$,
     $kk$Inflap сапарды жоспарлауға, орындарды, белсенділіктерді, экскурсияларды табуға, сервистерді қолдануға және қолдауға тез жазуға көмектеседі.$kk$,
     $kk$Inflap-та қызықты орындарды табуға, белсенділіктер мен экскурсияларды қарауға, чатта жазысуға, валюта бағамын көруге, хабарлама алуға және Көмек орталығын ашуға болады. Q&A жауап бермесе, қолдау чатын бастаңыз: қызметкер өтініш контекстін көріп, сөйлесуді жалғастырады.$kk$),
    ('app-faq-002', 'app_getting_started', 'choose-city-or-all-cities', 2, 'getting_started',
     $ru$Как выбрать город или смотреть “Все города”?$ru$,
     $ru$Выберите конкретный город для локальных рекомендаций или “Все города”, чтобы смотреть общий каталог без привязки к одному месту.$ru$,
     $ru$Фильтр города влияет на места, активности, экскурсии и ленту. Если вы еще не решили, куда поехать, режим “Все города” удобен для поиска идей. Если результаты кажутся слишком широкими, выберите страну или город, чтобы рекомендации стали точнее.$ru$,
     $en$How do I choose a city or view “All cities”?$en$,
     $en$Choose a specific city for local recommendations or “All cities” to browse the general catalog without one location.$en$,
     $en$The city filter affects places, activities, excursions and the feed. “All cities” is useful when you are still exploring ideas. If results feel too broad, choose a country or city to make recommendations more precise.$en$,
     $kk$Қаланы қалай таңдаймын немесе “Барлық қалаларды” қалай қараймын?$kk$,
     $kk$Жергілікті ұсыныстар үшін нақты қаланы таңдаңыз немесе бір орынға байланбай жалпы каталогты көру үшін “Барлық қалаларды” қолданыңыз.$kk$,
     $kk$Қала сүзгісі орындарға, белсенділіктерге, экскурсияларға және лентаға әсер етеді. Қайда баратыныңызды әлі таңдамаған болсаңыз, “Барлық қалалар” идея іздеуге ыңғайлы. Нәтиже тым кең болса, елді немесе қаланы таңдаңыз.$kk$),
    ('app-faq-003', 'app_getting_started', 'why-create-account', 3, 'getting_started',
     $ru$Зачем нужен аккаунт?$ru$,
     $ru$Аккаунт нужен для персональных функций: чатов, поддержки, активности профиля, уведомлений и сохранения вашего контекста.$ru$,
     $ru$Без аккаунта часть публичной информации может быть доступна, но персональные действия требуют авторизации. Так приложение понимает, кому показывать обращения в поддержку, непрочитанные чаты, уведомления, заявки гида и настройки профиля.$ru$,
     $en$Why do I need an account?$en$,
     $en$An account is needed for personal features: chats, support, profile activity, notifications and keeping your context.$en$,
     $en$Some public content may be available without an account, but personal actions require sign-in. This lets the app show your support conversations, unread chats, notifications, guide applications and profile settings correctly.$en$,
     $kk$Аккаунт не үшін керек?$kk$,
     $kk$Аккаунт жеке функциялар үшін керек: чаттар, қолдау, профиль әрекеттері, хабарламалар және контексті сақтау.$kk$,
     $kk$Кейбір ашық ақпарат аккаунтсыз қолжетімді болуы мүмкін, бірақ жеке әрекеттерге кіру қажет. Осылай қолданба қолдау сөйлесулерін, оқылмаған чаттарды, хабарламаларды, гид өтінімдерін және профиль баптауларын дұрыс көрсетеді.$kk$),
    ('app-faq-004', 'app_getting_started', 'search-help-center', 4, 'getting_started',
     $ru$Как лучше искать ответ в Центре помощи?$ru$,
     $ru$Начните с коротких слов: “чат”, “оплата”, “гид”, “уведомления”, “валюта”, “город” или название нужного сервиса.$ru$,
     $ru$Поиск работает по вопросам и ответам. Если вы не нашли ответ, попробуйте другое слово или откройте категорию. Если вопрос связан с конкретной активностью, экскурсией или пользователем, лучше создать чат поддержки или написать организатору из карточки.$ru$,
     $en$How should I search the Help Center?$en$,
     $en$Start with short keywords such as “chat”, “payment”, “guide”, “notifications”, “currency”, “city” or the service name.$en$,
     $en$Search looks through questions and answers. If you do not find an answer, try another keyword or open a category. If the question is about a specific activity, excursion or user, start a support chat or message the organizer from the card.$en$,
     $kk$Көмек орталығында қалай іздеген дұрыс?$kk$,
     $kk$“чат”, “төлем”, “гид”, “хабарлама”, “валюта”, “қала” сияқты қысқа сөздерден немесе сервис атауынан бастаңыз.$kk$,
     $kk$Іздеу сұрақтар мен жауаптар бойынша жұмыс істейді. Жауап табылмаса, басқа сөзді қолданыңыз немесе категорияны ашыңыз. Сұрақ нақты белсенділік, экскурсия немесе пайдаланушы туралы болса, қолдау чатын бастаған немесе карточкадан ұйымдастырушыға жазған дұрыс.$kk$),
    ('app-faq-005', 'app_getting_started', 'outdated-or-wrong-info', 5, 'getting_started',
     $ru$Что делать, если место, курс, активность или информация устарели?$ru$,
     $ru$Сообщите в поддержку и укажите, что именно устарело: название, адрес, дата, цена, расписание, курс или описание.$ru$,
     $ru$Мы быстрее исправим данные, если вы приложите ссылку на экран, скриншот или короткое объяснение. Для мест полезны адрес и город, для активностей и экскурсий — дата, организатор и название карточки.$ru$,
     $en$What if a place, rate, activity or detail is outdated?$en$,
     $en$Tell support what is outdated: name, address, date, price, schedule, exchange rate or description.$en$,
     $en$We can fix data faster if you include the screen link, a screenshot or a short explanation. For places, add address and city; for activities or excursions, add date, organizer and card title.$en$,
     $kk$Орын, бағам, белсенділік немесе ақпарат ескірсе не істеу керек?$kk$,
     $kk$Қолдауға нақты не ескіргенін жазыңыз: атауы, мекенжайы, күні, бағасы, кестесі, курс немесе сипаттамасы.$kk$,
     $kk$Экран сілтемесін, скриншотты немесе қысқа түсініктемені қоссаңыз, деректі тезірек түзетеміз. Орын үшін мекенжай мен қала, белсенділік/экскурсия үшін күн, ұйымдастырушы және карточка атауы пайдалы.$kk$),
    ('app-faq-006', 'app_getting_started', 'personalized-recommendations', 6, 'getting_started',
     $ru$Почему рекомендации могут отличаться у разных пользователей?$ru$,
     $ru$Рекомендации зависят от города, выбранных фильтров, активности в приложении и доступности данных.$ru$,
     $ru$Если вы переключили город, страну или режим “Все города”, выдача может измениться. Также влияют новые места, активности, популярность карточек и технические ограничения сервисов. Если кажется, что рекомендация неуместна, напишите в поддержку.$ru$,
     $en$Why can recommendations differ between users?$en$,
     $en$Recommendations depend on city, filters, app activity and available data.$en$,
     $en$Changing city, country or “All cities” can change the results. New places, activities, card popularity and service limitations may also affect ranking. If a recommendation feels wrong, contact support.$en$,
     $kk$Неге ұсыныстар әр пайдаланушыда әртүрлі болуы мүмкін?$kk$,
     $kk$Ұсыныстар қалаға, сүзгілерге, қолданбадағы әрекетке және қолжетімді деректерге байланысты.$kk$,
     $kk$Қаланы, елді немесе “Барлық қалалар” режимін ауыстырсаңыз, нәтиже өзгереді. Жаңа орындар, белсенділіктер, карточка танымалдығы және сервистік шектеулер де әсер етеді. Ұсыныс орынсыз көрінсе, қолдауға жазыңыз.$kk$),
    ('app-faq-007', 'app_account_profile', 'edit-profile-nickname-photo', 7, 'account',
     $ru$Как изменить никнейм, имя или фото профиля?$ru$,
     $ru$Откройте профиль и перейдите в редактирование. Изменения могут проверяться, если они влияют на публичный профиль или статус гида.$ru$,
     $ru$Используйте понятный никнейм и фото, по которому вас узнают другие участники. Не указывайте чужие данные, документы, номера карт или приватную информацию в публичных полях профиля.$ru$,
     $en$How do I change my nickname, name or profile photo?$en$,
     $en$Open your profile and go to edit mode. Some changes may be reviewed if they affect a public profile or guide status.$en$,
     $en$Use a clear nickname and a photo that helps others recognize you. Do not put other people’s data, documents, card numbers or private information into public profile fields.$en$,
     $kk$Никнеймді, атымды немесе профиль фотосын қалай өзгертемін?$kk$,
     $kk$Профильді ашып, өңдеу бөліміне өтіңіз. Кей өзгерістер ашық профильге немесе гид статусына әсер етсе, тексерілуі мүмкін.$kk$,
     $kk$Басқа қатысушылар танитындай түсінікті никнейм және фото қолданыңыз. Ашық профильге бөтен дерек, құжат, карта нөмірі немесе жеке ақпарат жазбаңыз.$kk$),
    ('app-faq-008', 'app_account_profile', 'guide-status-application', 8, 'account',
     $ru$Как подать заявку на статус гида?$ru$,
     $ru$Откройте профиль и заполните заявку гида, если эта функция доступна вашему аккаунту.$ru$,
     $ru$Укажите реальный опыт, языки, города, тематики экскурсий и документы, если они запрашиваются. Пока заявка на рассмотрении, аккаунт не считается подтвержденным гидом, но поддержка может видеть, что вы подали заявку.$ru$,
     $en$How do I apply for guide status?$en$,
     $en$Open your profile and fill in the guide application if this feature is available for your account.$en$,
     $en$Add real experience, languages, cities, excursion topics and documents if requested. While the application is under review, the account is not treated as a verified guide, although support can see that you applied.$en$,
     $kk$Гид статусына қалай өтінім беремін?$kk$,
     $kk$Профильді ашып, аккаунтыңызға қолжетімді болса, гид өтінімін толтырыңыз.$kk$,
     $kk$Нақты тәжірибені, тілдерді, қалаларды, экскурсия тақырыптарын және сұралса құжаттарды көрсетіңіз. Өтінім қаралып жатқанда аккаунт расталған гид болып саналмайды, бірақ қолдау өтінім жіберілгенін көре алады.$kk$),
    ('app-faq-009', 'app_account_profile', 'guide-application-pending', 9, 'account',
     $ru$Почему моя заявка гида все еще на рассмотрении?$ru$,
     $ru$Проверка может занимать время, если нужно сверить профиль, опыт, документы или безопасность предложений.$ru$,
     $ru$Пока заявка не одобрена, в поддержке ваш сегмент не должен считаться “подтвержденный гид”. Если ожидание слишком долгое, напишите в поддержку и укажите, когда отправили заявку и какой город/тематику выбрали.$ru$,
     $en$Why is my guide application still under review?$en$,
     $en$Review may take time if the team needs to check profile details, experience, documents or offer safety.$en$,
     $en$Until the application is approved, support should not treat your segment as “verified guide”. If the wait is too long, contact support and include when you applied and which city/topic you selected.$en$,
     $kk$Неге гид өтінімім әлі қаралып жатыр?$kk$,
     $kk$Профиль, тәжірибе, құжаттар немесе ұсыныстардың қауіпсіздігін тексеру уақыт алуы мүмкін.$kk$,
     $kk$Өтінім мақұлданғанға дейін қолдау сізді “расталған гид” сегменті ретінде есептемеуі керек. Күту ұзақ болса, қашан жібергеніңізді және қай қала/тақырыпты таңдағаныңызды көрсетіп, қолдауға жазыңыз.$kk$),
    ('app-faq-010', 'app_account_profile', 'profile-privacy', 10, 'account',
     $ru$Какая информация профиля видна другим пользователям?$ru$,
     $ru$Обычно другим видны публичные данные: никнейм, фото, описание и публичная активность, если она включена.$ru$,
     $ru$Не публикуйте в профиле паспортные данные, адрес, телефон, номер карты или другие чувствительные данные. Для вопросов по приватности, удалению данных или спорным публичным полям обратитесь в поддержку.$ru$,
     $en$What profile information can other users see?$en$,
     $en$Other users usually see public data: nickname, photo, bio and public activity if enabled.$en$,
     $en$Do not publish passport data, address, phone number, card number or other sensitive details in your profile. For privacy, data deletion or public-field concerns, contact support.$en$,
     $kk$Профильдегі қандай ақпарат басқа пайдаланушыларға көрінеді?$kk$,
     $kk$Әдетте басқа пайдаланушылар ашық деректерді көреді: никнейм, фото, сипаттама және қосылған болса ашық әрекеттер.$kk$,
     $kk$Профильде паспорт деректерін, мекенжайды, телефонды, карта нөмірін немесе басқа сезімтал ақпаратты жарияламаңыз. Құпиялылық, дерек жою немесе ашық өрістер бойынша қолдауға жазыңыз.$kk$),
    ('app-faq-011', 'app_account_profile', 'cannot-login', 11, 'account',
     $ru$Что делать, если не получается войти в аккаунт?$ru$,
     $ru$Проверьте интернет, правильность номера или способа входа, затем попробуйте повторить вход позже.$ru$,
     $ru$Если вход не восстанавливается, напишите в поддержку и укажите способ входа, примерное время ошибки, устройство и что видите на экране. Не отправляйте пароль, одноразовые коды и полные токены.$ru$,
     $en$What should I do if I cannot log in?$en$,
     $en$Check your internet connection, phone number or sign-in method, then try again later.$en$,
     $en$If sign-in still fails, contact support and include the sign-in method, approximate time, device and what you see on screen. Do not send passwords, one-time codes or full tokens.$en$,
     $kk$Аккаунтқа кіре алмасам не істеймін?$kk$,
     $kk$Интернетті, нөмірді немесе кіру тәсілін тексеріп, кейін қайта көріңіз.$kk$,
     $kk$Кіру қалпына келмесе, қолдауға кіру тәсілін, қате уақытын, құрылғыны және экранда не көрінетінін жазыңыз. Құпиясөз, бір реттік код немесе толық токен жібермеңіз.$kk$),
    ('app-faq-012', 'app_account_profile', 'account-data-delete', 12, 'account',
     $ru$Как попросить удалить или исправить данные аккаунта?$ru$,
     $ru$Если нужной настройки нет в профиле, создайте чат поддержки и опишите, какие данные нужно удалить или исправить.$ru$,
     $ru$Поддержка может запросить уточнения для защиты аккаунта. Мы не удаляем чужие данные по просьбе третьих лиц и не принимаем чувствительные документы в обычный чат без необходимости.$ru$,
     $en$How do I request account data deletion or correction?$en$,
     $en$If the setting is not available in your profile, start a support chat and describe which data should be deleted or corrected.$en$,
     $en$Support may ask clarifying questions to protect the account. We do not delete someone else’s data on behalf of third parties and do not request sensitive documents in regular chat unless necessary.$en$,
     $kk$Аккаунт деректерін жоюды немесе түзетуді қалай сұраймын?$kk$,
     $kk$Профильде қажет баптау болмаса, қолдау чатын ашып, қандай деректі жою немесе түзету керек екенін жазыңыз.$kk$,
     $kk$Аккаунтты қорғау үшін қолдау нақтылау сұрауы мүмкін. Үшінші тұлғаның өтінішімен бөтен деректі жоймаймыз және қажет болмаса сезімтал құжаттарды кәдімгі чатта сұрамаймыз.$kk$),
    ('app-faq-013', 'app_activities_excursions', 'activity-vs-excursion', 13, 'activities',
     $ru$Чем активность отличается от экскурсии?$ru$,
     $ru$Активность обычно проще и может быть встречей или событием, а экскурсия чаще ведется гидом и имеет маршрут, программу и правила участия.$ru$,
     $ru$Перед участием смотрите описание, дату, место встречи, организатора, язык, цену и условия отмены. Если формат непонятен, задайте вопрос организатору или гиду в чате карточки.$ru$,
     $en$What is the difference between an activity and an excursion?$en$,
     $en$An activity is often a simpler meetup or event, while an excursion is usually guided and has a route, program and participation rules.$en$,
     $en$Before joining, check description, date, meeting point, organizer, language, price and cancellation terms. If the format is unclear, ask the organizer or guide in the card chat.$en$,
     $kk$Белсенділік пен экскурсияның айырмашылығы қандай?$kk$,
     $kk$Белсенділік көбіне қарапайым кездесу немесе оқиға, ал экскурсия әдетте гидпен өтеді және маршруты, бағдарламасы, қатысу ережесі болады.$kk$,
     $kk$Қатысар алдында сипаттаманы, күнді, кездесу орнын, ұйымдастырушыны, тілді, бағаны және бас тарту шартын қараңыз. Формат түсініксіз болса, карточка чатында ұйымдастырушыға немесе гидке сұрақ қойыңыз.$kk$),
    ('app-faq-014', 'app_activities_excursions', 'ask-organizer-or-guide', 14, 'activities',
     $ru$Как задать вопрос организатору или гиду?$ru$,
     $ru$Откройте карточку активности или экскурсии и напишите в чат, если он доступен.$ru$,
     $ru$Вопрос лучше задавать до участия или оплаты: уточните место встречи, язык, длительность, что включено, возрастные ограничения, погоду и что взять с собой. Если организатор не отвечает или есть спор, создайте чат поддержки.$ru$,
     $en$How do I ask an organizer or guide a question?$en$,
     $en$Open the activity or excursion card and write in the chat if it is available.$en$,
     $en$Ask before joining or paying: clarify meeting point, language, duration, what is included, age limits, weather and what to bring. If the organizer does not reply or there is a dispute, start a support chat.$en$,
     $kk$Ұйымдастырушыға немесе гидке қалай сұрақ қоямын?$kk$,
     $kk$Белсенділік немесе экскурсия карточкасын ашып, қолжетімді болса чатқа жазыңыз.$kk$,
     $kk$Қатысуға немесе төлеуге дейін сұраған дұрыс: кездесу орны, тіл, ұзақтығы, не кіреді, жас шектеуі, ауа райы және не алу керектігін нақтылаңыз. Ұйымдастырушы жауап бермесе немесе дау болса, қолдау чатын бастаңыз.$kk$),
    ('app-faq-015', 'app_activities_excursions', 'check-before-joining', 15, 'activities',
     $ru$Что проверить перед участием в активности или экскурсии?$ru$,
     $ru$Проверьте дату, время, город, точку встречи, цену, что включено, ограничения, язык и правила отмены.$ru$,
     $ru$Если нужна специальная подготовка, питание, документы, удобная обувь или страховка, это должно быть понятно до участия. Для сложных маршрутов уточните уровень нагрузки и запасной план при плохой погоде.$ru$,
     $en$What should I check before joining an activity or excursion?$en$,
     $en$Check date, time, city, meeting point, price, inclusions, restrictions, language and cancellation rules.$en$,
     $en$If special preparation, food, documents, comfortable shoes or insurance are needed, clarify this before joining. For complex routes, ask about difficulty level and the bad-weather backup plan.$en$,
     $kk$Белсенділікке немесе экскурсияға қатысар алдында нені тексеру керек?$kk$,
     $kk$Күнін, уақытын, қаласын, кездесу орнын, бағасын, не кіретінін, шектеулерін, тілін және бас тарту ережесін тексеріңіз.$kk$,
     $kk$Арнайы дайындық, тамақ, құжат, ыңғайлы аяқ киім немесе сақтандыру керек болса, оны қатысуға дейін нақтылаңыз. Күрделі маршрутта жүктеме деңгейін және ауа райы нашар болса қосымша жоспарды сұраңыз.$kk$),
    ('app-faq-016', 'app_activities_excursions', 'meeting-point-changed', 16, 'activities',
     $ru$Что делать, если изменились время или место встречи?$ru$,
     $ru$Проверьте чат карточки и уведомления, затем подтвердите у организатора актуальную информацию.$ru$,
     $ru$Если изменение критичное и вы не можете участвовать, напишите организатору как можно раньше. При споре сохраните переписку и создайте обращение в поддержку, указав название карточки и дату.$ru$,
     $en$What if the meeting time or place changes?$en$,
     $en$Check the card chat and notifications, then confirm the current details with the organizer.$en$,
     $en$If the change is critical and you cannot join, message the organizer as early as possible. If there is a dispute, keep the chat history and contact support with the card title and date.$en$,
     $kk$Кездесу уақыты немесе орны өзгерсе не істеу керек?$kk$,
     $kk$Карточка чатын және хабарламаларды тексеріп, ұйымдастырушыдан өзекті ақпаратты растаңыз.$kk$,
     $kk$Өзгеріс маңызды болып, қатыса алмасаңыз, ұйымдастырушыға мүмкіндігінше ерте жазыңыз. Дау болса, хат алмасуды сақтап, карточка атауы мен күнін көрсетіп қолдауға жазыңыз.$kk$),
    ('app-faq-017', 'app_activities_excursions', 'cancel-or-cannot-attend', 17, 'activities',
     $ru$Что делать, если я не могу прийти?$ru$,
     $ru$Откройте карточку или чат и предупредите организатора заранее.$ru$,
     $ru$Условия переноса, отмены или возврата зависят от конкретной активности, экскурсии и правил организатора. Чем раньше вы сообщите, тем выше шанс найти решение без спора.$ru$,
     $en$What if I cannot attend?$en$,
     $en$Open the card or chat and notify the organizer in advance.$en$,
     $en$Rescheduling, cancellation or refund terms depend on the specific activity, excursion and organizer rules. The earlier you tell them, the better the chance of solving it without a dispute.$en$,
     $kk$Қатыса алмасам не істеу керек?$kk$,
     $kk$Карточканы немесе чатты ашып, ұйымдастырушыға алдын ала хабарлаңыз.$kk$,
     $kk$Ауыстыру, бас тарту немесе қайтару шарттары нақты белсенділікке, экскурсияға және ұйымдастырушы ережесіне байланысты. Неғұрлым ерте айтсаңыз, даусыз шешім табу мүмкіндігі жоғары.$kk$),
    ('app-faq-018', 'app_activities_excursions', 'choose-safe-guide-activity', 18, 'activities',
     $ru$Как выбрать безопасную активность или гида?$ru$,
     $ru$Смотрите описание, профиль организатора, условия, требования к участникам и задавайте уточняющие вопросы до участия.$ru$,
     $ru$Осторожно относитесь к просьбам перевести деньги вне приложения, отправить документы в личный чат или перейти по подозрительным ссылкам. Если карточка кажется опасной или вводящей в заблуждение, пожалуйтесь в поддержку.$ru$,
     $en$How do I choose a safe activity or guide?$en$,
     $en$Review the description, organizer profile, terms, participant requirements and ask questions before joining.$en$,
     $en$Be careful with requests to pay outside the app, send documents in private chat or open suspicious links. If a card seems unsafe or misleading, report it to support.$en$,
     $kk$Қауіпсіз белсенділікті немесе гидті қалай таңдаймын?$kk$,
     $kk$Сипаттаманы, ұйымдастырушы профилін, шарттарды, қатысушы талаптарын қарап, қатысар алдында сұрақ қойыңыз.$kk$,
     $kk$Қолданбадан тыс ақша аудару, жеке чатқа құжат жіберу немесе күмәнді сілтемеге өту туралы өтініштерге сақ болыңыз. Карточка қауіпті немесе адастыратын көрінсе, қолдауға шағымданыңыз.$kk$),
    ('app-faq-019', 'app_chats_support', 'where-are-chats-and-unread-badge', 19, 'support',
     $ru$Где находятся чаты и что означает счетчик?$ru$,
     $ru$Чаты находятся в отдельном разделе приложения, а счетчик показывает количество чатов с непрочитанными сообщениями.$ru$,
     $ru$Счетчик показывает не общее число сообщений, а количество диалогов, где есть что прочитать. Если сообщений больше 99, счетчик может отображаться как “99+”, чтобы не перегружать интерфейс.$ru$,
     $en$Where are chats and what does the badge mean?$en$,
     $en$Chats are in a dedicated app section, and the badge shows how many chats have unread messages.$en$,
     $en$The badge shows the number of conversations with unread messages, not the total message count. If there are more than 99, it may show “99+” to keep the interface readable.$en$,
     $kk$Чаттар қайда және счетчик нені білдіреді?$kk$,
     $kk$Чаттар қолданбаның жеке бөлімінде, ал счетчик оқылмаған хабарламасы бар чаттар санын көрсетеді.$kk$,
     $kk$Счетчик барлық хабарлама санын емес, оқылмағаны бар диалогтар санын көрсетеді. 99-дан көп болса, интерфейс ыңғайлы болуы үшін “99+” болып көрінуі мүмкін.$kk$),
    ('app-faq-020', 'app_chats_support', 'chat-messages-not-in-notifications', 20, 'support',
     $ru$Почему сообщения из чатов не отображаются в разделе уведомлений?$ru$,
     $ru$Сообщения обычных, активностных и экскурсионных чатов показываются через счетчик в разделе “Чаты”, а не как отдельные уведомления.$ru$,
     $ru$Так уведомления не превращаются в дубль переписки. В уведомлениях остаются события, на которые нужно обратить внимание отдельно, например ответ поддержки, важное изменение или системное сообщение.$ru$,
     $en$Why are chat messages not shown in Notifications?$en$,
     $en$Regular, activity and excursion chat messages are shown through the Chats badge, not as separate notification items.$en$,
     $en$This prevents Notifications from duplicating conversations. Notifications stay focused on events that need separate attention, such as support replies, important changes or system messages.$en$,
     $kk$Неге чат хабарламалары Хабарламалар бөлімінде көрінбейді?$kk$,
     $kk$Кәдімгі, белсенділік және экскурсия чаттарының хабарламалары жеке notification емес, “Чаттар” бөліміндегі счетчик арқылы көрсетіледі.$kk$,
     $kk$Осылай Хабарламалар бөлімі хат алмасудың көшірмесіне айналмайды. Онда қолдау жауабы, маңызды өзгеріс немесе жүйелік хабар сияқты бөлек назар қажет оқиғалар қалады.$kk$),
    ('app-faq-021', 'app_chats_support', 'support-chat-how-it-works', 21, 'support',
     $ru$Как работает чат поддержки?$ru$,
     $ru$Если Q&A не помог, создайте чат поддержки. Переписка сохраняется в одном контексте, чтобы вам не приходилось повторять историю заново.$ru$,
     $ru$Сотрудник поддержки отвечает из админки, а вы видите ответ в приложении. Если поддержка ответила, вы должны получить push или in-app notification, чтобы не возвращаться в чат вручную.$ru$,
     $en$How does support chat work?$en$,
     $en$If Q&A does not help, start a support chat. The conversation keeps one context so you do not have to repeat the story.$en$,
     $en$A support employee replies from the admin panel, and you see the answer in the app. When support replies, you should receive a push or in-app notification so you do not have to keep checking manually.$en$,
     $kk$Қолдау чаты қалай жұмыс істейді?$kk$,
     $kk$Q&A көмектеспесе, қолдау чатын бастаңыз. Сөйлесу бір контексте сақталады, сондықтан оқиғаны қайта-қайта түсіндірудің қажеті жоқ.$kk$,
     $kk$Қолдау қызметкері админкадан жауап береді, ал сіз жауапты қолданбада көресіз. Қолдау жауап берсе, чатқа қолмен қайта кірмеу үшін push немесе in-app notification келуі керек.$kk$),
    ('app-faq-022', 'app_chats_support', 'what-to-write-to-support', 22, 'support',
     $ru$Что написать в поддержку, чтобы вопрос решили быстрее?$ru$,
     $ru$Опишите цель, что произошло, где именно в приложении, когда, и приложите скриншот, если он помогает.$ru$,
     $ru$Для активности или экскурсии укажите название, дату, город и организатора. Для оплаты — сумму, валюту и примерное время. Для технической ошибки — устройство, версию приложения, шаги воспроизведения и текст ошибки. Не отправляйте пароли и одноразовые коды.$ru$,
     $en$What should I write to support to solve the issue faster?$en$,
     $en$Describe your goal, what happened, where in the app, when, and attach a screenshot if useful.$en$,
     $en$For an activity or excursion, include title, date, city and organizer. For payment, include amount, currency and approximate time. For a technical issue, include device, app version, reproduction steps and error text. Do not send passwords or one-time codes.$en$,
     $kk$Мәселе тезірек шешілуі үшін қолдауға не жазу керек?$kk$,
     $kk$Мақсатыңызды, не болғанын, қолданбаның қай жерінде және қашан болғанын жазыңыз, қажет болса скриншот қосыңыз.$kk$,
     $kk$Белсенділік немесе экскурсия үшін атауын, күнін, қаласын және ұйымдастырушыны көрсетіңіз. Төлем үшін соманы, валютаны және шамамен уақытын жазыңыз. Техникалық қате үшін құрылғыны, қолданба нұсқасын, қайталау қадамдарын және қате мәтінін беріңіз. Құпиясөз немесе бір реттік код жібермеңіз.$kk$),
    ('app-faq-023', 'app_chats_support', 'rate-support', 23, 'support',
     $ru$Зачем оценивать поддержку?$ru$,
     $ru$Оценка помогает понять, насколько полезным был ответ и где нужно улучшить процесс поддержки.$ru$,
     $ru$Если проблема решена, поставьте оценку и при желании добавьте комментарий. Если проблема не решена, лучше сначала продолжить чат или создать новое обращение, чтобы сотрудник увидел контекст.$ru$,
     $en$Why should I rate support?$en$,
     $en$Rating helps us understand how useful the answer was and where the support process needs improvement.$en$,
     $en$If the issue is solved, rate the conversation and optionally add a comment. If it is not solved, continue the chat or start a new request so the team can see the context.$en$,
     $kk$Қолдауды не үшін бағалау керек?$kk$,
     $kk$Баға жауаптың қаншалықты пайдалы болғанын және қолдау процесін қай жерде жақсарту керектігін түсінуге көмектеседі.$kk$,
     $kk$Мәселе шешілсе, бағалап, қаласаңыз пікір қалдырыңыз. Шешілмесе, қызметкер контекстті көруі үшін чатты жалғастырған немесе жаңа өтініш ашқан дұрыс.$kk$),
    ('app-faq-024', 'app_chats_support', 'closed-support-chat-new-question', 24, 'support',
     $ru$Что делать, если обращение закрыто, но появился новый вопрос?$ru$,
     $ru$Если вопрос новый или старая проблема вернулась, напишите новое сообщение — приложение должно создать или продолжить актуальное обращение.$ru$,
     $ru$Не смешивайте разные темы в одном сообщении, если они не связаны. Так поддержке проще назначить правильного сотрудника и не потерять важные детали.$ru$,
     $en$What if a support request is closed but I have a new question?$en$,
     $en$If the question is new or the old issue returned, send a new message so the app can create or continue the current request.$en$,
     $en$Avoid mixing unrelated topics in one message. This helps support assign the right employee and keep important details clear.$en$,
     $kk$Өтініш жабылған, бірақ жаңа сұрақ пайда болса не істеу керек?$kk$,
     $kk$Сұрақ жаңа болса немесе ескі мәселе қайта шықса, жаңа хабарлама жіберіңіз — қолданба өзекті өтінішті құруы немесе жалғастыруы керек.$kk$,
     $kk$Байланысы жоқ тақырыптарды бір хабарламаға араластырмаңыз. Бұл қолдауға дұрыс қызметкерді тағайындап, маңызды детальдарды жоғалтпауға көмектеседі.$kk$),
    ('app-faq-025', 'app_services_notifications', 'currency-converter-rates', 25, 'services',
     $ru$Как пользоваться курсами валют?$ru$,
     $ru$Откройте “Курсы валют”, выберите валюты и сумму. Курс служит ориентиром и может отличаться от курса банка или обменника.$ru$,
     $ru$Перед крупной покупкой проверяйте итоговую сумму у банка, платежной системы или обменника. Комиссии, weekend-rate, способ оплаты и страна карты могут менять фактический курс.$ru$,
     $en$How do I use currency rates?$en$,
     $en$Open Currency rates, choose currencies and amount. The rate is a reference and may differ from your bank or exchange office.$en$,
     $en$Before a large purchase, confirm the final amount with your bank, payment system or exchange office. Fees, weekend rates, payment method and card country can change the actual rate.$en$,
     $kk$Валюта бағамын қалай қолданамын?$kk$,
     $kk$“Валюта бағамын” ашып, валюталар мен соманы таңдаңыз. Курс бағдар ретінде беріледі және банк немесе айырбастау пункті курсынан өзгеше болуы мүмкін.$kk$,
     $kk$Ірі төлем алдында соңғы соманы банк, төлем жүйесі немесе айырбастау пунктінен тексеріңіз. Комиссия, демалыс күнгі курс, төлем тәсілі және карта елі нақты курсқа әсер етуі мүмкін.$kk$),
    ('app-faq-026', 'app_services_notifications', 'places-search-all-cities', 26, 'services',
     $ru$Как искать места?$ru$,
     $ru$Используйте поиск, категорию, город или режим “Все города”, если хотите посмотреть больше вариантов.$ru$,
     $ru$Если место не находится, попробуйте другое написание, английское название, категорию или город. Если информация неверная или место отсутствует, сообщите в поддержку с названием и городом.$ru$,
     $en$How do I search for places?$en$,
     $en$Use search, category, city or “All cities” if you want to browse more options.$en$,
     $en$If a place is not found, try another spelling, English name, category or city. If information is wrong or the place is missing, contact support with the name and city.$en$,
     $kk$Орындарды қалай іздеймін?$kk$,
     $kk$Іздеуді, категорияны, қаланы немесе көбірек нұсқа көру үшін “Барлық қалалар” режимін қолданыңыз.$kk$,
     $kk$Орын табылмаса, басқа жазылуын, ағылшынша атауын, категорияны немесе қаланы көріңіз. Ақпарат қате болса немесе орын жоқ болса, атауы мен қаласын көрсетіп қолдауға жазыңыз.$kk$),
    ('app-faq-027', 'app_services_notifications', 'notifications-read-status', 27, 'services',
     $ru$Как работают уведомления и отметка “прочитано”?$ru$,
     $ru$Уведомления помогают не пропустить важные события: ответ поддержки, системное сообщение или изменение, требующее внимания.$ru$,
     $ru$Когда вы открываете список уведомлений и видите элементы на экране, приложение может помечать их прочитанными. На кнопке уведомлений счетчик показывает количество непрочитанных уведомлений и при большом числе может отображать “99+”.$ru$,
     $en$How do notifications and read status work?$en$,
     $en$Notifications help you not miss important events: support replies, system messages or changes that need attention.$en$,
     $en$When you open a notification list and items become visible on screen, the app may mark them as read. The notification button badge shows unread notifications and may display “99+” for large counts.$en$,
     $kk$Хабарламалар және “оқылды” белгісі қалай жұмыс істейді?$kk$,
     $kk$Хабарламалар маңызды оқиғаларды өткізіп алмауға көмектеседі: қолдау жауабы, жүйелік хабар немесе назар қажет өзгеріс.$kk$,
     $kk$Хабарламалар тізімін ашып, элементтер экранда көрінгенде, қолданба оларды оқылды деп белгілеуі мүмкін. Хабарлама батырмасындағы счетчик оқылмаған хабарламалар санын көрсетеді және көп болса “99+” болуы мүмкін.$kk$),
    ('app-faq-028', 'app_services_notifications', 'support-reply-notification', 28, 'services',
     $ru$Как я узнаю, что поддержка ответила?$ru$,
     $ru$Когда сотрудник поддержки отвечает, вы должны увидеть push или in-app notification и перейти сразу в чат.$ru$,
     $ru$Если вы перешли из уведомления, приложение должно открыть чат ближе к последнему сообщению, а не в начало переписки. Если уведомления не приходят, проверьте разрешения уведомлений на устройстве и настройки приложения.$ru$,
     $en$How will I know that support replied?$en$,
     $en$When support replies, you should receive a push or in-app notification and go directly to the chat.$en$,
     $en$When opening from a notification, the app should show the chat near the latest message, not at the beginning. If notifications do not arrive, check device notification permissions and app settings.$en$,
     $kk$Қолдау жауап бергенін қалай білемін?$kk$,
     $kk$Қолдау қызметкері жауап берсе, push немесе in-app notification келіп, тікелей чатқа өте алуыңыз керек.$kk$,
     $kk$Хабарламадан ашқанда, қолданба чатты басынан емес, соңғы хабарламаға жақын жерден көрсетуі керек. Хабарлама келмесе, құрылғыдағы notification рұқсаттарын және қолданба баптауларын тексеріңіз.$kk$),
    ('app-faq-029', 'app_services_notifications', 'feed-and-community-recommendations', 29, 'services',
     $ru$Как работает лента и рекомендации?$ru$,
     $ru$Лента может учитывать город, страну, выбранные фильтры, актуальность контента и активность пользователей.$ru$,
     $ru$Если вы видите нерелевантный контент, смените город, фильтр или вкладку. Если контент нарушает правила, вводит в заблуждение или выглядит небезопасно, отправьте жалобу или напишите в поддержку.$ru$,
     $en$How do the feed and recommendations work?$en$,
     $en$The feed may consider city, country, filters, content freshness and user activity.$en$,
     $en$If content is not relevant, change city, filter or tab. If content violates rules, is misleading or unsafe, report it or contact support.$en$,
     $kk$Лента және ұсыныстар қалай жұмыс істейді?$kk$,
     $kk$Лента қала, ел, сүзгілер, контент өзектілігі және пайдаланушы белсенділігін ескеруі мүмкін.$kk$,
     $kk$Контент сәйкес болмаса, қаланы, сүзгіні немесе вкладканы өзгертіңіз. Контент ережені бұзса, адастырса немесе қауіпті көрінсе, шағым жіберіңіз немесе қолдауға жазыңыз.$kk$),
    ('app-faq-030', 'app_services_notifications', 'report-user-content-or-safety', 30, 'services',
     $ru$Как пожаловаться на пользователя, карточку или небезопасную ситуацию?$ru$,
     $ru$Используйте жалобу, если она есть на экране, или создайте чат поддержки с описанием ситуации.$ru$,
     $ru$Укажите ссылку или название карточки, никнейм пользователя, город, дату и что именно произошло. Если есть риск для жизни, здоровья или безопасности, сначала обратитесь в местные экстренные службы, а затем сообщите нам детали.$ru$,
     $en$How do I report a user, card or unsafe situation?$en$,
     $en$Use the report action if it is available on screen, or start a support chat and describe the situation.$en$,
     $en$Include the link or card title, user nickname, city, date and what happened. If there is a risk to life, health or safety, contact local emergency services first, then send us the details.$en$,
     $kk$Пайдаланушыға, карточкаға немесе қауіпті жағдайға қалай шағымданамын?$kk$,
     $kk$Экранда шағым батырмасы болса, соны қолданыңыз немесе қолдау чатын ашып, жағдайды сипаттаңыз.$kk$,
     $kk$Сілтемені немесе карточка атауын, пайдаланушы никнеймін, қаланы, күнді және не болғанын көрсетіңіз. Өмірге, денсаулыққа немесе қауіпсіздікке қауіп болса, алдымен жергілікті жедел қызметке хабарласып, кейін бізге детальдарды жіберіңіз.$kk$);

INSERT INTO help_categories (id, slug, sort_order, status, created_at, updated_at)
SELECT id, slug, sort_order, 'published', now(), now()
FROM app_faq_categories_seed
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    sort_order = EXCLUDED.sort_order,
    status = 'published',
    updated_at = now();

INSERT INTO help_category_translations (category_id, locale, title, created_at, updated_at)
SELECT id, 'ru', title_ru, now(), now()
FROM app_faq_categories_seed
UNION ALL
SELECT id, 'en', title_en, now(), now()
FROM app_faq_categories_seed
UNION ALL
SELECT id, 'kk', title_kk, now(), now()
FROM app_faq_categories_seed
ON CONFLICT (category_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    updated_at = now();

INSERT INTO help_articles (
    id,
    category_id,
    slug,
    status,
    version,
    owner_id,
    reviewer_id,
    visibility_rules,
    published_at,
    last_reviewed_at,
    created_at,
    updated_at
)
SELECT
    id,
    category_id,
    slug,
    'published',
    1,
    'system',
    'system',
    '{}'::jsonb,
    now(),
    now(),
    now(),
    now()
FROM app_faq_seed
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    slug = EXCLUDED.slug,
    status = 'published',
    version = help_articles.version + 1,
    owner_id = EXCLUDED.owner_id,
    reviewer_id = EXCLUDED.reviewer_id,
    visibility_rules = EXCLUDED.visibility_rules,
    published_at = COALESCE(help_articles.published_at, EXCLUDED.published_at),
    last_reviewed_at = EXCLUDED.last_reviewed_at,
    updated_at = now();

DELETE FROM help_article_translations
WHERE article_id IN (SELECT id FROM app_faq_seed);

INSERT INTO help_article_translations (article_id, locale, title, short_answer, body, created_at, updated_at)
SELECT id, 'ru', title_ru, short_ru, body_ru, now(), now()
FROM app_faq_seed
UNION ALL
SELECT id, 'en', title_en, short_en, body_en, now(), now()
FROM app_faq_seed
UNION ALL
SELECT id, 'kk', title_kk, short_kk, body_kk, now(), now()
FROM app_faq_seed;

DELETE FROM help_article_surfaces
WHERE article_id IN (SELECT id FROM app_faq_seed);

INSERT INTO help_article_surfaces (article_id, surface)
SELECT id, 'help_center'
FROM app_faq_seed
ON CONFLICT DO NOTHING;

DELETE FROM help_article_tags
WHERE article_id IN (SELECT id FROM app_faq_seed);

INSERT INTO help_article_tags (article_id, tag)
SELECT id, 'popular'
FROM app_faq_seed
UNION
SELECT id, 'app'
FROM app_faq_seed
UNION
SELECT id, category_tag
FROM app_faq_seed;
