-- Enrich city hubs with hiking and day-hike places.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_hiking_enrichment_resolved_places;
DROP TABLE IF EXISTS seed_hiking_enrichment_places;

CREATE TEMP TABLE seed_hiking_enrichment_places (
    country_code varchar(2) NOT NULL,
    price_currency varchar(3) NOT NULL,
    slug varchar(96) NOT NULL,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[],
    PRIMARY KEY (country_code, slug)
);

INSERT INTO seed_hiking_enrichment_places (
    country_code,
    price_currency,
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'KZ',
        'KZT',
        'alma-arasan-gorge',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.8,
        'Ущелье Алма-Арасан',
        'Alma-Arasan Gorge',
        'Алма-Арасан шатқалы',
        'Классический маршрут выходного дня из Алматы: горная река, хвойные склоны, термальная долина и удобный старт для спокойной прогулки по Заилийскому Алатау.',
        'A classic weekend route from Almaty with a mountain river, spruce slopes, a thermal valley and an easy trailhead for a relaxed Ile Alatau walk.',
        'Алматыдан шығатын демалыс күнінің классикалық бағыты: тау өзені, шыршалы беткейлер, термалды аңғар және Іле Алатауымен жеңіл серуенге ыңғайлы бастау нүктесі.',
        43.10900000,
        76.88700000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','day-hike','thermal-valley']::text[]
    ),
    (
        'KZ',
        'KZT',
        'gorelnik-gorge',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.7,
        'Ущелье Горельник',
        'Gorelnik Gorge',
        'Горельник шатқалы',
        'Живописная долина выше Медеу с лесной тропой, прохладным воздухом и быстрым доступом к нескольким маршрутам для хайкинга.',
        'A scenic valley above Medeu with a forest trail, cool mountain air and quick access to several hiking routes.',
        'Медеуден жоғары орналасқан көркем аңғар: орман соқпағы, салқын тау ауасы және бірнеше хайкинг бағытына жылдам шығу.',
        43.13800000,
        77.07400000,
        'AlmaAtaMedeu.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','medeu','day-hike']::text[]
    ),
    (
        'KZ',
        'KZT',
        'gorelnik-waterfalls',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.8,
        'Водопады Горельника',
        'Gorelnik Waterfalls',
        'Горельник сарқырамалары',
        'Популярная тропа от Медеу к каскадам Горельника: хороший вариант для полудневного похода с водой, лесом и панорамами ущелья.',
        'A popular trail from Medeu to the Gorelnik cascades, ideal for a half-day hike with water, forest and gorge views.',
        'Медеуден Горельник сарқырамаларына баратын танымал соқпақ: суы, орманы және шатқал көріністері бар жарты күндік маршрут.',
        43.12600000,
        77.07700000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','waterfalls','ile-alatau','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'furmanov-peak',
        'almaty',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.9,
        'Пик Фурманова',
        'Furmanov Peak',
        'Фурманов шыңы',
        'Один из самых узнаваемых хайкинговых маршрутов Алматы: набор высоты, открытые гребни и вид на город, Медеу и соседние вершины.',
        'A top recognizable hiking route in Almaty, with steady elevation gain, open ridges and views of the city, Medeu and nearby peaks.',
        'Алматыдағы ең танымал хайкинг бағыттарының бірі: биіктікке көтерілу, ашық жоталар және қалаға, Медеуге, көрші шыңдарға көрініс.',
        43.12800000,
        77.01800000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','summit','ile-alatau','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'aksai-skete',
        'almaty',
        'TEMPLE',
        0,
        4,
        'HOURS',
        4.6,
        'Аксайский скит',
        'Aksai Skete',
        'Ақсай скиті',
        'Тихое место в Аксайском ущелье с лесной дорогой, горным воздухом и маршрутом, который совмещает прогулку на природе и культурную остановку.',
        'A quiet place in Aksai Gorge with a forest road, mountain air and a route that combines nature walking with a cultural stop.',
        'Ақсай шатқалындағы тыныш орын: орман жолы, тау ауасы және табиғат серуені мен мәдени аялдаманы біріктіретін бағыт.',
        43.13800000,
        76.77800000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','aksai-gorge','cultural-hike','free-entry']::text[]
    ),
    (
        'KZ',
        'KZT',
        'kara-kungey-ridge',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Хребет Каракунгей',
        'Kara-Kungey Ridge',
        'Қаракүнгей жотасы',
        'Гребневой маршрут для опытных гостей Алматы: длинные виды на Заилийский Алатау, открытые склоны и ощущение большого горного дня.',
        'A ridge route for experienced Almaty visitors with long Ile Alatau views, open slopes and the feeling of a full mountain day.',
        'Алматыға келген тәжірибелі саяхатшыларға арналған жоталы бағыт: Іле Алатауына кең көріністер, ашық беткейлер және толық тау күнінің әсері.',
        43.08800000,
        77.05500000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ridge','ile-alatau','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'kok-zhailau-plateau',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.8,
        'Плато Кок-Жайляу',
        'Kok-Zhailau Plateau',
        'Көк-Жайлау үстірті',
        'Широкая зеленая седловина между городом и горами, куда идут за быстрым выходом на природу, видами на Алматы и мягким дневным маршрутом.',
        'A wide green saddle between the city and the mountains, popular for a quick nature escape, Almaty views and a gentle day route.',
        'Қала мен таудың арасындағы кең жасыл белес: табиғатқа тез шығуға, Алматы көріністеріне және жеңіл күндік маршрутқа қолайлы.',
        43.14100000,
        77.00400000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','plateau','ile-alatau','day-hike']::text[]
    ),
    (
        'KZ',
        'KZT',
        'butakovka-gorge',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.6,
        'Бутаковское ущелье',
        'Butakovka Gorge',
        'Бутаковка шатқалы',
        'Удобное ущелье на восточной стороне Алматы с лесной тропой, ручьем и спокойным маршрутом для первого знакомства с горами.',
        'An accessible gorge on the eastern side of Almaty with a forest trail, a stream and a calm route for a first mountain walk.',
        'Алматының шығыс жағындағы қолжетімді шатқал: орман соқпағы, бұлақ және таумен алғашқы танысуға арналған тыныш маршрут.',
        43.17400000,
        77.08200000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','gorge','ile-alatau','day-hike']::text[]
    ),
    (
        'KZ',
        'KZT',
        'kimasar-gorge',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.6,
        'Ущелье Кимасар',
        'Kimasar Gorge',
        'Қимасар шатқалы',
        'Маршрут рядом с Медеу и Кок-Жайляу: лес, родники и быстрый набор высоты без долгого трансфера из города.',
        'A route near Medeu and Kok-Zhailau with forest, springs and quick elevation gain without a long transfer from the city.',
        'Медеу мен Көк-Жайлау маңындағы бағыт: орман, бұлақтар және қаладан ұзақ жолсыз жылдам биіктікке көтерілу.',
        43.15100000,
        77.04800000,
        'AlmaAtaMedeu.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','gorge','ile-alatau','day-hike']::text[]
    ),
    (
        'KZ',
        'KZT',
        'kumbel-peak',
        'almaty',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.7,
        'Пик Кумбель',
        'Kumbel Peak',
        'Күмбел шыңы',
        'Панорамный маршрут над Кок-Жайляу с открытыми участками, видом на город и хорошей связкой для сильных однодневных походов.',
        'A panoramic route above Kok-Zhailau with open sections, city views and a strong option for full day hikes.',
        'Көк-Жайлау үстіндегі панорамалық бағыт: ашық учаскелер, қала көрінісі және толық күндік жорыққа жақсы нұсқа.',
        43.12400000,
        77.01700000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','summit','ile-alatau','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'sayram-ugam-national-park',
        'shymkent',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Сайрам-Угамский национальный парк',
        'Sayram-Ugam National Park',
        'Сайрам-Өгем ұлттық паркі',
        'Большая природная территория Западного Тянь-Шаня рядом с Шымкентом: каньоны, предгорья и маршруты от коротких прогулок до насыщенных походов.',
        'A large Western Tien Shan nature area near Shymkent with canyons, foothills and routes from short walks to demanding hikes.',
        'Шымкент маңындағы Батыс Тянь-Шаньның үлкен табиғи аумағы: каньондар, тау етектері және қысқа серуеннен күрделі жорыққа дейінгі маршруттар.',
        42.07000000,
        70.47000000,
        'Aksu-Zhabagly_Nature_Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','western-tien-shan','national-park','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'burgulyuk-gorge',
        'shymkent',
        'NATURE',
        0,
        5,
        'HOURS',
        4.5,
        'Ущелье Бургулюк',
        'Burgulyuk Gorge',
        'Бургулюк шатқалы',
        'Зеленое ущелье недалеко от Шымкента с водой, тенистыми участками и маршрутом для легкого похода в предгорьях.',
        'A green gorge near Shymkent with water, shaded sections and an easy foothill hiking route.',
        'Шымкент маңындағы жасыл шатқал: суы, көлеңкелі бөліктері және тау етегіндегі жеңіл жорық бағыты бар.',
        42.23500000,
        70.32200000,
        'Aksu-Zhabagly_Nature_Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','gorge','western-tien-shan','free-entry']::text[]
    ),
    (
        'KZ',
        'KZT',
        'kaskasu-gorge',
        'shymkent',
        'NATURE',
        0,
        6,
        'HOURS',
        4.6,
        'Ущелье Каскасу',
        'Kaskasu Gorge',
        'Қасқасу шатқалы',
        'Предгорный маршрут с альпийским настроением, прохладным воздухом и хорошей точкой старта для походов из Шымкента.',
        'A foothill route with an alpine mood, cool air and a strong trailhead for hikes from Shymkent.',
        'Альпілік әсері бар тау етегіндегі бағыт: салқын ауа және Шымкенттен шығатын жорықтарға ыңғайлы бастау нүктесі.',
        42.03000000,
        70.51000000,
        'Aksu-Zhabagly_Nature_Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','gorge','western-tien-shan','hiking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'bektau-ata',
        'balkhash',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Бектау-Ата',
        'Bektau-Ata',
        'Бектау-Ата',
        'Гранитный массив у Балхаша с гротами, скальными тропами и необычным ландшафтом, который хорошо подходит для активной остановки в степи.',
        'A granite massif near Balkhash with grottoes, rocky trails and an unusual landscape suited for an active stop in the steppe.',
        'Балқаш маңындағы гранитті массив: үңгірлер, жартасты соқпақтар және даладағы белсенді аялдамаға лайық ерекше ландшафт.',
        46.78700000,
        74.98000000,
        'Bektau-Ata.jpg',
        ARRAY['balkhash','karaganda']::text[],
        ARRAY['balkhash','karaganda']::text[],
        ARRAY['kazakhstan','granite','steppe','free-entry']::text[]
    ),
    (
        'KZ',
        'KZT',
        'karkaraly-national-park',
        'karaganda',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Каркаралинский национальный парк',
        'Karkaraly National Park',
        'Қарқаралы ұлттық паркі',
        'Лесные горы Центрального Казахстана с озерами, скалами и тропами для насыщенного походного дня из Караганды.',
        'Forested mountains of Central Kazakhstan with lakes, rocks and trails for a full hiking day from Karaganda.',
        'Орталық Қазақстанның орманды таулары: көлдер, жартастар және Қарағандыдан шығатын толық күндік жорықтарға арналған соқпақтар.',
        49.40500000,
        75.47500000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda']::text[],
        ARRAY['karaganda']::text[],
        ARRAY['kazakhstan','national-park','central-kazakhstan','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'sherkala-mountain',
        'aktau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.8,
        'Гора Шеркала',
        'Sherkala Mountain',
        'Шерқала тауы',
        'Символ Мангистау с выразительным силуэтом, пустынными панорамами и короткими тропами вокруг горы.',
        'A Mangystau landmark with a striking silhouette, desert panoramas and short trails around the mountain.',
        'Маңғыстаудың айқын силуэтті нышаны: шөл панорамалары және таудың айналасындағы қысқа соқпақтар.',
        44.25600000,
        52.00600000,
        'Sherkala_Mountain.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','desert','free-entry']::text[]
    ),
    (
        'KZ',
        'KZT',
        'tamshaly-canyon',
        'aktau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Каньон Тамшалы',
        'Tamshaly Canyon',
        'Тамшалы каньоны',
        'Короткий природный маршрут в Мангистау с каньоном, родником и контрастом пустынных стен и зелени у воды.',
        'A short Mangystau nature route with a canyon, spring and the contrast of desert walls and greenery near water.',
        'Маңғыстаудағы қысқа табиғи бағыт: каньон, бұлақ және шөл қабырғалары мен су маңындағы жасылдықтың айқын контрасты.',
        44.56700000,
        51.38200000,
        'Sherkala_Mountain.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','canyon','free-entry']::text[]
    ),
    (
        'KZ',
        'KZT',
        'west-altai-nature-reserve-trails',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.7,
        'Тропы Западно-Алтайского заповедника',
        'West Altai Nature Reserve Trails',
        'Батыс Алтай қорығы соқпақтары',
        'Таежные маршруты Восточного Казахстана с влажными лесами, горными ручьями и более северным характером походов.',
        'Taiga routes of East Kazakhstan with moist forests, mountain streams and a more northern hiking character.',
        'Шығыс Қазақстанның тайгалық бағыттары: ылғалды ормандар, тау бұлақтары және солтүстік сипаттағы жорық әсері.',
        50.33000000,
        83.55000000,
        'Katon-Karagay_National_Park.jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','nature-reserve','trekking']::text[]
    ),
    (
        'KZ',
        'KZT',
        'bolektau-viewpoint',
        'kokshetau',
        'NATURE',
        1000,
        3,
        'HOURS',
        4.6,
        'Смотровая Бөлектау',
        'Bolektau Viewpoint',
        'Бөлектау көрініс алаңы',
        'Короткий подъем в Бурабае с видом на озера, леса и скалы, удобный для легкой прогулки из Кокшетау.',
        'A short climb in Burabay with views of lakes, forests and rocks, convenient for an easy walk from Kokshetau.',
        'Бурабайдағы қысқа көтерілу: көлдерге, ормандарға және жартастарға көрініс, Көкшетаудан шығатын жеңіл серуенге ыңғайлы.',
        53.08500000,
        70.29200000,
        'Burabay_National_Park_Kazakhstan.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau']::text[],
        ARRAY['kazakhstan','burabay','viewpoint','day-hike']::text[]
    ),
    (
        'KG',
        'KGS',
        'kol-tor-lake-trek',
        'bishkek',
        'NATURE',
        100,
        8,
        'HOURS',
        4.8,
        'Трек к озеру Коль-Тор',
        'Kol-Tor Lake Trek',
        'Көл-Төр көліне трек',
        'Горный маршрут из Бишкека в сторону ущелья Кегеты с лесом, моренами и бирюзовым озером в конце подъема.',
        'A mountain route from Bishkek toward Kegety Gorge with forest, moraines and a turquoise lake at the end of the climb.',
        'Бішкектен Кегеті шатқалына қарай шығатын тау бағыты: орман, мореналар және көтерілу соңындағы көгілдір көл.',
        42.65000000,
        75.08400000,
        'Ala-Archa_National_Park_in_Kyrgyzstan.jpg',
        ARRAY['bishkek']::text[],
        ARRAY['bishkek']::text[],
        ARRAY['kyrgyzstan','kegety','alpine-lake','trekking']::text[]
    ),
    (
        'KG',
        'KGS',
        'altyn-arashan',
        'karakol',
        'NATURE',
        100,
        8,
        'HOURS',
        4.9,
        'Алтын-Арашан',
        'Altyn Arashan',
        'Алтын-Арашан',
        'Высокогорная долина у Каракола с горячими источниками, хвойными склонами и маршрутом, который часто становится главным походным впечатлением Иссык-Куля.',
        'A high mountain valley near Karakol with hot springs, spruce slopes and a route that often becomes a highlight of Issyk-Kul hiking.',
        'Қаракол маңындағы биік таулы аңғар: ыстық бұлақтар, шыршалы беткейлер және Ыстықкөлдегі басты жорық әсеріне айналатын бағыт.',
        42.35000000,
        78.56000000,
        'Altyn_Arashan_Kyrgyzstan.jpg',
        ARRAY['karakol']::text[],
        ARRAY['karakol']::text[],
        ARRAY['kyrgyzstan','issyk-kul','hot-springs','trekking']::text[]
    ),
    (
        'KG',
        'KGS',
        'ala-kul-lake-trek',
        'karakol',
        'NATURE',
        100,
        2,
        'DAYS',
        4.9,
        'Трек к озеру Ала-Куль',
        'Ala-Kul Lake Trek',
        'Ала-Көл көліне трек',
        'Знаковый трек над Караколом к бирюзовому высокогорному озеру, перевалу и большим видам Терскей Алатау.',
        'A signature trek above Karakol to a turquoise alpine lake, a high pass and wide Terskey Alatau views.',
        'Қаракол үстіндегі әйгілі трек: көгілдір биік таулы көл, асу және Теріскей Алатаудың кең көріністері.',
        42.31500000,
        78.53200000,
        'Ala-Kul_lake_Kyrgyzstan.jpg',
        ARRAY['karakol']::text[],
        ARRAY['karakol']::text[],
        ARRAY['kyrgyzstan','issyk-kul','alpine-lake','trekking']::text[]
    ),
    (
        'KG',
        'KGS',
        'karakol-gorge',
        'karakol',
        'NATURE',
        100,
        6,
        'HOURS',
        4.7,
        'Каракольское ущелье',
        'Karakol Gorge',
        'Қаракол шатқалы',
        'Широкое ущелье рядом с Караколом с хвойным лесом, рекой и маршрутами разной сложности для прогулок и трекинга.',
        'A broad gorge near Karakol with spruce forest, a river and routes of different difficulty for walks and trekking.',
        'Қаракол маңындағы кең шатқал: шыршалы орман, өзен және серуен мен треккингке арналған әртүрлі деңгейдегі бағыттар.',
        42.29500000,
        78.48000000,
        'Karakol_Gorge_Kyrgyzstan.jpg',
        ARRAY['karakol']::text[],
        ARRAY['karakol']::text[],
        ARRAY['kyrgyzstan','issyk-kul','gorge','hiking']::text[]
    ),
    (
        'UZ',
        'UZS',
        'greater-chimgan-trail',
        'chimgan',
        'NATURE',
        30000,
        6,
        'HOURS',
        4.7,
        'Тропа Большого Чимгана',
        'Greater Chimgan Trail',
        'Үлкен Шымған соқпағы',
        'Горный маршрут в Чаткальских отрогах недалеко от Ташкента с видами на Чимган, ущелья и курортную зону Чарвак.',
        'A mountain route in the Chatkal foothills near Tashkent with views of Chimgan, gorges and the Charvak resort area.',
        'Ташкент маңындағы Шатқал сілемдеріндегі тау бағыты: Шымғанға, шатқалдарға және Шарвак курорт аймағына көріністер.',
        41.54800000,
        70.02000000,
        'Chimgan_mountains_Uzbekistan.jpg',
        ARRAY['chimgan','tashkent']::text[],
        ARRAY['tashkent','chimgan']::text[],
        ARRAY['uzbekistan','chatkal','mountains','trekking']::text[]
    ),
    (
        'GE',
        'GEL',
        'tbilisi-national-park',
        'tbilisi',
        'NATURE',
        0,
        5,
        'HOURS',
        4.6,
        'Тбилисский национальный парк',
        'Tbilisi National Park',
        'Тбилиси ұлттық паркі',
        'Ближайший к Тбилиси природный парк с лесными тропами, хребтами и маршрутом для быстрого выхода из города на природу.',
        'The closest nature park to Tbilisi with forest trails, ridges and a route for a quick city-to-nature escape.',
        'Тбилисиге ең жақын табиғи парк: орман соқпақтары, жоталар және қаладан табиғатқа тез шығуға арналған бағыт.',
        41.82000000,
        44.93000000,
        'Tbilisi_National_Park.jpg',
        ARRAY['tbilisi']::text[],
        ARRAY['tbilisi']::text[],
        ARRAY['georgia','national-park','forest','free-entry']::text[]
    ),
    (
        'AM',
        'AMD',
        'azat-reservoir-trail',
        'garni',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Тропа к Азатскому водохранилищу',
        'Azat Reservoir Trail',
        'Азат су қоймасы соқпағы',
        'Маршрут рядом с Гарни и Ереваном к водохранилищу, сухим холмам и широким видам на долину Азата.',
        'A route near Garni and Yerevan toward the reservoir, dry hills and wide views of the Azat valley.',
        'Гарни мен Ереван маңындағы бағыт: су қоймасы, құрғақ төбелер және Азат аңғарына кең көріністер.',
        40.08500000,
        44.75500000,
        'Garni_Temple,_Armenia.jpg',
        ARRAY['garni','yerevan']::text[],
        ARRAY['yerevan','garni']::text[],
        ARRAY['armenia','azat-valley','day-hike','free-entry']::text[]
    ),
    (
        'AE',
        'AED',
        'hatta-mountain-trails',
        'hatta',
        'NATURE',
        0,
        4,
        'HOURS',
        4.7,
        'Горные тропы Хатты',
        'Hatta Mountain Trails',
        'Хатта тау соқпақтары',
        'Сеть каменистых маршрутов среди гор Хаджар недалеко от Дубая, с видами на дамбу, вади и пустынные склоны.',
        'A network of rocky routes in the Hajar Mountains near Dubai, with views of the dam, wadis and desert slopes.',
        'Дубай маңындағы Хаджар тауларындағы тасты маршруттар желісі: бөгетке, вади аңғарларына және шөл беткейлеріне көріністер.',
        24.80700000,
        56.12400000,
        'Hatta_Dam_-_UAE.jpg',
        ARRAY['hatta','dubai']::text[],
        ARRAY['dubai','hatta']::text[],
        ARRAY['united-arab-emirates','hajar-mountains','day-hike','free-entry']::text[]
    ),
    (
        'AE',
        'AED',
        'jebel-jais-hiking-trails',
        'ras-al-khaimah',
        'NATURE',
        0,
        5,
        'HOURS',
        4.8,
        'Тропы Джебель-Джайс',
        'Jebel Jais Hiking Trails',
        'Джебель-Джайс соқпақтары',
        'Горные маршруты самой высокой части ОАЭ с сухими каньонами, серпантинами и прохладным воздухом на высоте.',
        'Mountain routes in the highest part of the UAE with dry canyons, switchbacks and cooler air at elevation.',
        'БАӘ-нің ең биік бөлігіндегі тау бағыттары: құрғақ каньондар, серпантиндер және биіктіктегі салқын ауа.',
        25.94100000,
        56.13000000,
        'Jebel_Jais_Ras_Al_Khaimah.jpg',
        ARRAY['ras-al-khaimah','dubai']::text[],
        ARRAY['ras-al-khaimah','dubai']::text[],
        ARRAY['united-arab-emirates','hajar-mountains','trekking','free-entry']::text[]
    ),
    (
        'RU',
        'RUB',
        'agura-waterfalls',
        'sochi',
        'NATURE',
        200,
        4,
        'HOURS',
        4.6,
        'Агурские водопады',
        'Agura Waterfalls',
        'Агура сарқырамалары',
        'Классическая прогулка из Сочи по лесному ущелью к водопадам, скалам и видовым точкам Черноморского побережья.',
        'A classic walk from Sochi through a forest gorge to waterfalls, rocks and Black Sea coast viewpoints.',
        'Сочиден шығатын классикалық серуен: орманды шатқал, сарқырамалар, жартастар және Қара теңіз жағалауына көрініс нүктелері.',
        43.55200000,
        39.82100000,
        'Agura_Waterfalls_Sochi.jpg',
        ARRAY['sochi']::text[],
        ARRAY['sochi']::text[],
        ARRAY['russia','waterfalls','black-sea','hiking']::text[]
    ),
    (
        'TR',
        'TRY',
        'lycian-way-goynuk-canyon',
        'kemer',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Ликийская тропа у каньона Гейнюк',
        'Lycian Way near Goynuk Canyon',
        'Гейнюк каньоны маңындағы Ликия жолы',
        'Участок Ликийской тропы рядом с Антальей и Кемером: сосны, известняковые стены и маршрут к каньону Гейнюк.',
        'A Lycian Way section near Antalya and Kemer with pines, limestone walls and a route toward Goynuk Canyon.',
        'Анталья мен Кемер маңындағы Ликия жолының бөлігі: қарағайлар, әктас қабырғалар және Гейнюк каньонына бағыт.',
        36.66500000,
        30.53000000,
        'Goynuk_Canyon_Turkey.jpg',
        ARRAY['kemer','antalya']::text[],
        ARRAY['antalya','kemer']::text[],
        ARRAY['turkey','lycian-way','canyon','hiking']::text[]
    );

CREATE TEMP TABLE seed_hiking_enrichment_resolved_places AS
SELECT
    ('9f8d7c6b-5a4e-3d2c-1b0a-' || substr(md5(country_code || ':' || slug), 1, 12))::uuid AS id,
    country_code,
    price_currency,
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(country_code || ':' || slug || ':media'), 1, 8) || '-' ||
        substr(md5(country_code || ':' || slug || ':media'), 9, 4) || '-4' ||
        substr(md5(country_code || ':' || slug || ':media'), 14, 3) || '-8' ||
        substr(md5(country_code || ':' || slug || ':media'), 18, 3) || '-' ||
        substr(md5(country_code || ':' || slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || media_file || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || media_file AS media_source_url,
    ARRAY['hiking-enrichment-v1', lower(country_code), city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_hiking_enrichment_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_hiking_enrichment_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_hiking_enrichment_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_hiking_enrichment_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_hiking_enrichment_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_hiking_enrichment_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
