-- Additional Kazakhstan hiking and day-hike places.
-- This seed adds concrete routes inside already-known nature regions so users see actionable hiking plans, not only broad parks.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_kazakhstan_hiking_depth_resolved_places;
DROP TABLE IF EXISTS seed_kazakhstan_hiking_depth_places;

CREATE TEMP TABLE seed_kazakhstan_hiking_depth_places (
    slug varchar(96) PRIMARY KEY,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_kazakhstan_hiking_depth_places (
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'turgen-gorge',
        'almaty',
        'NATURE',
        1000,
        6,
        'HOURS',
        4.8,
        'Тургеньское ущелье',
        'Turgen Gorge',
        'Түрген шатқалы',
        'Зеленое ущелье к востоку от Алматы с рекой, хвойным лесом, пасеками и несколькими маршрутами к водопадам и альпийским лугам.',
        'A green gorge east of Almaty with a river, spruce forest, apiaries and several routes toward waterfalls and alpine meadows.',
        'Алматының шығысындағы жасыл шатқал: өзен, шыршалы орман, омарталар және сарқырамалар мен альпілік шалғындарға апаратын бірнеше бағыт.',
        43.24400000,
        77.65000000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','turgen','waterfalls','hiking']::text[]
    ),
    (
        'bear-falls-turgen',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.7,
        'Медвежий водопад в Тургени',
        'Bear Falls in Turgen Gorge',
        'Түргендегі Аюлы сарқырама',
        'Популярная тропа в Тургеньском ущелье к водопаду через лес и прохладную долину, удобная для насыщенной полудневной поездки из Алматы.',
        'A popular trail in Turgen Gorge to a waterfall through forest and a cool valley, convenient for a rich half-day trip from Almaty.',
        'Түрген шатқалындағы орман мен салқын аңғар арқылы сарқырамаға баратын танымал соқпақ, Алматыдан жарты күндік сапарға ыңғайлы.',
        43.21300000,
        77.69800000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','turgen','waterfall','day-hike']::text[]
    ),
    (
        'issyk-lake-trail',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.7,
        'Тропа к озеру Иссык',
        'Issyk Lake Trail',
        'Есік көліне соқпақ',
        'Горный маршрут к озеру Иссык среди склонов Заилийского Алатау, хороший для легкой прогулки, фото и поездки на один день из Алматы.',
        'A mountain route to Issyk Lake among Ile Alatau slopes, good for an easy walk, photos and a one-day trip from Almaty.',
        'Іле Алатауының беткейлері арасындағы Есік көліне апаратын тау бағыты: жеңіл серуенге, фотосуретке және Алматыдан бір күндік сапарға қолайлы.',
        43.25300000,
        77.48500000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','issyk','lake','day-hike']::text[]
    ),
    (
        'assy-plateau',
        'almaty',
        'NATURE',
        0,
        8,
        'HOURS',
        4.8,
        'Плато Ассы',
        'Assy Plateau',
        'Асы үстірті',
        'Высокогорное плато с широкими степными видами, пастбищами и дорогой к обсерватории, которое ощущается как большой открытый маршрут за пределами города.',
        'A high mountain plateau with wide steppe views, pastures and a road toward the observatory, feeling like a broad open route beyond the city.',
        'Кең дала көріністері, жайылымдары және обсерваторияға апаратын жолы бар биік таулы үстірт, қаладан тыс үлкен ашық бағыт сияқты сезіледі.',
        43.21800000,
        78.59100000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','plateau','observatory','free-entry']::text[]
    ),
    (
        'kaskelen-gorge',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.6,
        'Каскеленское ущелье',
        'Kaskelen Gorge',
        'Қаскелең шатқалы',
        'Доступное ущелье западнее Алматы с рекой, зелеными склонами и спокойными тропами для тех, кто хочет горы без дальнего трансфера.',
        'An accessible gorge west of Almaty with a river, green slopes and calm trails for travelers who want mountains without a long transfer.',
        'Алматының батысындағы қолжетімді шатқал: өзені, жасыл беткейлері және алыс жолсыз тауға шығуды қалайтындарға арналған тыныш соқпақтары бар.',
        43.07000000,
        76.65400000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','gorge','day-hike']::text[]
    ),
    (
        'monakhov-gorge',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.6,
        'Монахово ущелье',
        'Monakhov Gorge',
        'Монахов шатқалы',
        'Лесной маршрут в талгарской стороне Заилийского Алатау с ручьями, тенистыми участками и форматом спокойного дневного похода.',
        'A forest route on the Talgar side of Ile Alatau with streams, shaded sections and the feel of a quiet day hike.',
        'Іле Алатауының Талғар жағындағы орманды бағыт: бұлақтар, көлеңкелі бөліктер және тыныш күндік жорық форматы.',
        43.20400000,
        77.33800000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','talgar','forest','hiking']::text[]
    ),
    (
        'tuyuksu-glacier-trail',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Тропа к леднику Туюксу',
        'Tuyuksu Glacier Trail',
        'Тұйықсу мұздығына соқпақ',
        'Высокогорный маршрут от Медеу и Шымбулака к альпийской зоне, моренам и видам на ледник Туюксу для подготовленных гостей.',
        'A high mountain route from Medeu and Shymbulak toward the alpine zone, moraines and views of Tuyuksu Glacier for prepared hikers.',
        'Медеу мен Шымбұлақтан альпілік белдеуге, мореналарға және Тұйықсу мұздығына көріністерге апаратын дайын саяхатшыларға арналған биік таулы бағыт.',
        43.07100000,
        77.08100000,
        'Shymbulak, Almaty (P1180189).jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','glacier','medeu','trekking']::text[]
    ),
    (
        'tamgaly-tas-rocks',
        'almaty',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Скалы Тамгалы-Тас',
        'Tamgaly-Tas Rocks',
        'Таңбалы-Тас жартастары',
        'Скальные берега Или с петроглифами, короткими прогулками и видами на реку, подходящие для активной поездки из Алматы.',
        'Rocky Ili River banks with petroglyphs, short walks and river views, suited for an active trip from Almaty.',
        'Іле өзенінің жартасты жағалауы: петроглифтер, қысқа серуендер және өзен көріністері, Алматыдан белсенді сапарға қолайлы.',
        44.06100000,
        76.99800000,
        'Petroglyphs in Tamgaly, Kazakhstan 01.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ili-river','rocks','petroglyphs','free-entry']::text[]
    ),
    (
        'aksu-canyon',
        'shymkent',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.8,
        'Каньон Аксу',
        'Aksu Canyon',
        'Ақсу каньоны',
        'Глубокий каньон в районе Аксу-Жабаглы с драматичными стенами, смотровыми точками и сильным маршрутом для южного Казахстана.',
        'A deep canyon in the Aksu-Zhabagly area with dramatic walls, viewpoints and a strong route for southern Kazakhstan.',
        'Ақсу-Жабағылы аймағындағы терең каньон: әсерлі қабырғалар, көрініс нүктелері және оңтүстік Қазақстанға лайық күшті маршрут.',
        42.31900000,
        70.57600000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','aksu-zhabagly','canyon','western-tien-shan','trekking']::text[]
    ),
    (
        'ugam-gorge',
        'shymkent',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.7,
        'Угамское ущелье',
        'Ugam Gorge',
        'Өгем шатқалы',
        'Горная долина Западного Тянь-Шаня с рекой, предгорными тропами и хорошей связкой с маршрутами Сайрам-Угама.',
        'A Western Tien Shan mountain valley with a river, foothill trails and a natural pairing with Sayram-Ugam routes.',
        'Батыс Тянь-Шаньдағы тау аңғары: өзен, тау етегіндегі соқпақтар және Сайрам-Өгем бағыттарымен жақсы үйлеседі.',
        42.10300000,
        70.77500000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','ugam','western-tien-shan','gorge','hiking']::text[]
    ),
    (
        'akbet-peak',
        'pavlodar',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.7,
        'Гора Акбет',
        'Akbet Peak',
        'Ақбет шыңы',
        'Один из сильных подъемов Баянаула с гранитными склонами, соснами и видом на озера национального парка.',
        'One of Bayanaul strong climbs with granite slopes, pines and views over the national park lakes.',
        'Баянауылдағы ең әсерлі көтерілулердің бірі: гранитті беткейлер, қарағайлар және ұлттық парк көлдеріне көрініс.',
        50.79000000,
        75.67500000,
        'Bayanaul National Park.jpg',
        ARRAY['pavlodar']::text[],
        ARRAY['pavlodar']::text[],
        ARRAY['kazakhstan','bayanaul','peak','granite','trekking']::text[]
    ),
    (
        'konyr-aulie-cave',
        'pavlodar',
        'NATURE',
        1000,
        3,
        'HOURS',
        4.6,
        'Пещера Коныр-Аулие',
        'Konyr-Aulie Cave',
        'Қоңыр Әулие үңгірі',
        'Сакральная природная точка Баянаула с коротким подъемом, каменными проходами и видом на лесистые гранитные горы.',
        'A sacred Bayanaul nature point with a short ascent, stone passages and views of forested granite hills.',
        'Баянауылдағы киелі табиғи нүкте: қысқа көтерілу, тас өткелдер және орманды гранит тауларға көрініс.',
        50.79500000,
        75.63800000,
        'Bayanaul National Park.jpg',
        ARRAY['pavlodar']::text[],
        ARRAY['pavlodar']::text[],
        ARRAY['kazakhstan','bayanaul','cave','sacred-site','day-hike']::text[]
    ),
    (
        'buiratau-national-park',
        'astana',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.6,
        'Национальный парк Буйратау',
        'Buiratau National Park',
        'Бұйратау ұлттық паркі',
        'Степные сопки и лесные участки недалеко от Астаны, где можно собрать спокойный походный день с видами на североказахстанский ландшафт.',
        'Steppe hills and forest sections not far from Astana, good for a calm hiking day with northern Kazakhstan landscapes.',
        'Астанаға алыс емес дала шоқылары мен орманды бөліктер: солтүстік Қазақстан ландшафтына көріністері бар тыныш жорық күніне қолайлы.',
        51.60000000,
        73.55000000,
        'Sunset in Korgalzhyn Nature Reserve.jpg',
        ARRAY['astana']::text[],
        ARRAY['astana']::text[],
        ARRAY['kazakhstan','akmola','national-park','steppe','hiking']::text[]
    ),
    (
        'okzhetpes-rock',
        'kokshetau',
        'NATURE',
        1000,
        3,
        'HOURS',
        4.7,
        'Скала Окжетпес',
        'Okzhetpes Rock',
        'Оқжетпес жартасы',
        'Знаковая скала Бурабая с короткими прогулками вокруг озера, лесом и классическими видами курортной зоны.',
        'A signature Burabay rock with short lakeside walks, forest and classic resort area views.',
        'Бурабайдың әйгілі жартасы: көл жағасындағы қысқа серуендер, орман және курорт аймағының классикалық көріністері.',
        53.08400000,
        70.30500000,
        'Borovoe1.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau']::text[],
        ARRAY['kazakhstan','burabay','rock','lake','day-hike']::text[]
    ),
    (
        'torysh-valley',
        'aktau',
        'NATURE',
        0,
        5,
        'HOURS',
        4.8,
        'Долина шаров Торыш',
        'Torysh Valley',
        'Торыш шарлар аңғары',
        'Мангистауская долина с каменными конкрециями, короткими тропами между шарами и сильным ощущением пустынного ландшафта.',
        'A Mangystau valley with stone concretions, short paths between the spheres and a strong desert landscape feeling.',
        'Маңғыстаудағы тас шарлы аңғар: шарлардың арасындағы қысқа соқпақтар және шөл ландшафтының айқын әсері.',
        44.32600000,
        51.99900000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','desert','geology','free-entry']::text[]
    ),
    (
        'tuzbair-salt-flat',
        'aktau',
        'NATURE',
        0,
        6,
        'HOURS',
        4.8,
        'Сор Тузбаир',
        'Tuzbair Salt Flat',
        'Тұзбайыр соры',
        'Белые обрывы и солончак Мангистау с прогулками по кромке плато, видами на уступы и сильным маршрутом для фото и хайкинга.',
        'White cliffs and a Mangystau salt flat with walks along the plateau edge, views of escarpments and a strong route for photos and hiking.',
        'Маңғыстаудың ақ жартастары мен сор алқабы: үстірт жиегімен серуен, жарқабақтарға көрініс және фото мен хайкингке арналған әсерлі бағыт.',
        44.12700000,
        53.12000000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','salt-flat','ustyurt','free-entry']::text[]
    ),
    (
        'airakty-shomanai-valley',
        'aktau',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Долина Айракты-Шоманай',
        'Airakty-Shomanai Valley',
        'Айрақты-Шоманай аңғары',
        'Скальные останцы Мангистау, похожие на замковые стены, с короткими прогулками по пустынной долине и смотровыми точками.',
        'Mangystau rock outcrops resembling castle walls, with short walks through the desert valley and viewpoints.',
        'Қамал қабырғаларына ұқсайтын Маңғыстау жартастары: шөл аңғарындағы қысқа серуендер және көрініс нүктелері.',
        44.04500000,
        52.78600000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','rock-formations','desert','free-entry']::text[]
    ),
    (
        'zhygylgan-fault',
        'aktau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Провал Жыгылган',
        'Zhygylgan Fault',
        'Жығылған ойысы',
        'Необычный провал у побережья Каспия с каменными хаосами, морскими видами и маршрутом, который хорошо дополняет поездку по Мангистау.',
        'An unusual fault near the Caspian coast with rock chaos, sea views and a route that pairs well with a Mangystau trip.',
        'Каспий жағалауындағы ерекше ойыс: тас үйінділері, теңіз көріністері және Маңғыстау сапарын толықтыратын бағыт.',
        44.59900000,
        50.93800000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','caspian-sea','geology','free-entry']::text[]
    ),
    (
        'sibiny-lakes',
        'ust-kamenogorsk',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Сибинские озера',
        'Sibiny Lakes',
        'Сібе көлдері',
        'Гранитные озера Восточного Казахстана с короткими подъемами, чистой водой и спокойным форматом активного дня из Усть-Каменогорска.',
        'Granite lakes of East Kazakhstan with short climbs, clear water and a calm active-day format from Ust-Kamenogorsk.',
        'Шығыс Қазақстандағы гранитті көлдер: қысқа көтерілулер, мөлдір су және Өскеменнен шығатын тыныш белсенді күн форматы.',
        49.43000000,
        82.60000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','east-kazakhstan','lakes','granite','free-entry']::text[]
    ),
    (
        'rakhmanov-springs-trails',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Тропы Рахмановских ключей',
        'Rakhmanov Springs Trails',
        'Рахман қайнары соқпақтары',
        'Алтайские маршруты вокруг Рахмановских ключей с лесом, озером, горным воздухом и форматом медленного eco-adventure.',
        'Altai routes around Rakhmanov Springs with forest, lake, mountain air and a slower eco-adventure format.',
        'Рахман қайнары маңындағы Алтай бағыттары: орман, көл, тау ауасы және баяу экосаяхат форматы.',
        49.54000000,
        86.52000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','katon-karagay','springs','trekking']::text[]
    ),
    (
        'burkhan-bulak-waterfall',
        'taldykorgan',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Водопад Бурхан-Булак',
        'Burkhan-Bulak Waterfall',
        'Бұрхан-Бұлақ сарқырамасы',
        'Высокий водопад Жетысу в горах Джунгарского Алатау, сильная точка для подготовленного выезда из Талдыкоргана.',
        'A tall Zhetysu waterfall in the Dzungarian Alatau, a strong destination for a prepared trip from Taldykorgan.',
        'Жетісудағы Жоңғар Алатауындағы биік сарқырама, Талдықорғаннан дайындықпен шығатын әсерлі бағыт.',
        44.87400000,
        79.15800000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan']::text[],
        ARRAY['kazakhstan','zhetysu','waterfall','dzungarian-alatau','trekking']::text[]
    ),
    (
        'dzungarian-alatau-national-park',
        'taldykorgan',
        'NATURE',
        1000,
        2,
        'DAYS',
        4.8,
        'Национальный парк Джунгарский Алатау',
        'Dzungarian Alatau National Park',
        'Жоңғар Алатауы ұлттық паркі',
        'Горный парк Жетысу с дикими яблонями, ущельями, водопадами и маршрутами для более длинного трекинга из Талдыкоргана.',
        'A Zhetysu mountain park with wild apple forests, gorges, waterfalls and routes for longer trekking from Taldykorgan.',
        'Жетісудағы тау паркі: жабайы алма ормандары, шатқалдар, сарқырамалар және Талдықорғаннан шығатын ұзақ треккинг бағыттары.',
        45.20000000,
        80.25000000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan']::text[],
        ARRAY['kazakhstan','zhetysu','national-park','dzungarian-alatau','trekking']::text[]
    );

CREATE TEMP TABLE seed_kazakhstan_hiking_depth_resolved_places AS
SELECT
    ('86ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['kazakhstan-hiking-depth-v1', 'KZ', 'kz', city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_kazakhstan_hiking_depth_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    'KZ',
    city_id,
    category,
    price_amount,
    'KZT',
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_kazakhstan_hiking_depth_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_kazakhstan_hiking_depth_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_kazakhstan_hiking_depth_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_kazakhstan_hiking_depth_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_kazakhstan_hiking_depth_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
