-- Extended Kazakhstan hiking/day-hike route seed.
-- This layer adds concrete trail-level places without duplicating broad parks and already seeded anchors.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_kazakhstan_extended_hiking_resolved_places;
DROP TABLE IF EXISTS seed_kazakhstan_extended_hiking_places;

CREATE TEMP TABLE seed_kazakhstan_extended_hiking_places (
    slug varchar(96) PRIMARY KEY,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_kazakhstan_extended_hiking_places (
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'big-almaty-peak-trail',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Тропа на Большой Алматинский пик',
        'Big Almaty Peak Trail',
        'Үлкен Алматы шыңына соқпақ',
        'Сильный однодневный маршрут над Большим Алматинским озером с каменистым гребнем, видом на перевал и панорамой Заилийского Алатау.',
        'A strong day route above Big Almaty Lake with a rocky ridge, pass views and a wide Ile Alatau panorama.',
        'Үлкен Алматы көлінің үстіндегі әсерлі күндік бағыт: тасты жота, асу көрінісі және Іле Алатауының кең панорамасы.',
        43.03000000,
        76.97400000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','big-almaty-lake','summit','trekking']::text[]
    ),
    (
        'mynzhylky-plateau-trail',
        'almaty',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.8,
        'Тропа на плато Мынжылкы',
        'Mynzhylky Plateau Trail',
        'Мыңжылқы үстіртіне соқпақ',
        'Высокогорный маршрут от Шымбулака к широкой долине Малой Алматинки, моренам и видам на ледниковую зону Туюксу.',
        'A high mountain route from Shymbulak toward the broad Little Almatinka valley, moraines and Tuyuksu glacier views.',
        'Шымбұлақтан Кіші Алматы аңғарына, мореналарға және Тұйықсу мұздық аймағы көріністеріне апаратын биік таулы бағыт.',
        43.08000000,
        77.08000000,
        'Shymbulak, Almaty (P1180189).jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','mynzhylky','plateau','trekking']::text[]
    ),
    (
        'bogdanovich-glacier-view-trail',
        'almaty',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.8,
        'Тропа к виду на ледник Богдановича',
        'Bogdanovich Glacier View Trail',
        'Богданович мұздығына көрініс соқпағы',
        'Маршрут из зоны Шымбулака к высокому альпийскому ландшафту с моренами, открытыми склонами и видом на ледник Богдановича.',
        'A route from the Shymbulak area into high alpine scenery with moraines, open slopes and views of Bogdanovich Glacier.',
        'Шымбұлақ аймағынан мореналары, ашық беткейлері және Богданович мұздығына көрінісі бар биік альпілік ландшафтқа апаратын бағыт.',
        43.09000000,
        77.13000000,
        'Shymbulak, Almaty (P1180189).jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','bogdanovich-glacier','alpine','trekking']::text[]
    ),
    (
        'butakovka-waterfall-trail',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.7,
        'Тропа к водопаду Бутаковки',
        'Butakovka Waterfall Trail',
        'Бутаковка сарқырамасына соқпақ',
        'Лесная тропа на восточной стороне Алматы к небольшому водопаду, ручью и тенистым участкам для легкого похода без дальнего трансфера.',
        'A forest trail on the eastern side of Almaty to a small waterfall, stream and shaded sections for an easy hike without a long transfer.',
        'Алматының шығыс жағындағы орманды бағыт: шағын сарқырама, бұлақ және алыс жолсыз жеңіл жорыққа арналған көлеңкелі бөліктер.',
        43.16600000,
        77.08800000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','butakovka','waterfall','day-hike']::text[]
    ),
    (
        'kairak-waterfall-trail',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Тропа к водопаду Кайрак',
        'Kairak Waterfall Trail',
        'Қайрақ сарқырамасына соқпақ',
        'Длинный маршрут в Тургеньском направлении к мощному водопаду, хвойным склонам и более дикому сценарию Заилийского Алатау.',
        'A long Turgen-side route to a powerful waterfall, spruce slopes and a wilder Ile Alatau hiking scenario.',
        'Түрген бағытымен қуатты сарқырамаға, шыршалы беткейлерге және Іле Алатауының жабайырақ жорық сценарийіне апаратын ұзақ бағыт.',
        43.15000000,
        77.82000000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','turgen','kairak','waterfall','trekking']::text[]
    ),
    (
        'second-kolsai-lake-trek',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Трек ко второму Кольсайскому озеру',
        'Second Kolsai Lake Trek',
        'Екінші Көлсай көліне трек',
        'Горный трек от нижнего Кольсая к более тихому верхнему озеру через еловый лес, перепады высоты и классические виды Северного Тянь-Шаня.',
        'A mountain trek from Lower Kolsai to a quieter upper lake through spruce forest, elevation gain and classic Northern Tian Shan views.',
        'Төменгі Көлсайдан тынышырақ жоғарғы көлге апаратын тау трегі: шыршалы орман, биіктік айырмасы және Солтүстік Тянь-Шаньның классикалық көріністері.',
        42.95900000,
        78.33000000,
        'Kolsai lake.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','kolsai','alpine-lake','saty','trekking']::text[]
    ),
    (
        'kaindy-lake-viewpoint-trail',
        'almaty',
        'NATURE',
        1000,
        4,
        'HOURS',
        4.8,
        'Тропа к смотровой озера Каинды',
        'Kaindy Lake Viewpoint Trail',
        'Қайыңды көлі көрініс соқпағы',
        'Короткий маршрут над озером Каинды к видам на затопленный лес, голубую воду и хвойные склоны рядом с Саты.',
        'A short route above Lake Kaindy with views of the sunken forest, blue water and spruce slopes near Saty.',
        'Саты маңындағы Қайыңды көлінің үстінен су астындағы орманға, көгілдір суға және шыршалы беткейлерге көрініс беретін қысқа бағыт.',
        42.98400000,
        78.46500000,
        'Kaindy lake.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','kaindy','saty','lake-viewpoint','day-hike']::text[]
    ),
    (
        'aktogay-canyon-trail',
        'almaty',
        'NATURE',
        1000,
        6,
        'HOURS',
        4.8,
        'Тропа каньона Актогай',
        'Aktogay Canyon Trail',
        'Ақтоғай каньоны соқпағы',
        'Менее людный маршрут системы Чарына с широкими видами на красные стены, речную долину и сухие степные склоны.',
        'A less crowded route in the Charyn canyon system with wide views of red walls, a river valley and dry steppe slopes.',
        'Шарын жүйесіндегі адам аз жүретін бағыт: қызыл қабырғалар, өзен аңғары және құрғақ дала беткейлеріне кең көріністер.',
        43.29000000,
        79.09000000,
        'Charyn Canyon, Kazakhstan 01.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','charyn','aktogay','canyon','hiking']::text[]
    ),
    (
        'aktau-mountains-red-gorge-trail',
        'taldykorgan',
        'NATURE',
        1000,
        6,
        'HOURS',
        4.8,
        'Тропа Красного ущелья гор Актау',
        'Aktau Mountains Red Gorge Trail',
        'Ақтау таулары Қызыл шатқал соқпағы',
        'Пеший маршрут в Алтын-Эмеле среди разноцветных глиняных склонов, сухих русел и почти марсианского рельефа.',
        'A walking route in Altyn-Emel among colorful clay slopes, dry washes and an almost Martian landscape.',
        'Алтын-Емелдегі түрлі түсті сазды беткейлер, құрғақ сайлар және марстыққа ұқсас рельеф арасындағы жаяу бағыт.',
        44.00500000,
        78.72000000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan','almaty']::text[],
        ARRAY['kazakhstan','altyn-emel','aktau-mountains','red-gorge','hiking']::text[]
    ),
    (
        'katutau-volcanic-hills-trail',
        'taldykorgan',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.7,
        'Тропа вулканических холмов Катутау',
        'Katutau Volcanic Hills Trail',
        'Қатутау жанартаулы қыраттары соқпағы',
        'Маршрут по вулканическим холмам Алтын-Эмеля с темными скалами, сухими ложбинами и контрастом к светлым горам Актау.',
        'A route through Altyn-Emel volcanic hills with dark rocks, dry gullies and a strong contrast to the pale Aktau Mountains.',
        'Алтын-Емелдің жанартаулы қыраттары арқылы өтетін бағыт: қара жартас, құрғақ сайлар және ашық түсті Ақтау тауларына күшті контраст.',
        44.06000000,
        78.55000000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan','almaty']::text[],
        ARRAY['kazakhstan','altyn-emel','katutau','volcanic','day-hike']::text[]
    ),
    (
        'kokkol-waterfall-trail',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Тропа к водопаду Кокколь',
        'Kokkol Waterfall Trail',
        'Көккөл сарқырамасына соқпақ',
        'Алтайский маршрут в Катон-Карагайском направлении к одному из самых выразительных водопадов региона, с лесом, рекой и горным воздухом.',
        'An Altai route in the Katon-Karagay direction toward one of the region most expressive waterfalls, with forest, river and mountain air.',
        'Катонқарағай бағытындағы Алтай маршруты: өңірдің ең әсерлі сарқырамаларының біріне, орманға, өзенге және тау ауасына апарады.',
        49.76000000,
        86.37000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','katon-karagay','kokkol','waterfall','trekking']::text[]
    ),
    (
        'markakol-shore-trail',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        6,
        'HOURS',
        4.8,
        'Береговая тропа Маркаколя',
        'Markakol Shore Trail',
        'Марқакөл жағалауы соқпағы',
        'Удаленный маршрут Восточного Казахстана вдоль горного озера, таежных склонов и тихих бухт для медленного природного дня.',
        'A remote East Kazakhstan route along a mountain lake, taiga slopes and quiet bays for a slower nature day.',
        'Шығыс Қазақстандағы алыстау бағыт: тау көлі, тайгалы беткейлер және тыныш қойнаулар бойымен баяу табиғи күнге арналған.',
        48.74000000,
        85.76000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','east-kazakhstan','markakol','lake','taiga','hiking']::text[]
    ),
    (
        'kiin-kerish-valley-trail',
        'ust-kamenogorsk',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Тропа долины Киин-Кериш',
        'Kiin-Kerish Valley Trail',
        'Қиын-Керіш аңғары соқпағы',
        'Сухой маршрут по цветным глинистым останцам у Зайсана, где восточноказахстанская степь резко переходит в фантастический ландшафт.',
        'A dry route through colorful clay formations near Zaysan, where the East Kazakhstan steppe turns into a fantastic landscape.',
        'Зайсан маңындағы түрлі түсті сазды жартас пішіндері арқылы өтетін құрғақ бағыт, мұнда Шығыс Қазақстан даласы ерекше ландшафтқа айналады.',
        47.99000000,
        84.24000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','east-kazakhstan','kiin-kerish','zaysan','free-entry','hiking']::text[]
    ),
    (
        'kora-gorge-trail',
        'taldykorgan',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.8,
        'Тропа ущелья Кора',
        'Kora Gorge Trail',
        'Қора шатқалы соқпағы',
        'Горный маршрут Жетысу по долине Коры, который хорошо связывает Талдыкорган с дорогой к Бурхан-Булаку и Джунгарскому Алатау.',
        'A Zhetysu mountain route along the Kora valley, naturally connecting Taldykorgan with the road toward Burkhan-Bulak and the Dzungarian Alatau.',
        'Қора аңғары бойындағы Жетісу тау бағыты, Талдықорғанды Бұрхан-Бұлақ пен Жоңғар Алатауына апаратын жолмен табиғи байланыстырады.',
        45.02000000,
        79.02000000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan']::text[],
        ARRAY['kazakhstan','zhetysu','kora-gorge','dzungarian-alatau','trekking']::text[]
    ),
    (
        'sayram-su-lake-trail',
        'shymkent',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Тропа к озеру Сайрам-Су',
        'Sayram-Su Lake Trail',
        'Сайрам-Су көліне соқпақ',
        'Насыщенный маршрут Западного Тянь-Шаня к горному озеру, альпийским склонам и более спортивному сценарию из Шымкента.',
        'A full Western Tian Shan route to a mountain lake, alpine slopes and a more athletic plan from Shymkent.',
        'Шымкенттен шығатын Батыс Тянь-Шаньның қарқынды бағыты: тау көліне, альпілік беткейлерге және спорттықтау сценарийге апарады.',
        42.12000000,
        70.57000000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','sayram-ugam','sayram-su','mountain-lake','trekking']::text[]
    ),
    (
        'mashat-gorge-trail',
        'shymkent',
        'NATURE',
        0,
        5,
        'HOURS',
        4.6,
        'Тропа ущелья Машат',
        'Mashat Gorge Trail',
        'Машат шатқалы соқпағы',
        'Доступное ущелье на юге Казахстана с водой, зелеными стенками и мягким форматом похода для гостей Шымкента и Тараза.',
        'An accessible southern Kazakhstan gorge with water, green walls and an easy hiking format for Shymkent and Taraz visitors.',
        'Оңтүстік Қазақстандағы қолжетімді шатқал: суы, жасыл қабырғалары және Шымкент пен Тараз қонақтарына арналған жеңіл жорық форматы бар.',
        42.52000000,
        70.28000000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['shymkent','taraz']::text[],
        ARRAY['shymkent','taraz']::text[],
        ARRAY['kazakhstan','turkestan-region','mashat','gorge','free-entry','day-hike']::text[]
    ),
    (
        'shaitankol-lake-trail',
        'karaganda',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.8,
        'Тропа к озеру Шайтанколь',
        'Shaitankol Lake Trail',
        'Шайтанкөл көліне соқпақ',
        'Классический маршрут Каркаралы к небольшому озеру среди гранитных скал, сосен и легенд Сарыарки.',
        'A classic Karkaraly route to a small lake among granite cliffs, pines and Saryarka legends.',
        'Қарқаралыдағы классикалық бағыт: гранит жартастар, қарағайлар және Сарыарқа аңыздары арасындағы шағын көлге апарады.',
        49.39000000,
        75.42000000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda']::text[],
        ARRAY['karaganda']::text[],
        ARRAY['kazakhstan','karkaraly','shaitankol','lake','hiking']::text[]
    ),
    (
        'aksoran-peak-trail',
        'karaganda',
        'NATURE',
        0,
        8,
        'HOURS',
        4.8,
        'Тропа на пик Аксоран',
        'Aksoran Peak Trail',
        'Ақсораң шыңына соқпақ',
        'Поход по массиву Кызыларай к высшей точке Сарыарки, с гранитными склонами, степным горизонтом и сильным remote-сценарием.',
        'A Kyzylarai massif hike to the highest point of Saryarka, with granite slopes, steppe horizons and a strong remote scenario.',
        'Қызыларай массивімен Сарыарқаның ең биік нүктесіне апаратын жорық: гранит беткейлер, дала көкжиегі және алыстағы әсерлі сценарий.',
        48.65000000,
        75.98000000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda','balkhash']::text[],
        ARRAY['karaganda','balkhash']::text[],
        ARRAY['kazakhstan','kyzylarai','aksoran','saryarka','free-entry','trekking']::text[]
    ),
    (
        'zerenda-lake-forest-trail',
        'kokshetau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Лесная тропа озера Зеренда',
        'Zerenda Lake Forest Trail',
        'Зеренді көлі орман соқпағы',
        'Мягкий маршрут из Кокшетау вокруг лесных берегов Зеренды, с соснами, водой и спокойным форматом северного отдыха.',
        'A gentle route from Kokshetau around the forested shores of Zerenda, with pines, water and a calm northern nature format.',
        'Көкшетаудан Зеренді орманды жағалаулары бойымен өтетін жеңіл бағыт: қарағайлар, су және солтүстік табиғаттағы тыныш демалыс форматы.',
        52.90000000,
        69.15000000,
        'Burabay_National_Park_Kazakhstan.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau']::text[],
        ARRAY['kazakhstan','akmola-region','zerenda','lake','free-entry','walking']::text[]
    ),
    (
        'sinyukha-peak-trail',
        'kokshetau',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.7,
        'Тропа на гору Синюха',
        'Sinyukha Peak Trail',
        'Синюха тауына соқпақ',
        'Подъем в Бурабайской зоне к лесистым склонам и обзорным точкам, который добавляет Кокшетау отдельный активный маршрут.',
        'A climb in the Burabay area toward forested slopes and viewpoints, adding a separate active route for Kokshetau.',
        'Бурабай аймағындағы орманды беткейлер мен көрініс нүктелеріне көтерілу, Көкшетауға бөлек белсенді маршрут қосады.',
        53.08000000,
        70.32000000,
        'Burabay_National_Park_Kazakhstan.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau']::text[],
        ARRAY['kazakhstan','burabay','peak','forest','day-hike']::text[]
    ),
    (
        'kapamsay-canyon-trail',
        'aktau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.7,
        'Тропа каньона Капамсай',
        'Kapamsay Canyon Trail',
        'Қапамсай каньоны соқпағы',
        'Короткий маршрут Мангистау по светлым стенам каньона, сухому руслу и камерному пустынному ландшафту.',
        'A short Mangystau route through pale canyon walls, a dry wash and an intimate desert landscape.',
        'Маңғыстаудағы қысқа бағыт: ашық түсті каньон қабырғалары, құрғақ арна және ықшам шөл ландшафты.',
        44.17000000,
        52.51000000,
        'Sherkala_Mountain.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','kapamsay','canyon','free-entry','hiking']::text[]
    ),
    (
        'karagiye-depression-rim-trail',
        'aktau',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Тропа кромки впадины Карагие',
        'Karagiye Depression Rim Trail',
        'Қарақия ойысы жиегі соқпағы',
        'Маршрут по краю одной из самых низких точек Центральной Азии с видами на солончаки, обрывы и сухой рельеф Мангистау.',
        'A route along the rim of one of Central Asia lowest points, with views of salt flats, cliffs and dry Mangystau relief.',
        'Орталық Азиядағы ең төмен нүктелердің бірінің жиегімен өтетін бағыт: сорлар, жарқабақтар және Маңғыстаудың құрғақ бедеріне көріністер.',
        43.48000000,
        51.78000000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','karagiye','depression','free-entry','hiking']::text[]
    ),
    (
        'saura-canyon-lake-trail',
        'aktau',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Тропа каньона и озера Саура',
        'Saura Canyon and Lake Trail',
        'Саура каньоны мен көлі соқпағы',
        'Маршрут Мангистау к небольшому озеру среди каменных стен, где пустынная прогулка получает редкий водный акцент.',
        'A Mangystau route to a small lake among stone walls, giving a desert walk a rare water accent.',
        'Маңғыстаудағы тас қабырғалар арасындағы шағын көлге апаратын бағыт, шөл серуеніне сирек су акцентін береді.',
        44.34000000,
        51.25000000,
        'Sherkala_Mountain.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','saura','canyon','lake','free-entry']::text[]
    ),
    (
        'inder-salt-lake-trail',
        'atyrau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.5,
        'Тропа соленого озера Индер',
        'Inder Salt Lake Trail',
        'Индер тұзды көлі соқпағы',
        'Степной маршрут из Атырау к соленому озеру, белым берегам и открытому западноказахстанскому горизонту.',
        'A steppe route from Atyrau to a salt lake, pale shores and an open western Kazakhstan horizon.',
        'Атыраудан тұзды көлге, ақшыл жағалауға және Батыс Қазақстанның ашық көкжиегіне апаратын дала бағыты.',
        48.56000000,
        51.98000000,
        'Atyrau footbridge across Ural River.jpg',
        ARRAY['atyrau']::text[],
        ARRAY['atyrau']::text[],
        ARRAY['kazakhstan','atyrau-region','inder','salt-lake','free-entry','walking']::text[]
    );

CREATE TEMP TABLE seed_kazakhstan_extended_hiking_resolved_places AS
SELECT
    ('90ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['kazakhstan-extended-hiking-v1', 'KZ', 'kz', city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_kazakhstan_extended_hiking_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    'KZ',
    city_id,
    category,
    price_amount,
    'KZT',
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_kazakhstan_extended_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_kazakhstan_extended_hiking_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_kazakhstan_extended_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_kazakhstan_extended_hiking_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_kazakhstan_extended_hiking_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
