-- Additional Kazakhstan route-level hiking/day-hike seed.
-- This layer fills remaining practical trail gaps without duplicating broad parks or previously seeded hiking anchors.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_kazakhstan_additional_hiking_resolved_places;
DROP TABLE IF EXISTS seed_kazakhstan_additional_hiking_places;

CREATE TEMP TABLE seed_kazakhstan_additional_hiking_places (
    slug varchar(96) PRIMARY KEY,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_kazakhstan_additional_hiking_places (
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'ayusai-waterfalls-trail',
        'almaty',
        'NATURE',
        1000,
        5,
        'HOURS',
        4.8,
        'Тропа к водопадам Аюсай',
        'Ayusai Waterfalls Trail',
        'Аюсай сарқырамаларына соқпақ',
        'Короткий, но насыщенный маршрут в Большом Алматинском ущелье к каскадам Аюсая, гранитным стенкам и прохладному лесному коридору.',
        'A short but rich route in Big Almaty Gorge toward Ayusai cascades, granite walls and a cool forest corridor.',
        'Үлкен Алматы шатқалындағы Аюсай каскадтарына, гранит қабырғаларға және салқын орманды дәлізге апаратын қысқа әрі әсерлі бағыт.',
        43.12200000,
        76.93600000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','ayusai','waterfalls','day-hike']::text[]
    ),
    (
        'prohodnoye-gorge-trail',
        'almaty',
        'NATURE',
        1000,
        6,
        'HOURS',
        4.7,
        'Тропа ущелья Проходное',
        'Prohodnoye Gorge Trail',
        'Проходное шатқалы соқпағы',
        'Маршрут над Алма-Арасаном по долине Проходной с хвойными склонами, каменными выходами и ощущением настоящего горного дня рядом с городом.',
        'A route above the Alma-Arasan area through the Prohodnaya valley, with spruce slopes, rocky outcrops and a true mountain-day feel close to the city.',
        'Алма-Арасан үстіндегі Проходная аңғары арқылы өтетін бағыт: шыршалы беткейлер, тасты жерлер және қалаға жақын нағыз тау күні сезімі.',
        43.09600000,
        76.88400000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','prohodnoye','alma-arasan','trekking']::text[]
    ),
    (
        'left-talgar-gorge-trail',
        'almaty',
        'NATURE',
        1000,
        7,
        'HOURS',
        4.8,
        'Тропа ущелья Левый Талгар',
        'Left Talgar Gorge Trail',
        'Сол Талғар шатқалы соқпағы',
        'Лесной маршрут в сторону долины Левого Талгара с ручьями, тянь-шаньской елью и более тихим форматом похода вне самых популярных троп.',
        'A forest route toward the Left Talgar valley, with streams, Tien Shan spruce and a quieter hiking format away from the busiest trails.',
        'Сол Талғар аңғарына қарай өтетін орманды бағыт: бұлақтар, тянь-шань шыршасы және ең танымал соқпақтардан тынышырақ жорық форматы.',
        43.14500000,
        77.17800000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','left-talgar','forest','hiking']::text[]
    ),
    (
        'talgar-peak-base-trail',
        'almaty',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Тропа к базовым видам пика Талгар',
        'Talgar Peak Base Trail',
        'Талғар шыңы етегіндегі көрініс соқпағы',
        'Высокогорный маршрут к видовым точкам массива Талгара без выхода на техническое восхождение, с альпийскими склонами и сильной панорамой Заилийского Алатау.',
        'A high mountain route to Talgar massif viewpoints without committing to a technical ascent, with alpine slopes and a strong Ile Alatau panorama.',
        'Техникалық өрмелеуге шықпай-ақ Талғар массивінің көрініс нүктелеріне апаратын биік таулы бағыт: альпілік беткейлер мен Іле Алатауы панорамасы.',
        43.10600000,
        77.33500000,
        'Piktalgar.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','talgar-peak','alpine','trekking']::text[]
    ),
    (
        'bartogai-reservoir-view-trail',
        'almaty',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Смотровая тропа Бартогайского водохранилища',
        'Bartogai Reservoir View Trail',
        'Бартоғай су қоймасы көрініс соқпағы',
        'Открытый степной маршрут к видам на Бартогайское водохранилище, сухие холмы и связку с дорогой к Чарыну и Кольсаю.',
        'An open steppe route to Bartogai Reservoir views, dry hills and the road corridor toward Charyn and Kolsai.',
        'Бартоғай су қоймасына, құрғақ қыраттарға және Шарын мен Көлсай бағытына көрініс беретін ашық дала маршруты.',
        43.35600000,
        78.50700000,
        'Charyn Canyon, Kazakhstan 01.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','bartogai','reservoir','free-entry','walking']::text[]
    ),
    (
        'ketmen-ridge-trail',
        'almaty',
        'NATURE',
        0,
        7,
        'HOURS',
        4.7,
        'Тропа хребта Кетмень',
        'Ketmen Ridge Trail',
        'Кетпен жотасы соқпағы',
        'Маршрут востока Алматинской области по менее перегруженным горным склонам, с панорамами Кетменя, степными долинами и ощущением дальнего выезда.',
        'An eastern Almaty Region route across less crowded mountain slopes, with Ketmen panoramas, steppe valleys and the feel of a remote day out.',
        'Алматы облысының шығысындағы адам аз жүретін тау беткейлері арқылы өтетін бағыт: Кетпен панорамалары, дала аңғарлары және алыс сапар әсері.',
        43.07500000,
        79.91000000,
        'Charyn Canyon, Kazakhstan 01.jpg',
        ARRAY['almaty','taldykorgan']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ketmen','almaty-region','ridge','free-entry','trekking']::text[]
    ),
    (
        'tekeli-gorge-trail',
        'taldykorgan',
        'NATURE',
        0,
        5,
        'HOURS',
        4.7,
        'Тропа Текелийского ущелья',
        'Tekeli Gorge Trail',
        'Текелі шатқалы соқпағы',
        'Доступный горный маршрут Жетысу рядом с Текели: зеленая долина, ручьи, скальные участки и удобный формат выезда из Талдыкоргана.',
        'An accessible Zhetysu mountain route near Tekeli, with a green valley, streams, rocky sections and an easy departure format from Taldykorgan.',
        'Текелі маңындағы қолжетімді Жетісу тау бағыты: жасыл аңғар, бұлақтар, тасты бөліктер және Талдықорғаннан шығуға ыңғайлы формат.',
        44.83000000,
        78.82300000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan']::text[],
        ARRAY['kazakhstan','zhetysu','tekeli','gorge','free-entry','day-hike']::text[]
    ),
    (
        'eskeldy-gorge-trail',
        'taldykorgan',
        'NATURE',
        0,
        4,
        'HOURS',
        4.6,
        'Тропа ущелья Ескельды',
        'Eskeldy Gorge Trail',
        'Ескелді шатқалы соқпағы',
        'Спокойный маршрут у предгорий Джунгарского Алатау с зеленой долиной, родниками и мягким рельефом для дневной прогулки.',
        'A calm route near the Dzungarian Alatau foothills, with a green valley, springs and gentle terrain for a day walk.',
        'Жоңғар Алатауы етегіндегі тыныш бағыт: жасыл аңғар, бұлақтар және күндік серуенге қолайлы жұмсақ бедер.',
        44.99000000,
        78.35500000,
        'Altyn Emel 1.jpg',
        ARRAY['taldykorgan']::text[],
        ARRAY['taldykorgan']::text[],
        ARRAY['kazakhstan','zhetysu','eskeldy','foothills','free-entry','walking']::text[]
    ),
    (
        'yazevoe-lake-trail',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.9,
        'Тропа к Язевому озеру',
        'Yazevoe Lake Trail',
        'Язевое көліне соқпақ',
        'Алтайский маршрут в Катон-Карагайском направлении к озеру с видами на Белуху, хвойными склонами и ощущением настоящего дальнего трека.',
        'An Altai route in the Katon-Karagay direction to a lake with Belukha views, spruce slopes and the feel of a true remote trek.',
        'Катонқарағай бағытындағы Алтай маршруты: Белуха көрінісі бар көлге, шыршалы беткейлерге және нағыз алыстағы трек әсеріне апарады.',
        49.53400000,
        86.52000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','katon-karagay','yazevoe','lake','trekking']::text[]
    ),
    (
        'ivanov-ridge-trail',
        'ust-kamenogorsk',
        'NATURE',
        0,
        7,
        'HOURS',
        4.8,
        'Тропа Ивановского хребта',
        'Ivanov Ridge Trail',
        'Иванов жотасы соқпағы',
        'Маршрут из района Риддера по горной тайге и открытым гребням Ивановского хребта, хороший для сильного дневного похода в Восточном Казахстане.',
        'A Ridder-area route through mountain taiga and open crests of the Ivanov Ridge, suited for a strong East Kazakhstan day hike.',
        'Риддер маңындағы тау тайгасы мен Иванов жотасының ашық қырлары арқылы өтетін бағыт, Шығыс Қазақстандағы қарқынды күндік жорыққа қолайлы.',
        50.34700000,
        83.58400000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','east-kazakhstan','ridder','ivanov-ridge','free-entry','trekking']::text[]
    ),
    (
        'radon-lake-trail',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Тропа к Радоновому озеру',
        'Radon Lake Trail',
        'Радон көліне соқпақ',
        'Удаленный катон-карагайский маршрут к высокогорному озеру, который лучше подходит подготовленным гостям и маршрутам с гидом.',
        'A remote Katon-Karagay route toward a high mountain lake, better suited to prepared travelers and guided plans.',
        'Катонқарағайдағы биік таулы көлге апаратын алыстағы бағыт, дайын саяхатшыларға және гидпен жүретін жоспарларға көбірек сай келеді.',
        49.64600000,
        86.16400000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','katon-karagay','radon-lake','trekking']::text[]
    ),
    (
        'sairam-peak-base-trail',
        'shymkent',
        'NATURE',
        1000,
        8,
        'HOURS',
        4.8,
        'Тропа к подножию пика Сайрам',
        'Sairam Peak Base Trail',
        'Сайрам шыңы етегіне соқпақ',
        'Горный маршрут Сайрам-Угамского парка к альпийским видам под Сайрамским пиком, с можжевельниками и сильным набором высоты.',
        'A Sayram-Ugam park route toward alpine views below Sairam Peak, with juniper slopes and meaningful elevation gain.',
        'Сайрам-Өгем паркінде Сайрам шыңы астындағы альпілік көріністерге апаратын бағыт: аршалы беткейлер және айтарлықтай биіктік жинау.',
        42.06200000,
        70.56000000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['shymkent']::text[],
        ARRAY['shymkent']::text[],
        ARRAY['kazakhstan','sayram-ugam','sairam-peak','western-tien-shan','trekking']::text[]
    ),
    (
        'boraldai-gorge-trail',
        'taraz',
        'NATURE',
        0,
        5,
        'HOURS',
        4.6,
        'Тропа ущелья Боралдай',
        'Boraldai Gorge Trail',
        'Боралдай шатқалы соқпағы',
        'Маршрут между Таразом и югом Туркестанской области с сухими предгорьями, скальными стенками и спокойным природным сценарием.',
        'A route between Taraz and southern Turkestan Region, with dry foothills, rocky walls and a calm nature scenario.',
        'Тараз бен Түркістан облысының оңтүстігі арасындағы бағыт: құрғақ тау етегі, тасты қабырғалар және тыныш табиғи сценарий.',
        42.85500000,
        69.79600000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['taraz','shymkent']::text[],
        ARRAY['taraz','shymkent']::text[],
        ARRAY['kazakhstan','zhambyl-region','boraldai','gorge','free-entry','hiking']::text[]
    ),
    (
        'kyzylkol-lake-trail',
        'taraz',
        'NATURE',
        0,
        5,
        'HOURS',
        4.5,
        'Тропа озера Кызылколь',
        'Kyzylkol Lake Trail',
        'Қызылкөл көлі соқпағы',
        'Степной маршрут Жамбылской области к солоноватому озеру, открытым берегам и птицам, хорошо работающий как спокойная природная остановка.',
        'A Zhambyl Region steppe route to a saline lake, open shores and birds, useful as a calm nature stop.',
        'Жамбыл облысындағы тұздылау көлге, ашық жағалауға және құстарға апаратын дала бағыты, тыныш табиғи аялдамаға қолайлы.',
        43.04000000,
        70.04000000,
        'Aksu-Zhabagly Nature Reserve.jpg',
        ARRAY['taraz']::text[],
        ARRAY['taraz']::text[],
        ARRAY['kazakhstan','zhambyl-region','kyzylkol','lake','free-entry','birdwatching']::text[]
    ),
    (
        'kent-mountains-trail',
        'karaganda',
        'NATURE',
        0,
        7,
        'HOURS',
        4.7,
        'Тропа Кентских гор',
        'Kent Mountains Trail',
        'Кент таулары соқпағы',
        'Маршрут Каркаралинского массива к гранитным грядам, сосновым участкам и более уединенному формату Сарыарки.',
        'A Karkaraly massif route toward granite ridges, pine sections and a more secluded Saryarka hiking format.',
        'Қарқаралы массивіндегі гранит жоталарға, қарағайлы бөліктерге және Сарыарқаның оңашалау жорық форматына апаратын бағыт.',
        49.21400000,
        75.60500000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda']::text[],
        ARRAY['karaganda']::text[],
        ARRAY['kazakhstan','karkaraly','kent-mountains','saryarka','free-entry','hiking']::text[]
    ),
    (
        'begazy-granite-trail',
        'karaganda',
        'NATURE',
        0,
        6,
        'HOURS',
        4.6,
        'Гранитная тропа Бегазы',
        'Begazy Granite Trail',
        'Беғазы гранит соқпағы',
        'Маршрут у Бегазы сочетает степной ландшафт, гранитные выходы и археологический контекст Центрального Казахстана без сложного технического рельефа.',
        'A route near Begazy combining steppe scenery, granite outcrops and Central Kazakhstan archaeological context without difficult technical terrain.',
        'Беғазы маңындағы бағыт дала көрінісін, гранитті жерлерді және Орталық Қазақстанның археологиялық контекстін күрделі техникалық бедерсіз біріктіреді.',
        48.17600000,
        75.01600000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda','balkhash']::text[],
        ARRAY['karaganda','balkhash']::text[],
        ARRAY['kazakhstan','central-kazakhstan','begazy','granite','free-entry','walking']::text[]
    ),
    (
        'zhumbaktas-shore-trail',
        'kokshetau',
        'NATURE',
        1000,
        3,
        'HOURS',
        4.7,
        'Береговая тропа Жумбактаса',
        'Zhumbaktas Shore Trail',
        'Жұмбақтас жағалауы соқпағы',
        'Легкий маршрут в Бурабае вдоль озерных видов к Жумбактасу, удобный для короткой прогулки, фото и первого знакомства с северной природой.',
        'An easy Burabay route along lake views toward Zhumbaktas, convenient for a short walk, photos and a first taste of northern nature.',
        'Бурабайдағы Жұмбақтасқа қарай көл көріністері бойымен өтетін жеңіл бағыт, қысқа серуенге, фотоға және солтүстік табиғатпен танысуға ыңғайлы.',
        53.08500000,
        70.30700000,
        'Burabay_National_Park_Kazakhstan.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau','astana']::text[],
        ARRAY['kazakhstan','burabay','zhumbaktas','lake-shore','walking']::text[]
    ),
    (
        'bokty-mountain-view-trail',
        'aktau',
        'NATURE',
        0,
        4,
        'HOURS',
        4.8,
        'Смотровая тропа горы Бокты',
        'Bokty Mountain View Trail',
        'Боқты тауы көрініс соқпағы',
        'Пустынный маршрут Мангистау к выразительной одиночной горе, сухим плато и широким точкам для закатных видов.',
        'A Mangystau desert route to a striking isolated mountain, dry plateaus and wide sunset viewpoints.',
        'Маңғыстаудағы ерекше жеке тауға, құрғақ үстірттерге және күн батар көріністеріне апаратын шөл бағыты.',
        43.89600000,
        54.05900000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','bokty','desert','free-entry','hiking']::text[]
    ),
    (
        'boszhira-fang-view-trail',
        'aktau',
        'NATURE',
        0,
        5,
        'HOURS',
        4.9,
        'Тропа к видам на пики Босжиры',
        'Boszhira Fang View Trail',
        'Босжыра шоқылары көрініс соқпағы',
        'Пеший маршрут по плато Устюрт к видовым точкам на белые пики Босжиры, рассчитанный на гидовые поездки и аккуратное движение по пустынному рельефу.',
        'A Ustyurt plateau walking route toward viewpoints over the pale Boszhira fangs, designed for guided trips and careful movement across desert terrain.',
        'Үстірт платосымен Босжыраның ақ шоқыларына көрініс нүктелеріне апаратын жаяу бағыт, гидпен сапарға және шөл бедерінде мұқият жүруге арналған.',
        43.41300000,
        54.07400000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','ustyurt','boszhira','free-entry','trekking']::text[]
    );

CREATE TEMP TABLE seed_kazakhstan_additional_hiking_resolved_places AS
SELECT
    ('92ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    city_id,
    category,
    price_amount,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['kazakhstan-additional-hiking-v1', 'KZ', 'kz', city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_kazakhstan_additional_hiking_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    'KZ',
    city_id,
    category,
    price_amount,
    'KZT',
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_kazakhstan_additional_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_kazakhstan_additional_hiking_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_kazakhstan_additional_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_kazakhstan_additional_hiking_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_kazakhstan_additional_hiking_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
