-- Europe, Caucasus, Russia, Belarus and Ukraine route-level hiking/day-hike seed.
-- This layer adds concrete trails without duplicating broad parks, landmarks and previously seeded hiking anchors.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_europe_caucasus_hiking_resolved_places;
DROP TABLE IF EXISTS seed_europe_caucasus_hiking_places;

CREATE TEMP TABLE seed_europe_caucasus_hiking_places (
    slug varchar(96) PRIMARY KEY,
    country_code varchar(2) NOT NULL,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    price_currency varchar(3) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_europe_caucasus_hiking_places (
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'gergeti-glacier-trail',
        'GE',
        'stepantsminda',
        'NATURE',
        0,
        'GEL',
        8,
        'HOURS',
        4.9,
        'Тропа к леднику Гергети',
        'Gergeti Glacier Trail',
        'Гергети мұздығына соқпақ',
        'Высокогорный маршрут из Степанцминды к моренным склонам, видам на Казбек и ледниковой зоне для подготовленных гостей.',
        'A high mountain route from Stepantsminda toward moraine slopes, Kazbek views and the glacier zone for prepared hikers.',
        'Степанцминдадан мореналы беткейлерге, Қазбек көріністеріне және мұздық аймағына апаратын дайын саяхатшыларға арналған биік таулы бағыт.',
        42.65000000,
        44.56000000,
        'Gergeti_Trinity_Church,_Georgia.jpg',
        ARRAY['stepantsminda']::text[],
        ARRAY['stepantsminda','tbilisi']::text[],
        ARRAY['georgia','kazbek','glacier','trekking','free-entry']::text[]
    ),
    (
        'juta-chaukhi-lake-trail',
        'GE',
        'gudauri',
        'NATURE',
        0,
        'GEL',
        7,
        'HOURS',
        4.9,
        'Тропа Джута - озеро Чаухи',
        'Juta to Chaukhi Lake Trail',
        'Джутадан Чаухи көліне соқпақ',
        'Маршрут к альпийскому озеру под зубчатыми вершинами Чаухи, удобный как сильный дневной поход из Казбеги или Гудаури.',
        'A route to an alpine lake below the jagged Chaukhi peaks, useful as a strong day hike from Kazbegi or Gudauri.',
        'Чаухидің тісті шыңдары астындағы альпілік көлге апаратын бағыт, Қазбеги немесе Гудауриден қарқынды күндік жорыққа қолайлы.',
        42.57000000,
        44.76000000,
        'Gergeti_Trinity_Church,_Georgia.jpg',
        ARRAY['gudauri','stepantsminda']::text[],
        ARRAY['gudauri','stepantsminda']::text[],
        ARRAY['georgia','juta','chaukhi','alpine-lake','trekking','free-entry']::text[]
    ),
    (
        'mtirala-tsablnari-waterfall-loop',
        'GE',
        'chakvistavi',
        'NATURE',
        4,
        'GEL',
        4,
        'HOURS',
        4.7,
        'Петля к водопаду Цаблнари',
        'Mtirala Tsablnari Waterfall Loop',
        'Цаблнари сарқырамасы айналма соқпағы',
        'Влажный колхидский лес, подвесной мост, каменистая тропа и водопадная точка рядом с Чаквистави.',
        'A humid Colchic forest loop with a bridge, rocky path and waterfall stop near Chakvistavi.',
        'Чаквистави маңындағы ылғалды колхид орманымен өтетін айналма бағыт: көпір, тасты жол және сарқырама аялдамасы.',
        41.68000000,
        41.87500000,
        'Batumi,_Georgia.jpg',
        ARRAY['chakvistavi']::text[],
        ARRAY['batumi']::text[],
        ARRAY['georgia','adjara','colchic-forest','waterfall','hiking']::text[]
    ),
    (
        'parz-to-gosh-lake-trail',
        'AM',
        'dilijan',
        'NATURE',
        0,
        'AMD',
        5,
        'HOURS',
        4.8,
        'Тропа от Парза к озеру Гош',
        'Parz Lake to Gosh Lake Trail',
        'Парз көлінен Гош көліне соқпақ',
        'Лесной маршрут Дилижана между двумя озерами с мягким набором высоты, тенистыми участками и удобной связкой для дневной прогулки.',
        'A Dilijan forest route between two lakes, with gentle elevation, shaded sections and an easy day-walk connection.',
        'Дилижандағы екі көл арасындағы орман бағыты: жеңіл биіктік жинау, көлеңкелі бөліктер және күндік серуенге ыңғайлы байланыс.',
        40.74500000,
        44.95000000,
        'Yerevan,_Armenia.jpg',
        ARRAY['dilijan']::text[],
        ARRAY['dilijan','yerevan']::text[],
        ARRAY['armenia','dilijan','forest','lake','free-entry','hiking']::text[]
    ),
    (
        'mount-dimats-trail',
        'AM',
        'dilijan',
        'NATURE',
        0,
        'AMD',
        7,
        'HOURS',
        4.8,
        'Тропа на гору Диматс',
        'Mount Dimats Trail',
        'Димац тауына соқпақ',
        'Панорамный маршрут над Дилижаном к открытым гребням, зеленым долинам и спокойному горному сценарию без длинного трансфера.',
        'A panoramic route above Dilijan toward open ridges, green valleys and a calm mountain plan without a long transfer.',
        'Дилижан үстіндегі ашық жоталарға, жасыл аңғарларға және ұзақ жолсыз тыныш тау жоспарына апаратын панорамалық бағыт.',
        40.80500000,
        44.91000000,
        'Yerevan,_Armenia.jpg',
        ARRAY['dilijan']::text[],
        ARRAY['dilijan','yerevan']::text[],
        ARRAY['armenia','dilijan','mount-dimats','ridge','free-entry','trekking']::text[]
    ),
    (
        'azat-gorge-basalt-trail',
        'AM',
        'garni',
        'NATURE',
        0,
        'AMD',
        4,
        'HOURS',
        4.7,
        'Базальтовая тропа ущелья Азат',
        'Azat Gorge Basalt Trail',
        'Азат шатқалы базальт соқпағы',
        'Короткий маршрут из Гарни к базальтовым стенам ущелья Азат, реке и сухим склонам, который хорошо дополняет культурный день.',
        'A short route from Garni to basalt walls of Azat Gorge, the river and dry slopes, pairing well with a culture-focused day.',
        'Гарниден Азат шатқалының базальт қабырғаларына, өзенге және құрғақ беткейлерге апаратын қысқа бағыт, мәдени күнмен жақсы үйлеседі.',
        40.11500000,
        44.73500000,
        'Garni_Temple,_Armenia.jpg',
        ARRAY['garni']::text[],
        ARRAY['yerevan','garni']::text[],
        ARRAY['armenia','garni','azat-gorge','basalt','free-entry','walking']::text[]
    ),
    (
        'old-khndzoresk-cave-trail',
        'AM',
        'khndzoresk',
        'NATURE',
        0,
        'AMD',
        3,
        'HOURS',
        4.7,
        'Пещерная тропа Старого Хндзореска',
        'Old Khndzoresk Cave Trail',
        'Ескі Хндзореск үңгір соқпағы',
        'Маршрут по склонам Хндзореска между пещерными жилищами, мостом и видами на ущелье Сюника.',
        'A route across Khndzoresk slopes between cave dwellings, the bridge and Syunik gorge views.',
        'Хндзореск беткейлерімен үңгір үйлері, көпір және Сюник шатқалы көріністері арқылы өтетін бағыт.',
        39.50500000,
        46.43200000,
        'Tatev_Monastery,_Armenia.jpg',
        ARRAY['khndzoresk','goris']::text[],
        ARRAY['goris','tatev']::text[],
        ARRAY['armenia','syunik','khndzoresk','caves','free-entry','walking']::text[]
    ),
    (
        'candy-cane-mountains-trail',
        'AZ',
        'shamakhi',
        'NATURE',
        0,
        'AZN',
        4,
        'HOURS',
        4.7,
        'Тропа Цветных гор',
        'Candy Cane Mountains Trail',
        'Түрлі түсті таулар соқпағы',
        'Сухой маршрут по полосатым предгорьям между Баку и Шемахой, с ярким рельефом и короткими обзорными тропами.',
        'A dry route across striped foothills between Baku and Shamakhi, with vivid relief and short viewpoint paths.',
        'Баку мен Шамахы арасындағы жолақты тау етектерімен өтетін құрғақ бағыт: ашық бедер және қысқа көрініс соқпақтары.',
        40.91000000,
        48.98000000,
        'Shamakhi Astrophysical Observatory.jpg',
        ARRAY['shamakhi']::text[],
        ARRAY['baku','shamakhi']::text[],
        ARRAY['azerbaijan','shamakhi','striped-mountains','free-entry','walking']::text[]
    ),
    (
        'goygol-lake-shore-trail',
        'AZ',
        'goygol',
        'NATURE',
        2,
        'AZN',
        4,
        'HOURS',
        4.8,
        'Береговая тропа озера Гейгель',
        'Goygol Lake Shore Trail',
        'Гёйгёль көлі жағалауы соқпағы',
        'Горная прогулка вдоль синей воды, лесных склонов и обзорных точек вокруг озера Гейгель.',
        'A mountain walk along blue water, forested slopes and viewpoints around Goygol Lake.',
        'Гёйгёль көлі маңындағы көгілдір су, орманды беткейлер және көрініс нүктелері бойымен өтетін тау серуені.',
        40.40500000,
        46.32500000,
        'Goygol Lake Azerbaijan.jpg',
        ARRAY['goygol']::text[],
        ARRAY['goygol','ganja']::text[],
        ARRAY['azerbaijan','goygol','lake-shore','hiking']::text[]
    ),
    (
        'khanbulan-lake-forest-trail',
        'AZ',
        'hirkan',
        'NATURE',
        2,
        'AZN',
        4,
        'HOURS',
        4.7,
        'Лесная тропа озера Ханбулан',
        'Khanbulan Lake Forest Trail',
        'Ханбулан көлі орман соқпағы',
        'Ленкоранский лесной маршрут к озеру Ханбулан с влажными склонами, субтропической зеленью и спокойным природным днем.',
        'A Lankaran forest route to Khanbulan Lake with humid slopes, subtropical greenery and a calm nature day.',
        'Ленкоран маңындағы Ханбулан көліне апаратын орман бағыты: ылғалды беткейлер, субтропикалық жасылдық және тыныш табиғи күн.',
        38.67500000,
        48.74500000,
        'Lankaran Azerbaijan.jpg',
        ARRAY['hirkan','lankaran']::text[],
        ARRAY['lankaran']::text[],
        ARRAY['azerbaijan','lankaran','khanbulan','forest','hiking']::text[]
    ),
    (
        'losiny-ostrov-ecological-trail',
        'RU',
        'moscow',
        'NATURE',
        0,
        'RUB',
        3,
        'HOURS',
        4.5,
        'Экотропа Лосиного Острова',
        'Losiny Ostrov Ecological Trail',
        'Лосиный Остров экосоқпағы',
        'Городская природная тропа Москвы с лесом, заболоченными участками и быстрым способом сменить центр на тихий зеленый маршрут.',
        'A Moscow city nature trail with forest, wetland sections and a quick way to swap the center for a quiet green route.',
        'Мәскеудегі орман, сулы-батпақты бөліктер және орталықтан тыныш жасыл бағытқа тез ауысуға мүмкіндік беретін қалалық табиғи соқпақ.',
        55.86000000,
        37.78000000,
        'Kremlin_and_Red_Square.1.jpg',
        ARRAY['moscow']::text[],
        ARRAY['moscow']::text[],
        ARRAY['russia','moscow','city-nature','forest','free-entry','walking']::text[]
    ),
    (
        'komarovo-shore-eco-trail',
        'RU',
        'spb',
        'NATURE',
        0,
        'RUB',
        3,
        'HOURS',
        4.6,
        'Береговая экотропа Комарово',
        'Komarovo Shore Eco Trail',
        'Комарово жағалауы экосоқпағы',
        'Легкий маршрут у Финского залива с сосновым лесом, дюнами, деревянными настилами и спокойной северной атмосферой.',
        'An easy Gulf of Finland route with pine forest, dunes, boardwalk sections and a calm northern atmosphere.',
        'Фин шығанағы маңындағы жеңіл бағыт: қарағайлы орман, құмды төбелер, ағаш жолдар және тыныш солтүстік атмосфера.',
        60.18400000,
        29.80700000,
        'Spb_06-2017_img33_New_Holland.jpg',
        ARRAY['spb']::text[],
        ARRAY['spb']::text[],
        ARRAY['russia','saint-petersburg','komarovo','shore','free-entry','walking']::text[]
    ),
    (
        'eagle-rocks-matsesta-trail',
        'RU',
        'sochi',
        'NATURE',
        200,
        'RUB',
        4,
        'HOURS',
        4.7,
        'Тропа Орлиные скалы и Мацеста',
        'Eagle Rocks and Matsesta Springs Trail',
        'Бүркіт жартастары мен Мацеста соқпағы',
        'Сочинский маршрут к известняковым скалам, лесу и видам на море, который хорошо работает как активная половина дня.',
        'A Sochi route to limestone cliffs, forest and sea views, working well as an active half-day plan.',
        'Сочидегі әктасты жартастарға, орманға және теңіз көріністеріне апаратын бағыт, белсенді жарты күндік жоспарға қолайлы.',
        43.55300000,
        39.82000000,
        'Agura_Waterfalls_Sochi.jpg',
        ARRAY['sochi']::text[],
        ARRAY['sochi']::text[],
        ARRAY['russia','sochi','matsesta','cliffs','hiking']::text[]
    ),
    (
        'seven-brothers-rocks-trail',
        'RU',
        'yekaterinburg',
        'NATURE',
        0,
        'RUB',
        5,
        'HOURS',
        4.7,
        'Тропа к скалам Семь Братьев',
        'Seven Brothers Rocks Trail',
        'Жеті Ағайынды жартастар соқпағы',
        'Уральский маршрут из Екатеринбурга к гранитным останцам, сосновому лесу и обзорным точкам Среднего Урала.',
        'A Ural route from Yekaterinburg to granite outcrops, pine forest and Middle Ural viewpoints.',
        'Екатеринбургтен гранит жартастарға, қарағайлы орманға және Орта Орал көрініс нүктелеріне апаратын бағыт.',
        56.99000000,
        60.35000000,
        'Yekaterinburg._Yeltsin_Center._2021.jpg',
        ARRAY['yekaterinburg']::text[],
        ARRAY['yekaterinburg']::text[],
        ARRAY['russia','ural','rocks','forest','free-entry','hiking']::text[]
    ),
    (
        'blue-lakes-forest-loop-kazan',
        'RU',
        'kazan',
        'NATURE',
        0,
        'RUB',
        3,
        'HOURS',
        4.6,
        'Лесная петля Голубых озер',
        'Blue Lakes Forest Loop',
        'Көк көлдер орман айналма соқпағы',
        'Короткий природный маршрут рядом с Казанью по лесу, прозрачным карстовым озерам и спокойным береговым участкам.',
        'A short nature route near Kazan through forest, clear karst lakes and calm shore sections.',
        'Қазан маңындағы орман, мөлдір карст көлдері және тыныш жағалау бөліктері арқылы өтетін қысқа табиғи бағыт.',
        55.88300000,
        49.16000000,
        'Казанский кремль. Панорама с колеса обозрения.jpg',
        ARRAY['kazan']::text[],
        ARRAY['kazan']::text[],
        ARRAY['russia','kazan','blue-lakes','forest','free-entry','walking']::text[]
    ),
    (
        'slobodka-ridge-lakes-view-trail',
        'BY',
        'braslav',
        'NATURE',
        0,
        'BYN',
        3,
        'HOURS',
        4.7,
        'Тропа Слободской гряды к озерным видам',
        'Slobodka Ridge Lakes View Trail',
        'Слободка жотасы көл көрінісі соқпағы',
        'Короткий маршрут по холмистой гряде у Браслава с видами на цепочку озер, деревни и мягкий северный ландшафт.',
        'A short route along a hilly ridge near Braslav, with views over a chain of lakes, villages and gentle northern scenery.',
        'Браслав маңындағы қыратты жота бойымен өтетін қысқа бағыт: көлдер тізбегіне, ауылдарға және жұмсақ солтүстік ландшафтқа көрініс береді.',
        55.64000000,
        27.06000000,
        'Braslav_Lakes_National_Park.jpg',
        ARRAY['braslav']::text[],
        ARRAY['braslav','minsk']::text[],
        ARRAY['belarus','braslav','lakes','ridge','free-entry','walking']::text[]
    ),
    (
        'blue-lakes-eco-trail-naroch',
        'BY',
        'naroch',
        'NATURE',
        0,
        'BYN',
        4,
        'HOURS',
        4.7,
        'Экотропа Голубых озер',
        'Blue Lakes Eco Trail',
        'Көк көлдер экосоқпағы',
        'Маршрут Нарочанского края через лес, озерные берега и обзорные точки, хороший для спокойного природного дня.',
        'A Naroch-area route through forest, lake shores and viewpoints, suited for a calm nature day.',
        'Нарочь өңіріндегі орман, көл жағалауы және көрініс нүктелері арқылы өтетін бағыт, тыныш табиғи күнге қолайлы.',
        54.87000000,
        26.76000000,
        'Naroch_National_Park.jpg',
        ARRAY['naroch']::text[],
        ARRAY['naroch','minsk']::text[],
        ARRAY['belarus','naroch','eco-trail','lakes','free-entry','hiking']::text[]
    ),
    (
        'tsarskaya-polyana-forest-trail',
        'BY',
        'belovezhskaya-pushcha',
        'NATURE',
        0,
        'BYN',
        3,
        'HOURS',
        4.7,
        'Лесная тропа Царской поляны',
        'Tsarskaya Polyana Forest Trail',
        'Патша алаңы орман соқпағы',
        'Маршрут по старому лесу Беловежской зоны с мягким рельефом, полянами и спокойным форматом наблюдения за природой.',
        'A route through old forest in the Belovezhskaya area, with gentle terrain, glades and a calm nature-watching format.',
        'Беловеж аймағындағы көне орман арқылы өтетін бағыт: жұмсақ бедер, алаңқайлар және табиғатты тыныш бақылау форматы.',
        52.60000000,
        23.84000000,
        'Belovezhskaya_Pushcha.jpg',
        ARRAY['belovezhskaya-pushcha']::text[],
        ARRAY['brest','belovezhskaya-pushcha']::text[],
        ARRAY['belarus','belovezhskaya','forest','free-entry','walking']::text[]
    ),
    (
        'pripyat-floodplain-boardwalk-trail',
        'BY',
        'pripyatsky',
        'NATURE',
        0,
        'BYN',
        3,
        'HOURS',
        4.7,
        'Настильная тропа поймы Припяти',
        'Pripyat Floodplain Boardwalk Trail',
        'Припять жайылмасы ағаш соқпағы',
        'Маршрут через пойменные луга, болотные участки и деревянные настилы, где удобно смотреть птиц и речной ландшафт.',
        'A route through floodplain meadows, wetland sections and boardwalks, convenient for birds and river scenery.',
        'Жайылма шалғындар, батпақты бөліктер және ағаш жолдар арқылы өтетін бағыт, құстар мен өзен ландшафтын көруге ыңғайлы.',
        52.06000000,
        28.11000000,
        'Pripyatsky_National_Park.jpg',
        ARRAY['pripyatsky','turov']::text[],
        ARRAY['pripyatsky','turov']::text[],
        ARRAY['belarus','pripyat','floodplain','boardwalk','free-entry','birdwatching']::text[]
    ),
    (
        'makovytsia-mountain-trail',
        'UA',
        'yaremche',
        'NATURE',
        0,
        'UAH',
        5,
        'HOURS',
        4.8,
        'Тропа на гору Маковица',
        'Makovytsia Mountain Trail',
        'Маковиця тауына соқпақ',
        'Карпатский маршрут из Яремче к лесным склонам, полонинам и видам на долину Прута.',
        'A Carpathian route from Yaremche toward forested slopes, meadows and views over the Prut valley.',
        'Яремчеден орманды беткейлерге, шалғындарға және Прут аңғары көріністеріне апаратын Карпат бағыты.',
        48.45500000,
        24.59000000,
        'Dovbush_Trail_Yaremche.jpg',
        ARRAY['yaremche']::text[],
        ARRAY['yaremche']::text[],
        ARRAY['ukraine','carpathians','yaremche','mountain','free-entry','hiking']::text[]
    ),
    (
        'hoverla-ascent-zarosliak',
        'UA',
        'bukovel',
        'NATURE',
        100,
        'UAH',
        8,
        'HOURS',
        4.9,
        'Подъем на Говерлу от Заросляка',
        'Hoverla Ascent from Zarosliak',
        'Заросляктан Говерлаға көтерілу',
        'Классический карпатский подъем к высшей точке Украины с каменистой верхней частью, ветром и широкими видами Черногоры.',
        'A classic Carpathian ascent to Ukraine highest point, with a rocky upper section, wind and broad Chornohora views.',
        'Украинаның ең биік нүктесіне апаратын классикалық Карпат көтерілуі: тасты жоғарғы бөлік, жел және Черногораның кең көріністері.',
        48.16000000,
        24.50000000,
        'Bukovel_Resort.jpg',
        ARRAY['bukovel','yaremche']::text[],
        ARRAY['bukovel','yaremche']::text[],
        ARRAY['ukraine','carpathians','hoverla','summit','trekking']::text[]
    ),
    (
        'synyak-mountain-trail',
        'UA',
        'bukovel',
        'NATURE',
        0,
        'UAH',
        5,
        'HOURS',
        4.7,
        'Тропа на гору Синяк',
        'Synyak Mountain Trail',
        'Синяк тауына соқпақ',
        'Маршрут рядом с Буковелем к лесным склонам, каменистым участкам и панораме курортной долины.',
        'A route near Bukovel toward forested slopes, rocky sections and a panorama of the resort valley.',
        'Буковель маңындағы орманды беткейлерге, тасты бөліктерге және курорт аңғары панорамасына апаратын бағыт.',
        48.38000000,
        24.43000000,
        'Bukovel_Resort.jpg',
        ARRAY['bukovel']::text[],
        ARRAY['bukovel','yaremche']::text[],
        ARRAY['ukraine','carpathians','bukovel','synyak','free-entry','hiking']::text[]
    ),
    (
        'borzhava-velykyi-verkh-trail',
        'UA',
        'uzhhorod',
        'NATURE',
        0,
        'UAH',
        7,
        'HOURS',
        4.8,
        'Тропа Боржавы к Великому Верху',
        'Borzhava Ridge to Velykyi Verkh Trail',
        'Боржава жотасынан Великий Верхке соқпақ',
        'Открытый карпатский гребень с травянистыми склонами, ветреной погодой и длинными панорамами Закарпатья.',
        'An open Carpathian ridge with grassy slopes, windy weather and long Transcarpathian panoramas.',
        'Шөпті беткейлері, желді ауа райы және Закарпатияның ұзын панорамалары бар ашық Карпат жотасы.',
        48.65000000,
        23.25000000,
        'Uzhhorod_Castle.jpg',
        ARRAY['uzhhorod','mukachevo']::text[],
        ARRAY['uzhhorod','mukachevo']::text[],
        ARRAY['ukraine','transcarpathia','borzhava','ridge','free-entry','trekking']::text[]
    ),
    (
        'eiger-trail',
        'CH',
        'interlaken',
        'NATURE',
        0,
        'CHF',
        4,
        'HOURS',
        4.9,
        'Тропа Айгера',
        'Eiger Trail',
        'Айгер соқпағы',
        'Альпийский маршрут у подножия северной стены Айгера с ледниковыми видами, скальными участками и сильной связкой для гостей Интерлакена.',
        'An alpine route below the Eiger north face, with glacier views, rocky sections and a strong connection for Interlaken guests.',
        'Айгердің солтүстік қабырғасы астындағы альпілік бағыт: мұздық көріністері, тасты бөліктер және Интерлакен қонақтарына лайық байланыс.',
        46.58500000,
        8.00500000,
        'Jungfreijoch.jpg',
        ARRAY['interlaken','grindelwald']::text[],
        ARRAY['interlaken','grindelwald']::text[],
        ARRAY['switzerland','eiger','alps','glacier-view','free-entry','hiking']::text[]
    ),
    (
        'nockspitze-saile-summit-trail',
        'AT',
        'innsbruck',
        'NATURE',
        0,
        'EUR',
        6,
        'HOURS',
        4.8,
        'Тропа на Нокшпитце - Зайле',
        'Nockspitze Saile Summit Trail',
        'Нокшпитце - Зайле шыңы соқпағы',
        'Маршрут над Инсбруком к обзорной вершине с альпийскими лугами, каменистым финалом и видами на долину Инна.',
        'A route above Innsbruck to a panoramic summit with alpine meadows, a rocky finish and views over the Inn valley.',
        'Инсбрук үстіндегі альпілік шалғындарға, тасты финалға және Инн аңғары көріністеріне апаратын панорамалық шың бағыты.',
        47.19500000,
        11.34500000,
        'Goldenes_Dachl_(Innsbruck).jpg',
        ARRAY['innsbruck']::text[],
        ARRAY['innsbruck']::text[],
        ARRAY['austria','innsbruck','alps','summit','free-entry','trekking']::text[]
    );

CREATE TEMP TABLE seed_europe_caucasus_hiking_resolved_places AS
SELECT
    ('93ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['europe-caucasus-hiking-v1', country_code, lower(country_code), city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_europe_caucasus_hiking_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_europe_caucasus_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_europe_caucasus_hiking_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_europe_caucasus_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_europe_caucasus_hiking_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_europe_caucasus_hiking_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
