-- Americas and Africa route-level hiking/day-hike seed.
-- This layer adds concrete trails without duplicating broad parks, landmarks and previously seeded route anchors.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_americas_africa_hiking_resolved_places;
DROP TABLE IF EXISTS seed_americas_africa_hiking_places;

CREATE TEMP TABLE seed_americas_africa_hiking_places (
    slug varchar(96) PRIMARY KEY,
    country_code varchar(2) NOT NULL,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    price_currency varchar(3) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_americas_africa_hiking_places (
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'mist-trail-vernal-nevada-falls',
        'US',
        'yosemite',
        'NATURE',
        35,
        'USD',
        6,
        'HOURS',
        4.9,
        'Тропа Mist к водопадам Vernal и Nevada',
        'Mist Trail to Vernal and Nevada Falls',
        'Vernal және Nevada сарқырамаларына Mist соқпағы',
        'Классический маршрут Йосемити по гранитным ступеням, речному каньону и двум мощным водопадам для активного дневного плана.',
        'A classic Yosemite route on granite steps, river canyon sections and two powerful waterfalls for an active day plan.',
        'Йосемитидегі гранит сатылар, өзен каньоны және екі қуатты сарқырама арқылы өтетін белсенді күндік бағыт.',
        37.72700000,
        -119.54300000,
        'Yosemite_Valley_from_Tunnel_View.jpg',
        ARRAY['yosemite']::text[],
        ARRAY['yosemite','san-francisco']::text[],
        ARRAY['united-states','california','waterfalls','granite','trekking']::text[]
    ),
    (
        'bright-angel-day-hike',
        'US',
        'grand-canyon',
        'NATURE',
        35,
        'USD',
        5,
        'HOURS',
        4.9,
        'Дневной маршрут Bright Angel',
        'Bright Angel Trail Day Hike',
        'Bright Angel күндік соқпағы',
        'Каньонный маршрут с серпантинами, каменными стенами и сильным перепадом высоты, где важно заранее рассчитать обратный подъем.',
        'A canyon route with switchbacks, stone walls and serious elevation change, where the return climb must be planned carefully.',
        'Серпантиндері, тас қабырғалары және үлкен биіктік айырмасы бар каньон бағыты, қайтар көтерілуін алдын ала есептеу маңызды.',
        36.05700000,
        -112.14300000,
        'Grand_Canyon_South_Rim.jpg',
        ARRAY['grand-canyon']::text[],
        ARRAY['grand-canyon','las-vegas']::text[],
        ARRAY['united-states','arizona','canyon','day-hike']::text[]
    ),
    (
        'sky-pond-trail',
        'US',
        'rocky-mountain',
        'NATURE',
        30,
        'USD',
        7,
        'HOURS',
        4.9,
        'Тропа к озеру Sky Pond',
        'Sky Pond Trail',
        'Sky Pond көліне соқпақ',
        'Высокогорный маршрут через озера, водопадный участок и каменные чаши Скалистых гор для подготовленных гостей.',
        'A high mountain route through lakes, a waterfall section and rocky basins of the Rockies for prepared hikers.',
        'Көлдер, сарқырама бөлігі және жартасты тау қазаншұңқырлары арқылы өтетін дайын саяхатшыларға арналған биік таулы бағыт.',
        40.31000000,
        -105.66400000,
        'Rocky_Mountain_National_Park.jpg',
        ARRAY['rocky-mountain']::text[],
        ARRAY['denver','rocky-mountain']::text[],
        ARRAY['united-states','colorado','alpine-lake','trekking']::text[]
    ),
    (
        'observation-point-east-mesa-trail',
        'US',
        'zion',
        'NATURE',
        35,
        'USD',
        5,
        'HOURS',
        4.8,
        'Тропа Observation Point через East Mesa',
        'Observation Point Trail via East Mesa',
        'East Mesa арқылы Observation Point соқпағы',
        'Маршрут к высокой обзорной точке с видом на красные стены Зайона, более спокойный по экспозиции, чем самые известные гребневые тропы.',
        'A route to a high viewpoint over red Zion walls, calmer in exposure than the most famous ridge trails.',
        'Зайонның қызыл қабырғаларына қарайтын биік көрініс нүктесіне апаратын бағыт, ең танымал жоталы соқпақтарға қарағанда тынышырақ.',
        37.27800000,
        -112.90000000,
        'Zion_Canyon.jpg',
        ARRAY['zion']::text[],
        ARRAY['zion','las-vegas']::text[],
        ARRAY['united-states','utah','viewpoint','canyon','hiking']::text[]
    ),
    (
        'rattlesnake-ledge-trail',
        'US',
        'seattle',
        'NATURE',
        0,
        'USD',
        4,
        'HOURS',
        4.7,
        'Тропа Rattlesnake Ledge',
        'Rattlesnake Ledge Trail',
        'Rattlesnake Ledge соқпағы',
        'Популярный лесной маршрут недалеко от Сиэтла к скальному выступу с видом на озеро и хвойные склоны Каскадных гор.',
        'A popular forest route near Seattle to a rocky ledge overlooking a lake and Cascade foothills.',
        'Сиэтл маңындағы орман арқылы көлге және Каскад тау етектеріне қарайтын жартасты алаңға апаратын танымал бағыт.',
        47.43500000,
        -121.77000000,
        'Space_Needle002.jpg',
        ARRAY['seattle']::text[],
        ARRAY['seattle']::text[],
        ARRAY['united-states','washington','forest','viewpoint','free-entry','hiking']::text[]
    ),
    (
        'plain-six-glaciers-trail',
        'CA',
        'banff',
        'NATURE',
        11,
        'CAD',
        6,
        'HOURS',
        4.9,
        'Тропа Plain of Six Glaciers',
        'Plain of Six Glaciers Trail',
        'Алты мұздық жазығы соқпағы',
        'Альпийский маршрут от бирюзовой воды к моренным равнинам, ледниковым видам и чайному домику в горах Банфа.',
        'An alpine route from turquoise water toward moraine flats, glacier views and a mountain tea house in Banff.',
        'Банфтағы көгілдір судан мореналы жазықтарға, мұздық көріністеріне және тау шай үйіне апаратын альпілік бағыт.',
        51.41600000,
        -116.24000000,
        'Lake_Louise_Banff.jpg',
        ARRAY['banff']::text[],
        ARRAY['banff','calgary']::text[],
        ARRAY['canada','alberta','glacier-view','trekking']::text[]
    ),
    (
        'johnston-canyon-ink-pots-trail',
        'CA',
        'banff',
        'NATURE',
        11,
        'CAD',
        5,
        'HOURS',
        4.8,
        'Тропа Johnston Canyon к Ink Pots',
        'Johnston Canyon to Ink Pots Trail',
        'Johnston Canyon-нан Ink Pots-қа соқпақ',
        'Маршрут по каньону, мостикам и лесной долине к минеральным источникам с прозрачной водой и открытыми видами.',
        'A canyon, catwalk and forest-valley route toward clear mineral springs and open views.',
        'Каньон, аспалы жолдар және орманды аңғар арқылы мөлдір минералды бұлақтарға және ашық көріністерге апаратын бағыт.',
        51.24500000,
        -115.83900000,
        'Banff_Gondola.jpg',
        ARRAY['banff']::text[],
        ARRAY['banff','calgary']::text[],
        ARRAY['canada','banff','canyon','springs','hiking']::text[]
    ),
    (
        'valley-five-lakes-trail',
        'CA',
        'jasper',
        'NATURE',
        11,
        'CAD',
        4,
        'HOURS',
        4.8,
        'Тропа долины пяти озер',
        'Valley of the Five Lakes Trail',
        'Бес көл аңғары соқпағы',
        'Лесная петля Джаспера между небольшими озерами разного оттенка, мягким рельефом и спокойным форматом полудневного похода.',
        'A Jasper forest loop between small lakes of different colors, with gentle terrain and an easy half-day hiking format.',
        'Джаспердегі түрлі түсті шағын көлдер арасындағы орман айналмасы, жұмсақ бедер және жарты күндік жеңіл жорық форматы.',
        52.81200000,
        -118.00600000,
        'Maligne_Lake_Jasper.jpg',
        ARRAY['jasper']::text[],
        ARRAY['jasper']::text[],
        ARRAY['canada','jasper','lakes','forest','hiking']::text[]
    ),
    (
        'garibaldi-lake-trail',
        'CA',
        'whistler',
        'NATURE',
        0,
        'CAD',
        8,
        'HOURS',
        4.9,
        'Тропа к озеру Гарибальди',
        'Garibaldi Lake Trail',
        'Гарибальди көліне соқпақ',
        'Длинный маршрут из зоны Уистлера к альпийскому озеру, хвойному лесу и вулканическим панорамам Британской Колумбии.',
        'A long route from the Whistler area to an alpine lake, spruce forest and volcanic British Columbia panoramas.',
        'Уистлер аймағынан альпілік көлге, шыршалы орманға және Британдық Колумбияның жанартаулы панорамаларына апаратын ұзақ бағыт.',
        49.95800000,
        -123.12000000,
        'Whistler_Blackcomb.jpg',
        ARRAY['whistler']::text[],
        ARRAY['vancouver','whistler']::text[],
        ARRAY['canada','british-columbia','garibaldi','alpine-lake','free-entry','trekking']::text[]
    ),
    (
        'nevado-toluca-crater-lakes-trail',
        'MX',
        'mexico-city',
        'NATURE',
        60,
        'MXN',
        6,
        'HOURS',
        4.8,
        'Тропа кратерных озер Невадо-де-Толука',
        'Nevado de Toluca Crater Lakes Trail',
        'Невадо-де-Толука кратер көлдері соқпағы',
        'Высотный маршрут из Центральной Мексики к вулканическому кратеру, озерам и открытому альпийскому рельефу.',
        'A high-altitude Central Mexico route to a volcanic crater, lakes and open alpine terrain.',
        'Орталық Мексикадағы жанартаулық кратерге, көлдерге және ашық альпілік бедерге апаратын биік таулы бағыт.',
        19.10800000,
        -99.75800000,
        'Palacio de Bellas Artes.jpg',
        ARRAY['mexico-city']::text[],
        ARRAY['mexico-city']::text[],
        ARRAY['mexico','volcano','crater-lakes','trekking']::text[]
    ),
    (
        'iztaccihuatl-paso-cortes-trail',
        'MX',
        'puebla',
        'NATURE',
        60,
        'MXN',
        7,
        'HOURS',
        4.8,
        'Тропа Истаксиуатль от Пасо-де-Кортес',
        'Iztaccihuatl Paso de Cortes Trail',
        'Пасо-де-Кортестен Истаксиуатль соқпағы',
        'Высотный вулканический маршрут между Пуэблой и Мехико с хвойным лесом, каменистыми склонами и видами на вулканы.',
        'A high volcanic route between Puebla and Mexico City, with pine forest, rocky slopes and volcano views.',
        'Пуэбла мен Мехико арасындағы биік жанартаулық бағыт: қарағайлы орман, тасты беткейлер және жанартаулар көрінісі.',
        19.12500000,
        -98.66000000,
        'Palacio de Bellas Artes.jpg',
        ARRAY['puebla','mexico-city']::text[],
        ARRAY['puebla','mexico-city']::text[],
        ARRAY['mexico','puebla','volcano','high-altitude','trekking']::text[]
    ),
    (
        'sierra-norte-pueblos-mancomunados-trail',
        'MX',
        'oaxaca',
        'NATURE',
        0,
        'MXN',
        7,
        'HOURS',
        4.7,
        'Тропа Sierra Norte Pueblos Mancomunados',
        'Sierra Norte Pueblos Mancomunados Trail',
        'Sierra Norte Pueblos Mancomunados соқпағы',
        'Горный маршрут Оахаки через сосново-дубовые леса, деревни и прохладные гребни северной сьерры.',
        'An Oaxaca mountain route through pine-oak forests, villages and cool ridges of the northern sierra.',
        'Оахакадағы қарағай-емен ормандары, ауылдар және солтүстік сьерраның салқын жоталары арқылы өтетін тау бағыты.',
        17.25000000,
        -96.45000000,
        'Monte Alban Oaxaca Mexico.jpg',
        ARRAY['oaxaca']::text[],
        ARRAY['oaxaca']::text[],
        ARRAY['mexico','oaxaca','sierra-norte','forest','free-entry','hiking']::text[]
    ),
    (
        'pedra-bonita-trail',
        'BR',
        'rio-de-janeiro',
        'NATURE',
        0,
        'BRL',
        3,
        'HOURS',
        4.8,
        'Тропа Pedra Bonita',
        'Pedra Bonita Trail',
        'Pedra Bonita соқпағы',
        'Короткий подъем в Рио к площадке с видами на океан, зеленые склоны и городские пляжи.',
        'A short Rio ascent to a viewpoint over the ocean, green slopes and city beaches.',
        'Риодағы мұхитқа, жасыл беткейлерге және қалалық жағажайларға көрініс беретін алаңға қысқа көтерілу.',
        -22.98800000,
        -43.28500000,
        'Christ the Redeemer - Cristo Redentor.jpg',
        ARRAY['rio-de-janeiro']::text[],
        ARRAY['rio-de-janeiro']::text[],
        ARRAY['brazil','rio','viewpoint','free-entry','hiking']::text[]
    ),
    (
        'dois-irmaos-trail',
        'BR',
        'rio-de-janeiro',
        'NATURE',
        0,
        'BRL',
        3,
        'HOURS',
        4.8,
        'Тропа Dois Irmaos',
        'Dois Irmaos Trail',
        'Dois Irmaos соқпағы',
        'Городской маршрут к вершине над Леблоном и Видигалом, где открывается панорама пляжей и лагуны.',
        'An urban mountain route above Leblon and Vidigal, opening a panorama of beaches and the lagoon.',
        'Леблон мен Видигал үстіндегі қалалық тау бағыты, жағажайлар мен лагуна панорамасын ашады.',
        -22.99600000,
        -43.24000000,
        'Vista aérea das praias de Copacabana e de Ipanema (007ALA112).jpg',
        ARRAY['rio-de-janeiro']::text[],
        ARRAY['rio-de-janeiro']::text[],
        ARRAY['brazil','rio','urban-hike','free-entry','viewpoint']::text[]
    ),
    (
        'lagoinha-do-leste-trail',
        'BR',
        'florianopolis',
        'NATURE',
        0,
        'BRL',
        4,
        'HOURS',
        4.8,
        'Тропа Lagoinha do Leste',
        'Lagoinha do Leste Trail',
        'Lagoinha do Leste соқпағы',
        'Прибрежный маршрут Флорианополиса к дикому пляжу, лагуне и зеленым холмам южной части острова.',
        'A Florianopolis coastal route to a wild beach, lagoon and green hills on the island south side.',
        'Флорианополистегі аралдың оңтүстігіндегі жабайы жағажайға, лагунаға және жасыл төбелерге апаратын жағалау бағыты.',
        -27.77500000,
        -48.48500000,
        'Vista aérea das praias de Copacabana e de Ipanema (007ALA112).jpg',
        ARRAY['florianopolis']::text[],
        ARRAY['florianopolis']::text[],
        ARRAY['brazil','florianopolis','coastal-trail','free-entry','hiking']::text[]
    ),
    (
        'mirante-da-janela-trail',
        'BR',
        'chapada-dos-veadeiros',
        'NATURE',
        0,
        'BRL',
        5,
        'HOURS',
        4.8,
        'Тропа Mirante da Janela',
        'Mirante da Janela Trail',
        'Mirante da Janela соқпағы',
        'Маршрут Серрадо к каменной рамке и видам на водопады, сухие плато и глубокие долины центральной Бразилии.',
        'A cerrado route to a stone-window viewpoint over waterfalls, dry plateaus and deep valleys of central Brazil.',
        'Орталық Бразилиядағы сарқырамаларға, құрғақ үстірттерге және терең аңғарларға қарайтын тас терезе нүктесіне апаратын серрадо бағыты.',
        -14.15000000,
        -47.65000000,
        'Lençóis Maranhenses 2018.jpg',
        ARRAY['chapada-dos-veadeiros']::text[],
        ARRAY['brasilia','chapada-dos-veadeiros']::text[],
        ARRAY['brazil','cerrado','viewpoint','free-entry','hiking']::text[]
    ),
    (
        'laguna-torre-trail',
        'AR',
        'el-chalten',
        'NATURE',
        0,
        'ARS',
        7,
        'HOURS',
        4.9,
        'Тропа к лагуне Torre',
        'Laguna Torre Trail',
        'Torre лагунасына соқпақ',
        'Патагонский маршрут из Эль-Чальтена к ледниковой лагуне, ветреным долинам и видам на гранитные башни.',
        'A Patagonian route from El Chalten toward a glacial lagoon, windy valleys and granite tower views.',
        'Эль-Чальтеннен мұздық лагунаға, желді аңғарларға және гранит мұнараларға көріністерге апаратын Патагония бағыты.',
        -49.32000000,
        -73.05000000,
        'PeritoMoreno005.jpg',
        ARRAY['el-chalten']::text[],
        ARRAY['el-chalten']::text[],
        ARRAY['argentina','patagonia','glacial-lagoon','free-entry','trekking']::text[]
    ),
    (
        'cerro-llao-llao-trail',
        'AR',
        'bariloche',
        'NATURE',
        0,
        'ARS',
        3,
        'HOURS',
        4.7,
        'Тропа Cerro Llao Llao',
        'Cerro Llao Llao Trail',
        'Cerro Llao Llao соқпағы',
        'Короткий лесной маршрут Барилоче к холму с видами на озера, острова и горные гребни Науэль-Уапи.',
        'A short Bariloche forest route to a hill with views of lakes, islands and Nahuel Huapi ridges.',
        'Барилочедегі көлдерге, аралдарға және Науэль-Уапи жоталарына көрініс беретін төбеге апаратын қысқа орман бағыты.',
        -41.05500000,
        -71.54000000,
        'Llao Llao Peninsula.jpg',
        ARRAY['bariloche']::text[],
        ARRAY['bariloche']::text[],
        ARRAY['argentina','bariloche','lake-view','free-entry','walking']::text[]
    ),
    (
        'laguna-esmeralda-trail',
        'AR',
        'ushuaia',
        'NATURE',
        0,
        'ARS',
        5,
        'HOURS',
        4.8,
        'Тропа к лагуне Esmeralda',
        'Laguna Esmeralda Trail',
        'Esmeralda лагунасына соқпақ',
        'Маршрут Огненной Земли через лес, торфяники и открытые долины к яркой горной лагуне.',
        'A Tierra del Fuego route through forest, peatlands and open valleys to a vivid mountain lagoon.',
        'Отты Жердегі орман, шымтезек жерлер және ашық аңғарлар арқылы жарқын тау лагунасына апаратын бағыт.',
        -54.72100000,
        -68.12200000,
        'PeritoMoreno005.jpg',
        ARRAY['ushuaia']::text[],
        ARRAY['ushuaia']::text[],
        ARRAY['argentina','tierra-del-fuego','lagoon','free-entry','hiking']::text[]
    ),
    (
        'guanayara-trail',
        'CU',
        'trinidad',
        'NATURE',
        10,
        'CUP',
        4,
        'HOURS',
        4.7,
        'Тропа Гуанаяра',
        'Guanayara Trail',
        'Гуанаяра соқпағы',
        'Маршрут гор Эскамбрай к реке, природным бассейнам и прохладному лесу недалеко от Тринидада.',
        'An Escambray route near Trinidad toward a river, natural pools and cool forest.',
        'Тринидад маңындағы Эскамбрай бағыты: өзенге, табиғи бассейндерге және салқын орманға апарады.',
        21.91500000,
        -80.03300000,
        'Plaza_Mayor,_Trinidad,_Cuba.jpg',
        ARRAY['trinidad']::text[],
        ARRAY['trinidad']::text[],
        ARRAY['cuba','escambray','river','forest','hiking']::text[]
    ),
    (
        'colored-canyon-trail',
        'EG',
        'dahab',
        'NATURE',
        200,
        'EGP',
        4,
        'HOURS',
        4.7,
        'Тропа Цветного каньона',
        'Colored Canyon Trail',
        'Түсті каньон соқпағы',
        'Синайский маршрут по узким песчаниковым проходам, цветным стенам и сухому пустынному рельефу.',
        'A Sinai route through narrow sandstone passages, colored walls and dry desert terrain.',
        'Синайдағы тар құмтас өткелдер, түсті қабырғалар және құрғақ шөл бедері арқылы өтетін бағыт.',
        29.01300000,
        34.66000000,
        'Dahab_Lagoon.jpg',
        ARRAY['dahab']::text[],
        ARRAY['dahab','sharm-el-sheikh']::text[],
        ARRAY['egypt','sinai','canyon','desert','hiking']::text[]
    ),
    (
        'toubkal-refuge-trail',
        'MA',
        'imlil',
        'NATURE',
        0,
        'MAD',
        8,
        'HOURS',
        4.8,
        'Тропа к приюту Тубкаль',
        'Toubkal Refuge Trail',
        'Тубкаль панасына соқпақ',
        'Высокогорный маршрут из Имлиля по долине и каменистым склонам к базовой точке восхождений Высокого Атласа.',
        'A high mountain route from Imlil through valley paths and rocky slopes toward the High Atlas ascent base.',
        'Имлильден аңғар жолдары және тасты беткейлер арқылы Биік Атласқа көтерілу базасына апаратын биік таулы бағыт.',
        31.07400000,
        -7.93000000,
        'Jemaa_el-Fnaa_at_night.jpg',
        ARRAY['imlil']::text[],
        ARRAY['imlil','marrakech']::text[],
        ARRAY['morocco','high-atlas','toubkal','free-entry','trekking']::text[]
    ),
    (
        'jebel-saghro-bab-n-ali-trail',
        'MA',
        'ouarzazate',
        'NATURE',
        0,
        'MAD',
        6,
        'HOURS',
        4.7,
        'Тропа Джебель-Сагро к Баб-н-Али',
        $$Jebel Saghro Bab n'Ali Trail$$,
        'Джебель-Сагро Баб-н-Али соқпағы',
        'Сухой горный маршрут восточнее Уарзазата среди черных скал, плато и драматичных каменных башен.',
        'A dry mountain route east of Ouarzazate among dark rocks, plateaus and dramatic stone towers.',
        'Уарзазаттың шығысындағы қара жартастар, үстірттер және әсерлі тас мұнаралар арасындағы құрғақ тау бағыты.',
        30.74000000,
        -5.62000000,
        'Ait_Ben_Haddou_03.JPG',
        ARRAY['ouarzazate']::text[],
        ARRAY['ouarzazate']::text[],
        ARRAY['morocco','jebel-saghro','desert-mountains','free-entry','hiking']::text[]
    ),
    (
        'talassemtane-forest-trail',
        'MA',
        'chefchaouen',
        'NATURE',
        0,
        'MAD',
        5,
        'HOURS',
        4.7,
        'Лесная тропа Талассемтане',
        'Talassemtane Forest Trail',
        'Талассемтане орман соқпағы',
        'Маршрут Рифских гор из Шефшауэна через хвойный лес, известняковые склоны и прохладные долины.',
        'A Rif Mountains route from Chefchaouen through conifer forest, limestone slopes and cool valleys.',
        'Шефшауэннен Риф таулары арқылы қылқан орманға, әктасты беткейлерге және салқын аңғарларға апаратын бағыт.',
        35.21000000,
        -5.16000000,
        'Chefchaouen,_Rif_Mountains,_Morocco,_Blue_City.jpg',
        ARRAY['chefchaouen']::text[],
        ARRAY['chefchaouen','tangier']::text[],
        ARRAY['morocco','rif','forest','free-entry','hiking']::text[]
    ),
    (
        'elephant-hill-trail',
        'KE',
        'aberdares',
        'NATURE',
        20,
        'KES',
        7,
        'HOURS',
        4.8,
        'Тропа Elephant Hill',
        'Elephant Hill Trail',
        'Elephant Hill соқпағы',
        'Высотный маршрут Абердэр к болотистым верхним склонам, бамбуковому лесу и открытым видам центральной Кении.',
        'A high Aberdares route to boggy upper slopes, bamboo forest and open central Kenya views.',
        'Абердэрдегі батпақты жоғарғы беткейлерге, бамбук орманына және орталық Кения көріністеріне апаратын биік бағыт.',
        -0.62500000,
        36.72000000,
        'Aberdare_National_Park.jpg',
        ARRAY['aberdares','nyeri']::text[],
        ARRAY['nyeri','nairobi']::text[],
        ARRAY['kenya','aberdares','bamboo-forest','trekking']::text[]
    ),
    (
        'udzungwa-mwanihana-trail',
        'TZ',
        'udzungwa',
        'NATURE',
        10,
        'TZS',
        8,
        'HOURS',
        4.8,
        'Тропа Mwanihana в Удзунгве',
        'Udzungwa Mwanihana Trail',
        'Удзунгва Mwanihana соқпағы',
        'Лесной маршрут Восточной Африки через влажные склоны, тропическую зелень и обзорные точки над долиной.',
        'An East African forest route through humid slopes, tropical greenery and viewpoints over the valley.',
        'Шығыс Африкадағы ылғалды беткейлер, тропикалық жасылдық және аңғарға көрініс нүктелері арқылы өтетін орман бағыты.',
        -7.78000000,
        36.87000000,
        'Udzungwa_Mountains_National_Park.jpg',
        ARRAY['udzungwa']::text[],
        ARRAY['morogoro','udzungwa']::text[],
        ARRAY['tanzania','udzungwa','rainforest','trekking']::text[]
    ),
    (
        'mount-meru-momella-gate-day-hike',
        'TZ',
        'mount-meru',
        'NATURE',
        10,
        'TZS',
        5,
        'HOURS',
        4.7,
        'Дневной маршрут горы Меру от ворот Momella',
        'Mount Meru Momella Gate Day Hike',
        'Momella қақпасынан Меру тауы күндік бағыты',
        'Маршрут от ворот Момелла к лесным участкам и нижним склонам Меру, подходящий для знакомства с горой без полной экспедиции.',
        'A route from Momella Gate toward forest sections and lower Meru slopes, useful for meeting the mountain without a full expedition.',
        'Momella қақпасынан орман бөліктеріне және Меру төменгі беткейлеріне апаратын бағыт, толық экспедициясыз таумен танысуға қолайлы.',
        -3.23600000,
        36.78000000,
        'Mount_Meru_Tanzania.jpg',
        ARRAY['mount-meru','arusha']::text[],
        ARRAY['arusha','mount-meru']::text[],
        ARRAY['tanzania','arusha','mount-meru','forest','hiking']::text[]
    ),
    (
        'mare-aux-cochons-trail',
        'SC',
        'mahe',
        'NATURE',
        0,
        'SCR',
        5,
        'HOURS',
        4.7,
        'Тропа Mare aux Cochons',
        'Mare aux Cochons Trail',
        'Mare aux Cochons соқпағы',
        'Внутренняя тропа Маэ через влажный лес, гранитные участки и тихие природные зоны вдали от пляжей.',
        'An inland Mahe trail through humid forest, granite sections and quiet nature zones away from the beaches.',
        'Маэ аралындағы жағажайлардан алыс ылғалды орман, гранит бөліктер және тыныш табиғи аймақтар арқылы өтетін ішкі бағыт.',
        -4.63000000,
        55.42000000,
        'Beau Vallon Beach (11177463746).jpg',
        ARRAY['mahe','victoria']::text[],
        ARRAY['mahe','victoria']::text[],
        ARRAY['seychelles','mahe','forest','granite','free-entry','hiking']::text[]
    );

CREATE TEMP TABLE seed_americas_africa_hiking_resolved_places AS
SELECT
    ('94ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['americas-africa-hiking-v1', country_code, lower(country_code), city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_americas_africa_hiking_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_americas_africa_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_americas_africa_hiking_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_americas_africa_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_americas_africa_hiking_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_americas_africa_hiking_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
