-- Additional Kazakhstan route-level hiking/day-hike seed.
-- This layer keeps broad parks and already seeded anchors intact and adds more concrete route choices.
-- price_amount stores a conservative entry floor. Zero means free public access.

DROP TABLE IF EXISTS seed_kazakhstan_more_hiking_resolved_places;
DROP TABLE IF EXISTS seed_kazakhstan_more_hiking_places;

CREATE TEMP TABLE seed_kazakhstan_more_hiking_places (
    slug varchar(96) PRIMARY KEY,
    country_code varchar(2) NOT NULL,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    price_amount numeric(12,2) NOT NULL,
    price_currency varchar(3) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL DEFAULT 'HOURS',
    rating numeric(2,1) NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    media_file text NOT NULL,
    access_city_ids text[] NOT NULL,
    departure_city_ids text[] NOT NULL,
    extra_tags text[] NOT NULL DEFAULT ARRAY[]::text[]
);

INSERT INTO seed_kazakhstan_more_hiking_places (
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    extra_tags
) VALUES
    (
        'mokhnatka-mountain-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        4,
        'HOURS',
        4.7,
        'Тропа на гору Мохнатка',
        'Mokhnatka Mountain Trail',
        'Мохнатка тауына соқпақ',
        'Короткий маршрут над Медеу к открытому гребню и видам на Малую Алматинку, удобный как активный полудневный выход из города.',
        'A short route above Medeu to an open ridge and Little Almatinka views, useful as an active half-day mountain escape from the city.',
        'Медеу үстіндегі ашық жотаға және Кіші Алматы көріністеріне апаратын қысқа бағыт, қаладан белсенді жарты күндік шығуға ыңғайлы.',
        43.14700000,
        77.06200000,
        'AlmaAtaMedeu.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','medeu','ridge','day-hike']::text[]
    ),
    (
        'titov-lake-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        8,
        'HOURS',
        4.8,
        'Тропа к озеру Титова',
        'Titov Lake Trail',
        'Титов көліне соқпақ',
        'Высокогорный маршрут из района Туюксу к моренам, каменным участкам и небольшому озеру для подготовленных походов.',
        'A high mountain route from the Tuyuksu area toward moraines, rocky sections and a small lake for prepared hikers.',
        'Тұйықсу аймағынан мореналарға, тасты бөліктерге және шағын көлге апаратын дайын саяхатшыларға арналған биік таулы бағыт.',
        43.07500000,
        77.10500000,
        'Shymbulak, Almaty (P1180189).jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','tuyuksu','alpine-lake','trekking']::text[]
    ),
    (
        'kamenskoye-plateau-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        6,
        'HOURS',
        4.7,
        'Тропа Каменского плато',
        'Kamenskoye Plateau Trail',
        'Каменское үстірті соқпағы',
        'Маршрут между зелеными седловинами Заилийского Алатау с лесом, открытыми склонами и видом на городские долины.',
        'A route between green Ile Alatau saddles with forest, open slopes and views toward the city valleys.',
        'Іле Алатауының жасыл белестері арасындағы орман, ашық беткейлер және қала аңғарларына көрініс беретін бағыт.',
        43.13000000,
        77.02500000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','plateau','forest','hiking']::text[]
    ),
    (
        'kok-zhailau-waterfall-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        5,
        'HOURS',
        4.7,
        'Тропа к водопаду Кок-Жайляу',
        'Kok-Zhailau Waterfall Trail',
        'Көк-Жайлау сарқырамасына соқпақ',
        'Ответвление популярной зоны к лесному водопаду, где маршрут остается близким к Алматы, но дает ощущение настоящей горной тропы.',
        'A branch route in the popular area toward a forest waterfall, still close to Almaty but with a true mountain-trail feel.',
        'Танымал аймақтан орман сарқырамасына баратын тармақ, Алматыға жақын болса да нағыз тау соқпағы әсерін береді.',
        43.13200000,
        77.00700000,
        'Ile-Alatau_National_Park.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','waterfall','day-hike']::text[]
    ),
    (
        'medeu-terrenkur-health-trail',
        'KZ',
        'almaty',
        'NATURE',
        0,
        'KZT',
        2,
        'HOURS',
        4.6,
        'Терренкур Медеу',
        'Medeu Terrenkur Health Trail',
        'Медеу терренкуры',
        'Легкий оздоровительный маршрут рядом с Медеу: ровный темп, хвойный воздух и формат для тех, кто хочет короткую прогулку без сложного набора.',
        'An easy health route near Medeu with steady pacing, spruce air and a short-walk format without difficult elevation gain.',
        'Медеу маңындағы жеңіл сауықтыру бағыты: бірқалыпты қарқын, шыршалы ауа және күрделі көтерілуі жоқ қысқа серуен форматы.',
        43.15700000,
        77.05700000,
        'AlmaAtaMedeu.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty','medeu','free-entry','walking']::text[]
    ),
    (
        'manshuk-mametova-lake-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        8,
        'HOURS',
        4.8,
        'Тропа к озеру Маншук Маметовой',
        'Manshuk Mametova Lake Trail',
        'Мәншүк Мәметова көліне соқпақ',
        'Спортивный альпийский маршрут в районе Малой Алматинки к каменным моренам и высокогорному озеру для опытных гостей.',
        'A sporty alpine route in the Little Almatinka area toward rocky moraines and a high mountain lake for experienced visitors.',
        'Кіші Алматы аймағындағы тәжірибелі қонақтарға арналған тасты мореналар мен биік тау көліне апаратын спорттық альпілік бағыт.',
        43.05800000,
        77.08500000,
        'Shymbulak, Almaty (P1180189).jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','ile-alatau','alpine-lake','trekking']::text[]
    ),
    (
        'esik-waterfall-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        4,
        'HOURS',
        4.6,
        'Тропа к Есикскому водопаду',
        'Esik Waterfall Trail',
        'Есік сарқырамасына соқпақ',
        'Маршрут восточнее Алматы к лесной долине, ручьям и водопадному участку, хорошо дополняющий поездку в сторону Есика.',
        'A route east of Almaty toward a forest valley, streams and a waterfall section, pairing well with an Esik side trip.',
        'Алматының шығысында орманды аңғарға, бұлақтарға және сарқырама бөлігіне апаратын бағыт, Есік жаққа сапарды жақсы толықтырады.',
        43.29200000,
        77.47300000,
        'Big Almaty Lake 2014.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','esik','waterfall','day-hike']::text[]
    ),
    (
        'oi-qaragai-forest-ridge-trail',
        'KZ',
        'almaty',
        'NATURE',
        1000,
        'KZT',
        4,
        'HOURS',
        4.6,
        'Лесная тропа Ой-Карагайского склона',
        'Oi-Qaragai Forest Ridge Trail',
        'Ой-Қарағай орман жотасы соқпағы',
        'Мягкий маршрут Талгарского направления по лесному склону и обзорным точкам, удобный для семейного активного дня.',
        'A gentle Talgar-side route across forest slopes and viewpoints, convenient for a family active day.',
        'Талғар бағытындағы орманды беткейлер мен көрініс нүктелері арқылы өтетін отбасылық белсенді күнге ыңғайлы жұмсақ бағыт.',
        43.23400000,
        77.23200000,
        'Piktalgar.jpg',
        ARRAY['almaty']::text[],
        ARRAY['almaty']::text[],
        ARRAY['kazakhstan','almaty-region','talgar','forest','day-hike']::text[]
    ),
    (
        'lineyskie-belki-trail',
        'KZ',
        'ust-kamenogorsk',
        'NATURE',
        0,
        'KZT',
        7,
        'HOURS',
        4.8,
        'Тропа Линейских белков',
        'Lineyskie Belki Trail',
        'Линейские белки соқпағы',
        'Риддерский маршрут по горной тайге и открытым гребням с видами на Западный Алтай, рассчитанный на сильный дневной поход.',
        'A Ridder area route through mountain taiga and open ridges with West Altai views, suited to a strong day hike.',
        'Риддер маңындағы тау тайгасы мен ашық жоталар арқылы өтетін, Батыс Алтай көріністері бар қарқынды күндік бағыт.',
        50.36000000,
        83.76000000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','east-kazakhstan','ridder','altai','trekking']::text[]
    ),
    (
        'poperechnoye-lake-trail',
        'KZ',
        'ust-kamenogorsk',
        'NATURE',
        1000,
        'KZT',
        8,
        'HOURS',
        4.8,
        'Тропа к озеру Поперечное',
        'Poperechnoye Lake Trail',
        'Поперечное көліне соқпақ',
        'Алтайский маршрут к высокогорному озеру с лесными долинами, каменными участками и форматом для подготовленных путешественников.',
        'An Altai route to a high mountain lake with forest valleys, rocky sections and a format for prepared travelers.',
        'Орманды аңғарлар, тасты бөліктер және дайын саяхатшыларға арналған формат бар биік тау көліне апаратын Алтай бағыты.',
        49.73800000,
        86.48600000,
        'Beautiful view of the mountains (Katon-Karagay).jpg',
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['ust-kamenogorsk']::text[],
        ARRAY['kazakhstan','altai','katon-karagay','alpine-lake','trekking']::text[]
    ),
    (
        'zhasybai-lake-shore-trail',
        'KZ',
        'pavlodar',
        'NATURE',
        1000,
        'KZT',
        3,
        'HOURS',
        4.7,
        'Береговая тропа озера Жасыбай',
        'Zhasybai Lake Shore Trail',
        'Жасыбай көлі жағалауы соқпағы',
        'Баянаульская прогулка вдоль озера, гранитных склонов и сосновых участков, подходящая для спокойного летнего дня.',
        'A Bayanaul area walk along the lake, granite slopes and pine sections, suited to a calm summer day.',
        'Баянауыл аймағындағы көл, гранит беткейлер және қарағайлы бөліктер бойымен өтетін тыныш жазғы күнге қолайлы серуен.',
        50.80400000,
        75.62100000,
        'Bayanaul National Park.jpg',
        ARRAY['pavlodar']::text[],
        ARRAY['pavlodar']::text[],
        ARRAY['kazakhstan','bayanaul','zhasybai','lake-shore','walking']::text[]
    ),
    (
        'toraigyr-lake-view-trail',
        'KZ',
        'pavlodar',
        'NATURE',
        1000,
        'KZT',
        4,
        'HOURS',
        4.6,
        'Смотровая тропа озера Торайгыр',
        'Toraigyr Lake View Trail',
        'Торайғыр көлі көрініс соқпағы',
        'Маршрут Баянаульского массива к открытым видам на озеро, степь и гранитные формы северного Сарыарка.',
        'A Bayanaul massif route to open views over the lake, steppe and granite forms of northern Saryarka.',
        'Баянауыл массивіндегі көлге, далаға және солтүстік Сарыарқаның гранит пішіндеріне ашық көрініс беретін бағыт.',
        50.82000000,
        75.75000000,
        'Bayanaul National Park.jpg',
        ARRAY['pavlodar']::text[],
        ARRAY['pavlodar']::text[],
        ARRAY['kazakhstan','bayanaul','toraigyr','viewpoint','hiking']::text[]
    ),
    (
        'abylai-khan-meadow-trail',
        'KZ',
        'kokshetau',
        'NATURE',
        1000,
        'KZT',
        2,
        'HOURS',
        4.6,
        'Тропа поляны Абылай хана',
        'Abylai Khan Meadow Trail',
        'Абылай хан алаңы соқпағы',
        'Короткая северная прогулка между соснами, гранитными выступами и озерными видами курортной зоны Бурабая.',
        'A short northern walk among pines, granite outcrops and lake views in the Burabay resort area.',
        'Бурабай курорттық аймағындағы қарағайлар, гранитті шығыңқылар және көл көріністері арасындағы қысқа солтүстік серуен.',
        53.08700000,
        70.30100000,
        'Burabay_National_Park_Kazakhstan.jpg',
        ARRAY['kokshetau']::text[],
        ARRAY['kokshetau','astana']::text[],
        ARRAY['kazakhstan','burabay','meadow','walking']::text[]
    ),
    (
        'kyzyltas-ridge-trail',
        'KZ',
        'karaganda',
        'NATURE',
        0,
        'KZT',
        6,
        'HOURS',
        4.6,
        'Тропа хребта Кызылтас',
        'Kyzyltas Ridge Trail',
        'Қызылтас жотасы соқпағы',
        'Сарыаркинский маршрут по красноватым гранитным грядам, степному горизонту и сухим ущельям Центрального Казахстана.',
        'A Saryarka route across reddish granite ridges, steppe horizon and dry gullies of Central Kazakhstan.',
        'Сарыарқадағы қызғылт гранит жоталар, дала көкжиегі және Орталық Қазақстанның құрғақ сайлары арқылы өтетін бағыт.',
        49.05000000,
        75.26000000,
        'Karkaraly_National_Park.jpg',
        ARRAY['karaganda']::text[],
        ARRAY['karaganda','balkhash']::text[],
        ARRAY['kazakhstan','central-kazakhstan','granite','free-entry','hiking']::text[]
    ),
    (
        'karynzharyk-depression-view-trail',
        'KZ',
        'aktau',
        'NATURE',
        0,
        'KZT',
        5,
        'HOURS',
        4.8,
        'Смотровая тропа впадины Карынжарык',
        'Karynzharyk Depression View Trail',
        'Қарынжарық ойысы көрініс соқпағы',
        'Удаленный маршрут Устюрта к белым обрывам, солончакам и широким пустынным видам, который лучше планировать с гидом.',
        'A remote Ustyurt route toward white cliffs, salt flats and wide desert views, best planned with a guide.',
        'Үстірттегі ақ жартастарға, сорларға және кең шөл көріністеріне апаратын алыстағы бағыт, гидпен жоспарлаған дұрыс.',
        42.73000000,
        54.06000000,
        'Bozzhyra valley, Mangistau region, Kazakhstan.jpg',
        ARRAY['aktau']::text[],
        ARRAY['aktau']::text[],
        ARRAY['kazakhstan','mangystau','ustyurt','desert','free-entry','trekking']::text[]
    );

CREATE TEMP TABLE seed_kazakhstan_more_hiking_resolved_places AS
SELECT
    ('96ad0000-0000-4000-8000-' || substr(md5(slug), 1, 12))::uuid AS id,
    slug,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    media_file,
    access_city_ids,
    departure_city_ids,
    (
        substr(md5(slug || ':media'), 1, 8) || '-' ||
        substr(md5(slug || ':media'), 9, 4) || '-4' ||
        substr(md5(slug || ':media'), 14, 3) || '-8' ||
        substr(md5(slug || ':media'), 18, 3) || '-' ||
        substr(md5(slug || ':media'), 21, 12)
    )::uuid AS media_id,
    'https://commons.wikimedia.org/wiki/Special:FilePath/' || replace(media_file, ' ', '%20') || '?width=1400' AS media_url,
    'https://commons.wikimedia.org/wiki/File:' || replace(media_file, ' ', '_') AS media_source_url,
    ARRAY['kazakhstan-more-hiking-v1', country_code, lower(country_code), city_id, slug, lower(category), 'hiking']::text[] || extra_tags AS tags
FROM seed_kazakhstan_more_hiking_places;

INSERT INTO places (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    latitude,
    longitude,
    location_source_url,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    latitude,
    longitude,
    'https://inflap.app/map?lat=' || trim(to_char(latitude, 'FM999999990.000000')) || '&lon=' || trim(to_char(longitude, 'FM999999990.000000')),
    NOW(),
    NOW()
FROM seed_kazakhstan_more_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    author_user_id = EXCLUDED.author_user_id,
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_source_url = EXCLUDED.location_source_url,
    updated_at = NOW();

INSERT INTO place_translations (
    place_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    id,
    locale,
    title,
    description,
    NOW(),
    NOW()
FROM seed_kazakhstan_more_hiking_resolved_places
CROSS JOIN LATERAL (
    VALUES
        ('ru', title_ru, description_ru),
        ('en', title_en, description_en),
        ('kk', title_kk, description_kk)
) AS localized(locale, title, description)
ON CONFLICT (place_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO place_media (
    id,
    place_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    media_source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_kazakhstan_more_hiking_resolved_places
ON CONFLICT (id) DO UPDATE SET
    place_id = EXCLUDED.place_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    access_city.city_id,
    'ACCESS',
    access_city.ord::int - 1
FROM seed_kazakhstan_more_hiking_resolved_places
CROSS JOIN LATERAL unnest(access_city_ids) WITH ORDINALITY AS access_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

INSERT INTO place_city_links (
    place_id,
    city_id,
    kind,
    sort_order
)
SELECT
    id,
    departure_city.city_id,
    'DEPARTURE',
    departure_city.ord::int - 1
FROM seed_kazakhstan_more_hiking_resolved_places
CROSS JOIN LATERAL unnest(departure_city_ids) WITH ORDINALITY AS departure_city(city_id, ord)
ON CONFLICT (place_id, city_id, kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;
