CREATE TABLE IF NOT EXISTS place_visit_reference_values (
    category varchar(64) NOT NULL,
    code varchar(64) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (category, code)
);

CREATE TABLE IF NOT EXISTS place_visit_reference_translations (
    category varchar(64) NOT NULL,
    code varchar(64) NOT NULL,
    locale varchar(8) NOT NULL,
    label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (category, code, locale),
    FOREIGN KEY (category, code) REFERENCES place_visit_reference_values(category, code) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS place_visit_reference_values_active_idx
    ON place_visit_reference_values (category, is_active, sort_order, code);

WITH seed(category, code, sort_order, is_active, ru, en, kk) AS (
    VALUES
    ('best_time', 'MORNING', 10, true, 'Утро', 'Morning', 'Таң'),
    ('best_time', 'AFTERNOON', 20, true, 'День', 'Afternoon', 'Күндіз'),
    ('best_time', 'EVENING', 30, true, 'Вечер', 'Evening', 'Кеш'),
    ('best_time', 'NIGHT', 40, true, 'Ночь', 'Night', 'Түн'),
    ('best_time', 'SUNRISE', 50, true, 'Рассвет', 'Sunrise', 'Күн шығуы'),
    ('best_time', 'SUNSET', 60, true, 'Закат', 'Sunset', 'Күн батуы'),
    ('best_time', 'ANYTIME', 70, true, 'В любое время', 'Any time', 'Кез келген уақыт'),

    ('fee_type', 'ENTRANCE', 10, true, 'Вход', 'Entrance', 'Кіру'),
    ('fee_type', 'TRANSPORT', 20, true, 'Дополнительный транспорт', 'Additional transport', 'Қосымша көлік'),
    ('fee_type', 'GUIDE', 30, true, 'Гид', 'Guide', 'Гид'),
    ('fee_type', 'TOUR', 40, true, 'Экскурсия', 'Tour', 'Экскурсия'),
    ('fee_type', 'PARKING', 50, true, 'Парковка', 'Parking', 'Тұрақ'),
    ('fee_type', 'AUDIO_GUIDE', 60, true, 'Аудиогид', 'Audio guide', 'Аудиогид'),
    ('fee_type', 'ACTIVITY', 70, true, 'Активность', 'Activity', 'Белсенділік'),
    ('fee_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),

    ('fee_unit', 'PERSON', 10, true, 'Человек', 'Person', 'Адам'),
    ('fee_unit', 'ADULT', 20, true, 'Взрослый', 'Adult', 'Ересек'),
    ('fee_unit', 'CHILD', 30, true, 'Ребенок', 'Child', 'Бала'),
    ('fee_unit', 'STUDENT', 40, true, 'Студент', 'Student', 'Студент'),
    ('fee_unit', 'CAR', 50, true, 'Автомобиль', 'Car', 'Автокөлік'),
    ('fee_unit', 'VEHICLE', 60, true, 'Транспорт', 'Vehicle', 'Көлік'),
    ('fee_unit', 'GROUP', 70, true, 'Группа', 'Group', 'Топ'),
    ('fee_unit', 'TICKET', 80, true, 'Билет', 'Ticket', 'Билет'),
    ('fee_unit', 'DAY', 90, true, 'День', 'Day', 'Күн'),
    ('fee_unit', 'HOUR', 100, true, 'Час', 'Hour', 'Сағат'),
    ('fee_unit', 'RIDE', 110, true, 'Поездка', 'Ride', 'Сапар'),
    ('fee_unit', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),

    ('road_condition', 'PAVED', 10, true, 'Асфальтированная дорога', 'Paved road', 'Асфальт жол'),
    ('road_condition', 'GRAVEL', 20, true, 'Гравийная дорога', 'Gravel road', 'Қиыршық тас жол'),
    ('road_condition', 'MIXED', 30, true, 'Смешанное покрытие', 'Mixed surface', 'Аралас жол'),
    ('road_condition', 'DIRT', 40, true, 'Грунтовая дорога', 'Dirt road', 'Топырақ жол'),
    ('road_condition', 'ROUGH', 50, true, 'Сложная дорога', 'Rough road', 'Қиын жол'),
    ('road_condition', 'OFFROAD', 60, true, 'Бездорожье', 'Off-road', 'Жолсыз жер'),
    ('road_condition', 'WALK_ONLY', 70, true, 'Только пешком', 'Walk only', 'Тек жаяу'),
    ('road_condition', 'WATER', 80, true, 'Водный маршрут', 'Water route', 'Су бағыты'),
    ('road_condition', 'UNKNOWN', 900, true, 'Уточнить перед поездкой', 'Check before travel', 'Сапар алдында нақтылау'),

    ('transport_type', 'CAR', 10, true, 'Автомобиль', 'Car', 'Автокөлік'),
    ('transport_type', 'WALK', 20, true, 'Пешком', 'Walk', 'Жаяу'),
    ('transport_type', 'PUBLIC_TRANSPORT', 30, true, 'Общественный транспорт', 'Public transport', 'Қоғамдық көлік'),
    ('transport_type', 'TAXI', 40, true, 'Такси', 'Taxi', 'Такси'),
    ('transport_type', 'BUS', 50, true, 'Автобус', 'Bus', 'Автобус'),
    ('transport_type', 'TRAIN', 60, true, 'Поезд', 'Train', 'Пойыз'),
    ('transport_type', 'METRO', 70, true, 'Метро', 'Metro', 'Метро'),
    ('transport_type', 'BOAT', 80, true, 'Лодка / катер', 'Boat', 'Қайық / катер'),
    ('transport_type', 'CABLE_CAR', 90, true, 'Канатная дорога', 'Cable car', 'Аспалы жол'),
    ('transport_type', 'BIKE', 100, true, 'Велосипед', 'Bike', 'Велосипед'),
    ('transport_type', 'SHUTTLE', 110, true, 'Шаттл', 'Shuttle', 'Шаттл'),
    ('transport_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),

    ('practical_note_type', 'GENERAL', 10, true, 'Общее', 'General', 'Жалпы'),
    ('practical_note_type', 'WEATHER', 20, true, 'Погода', 'Weather', 'Ауа райы'),
    ('practical_note_type', 'SAFETY', 30, true, 'Безопасность', 'Safety', 'Қауіпсіздік'),
    ('practical_note_type', 'ACCESS', 40, true, 'Доступ', 'Access', 'Қолжетімділік'),
    ('practical_note_type', 'BOOKING', 50, true, 'Бронирование', 'Booking', 'Брондау'),
    ('practical_note_type', 'CROWD', 60, true, 'Очереди и толпы', 'Crowds and queues', 'Кезек пен адам көптігі'),
    ('practical_note_type', 'PAYMENT', 70, true, 'Оплата', 'Payment', 'Төлем'),
    ('practical_note_type', 'CONNECTION', 80, true, 'Связь', 'Connection', 'Байланыс'),
    ('practical_note_type', 'PERMIT', 90, true, 'Разрешение', 'Permit', 'Рұқсат'),
    ('practical_note_type', 'CLOSURE', 100, true, 'Закрытие / ограничения', 'Closure or limits', 'Жабылу / шектеу'),
    ('practical_note_type', 'FAMILY', 110, true, 'С детьми', 'With children', 'Балалармен'),
    ('practical_note_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),

    ('practical_note_priority', 'INFO', 10, true, 'Информация', 'Information', 'Ақпарат'),
    ('practical_note_priority', 'IMPORTANT', 20, true, 'Важно', 'Important', 'Маңызды'),
    ('practical_note_priority', 'WARNING', 30, true, 'Предупреждение', 'Warning', 'Ескерту'),
    ('practical_note_priority', 'CRITICAL', 40, true, 'Критично', 'Critical', 'Өте маңызды'),

    ('recommended_item_type', 'WATER', 10, true, 'Вода', 'Water', 'Су'),
    ('recommended_item_type', 'SHOES', 20, true, 'Удобная обувь', 'Comfortable shoes', 'Ыңғайлы аяқ киім'),
    ('recommended_item_type', 'POWERBANK', 30, true, 'Power bank', 'Power bank', 'Қуаттағыш'),
    ('recommended_item_type', 'DOCUMENTS', 40, true, 'Документы', 'Documents', 'Құжаттар'),
    ('recommended_item_type', 'CASH', 50, true, 'Наличные', 'Cash', 'Қолма-қол ақша'),
    ('recommended_item_type', 'SPF', 60, true, 'SPF / защита от солнца', 'SPF / sun protection', 'SPF / күннен қорғаныс'),
    ('recommended_item_type', 'MAP', 70, true, 'Офлайн-карта', 'Offline map', 'Офлайн карта'),
    ('recommended_item_type', 'FOOD', 80, true, 'Еда', 'Food', 'Тамақ'),
    ('recommended_item_type', 'RAIN', 90, true, 'Дождевик', 'Rain jacket', 'Жаңбырлық'),
    ('recommended_item_type', 'REPELLENT', 100, true, 'Репеллент', 'Repellent', 'Репеллент'),
    ('recommended_item_type', 'JACKET', 110, true, 'Куртка / теплый слой', 'Jacket / warm layer', 'Күртке / жылы қабат'),
    ('recommended_item_type', 'SWIMWEAR', 120, true, 'Купальные вещи', 'Swimwear', 'Шомылу киімі'),
    ('recommended_item_type', 'HAT', 130, true, 'Головной убор', 'Hat', 'Бас киім'),
    ('recommended_item_type', 'SUNGLASSES', 140, true, 'Солнцезащитные очки', 'Sunglasses', 'Күннен қорғайтын көзілдірік'),
    ('recommended_item_type', 'MEDICINE', 150, true, 'Аптечка / лекарства', 'First aid / medicine', 'Дәрі қобдишасы / дәрі'),
    ('recommended_item_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),

    ('recommended_item_importance', 'REQUIRED', 10, true, 'Обязательно', 'Required', 'Міндетті'),
    ('recommended_item_importance', 'RECOMMENDED', 20, true, 'Рекомендуется', 'Recommended', 'Ұсынылады'),
    ('recommended_item_importance', 'OPTIONAL', 30, true, 'По желанию', 'Optional', 'Қалауыңызша'),

    ('season', 'SPRING', 10, true, 'Весна', 'Spring', 'Көктем'),
    ('season', 'SUMMER', 20, true, 'Лето', 'Summer', 'Жаз'),
    ('season', 'AUTUMN', 30, true, 'Осень', 'Autumn', 'Күз'),
    ('season', 'WINTER', 40, true, 'Зима', 'Winter', 'Қыс'),
    ('season', 'ALL_SEASON', 50, true, 'Круглый год', 'All season', 'Жыл бойы'),
    ('season', 'DRY_SEASON', 60, true, 'Сухой сезон', 'Dry season', 'Құрғақ маусым'),
    ('season', 'WET_SEASON', 70, true, 'Сезон дождей', 'Wet season', 'Жаңбырлы маусым')
)
INSERT INTO place_visit_reference_values (category, code, sort_order, is_active, updated_at)
SELECT category, code, sort_order, is_active, NOW()
FROM seed
ON CONFLICT (category, code) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

WITH seed(category, code, sort_order, is_active, ru, en, kk) AS (
    VALUES
    ('best_time', 'MORNING', 10, true, 'Утро', 'Morning', 'Таң'),
    ('best_time', 'AFTERNOON', 20, true, 'День', 'Afternoon', 'Күндіз'),
    ('best_time', 'EVENING', 30, true, 'Вечер', 'Evening', 'Кеш'),
    ('best_time', 'NIGHT', 40, true, 'Ночь', 'Night', 'Түн'),
    ('best_time', 'SUNRISE', 50, true, 'Рассвет', 'Sunrise', 'Күн шығуы'),
    ('best_time', 'SUNSET', 60, true, 'Закат', 'Sunset', 'Күн батуы'),
    ('best_time', 'ANYTIME', 70, true, 'В любое время', 'Any time', 'Кез келген уақыт'),
    ('fee_type', 'ENTRANCE', 10, true, 'Вход', 'Entrance', 'Кіру'),
    ('fee_type', 'TRANSPORT', 20, true, 'Дополнительный транспорт', 'Additional transport', 'Қосымша көлік'),
    ('fee_type', 'GUIDE', 30, true, 'Гид', 'Guide', 'Гид'),
    ('fee_type', 'TOUR', 40, true, 'Экскурсия', 'Tour', 'Экскурсия'),
    ('fee_type', 'PARKING', 50, true, 'Парковка', 'Parking', 'Тұрақ'),
    ('fee_type', 'AUDIO_GUIDE', 60, true, 'Аудиогид', 'Audio guide', 'Аудиогид'),
    ('fee_type', 'ACTIVITY', 70, true, 'Активность', 'Activity', 'Белсенділік'),
    ('fee_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),
    ('fee_unit', 'PERSON', 10, true, 'Человек', 'Person', 'Адам'),
    ('fee_unit', 'ADULT', 20, true, 'Взрослый', 'Adult', 'Ересек'),
    ('fee_unit', 'CHILD', 30, true, 'Ребенок', 'Child', 'Бала'),
    ('fee_unit', 'STUDENT', 40, true, 'Студент', 'Student', 'Студент'),
    ('fee_unit', 'CAR', 50, true, 'Автомобиль', 'Car', 'Автокөлік'),
    ('fee_unit', 'VEHICLE', 60, true, 'Транспорт', 'Vehicle', 'Көлік'),
    ('fee_unit', 'GROUP', 70, true, 'Группа', 'Group', 'Топ'),
    ('fee_unit', 'TICKET', 80, true, 'Билет', 'Ticket', 'Билет'),
    ('fee_unit', 'DAY', 90, true, 'День', 'Day', 'Күн'),
    ('fee_unit', 'HOUR', 100, true, 'Час', 'Hour', 'Сағат'),
    ('fee_unit', 'RIDE', 110, true, 'Поездка', 'Ride', 'Сапар'),
    ('fee_unit', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),
    ('road_condition', 'PAVED', 10, true, 'Асфальтированная дорога', 'Paved road', 'Асфальт жол'),
    ('road_condition', 'GRAVEL', 20, true, 'Гравийная дорога', 'Gravel road', 'Қиыршық тас жол'),
    ('road_condition', 'MIXED', 30, true, 'Смешанное покрытие', 'Mixed surface', 'Аралас жол'),
    ('road_condition', 'DIRT', 40, true, 'Грунтовая дорога', 'Dirt road', 'Топырақ жол'),
    ('road_condition', 'ROUGH', 50, true, 'Сложная дорога', 'Rough road', 'Қиын жол'),
    ('road_condition', 'OFFROAD', 60, true, 'Бездорожье', 'Off-road', 'Жолсыз жер'),
    ('road_condition', 'WALK_ONLY', 70, true, 'Только пешком', 'Walk only', 'Тек жаяу'),
    ('road_condition', 'WATER', 80, true, 'Водный маршрут', 'Water route', 'Су бағыты'),
    ('road_condition', 'UNKNOWN', 900, true, 'Уточнить перед поездкой', 'Check before travel', 'Сапар алдында нақтылау'),
    ('transport_type', 'CAR', 10, true, 'Автомобиль', 'Car', 'Автокөлік'),
    ('transport_type', 'WALK', 20, true, 'Пешком', 'Walk', 'Жаяу'),
    ('transport_type', 'PUBLIC_TRANSPORT', 30, true, 'Общественный транспорт', 'Public transport', 'Қоғамдық көлік'),
    ('transport_type', 'TAXI', 40, true, 'Такси', 'Taxi', 'Такси'),
    ('transport_type', 'BUS', 50, true, 'Автобус', 'Bus', 'Автобус'),
    ('transport_type', 'TRAIN', 60, true, 'Поезд', 'Train', 'Пойыз'),
    ('transport_type', 'METRO', 70, true, 'Метро', 'Metro', 'Метро'),
    ('transport_type', 'BOAT', 80, true, 'Лодка / катер', 'Boat', 'Қайық / катер'),
    ('transport_type', 'CABLE_CAR', 90, true, 'Канатная дорога', 'Cable car', 'Аспалы жол'),
    ('transport_type', 'BIKE', 100, true, 'Велосипед', 'Bike', 'Велосипед'),
    ('transport_type', 'SHUTTLE', 110, true, 'Шаттл', 'Shuttle', 'Шаттл'),
    ('transport_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),
    ('practical_note_type', 'GENERAL', 10, true, 'Общее', 'General', 'Жалпы'),
    ('practical_note_type', 'WEATHER', 20, true, 'Погода', 'Weather', 'Ауа райы'),
    ('practical_note_type', 'SAFETY', 30, true, 'Безопасность', 'Safety', 'Қауіпсіздік'),
    ('practical_note_type', 'ACCESS', 40, true, 'Доступ', 'Access', 'Қолжетімділік'),
    ('practical_note_type', 'BOOKING', 50, true, 'Бронирование', 'Booking', 'Брондау'),
    ('practical_note_type', 'CROWD', 60, true, 'Очереди и толпы', 'Crowds and queues', 'Кезек пен адам көптігі'),
    ('practical_note_type', 'PAYMENT', 70, true, 'Оплата', 'Payment', 'Төлем'),
    ('practical_note_type', 'CONNECTION', 80, true, 'Связь', 'Connection', 'Байланыс'),
    ('practical_note_type', 'PERMIT', 90, true, 'Разрешение', 'Permit', 'Рұқсат'),
    ('practical_note_type', 'CLOSURE', 100, true, 'Закрытие / ограничения', 'Closure or limits', 'Жабылу / шектеу'),
    ('practical_note_type', 'FAMILY', 110, true, 'С детьми', 'With children', 'Балалармен'),
    ('practical_note_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),
    ('practical_note_priority', 'INFO', 10, true, 'Информация', 'Information', 'Ақпарат'),
    ('practical_note_priority', 'IMPORTANT', 20, true, 'Важно', 'Important', 'Маңызды'),
    ('practical_note_priority', 'WARNING', 30, true, 'Предупреждение', 'Warning', 'Ескерту'),
    ('practical_note_priority', 'CRITICAL', 40, true, 'Критично', 'Critical', 'Өте маңызды'),
    ('recommended_item_type', 'WATER', 10, true, 'Вода', 'Water', 'Су'),
    ('recommended_item_type', 'SHOES', 20, true, 'Удобная обувь', 'Comfortable shoes', 'Ыңғайлы аяқ киім'),
    ('recommended_item_type', 'POWERBANK', 30, true, 'Power bank', 'Power bank', 'Қуаттағыш'),
    ('recommended_item_type', 'DOCUMENTS', 40, true, 'Документы', 'Documents', 'Құжаттар'),
    ('recommended_item_type', 'CASH', 50, true, 'Наличные', 'Cash', 'Қолма-қол ақша'),
    ('recommended_item_type', 'SPF', 60, true, 'SPF / защита от солнца', 'SPF / sun protection', 'SPF / күннен қорғаныс'),
    ('recommended_item_type', 'MAP', 70, true, 'Офлайн-карта', 'Offline map', 'Офлайн карта'),
    ('recommended_item_type', 'FOOD', 80, true, 'Еда', 'Food', 'Тамақ'),
    ('recommended_item_type', 'RAIN', 90, true, 'Дождевик', 'Rain jacket', 'Жаңбырлық'),
    ('recommended_item_type', 'REPELLENT', 100, true, 'Репеллент', 'Repellent', 'Репеллент'),
    ('recommended_item_type', 'JACKET', 110, true, 'Куртка / теплый слой', 'Jacket / warm layer', 'Күртке / жылы қабат'),
    ('recommended_item_type', 'SWIMWEAR', 120, true, 'Купальные вещи', 'Swimwear', 'Шомылу киімі'),
    ('recommended_item_type', 'HAT', 130, true, 'Головной убор', 'Hat', 'Бас киім'),
    ('recommended_item_type', 'SUNGLASSES', 140, true, 'Солнцезащитные очки', 'Sunglasses', 'Күннен қорғайтын көзілдірік'),
    ('recommended_item_type', 'MEDICINE', 150, true, 'Аптечка / лекарства', 'First aid / medicine', 'Дәрі қобдишасы / дәрі'),
    ('recommended_item_type', 'OTHER', 900, true, 'Другое', 'Other', 'Басқа'),
    ('recommended_item_importance', 'REQUIRED', 10, true, 'Обязательно', 'Required', 'Міндетті'),
    ('recommended_item_importance', 'RECOMMENDED', 20, true, 'Рекомендуется', 'Recommended', 'Ұсынылады'),
    ('recommended_item_importance', 'OPTIONAL', 30, true, 'По желанию', 'Optional', 'Қалауыңызша'),
    ('season', 'SPRING', 10, true, 'Весна', 'Spring', 'Көктем'),
    ('season', 'SUMMER', 20, true, 'Лето', 'Summer', 'Жаз'),
    ('season', 'AUTUMN', 30, true, 'Осень', 'Autumn', 'Күз'),
    ('season', 'WINTER', 40, true, 'Зима', 'Winter', 'Қыс'),
    ('season', 'ALL_SEASON', 50, true, 'Круглый год', 'All season', 'Жыл бойы'),
    ('season', 'DRY_SEASON', 60, true, 'Сухой сезон', 'Dry season', 'Құрғақ маусым'),
    ('season', 'WET_SEASON', 70, true, 'Сезон дождей', 'Wet season', 'Жаңбырлы маусым')
)
INSERT INTO place_visit_reference_translations (category, code, locale, label, updated_at)
SELECT seed.category, seed.code, localized.locale, localized.label, NOW()
FROM seed
CROSS JOIN LATERAL (
    VALUES
        ('ru', seed.ru),
        ('en', seed.en),
        ('kk', seed.kk)
) AS localized(locale, label)
ON CONFLICT (category, code, locale) DO UPDATE SET
    label = EXCLUDED.label,
    updated_at = NOW();
