package app

var supportedCurrencies = map[string]Currency{
	"AED": {Code: "AED", Name: "United Arab Emirates dirham", Symbol: "د.إ", MinorUnits: 2},
	"AMD": {Code: "AMD", Name: "Armenian dram", Symbol: "֏", MinorUnits: 2},
	"AUD": {Code: "AUD", Name: "Australian dollar", Symbol: "$", MinorUnits: 2},
	"AZN": {Code: "AZN", Name: "Azerbaijani manat", Symbol: "₼", MinorUnits: 2},
	"BRL": {Code: "BRL", Name: "Brazilian real", Symbol: "R$", MinorUnits: 2},
	"CAD": {Code: "CAD", Name: "Canadian dollar", Symbol: "$", MinorUnits: 2},
	"CHF": {Code: "CHF", Name: "Swiss franc", Symbol: "CHF", MinorUnits: 2},
	"CNY": {Code: "CNY", Name: "Chinese yuan", Symbol: "¥", MinorUnits: 2},
	"EUR": {Code: "EUR", Name: "Euro", Symbol: "€", MinorUnits: 2},
	"GBP": {Code: "GBP", Name: "British pound", Symbol: "£", MinorUnits: 2},
	"GEL": {Code: "GEL", Name: "Georgian lari", Symbol: "₾", MinorUnits: 2},
	"HKD": {Code: "HKD", Name: "Hong Kong dollar", Symbol: "$", MinorUnits: 2},
	"IDR": {Code: "IDR", Name: "Indonesian rupiah", Symbol: "Rp", MinorUnits: 0},
	"INR": {Code: "INR", Name: "Indian rupee", Symbol: "₹", MinorUnits: 2},
	"JPY": {Code: "JPY", Name: "Japanese yen", Symbol: "¥", MinorUnits: 0},
	"KGS": {Code: "KGS", Name: "Kyrgyzstani som", Symbol: "с", MinorUnits: 2},
	"KRW": {Code: "KRW", Name: "South Korean won", Symbol: "₩", MinorUnits: 0},
	"KZT": {Code: "KZT", Name: "Kazakhstani tenge", Symbol: "₸", MinorUnits: 2},
	"MYR": {Code: "MYR", Name: "Malaysian ringgit", Symbol: "RM", MinorUnits: 2},
	"NZD": {Code: "NZD", Name: "New Zealand dollar", Symbol: "$", MinorUnits: 2},
	"PLN": {Code: "PLN", Name: "Polish zloty", Symbol: "zł", MinorUnits: 2},
	"RUB": {Code: "RUB", Name: "Russian ruble", Symbol: "₽", MinorUnits: 2},
	"SGD": {Code: "SGD", Name: "Singapore dollar", Symbol: "$", MinorUnits: 2},
	"THB": {Code: "THB", Name: "Thai baht", Symbol: "฿", MinorUnits: 2},
	"TJS": {Code: "TJS", Name: "Tajikistani somoni", Symbol: "SM", MinorUnits: 2},
	"TMT": {Code: "TMT", Name: "Turkmen manat", Symbol: "m", MinorUnits: 2},
	"TRY": {Code: "TRY", Name: "Turkish lira", Symbol: "₺", MinorUnits: 2},
	"UAH": {Code: "UAH", Name: "Ukrainian hryvnia", Symbol: "₴", MinorUnits: 2},
	"USD": {Code: "USD", Name: "US dollar", Symbol: "$", MinorUnits: 2},
	"UZS": {Code: "UZS", Name: "Uzbekistani som", Symbol: "so'm", MinorUnits: 2},
	"VND": {Code: "VND", Name: "Vietnamese dong", Symbol: "₫", MinorUnits: 0},
}
