-- Priority Vietnam attractions seed.
-- Texts are original Inflap editorial summaries localized for ru, en, kk.
-- Sources audited in May 2026:
-- - Tripadvisor and Klook for tourist-demand signals.
-- - Vietnam.travel for destination-level validation.
-- - Wikimedia Commons for representative cover media.
-- - OpenStreetMap search URLs for lightweight location verification anchors.
-- Selection policy:
-- - country_code is always VN;
-- - city_id stores the practical tourist hub for filtering and guide departures;
-- - existing imported anchors from earlier Vietnam migrations are not duplicated;
-- - ratings are editorial baselines for imported curated content until user reviews take over;
-- - price is left NULL because tickets, tours and opening conditions change by season/operator.

DROP TABLE IF EXISTS seed_vietnam_priority_attractions;

CREATE TEMP TABLE seed_vietnam_priority_attractions (
    id uuid PRIMARY KEY,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL,
    rating numeric(2, 1) NOT NULL,
    tags text[] NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    location_source_url text NOT NULL,
    media_id uuid NOT NULL,
    media_url text NOT NULL,
    source_url text NOT NULL
);

INSERT INTO seed_vietnam_priority_attractions (
    id,
    city_id,
    category,
    duration_value,
    duration_unit,
    rating,
    tags,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    location_source_url,
    media_id,
    media_url,
    source_url
) VALUES
    ('50cffc30-8f22-4c9f-a521-227fdb855854'::uuid, 'ha-long', 'NATURE', 2, 'HOURS', 4.7, ARRAY['vietnam', 'ha-long', 'sung-sot-cave', 'cave', 'cruise', 'nature']::text[], 'Пещера Сунг Сот', 'Sung Sot Cave', 'Сунг Сот үңгірі', 'Большая пещера в бухте Халонг с подсвеченными залами, смотровыми переходами и классическим маршрутом круизов. Хорошо дополняет прогулку по заливу, когда нужен природный объект без сложного треккинга.', 'A large cave in Ha Long Bay with lit chambers, viewing paths and a classic cruise-stop route. It adds a strong nature highlight to bay trips without demanding a difficult trek.', 'Халонг шығанағындағы жарықтандырылған залдары, қарау жолдары және классикалық круиз аялдамасы бар үлкен үңгір. Қиын треккингсіз табиғи нысан керек кезде шығанақ маршрутын жақсы толықтырады.', 20.84560000, 107.09230000, 'https://www.openstreetmap.org/search?query=Sung%20Sot%20Cave%20Ha%20Long', '50000000-0000-4000-8000-000000000001'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sung_Sot_cave_Ha_Long_Bay.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Sung_Sot_cave_Ha_Long_Bay.jpg'),
    ('068b2c8d-f1b8-4eaa-8382-c8bc9460551f'::uuid, 'ha-long', 'BEACH', 3, 'HOURS', 4.6, ARRAY['vietnam', 'ha-long', 'titop-island', 'beach', 'viewpoint', 'cruise']::text[], 'Остров Титоп', 'Titop Island', 'Титоп аралы', 'Остров в бухте Халонг с небольшим пляжем и коротким подъемом к панорамной площадке. Подходит для круизов, фото и отдыха у воды в одном компактном маршруте.', 'An island in Ha Long Bay with a small beach and a short climb to a panoramic viewpoint. It combines cruise scenery, photos and a water break in one compact stop.', 'Халонг шығанағындағы шағын жағажайы және панорамалық алаңға қысқа көтерілуі бар арал. Круиз, фото және су жағасындағы демалысты бір ықшам аялдамаға біріктіреді.', 20.81930000, 107.08090000, 'https://www.openstreetmap.org/search?query=Titop%20Island%20Ha%20Long', '50000000-0000-4000-8000-000000000002'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/H%E1%BA%A1_Long_Bay,_Ti_T%E1%BB%91p_Island,_2020-01_CN-01.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:H%E1%BA%A1_Long_Bay,_Ti_T%E1%BB%91p_Island,_2020-01_CN-01.jpg'),
    ('3a8f1a1f-1578-4041-8f17-98578e57523d'::uuid, 'ha-long', 'NATURE', 6, 'HOURS', 4.7, ARRAY['vietnam', 'ha-long', 'bai-tu-long-bay', 'bay', 'cruise', 'quiet']::text[], 'Бухта Бай Ту Лонг', 'Bai Tu Long Bay', 'Бай Ту Лонг шығанағы', 'Более спокойная часть северного морского ландшафта рядом с Халонгом, где ценят круизы, известняковые острова и меньшую плотность маршрутов. Хороший вариант для премиального или размеренного дня на воде.', 'A calmer northern seascape near Ha Long, valued for cruises, limestone islands and lower route density. It is a strong option for a premium or slower day on the water.', 'Халонг маңындағы круиздері, әктас аралдары және маршрут тығыздығы төмен тынышырақ солтүстік теңіз ландшафты. Су үстіндегі премиум немесе баяу күнге жақсы нұсқа.', 20.94390000, 107.27670000, 'https://www.openstreetmap.org/search?query=Bai%20Tu%20Long%20Bay', '50000000-0000-4000-8000-000000000003'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/B%C3%A1i_T%E1%BB%AD_Long_Bay_-_05.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:B%C3%A1i_T%E1%BB%AD_Long_Bay_-_05.jpg'),
    ('7d3c444d-8149-41af-9c56-a638b4c0177e'::uuid, 'ha-long', 'ENTERTAINMENT', 4, 'HOURS', 4.5, ARRAY['vietnam', 'ha-long', 'sun-world', 'theme-park', 'family', 'cable-car']::text[], 'Sun World Ha Long', 'Sun World Ha Long', 'Sun World Ha Long', 'Развлекательный комплекс Халонга с парком, канатной дорогой и семейными сценариями после круиза или пляжа. Полезен как вечерний и дождливый день, когда туристам нужен понятный leisure-формат.', 'A Ha Long entertainment complex with a park, cable car and family-friendly options after a cruise or beach time. It is useful for evenings and rainy days when travelers want an easy leisure format.', 'Халонгтағы парк, аспалы жол және круизден не жағажайдан кейінгі отбасылық сценарийлері бар ойын-сауық кешені. Туристерге жеңіл leisure форматы керек кешке немесе жаңбырлы күнге пайдалы.', 20.95670000, 107.03930000, 'https://www.openstreetmap.org/search?query=Sun%20World%20Ha%20Long', '50000000-0000-4000-8000-000000000004'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sun_World_Ha_Long_Park_%2849357908961%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Sun_World_Ha_Long_Park_(49357908961).jpg'),
    ('a0feacec-c1bb-42b3-8bc4-bc17f65b3a86'::uuid, 'ha-long', 'BEACH', 2, 'HOURS', 4.4, ARRAY['vietnam', 'ha-long', 'bai-chay-beach', 'beach', 'city', 'family']::text[], 'Пляж Бай Чай', 'Bai Chay Beach', 'Бай Чай жағажайы', 'Городской пляж Халонга рядом с отелями, ресторанами и вечерними прогулками. Это простой вариант для отдыха у моря без отдельного круиза или дальнего трансфера.', 'A city beach in Ha Long near hotels, restaurants and evening walks. It is an easy seaside option without a separate cruise or long transfer.', 'Қонақүйлерге, мейрамханаларға және кешкі серуенге жақын Халонг қалалық жағажайы. Жеке круизсіз немесе ұзақ трансферсіз теңіз жағасында демалудың жеңіл нұсқасы.', 20.95170000, 107.02490000, 'https://www.openstreetmap.org/search?query=Bai%20Chay%20Beach%20Ha%20Long', '50000000-0000-4000-8000-000000000005'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bai_Chay_beach,_Ha_Long,_Vietnam,_20240129_0915_3958.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Bai_Chay_beach,_Ha_Long,_Vietnam,_20240129_0915_3958.jpg'),

    ('1a02110b-516c-4b0a-b37f-9b211faf18db'::uuid, 'ninh-binh', 'NATURE', 4, 'HOURS', 4.8, ARRAY['vietnam', 'ninh-binh', 'tam-coc', 'bich-dong', 'boat', 'karst']::text[], 'Тамкок - Бикдонг', 'Tam Coc - Bich Dong', 'Тамкок - Бикдонг', 'Лодочный маршрут среди карстовых скал, рисовых полей и пещер рядом с пагодой Бикдонг. Это один из самых понятных способов увидеть Ниньбинь как природный и культурный ландшафт.', 'A boat route among karst cliffs, rice fields and caves near Bich Dong Pagoda. It is one of the clearest ways to experience Ninh Binh as both a natural and cultural landscape.', 'Бикдонг пагодасы маңындағы карст жартастары, күріш алқаптары және үңгірлер арасындағы қайық маршруты. Ниньбиньді табиғи әрі мәдени ландшафт ретінде көрудің ең түсінікті жолдарының бірі.', 20.21520000, 105.93680000, 'https://www.openstreetmap.org/search?query=Tam%20Coc%20Bich%20Dong%20Ninh%20Binh', '50000000-0000-4000-8000-000000000006'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tam_Coc_Ninh_Binh.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Tam_Coc_Ninh_Binh.jpg'),
    ('0875c8ea-cd32-45af-99ec-1b11083ce7ca'::uuid, 'ninh-binh', 'NATURE', 2, 'HOURS', 4.8, ARRAY['vietnam', 'ninh-binh', 'mua-cave', 'viewpoint', 'stairs', 'karst']::text[], 'Смотровая площадка Муа', 'Mua Cave Viewpoint', 'Муа үңгірі көрініс алаңы', 'Подъем к одной из самых известных панорам Ниньбиня с видом на рисовые поля, реку и карстовые горы. Лучше закладывать время на лестницу, жару и фото на вершине.', 'A climb to one of Ninh Binh most famous panoramas, overlooking rice fields, river bends and karst mountains. Plan time for the stairs, heat and photos at the top.', 'Күріш алқаптары, өзен иірімдері және карст таулары көрінетін Ниньбиньдегі ең танымал панорамалардың біріне көтерілу. Баспалдаққа, ыстыққа және төбедегі фотоға уақыт қалдырған дұрыс.', 20.22960000, 105.93550000, 'https://www.openstreetmap.org/search?query=Mua%20Cave%20Viewpoint%20Ninh%20Binh', '50000000-0000-4000-8000-000000000007'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/View_from_Hang_Mua.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:View_from_Hang_Mua.jpg'),
    ('8e566a6c-dba3-42b4-b279-87f7451992e6'::uuid, 'ninh-binh', 'ARCHITECTURE', 2, 'HOURS', 4.6, ARRAY['vietnam', 'ninh-binh', 'hoa-lu', 'ancient-capital', 'history', 'temples']::text[], 'Древняя столица Хоалы', 'Hoa Lu Ancient Capital', 'Хоалы ежелгі астанасы', 'Исторический комплекс первых вьетнамских династий с храмами, воротами и спокойным сельским окружением. Хорошо соединяется с Транганом или Тамкоком в однодневной программе.', 'A historic complex of early Vietnamese dynasties with temples, gates and a calm rural setting. It pairs naturally with Trang An or Tam Coc in a day itinerary.', 'Ерте Вьетнам әулеттерінің храмдары, қақпалары және тыныш ауылдық ортасы бар тарихи кешені. Бір күндік бағдарламада Транган немесе Тамкокпен жақсы үйлеседі.', 20.28230000, 105.90630000, 'https://www.openstreetmap.org/search?query=Hoa%20Lu%20Ancient%20Capital', '50000000-0000-4000-8000-000000000008'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Codohoalu2010k1.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Codohoalu2010k1.jpg'),
    ('eeb92596-d1fc-4a2a-b68d-e9056a9f5c9a'::uuid, 'ninh-binh', 'TEMPLE', 3, 'HOURS', 4.6, ARRAY['vietnam', 'ninh-binh', 'bai-dinh-pagoda', 'temple', 'buddhist', 'large-complex']::text[], 'Пагода Байдинь', 'Bai Dinh Pagoda', 'Байдинь пагодасы', 'Крупный буддийский комплекс Ниньбиня с длинными галереями, статуями и масштабной храмовой архитектурой. Подходит для маршрутов о духовной культуре и больших церемониальных пространствах.', 'A large Buddhist complex in Ninh Binh with long galleries, statues and monumental temple architecture. It suits routes about spiritual culture and ceremonial spaces.', 'Ниньбиньдегі ұзын галереялары, мүсіндері және ауқымды храм сәулеті бар үлкен буддистік кешен. Рухани мәдениет және салтанатты кеңістіктер туралы маршруттарға сай.', 20.27650000, 105.86460000, 'https://www.openstreetmap.org/search?query=Bai%20Dinh%20Pagoda%20Ninh%20Binh', '50000000-0000-4000-8000-000000000009'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chua_Bai_Dinh_X8.JPG?width=1400', 'https://commons.wikimedia.org/wiki/File:Chua_Bai_Dinh_X8.JPG'),
    ('2870c7d1-306c-43f4-a7ab-ab8b0d977be3'::uuid, 'ninh-binh', 'NATURE', 5, 'HOURS', 4.6, ARRAY['vietnam', 'ninh-binh', 'cuc-phuong-national-park', 'forest', 'trekking', 'wildlife']::text[], 'Национальный парк Кукфыонг', 'Cuc Phuong National Park', 'Кукфыонг ұлттық паркі', 'Старейший национальный парк Вьетнама с лесными тропами, центрами спасения животных и природными маршрутами. Хорош для туристов, которые хотят уйти от только лодочных программ Ниньбиня.', 'Vietnam oldest national park, with forest trails, wildlife rescue centers and nature routes. It is useful for travelers who want more than Ninh Binh boat itineraries.', 'Вьетнамның ең көне ұлттық паркі: орман соқпақтары, жануарларды құтқару орталықтары және табиғи маршруттар бар. Ниньбиньдегі тек қайық бағдарламасынан бөлек нәрсе іздейтіндерге жақсы.', 20.31670000, 105.60830000, 'https://www.openstreetmap.org/search?query=Cuc%20Phuong%20National%20Park', '50000000-0000-4000-8000-000000000010'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cuc.Phuong.National.Park.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Cuc.Phuong.National.Park.jpg'),

    ('2ac7d4d5-fdcc-4f8a-b266-e389b0070ac3'::uuid, 'sa-pa', 'NATURE', 4, 'HOURS', 4.8, ARRAY['vietnam', 'sa-pa', 'muong-hoa-valley', 'rice-terraces', 'trekking', 'villages']::text[], 'Долина Мыонгхоа', 'Muong Hoa Valley', 'Мыонгхоа аңғары', 'Долина рядом с Сапой с террасными полями, деревнями и пешими маршрутами. Это основа для мягкого треккинга и знакомства с горным севером Вьетнама.', 'A valley near Sa Pa with rice terraces, villages and walking routes. It is a core area for gentle trekking and discovering the mountainous north of Vietnam.', 'Сапа маңындағы террасалы алқаптары, ауылдары және жаяу маршруттары бар аңғар. Вьетнамның таулы солтүстігімен танысуға және жеңіл треккингке негізгі аймақ.', 22.31050000, 103.87030000, 'https://www.openstreetmap.org/search?query=Muong%20Hoa%20Valley%20Sa%20Pa', '50000000-0000-4000-8000-000000000011'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C6%B0%E1%BB%9Dng_Hoa_Valley_06.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:M%C6%B0%E1%BB%9Dng_Hoa_Valley_06.jpg'),
    ('de6a1063-c64a-4a03-8509-12e619fdf91f'::uuid, 'sa-pa', 'OTHER', 2, 'HOURS', 4.3, ARRAY['vietnam', 'sa-pa', 'cat-cat-village', 'village', 'culture', 'walking']::text[], 'Деревня Кат Кат', 'Cat Cat Village', 'Кат Кат ауылы', 'Популярная туристическая деревня рядом с Сапой с прогулочным маршрутом, водопадами и ремесленными сценами. Она не самая уединенная, зато понятна для первого короткого знакомства с регионом.', 'A popular tourist village near Sa Pa with a walking route, waterfalls and craft scenes. It is not the quietest option, but it works for a first short introduction to the region.', 'Сапа маңындағы жаяу маршруты, сарқырамалары және қолөнер көріністері бар танымал туристік ауыл. Ең тыныш орын емес, бірақ аймақпен алғашқы қысқа танысуға түсінікті.', 22.32620000, 103.82290000, 'https://www.openstreetmap.org/search?query=Cat%20Cat%20Village%20Sa%20Pa', '50000000-0000-4000-8000-000000000012'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mountains_over_Cat_Cat_village_near_Sa_Pa,_Vietnam,_20240126_1123_3506.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Mountains_over_Cat_Cat_village_near_Sa_Pa,_Vietnam,_20240126_1123_3506.jpg'),
    ('db5ea0d7-7665-4e9a-a2bf-598e49f92f26'::uuid, 'sa-pa', 'NATURE', 1, 'HOURS', 4.4, ARRAY['vietnam', 'sa-pa', 'silver-waterfall', 'waterfall', 'nature', 'short-stop']::text[], 'Серебряный водопад', 'Silver Waterfall', 'Күміс сарқырама', 'Живописный водопад на дороге из Сапы к горным перевалам. Хорош как короткая природная остановка в маршруте к водопаду Любви или перевалу О Куй Хо.', 'A scenic waterfall on the road from Sa Pa toward the mountain passes. It works as a short nature stop on routes to Love Waterfall or O Quy Ho Pass.', 'Сападан тау асуларына баратын жолдағы көрікті сарқырама. Махаббат сарқырамасына немесе О Куй Хо асуына баратын маршруттағы қысқа табиғи аялдамаға жақсы.', 22.36160000, 103.77940000, 'https://www.openstreetmap.org/search?query=Silver%20Waterfall%20Sa%20Pa', '50000000-0000-4000-8000-000000000013'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Thacbac3.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Thacbac3.jpg'),
    ('051a79f2-dc58-4331-b0e7-eaf2dfe05f20'::uuid, 'sa-pa', 'NATURE', 2, 'HOURS', 4.7, ARRAY['vietnam', 'sa-pa', 'o-quy-ho-pass', 'mountain-pass', 'viewpoint', 'road-trip']::text[], 'Перевал О Куй Хо', 'O Quy Ho Pass', 'О Куй Хо асуы', 'Высокогорный перевал рядом с Сапой с сильными видами на хребты и долины. Подходит для road-trip маршрутов, фото и остановок на свежем воздухе.', 'A high mountain pass near Sa Pa with strong views over ridges and valleys. It suits road-trip routes, photos and fresh-air stops.', 'Сапа маңындағы жоталар мен аңғарларға күшті көрініс ашатын биік тау асуы. Road-trip, фото және таза ауадағы аялдамаларға сай.', 22.35440000, 103.76720000, 'https://www.openstreetmap.org/search?query=O%20Quy%20Ho%20Pass', '50000000-0000-4000-8000-000000000014'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/O_Quy_Ho_pass.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:O_Quy_Ho_pass.jpg'),
    ('b05b276c-a167-40c0-8889-aab43a23daaf'::uuid, 'sa-pa', 'ARCHITECTURE', 1, 'HOURS', 4.3, ARRAY['vietnam', 'sa-pa', 'stone-church', 'architecture', 'center', 'landmark']::text[], 'Каменная церковь Сапы', 'Sapa Stone Church', 'Сапа тас шіркеуі', 'Центральный архитектурный ориентир Сапы рядом с площадью, кафе и вечерними прогулками. Удобная точка встречи и короткая остановка перед горными маршрутами.', 'A central architectural landmark of Sa Pa near the square, cafes and evening walks. It is an easy meeting point and a short stop before mountain routes.', 'Сапаның алаң, кафелер және кешкі серуендер жанындағы орталық сәулеттік белгісі. Тау маршруттары алдында ыңғайлы кездесу нүктесі және қысқа аялдама.', 22.33650000, 103.84380000, 'https://www.openstreetmap.org/search?query=Sapa%20Stone%20Church', '50000000-0000-4000-8000-000000000015'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sapa_Church.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Sapa_Church.jpg'),

    ('78369fbb-7ddb-43a5-a651-541de4aba1f0'::uuid, 'hue', 'TEMPLE', 1, 'HOURS', 4.7, ARRAY['vietnam', 'hue', 'thien-mu-pagoda', 'pagoda', 'perfume-river', 'culture']::text[], 'Пагода Тхьенму', 'Thien Mu Pagoda', 'Тхьенму пагодасы', 'Историческая пагода на берегу Ароматной реки, один из главных символов Хюэ. Ее удобно включать в маршруты по реке, цитадели и императорскому наследию.', 'A historic pagoda on the Perfume River and one of Hue main symbols. It fits naturally into routes around the river, citadel and imperial heritage.', 'Ароматты өзен жағасындағы тарихи пагода және Хюэнің басты нышандарының бірі. Өзен, цитадель және императорлық мұра маршруттарына табиғи түрде қосылады.', 16.45360000, 107.54470000, 'https://www.openstreetmap.org/search?query=Thien%20Mu%20Pagoda%20Hue', '50000000-0000-4000-8000-000000000016'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Thien%20Mu%20Pagoda%2C%20Hue%20%2815250812170%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Thien_Mu_Pagoda,_Hue_(15250812170).jpg'),
    ('bd8693af-fcdd-4906-815d-081fe511fcc3'::uuid, 'hue', 'ARCHITECTURE', 2, 'HOURS', 4.7, ARRAY['vietnam', 'hue', 'minh-mang-tomb', 'royal-tomb', 'architecture', 'history']::text[], 'Гробница Минь Манга', 'Tomb of Minh Mang', 'Минь Манг кесенесі', 'Императорская гробница с озерами, павильонами и строгой осевой композицией. Хорошо раскрывает Хюэ как город королевской архитектуры и ландшафтных ансамблей.', 'An imperial tomb with lakes, pavilions and a formal axial layout. It shows Hue as a city of royal architecture and landscaped ensembles.', 'Көлдері, павильондары және қатаң осьтік композициясы бар императорлық кесене. Хюэні корольдік сәулет пен ландшафт ансамбльдерінің қаласы ретінде ашады.', 16.38350000, 107.56980000, 'https://www.openstreetmap.org/search?query=Tomb%20of%20Minh%20Mang%20Hue', '50000000-0000-4000-8000-000000000017'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hue%20Vietnam%20Tomb-of-Emperor-Minh-Mang-01.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Hue_Vietnam_Tomb-of-Emperor-Minh-Mang-01.jpg'),
    ('4539231b-4db3-4081-814d-d134ce2d47fd'::uuid, 'hue', 'ARCHITECTURE', 2, 'HOURS', 4.6, ARRAY['vietnam', 'hue', 'tu-duc-tomb', 'royal-tomb', 'history', 'gardens']::text[], 'Гробница Ты Дыка', 'Tomb of Tu Duc', 'Ты Дык кесенесі', 'Королевский комплекс с прудами, павильонами и более камерной атмосферой, чем у многих других гробниц Хюэ. Подходит для неспешного исторического маршрута.', 'A royal complex with ponds, pavilions and a more intimate mood than many other Hue tombs. It suits a slower historical route.', 'Тоғандары, павильондары және Хюэнің көптеген кесенелеріне қарағанда ықшам атмосферасы бар корольдік кешен. Баяу тарихи маршрутқа сай.', 16.43220000, 107.56580000, 'https://www.openstreetmap.org/search?query=Tomb%20of%20Tu%20Duc%20Hue', '50000000-0000-4000-8000-000000000018'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomb%20of%20Tu%20Duc.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Tomb_of_Tu_Duc.jpg'),
    ('04a331f6-90bd-40db-b94f-83c684eb5e59'::uuid, 'hue', 'ARCHITECTURE', 2, 'HOURS', 4.7, ARRAY['vietnam', 'hue', 'khai-dinh-tomb', 'royal-tomb', 'mosaic', 'architecture']::text[], 'Гробница Кхай Диня', 'Tomb of Khai Dinh', 'Кхай Динь кесенесі', 'Контрастная императорская гробница с лестницами, мозаиками и смешением вьетнамской и европейской архитектуры. Один из самых фотогеничных объектов вокруг Хюэ.', 'A striking imperial tomb with stairways, mosaics and a blend of Vietnamese and European architecture. It is one of the most photogenic sites around Hue.', 'Баспалдақтары, мозаикалары және вьетнамдық пен еуропалық сәулет араласқан ерекше императорлық кесене. Хюэ маңындағы ең фотогенді орындардың бірі.', 16.39780000, 107.59040000, 'https://www.openstreetmap.org/search?query=Tomb%20of%20Khai%20Dinh%20Hue', '50000000-0000-4000-8000-000000000019'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20tomb%20of%20Emperor%20Khai%20Dinh%20%2812060793854%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:The_tomb_of_Emperor_Khai_Dinh_(12060793854).jpg'),
    ('c049918a-7ea1-4012-9717-4605fd26ae64'::uuid, 'hue', 'NATURE', 2, 'HOURS', 4.5, ARRAY['vietnam', 'hue', 'perfume-river', 'river', 'boat', 'sunset']::text[], 'Ароматная река', 'Perfume River', 'Ароматты өзен', 'Главная водная ось Хюэ для прогулок, лодочных маршрутов и видов на городские берега. Хорошо соединяет пагоды, цитадель и вечерние сценарии.', 'The main water axis of Hue for walks, boat routes and views of the city banks. It connects pagodas, the citadel and evening itineraries well.', 'Хюэнің серуен, қайық маршруттары және қала жағалауын көруге арналған басты су осі. Пагодаларды, цитадельді және кешкі сценарийлерді жақсы байланыстырады.', 16.46920000, 107.57850000, 'https://www.openstreetmap.org/search?query=Perfume%20River%20Hue', '50000000-0000-4000-8000-000000000020'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Perfume%20River%2C%20Hue%2C%20Vietnam%20%286927400994%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Perfume_River,_Hue,_Vietnam_(6927400994).jpg'),
    ('8302674f-7fbc-4f13-8ce1-9c46a08e311e'::uuid, 'hue', 'MARKET', 2, 'HOURS', 4.4, ARRAY['vietnam', 'hue', 'dong-ba-market', 'market', 'food', 'shopping']::text[], 'Рынок Донг Ба', 'Dong Ba Market', 'Донг Ба базары', 'Главный рынок Хюэ с локальной едой, продуктами, тканями и сувенирами. Удобен для короткого гастрономического маршрута и практичных покупок рядом с центром.', 'Hue main market with local food, produce, fabrics and souvenirs. It is useful for a short food route and practical shopping near the center.', 'Хюэнің жергілікті тағам, азық-түлік, мата және кәдесыйлары бар басты базары. Орталыққа жақын қысқа гастро-маршрут пен практикалық саудаға ыңғайлы.', 16.47290000, 107.58550000, 'https://www.openstreetmap.org/search?query=Dong%20Ba%20Market%20Hue', '50000000-0000-4000-8000-000000000021'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dong%20Ba%20Market%20%28Hue%29%20-%20Ch%E1%BB%A3%20%C4%90%C3%B4ng%20Ba%20Hu%E1%BA%BF%20%28July%202024%29%20-%20img%2001.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Dong_Ba_Market_(Hue)_-_Ch%E1%BB%A3_%C4%90%C3%B4ng_Ba_Hu%E1%BA%BF_(July_2024)_-_img_01.jpg'),

    ('351a6e3e-8cd8-46d0-be36-c8eb00addc39'::uuid, 'ho-chi-minh-city', 'MUSEUM', 4, 'HOURS', 4.7, ARRAY['vietnam', 'ho-chi-minh-city', 'cu-chi-tunnels', 'history', 'day-trip', 'museum']::text[], 'Туннели Кути', 'Cu Chi Tunnels', 'Кути туннельдері', 'Исторический подземный комплекс к северо-западу от Хошимина, который часто выбирают как полудневную экскурсию. Объект помогает понять военную историю и условия жизни в туннельной системе.', 'A historic underground complex northwest of Ho Chi Minh City, often visited as a half-day tour. It helps explain wartime history and life inside the tunnel system.', 'Хошиминнің солтүстік-батысындағы жарты күндік экскурсия ретінде жиі таңдалатын тарихи жер асты кешені. Соғыс тарихын және туннель жүйесіндегі өмірді түсінуге көмектеседі.', 11.14310000, 106.46450000, 'https://www.openstreetmap.org/search?query=Cu%20Chi%20Tunnels', '50000000-0000-4000-8000-000000000022'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cu%20Chi%20Tunnel.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Cu_Chi_Tunnel.jpg'),
    ('ce3f9b65-d150-4e4a-8b4f-73e9c33656bc'::uuid, 'ho-chi-minh-city', 'ARCHITECTURE', 1, 'HOURS', 4.6, ARRAY['vietnam', 'ho-chi-minh-city', 'central-post-office', 'architecture', 'french-colonial', 'center']::text[], 'Центральный почтамт Сайгона', 'Saigon Central Post Office', 'Сайгон орталық поштасы', 'Историческое здание почтамта в центре Хошимина с узнаваемой французской архитектурой. Удобно совмещается с собором Нотр-Дам и прогулкой по центральному району.', 'A historic post office in central Ho Chi Minh City with recognizable French architecture. It pairs easily with Notre-Dame Cathedral and a central district walk.', 'Хошимин орталығындағы француз сәулетімен танылатын тарихи пошта ғимараты. Нотр-Дам соборымен және орталық аудан серуенімен оңай үйлеседі.', 10.77990000, 106.69990000, 'https://www.openstreetmap.org/search?query=Saigon%20Central%20Post%20Office', '50000000-0000-4000-8000-000000000023'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Central%20Post%20Office.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:The_Central_Post_Office.jpg'),
    ('5b391e30-13eb-4b87-ba2e-0357f3001b11'::uuid, 'ho-chi-minh-city', 'ARCHITECTURE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'ho-chi-minh-city', 'notre-dame-cathedral', 'architecture', 'landmark', 'center']::text[], 'Собор Нотр-Дам в Сайгоне', 'Notre-Dame Cathedral Basilica of Saigon', 'Сайгон Нотр-Дам соборы', 'Иконический собор в историческом центре Хошимина и важная точка городских маршрутов. Даже при ограничениях доступа он остается сильным ориентиром для прогулки и фото.', 'An iconic cathedral in historic central Ho Chi Minh City and an important city-route landmark. Even with access limits, it remains a strong walking and photo anchor.', 'Хошиминнің тарихи орталығындағы әйгілі собор және қалалық маршруттардың маңызды белгісі. Кіру шектеулі болса да, серуен мен фото үшін мықты бағдар болып қалады.', 10.77980000, 106.69900000, 'https://www.openstreetmap.org/search?query=Notre-Dame%20Cathedral%20Basilica%20of%20Saigon', '50000000-0000-4000-8000-000000000024'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Saigon%20Notre-Dame%20Basilica.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Saigon_Notre-Dame_Basilica.jpg'),
    ('41606913-cc18-49c6-bafa-7b3d86105a06'::uuid, 'ho-chi-minh-city', 'ENTERTAINMENT', 1, 'HOURS', 4.5, ARRAY['vietnam', 'ho-chi-minh-city', 'bitexco', 'skydeck', 'viewpoint', 'indoor']::text[], 'Смотровая площадка Bitexco', 'Bitexco Financial Tower Skydeck', 'Bitexco Financial Tower Skydeck', 'Высотная смотровая площадка в центре Хошимина с видом на реку, деловые кварталы и плотный городской ритм. Хороша для первого вечера или indoor-паузы в жару.', 'A high-rise observation deck in central Ho Chi Minh City with views of the river, business districts and dense city rhythm. It works well for a first evening or an indoor break from the heat.', 'Хошимин орталығындағы өзенге, іскер аудандарға және қаланың тығыз ырғағына көрініс ашатын биік шолу алаңы. Алғашқы кешке немесе ыстықтан indoor үзіліске жақсы.', 10.77160000, 106.70430000, 'https://www.openstreetmap.org/search?query=Bitexco%20Financial%20Tower%20Skydeck', '50000000-0000-4000-8000-000000000025'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Saigon%20Skydeck%20%2836327761234%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Saigon_Skydeck_(36327761234).jpg'),
    ('60850d97-4f5e-4b98-96ad-7e41e09e75a7'::uuid, 'ho-chi-minh-city', 'TEMPLE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'ho-chi-minh-city', 'jade-emperor-pagoda', 'temple', 'culture', 'incense']::text[], 'Пагода Нефритового императора', 'Jade Emperor Pagoda', 'Нефрит император пагодасы', 'Атмосферный храм Хошимина с резьбой, дымом благовоний и плотным культурным слоем. Подходит для маршрутов, где хочется выйти за пределы главных колониальных зданий.', 'An atmospheric Ho Chi Minh City temple with carvings, incense smoke and dense cultural detail. It is useful when routes need more than the main colonial landmarks.', 'Ою-өрнектері, хош иіс түтіні және қалың мәдени деталі бар Хошиминдегі атмосфералы храм. Маршрут негізгі отарлық ғимараттардан ары шығуы керек кезде пайдалы.', 10.79170000, 106.69830000, 'https://www.openstreetmap.org/search?query=Jade%20Emperor%20Pagoda%20Saigon', '50000000-0000-4000-8000-000000000026'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jade%20Emperor%20Pagoda%20Saigon.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Jade_Emperor_Pagoda_Saigon.jpg'),
    ('d7a8e30e-2634-434d-8d32-44000738570b'::uuid, 'ho-chi-minh-city', 'ENTERTAINMENT', 2, 'HOURS', 4.2, ARRAY['vietnam', 'ho-chi-minh-city', 'bui-vien', 'walking-street', 'nightlife', 'backpacker']::text[], 'Пешеходная улица Буй Вьен', 'Bui Vien Walking Street', 'Буй Вьен жаяу көшесі', 'Шумная вечерняя улица с барами, музыкой, кафе и туристическим потоком. Ее стоит показывать как nightlife-точку, а не спокойную семейную прогулку.', 'A busy evening street with bars, music, cafes and a strong tourist flow. It should be presented as a nightlife spot rather than a calm family walk.', 'Барлары, музыкасы, кафелері және туристік ағыны көп кешкі көше. Оны тыныш отбасылық серуен емес, nightlife-нүкте ретінде көрсеткен дұрыс.', 10.76780000, 106.69310000, 'https://www.openstreetmap.org/search?query=Bui%20Vien%20Walking%20Street', '50000000-0000-4000-8000-000000000027'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bui%20Vien%20Walking%20Street%201.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Bui_Vien_Walking_Street_1.jpg'),

    ('7ceed1a6-7c1c-464c-be77-f7acf2c93fbf'::uuid, 'da-lat', 'NATURE', 3, 'HOURS', 4.7, ARRAY['vietnam', 'da-lat', 'datanla-waterfall', 'waterfall', 'alpine-coaster', 'nature']::text[], 'Водопад Датанла', 'Datanla Waterfall', 'Датанла сарқырамасы', 'Популярный природный парк Далата с водопадами, лесной атмосферой и альпийскими санями. Это удобный объект для активного, но не слишком сложного отдыха рядом с городом.', 'A popular Da Lat nature park with waterfalls, forest atmosphere and an alpine coaster. It is convenient for active but not too difficult leisure near the city.', 'Далаттағы сарқырамалары, орман атмосферасы және альпілік шанасы бар танымал табиғи парк. Қалаға жақын белсенді, бірақ тым қиын емес демалысқа ыңғайлы.', 11.90390000, 108.44990000, 'https://www.openstreetmap.org/search?query=Datanla%20Waterfall%20Da%20Lat', '50000000-0000-4000-8000-000000000028'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Datanla_Waterfall_1.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Datanla_Waterfall_1.jpg'),
    ('5465a4c9-157f-4f3e-90b9-91d83effeafb'::uuid, 'da-lat', 'TEMPLE', 1, 'HOURS', 4.7, ARRAY['vietnam', 'da-lat', 'linh-phuoc-pagoda', 'pagoda', 'mosaic', 'culture']::text[], 'Пагода Линь Фуок', 'Linh Phuoc Pagoda', 'Линь Фуок пагодасы', 'Яркая пагода рядом с Далатом, известная мозаиками, башней и декоративной архитектурой. Хорошо подходит для культурной остановки и маршрута на поезде к Чаймату.', 'A vivid pagoda near Da Lat known for mosaics, a tower and decorative architecture. It works well as a cultural stop and part of the train route to Trai Mat.', 'Далат маңындағы мозаикалары, мұнарасы және сәндік сәулетімен белгілі жарқын пагода. Мәдени аялдама және Чайматқа пойыз маршрутының бөлігі ретінде жақсы.', 11.94440000, 108.50520000, 'https://www.openstreetmap.org/search?query=Linh%20Phuoc%20Pagoda%20Da%20Lat', '50000000-0000-4000-8000-000000000029'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Linh_Phuoc_Pagoda_07.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Linh_Phuoc_Pagoda_07.jpg'),
    ('47077c61-67f3-4795-ad9a-8ce9241229b2'::uuid, 'da-lat', 'NATURE', 4, 'HOURS', 4.6, ARRAY['vietnam', 'da-lat', 'pongour-waterfall', 'waterfall', 'day-trip', 'nature']::text[], 'Водопад Понгур', 'Pongour Waterfall', 'Понгур сарқырамасы', 'Широкий каскадный водопад к югу от Далата, который выбирают для природных дневных поездок. Лучше планировать с учетом сезона воды и времени на дорогу.', 'A wide cascade waterfall south of Da Lat, chosen for nature day trips. It is best planned with water season and transfer time in mind.', 'Далаттың оңтүстігіндегі табиғи күндік сапарларға таңдалатын кең каскадты сарқырама. Су маусымы мен жол уақытын ескеріп жоспарлаған дұрыс.', 11.69030000, 108.28280000, 'https://www.openstreetmap.org/search?query=Pongour%20Waterfall%20Da%20Lat', '50000000-0000-4000-8000-000000000030'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pongour_Waterfall,_Dalat.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Pongour_Waterfall,_Dalat.jpg'),
    ('e60e5b78-cc7a-492c-8bd2-194ee93424ac'::uuid, 'da-lat', 'NATURE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'da-lat', 'xuan-huong-lake', 'lake', 'walk', 'city']::text[], 'Озеро Суан Хыонг', 'Xuan Huong Lake', 'Суан Хыонг көлі', 'Центральное озеро Далата для прогулок, кафе, вечерних видов и мягкого знакомства с городом. Удобная бесплатная точка рядом с отелями и рынком.', 'The central Da Lat lake for walks, cafes, evening views and an easy introduction to the city. It is a convenient free stop near hotels and the market.', 'Далаттың серуен, кафе, кешкі көрініс және қаламен жеңіл танысуға арналған орталық көлі. Қонақүйлер мен базарға жақын ыңғайлы тегін аялдама.', 11.94000000, 108.44190000, 'https://www.openstreetmap.org/search?query=Xuan%20Huong%20Lake%20Da%20Lat', '50000000-0000-4000-8000-000000000031'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Xuan_Huong_Lake_%2846420763535%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Xuan_Huong_Lake_(46420763535).jpg'),
    ('d523f07d-8580-430c-aca2-5cc8bed25418'::uuid, 'da-lat', 'ARCHITECTURE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'da-lat', 'railway-station', 'architecture', 'train', 'history']::text[], 'Железнодорожный вокзал Далата', 'Da Lat Railway Station', 'Далат теміржол вокзалы', 'Исторический вокзал с узнаваемой архитектурой и туристическим поездом к району Чаймат. Хорошая короткая остановка для фото, истории и спокойного городского маршрута.', 'A historic railway station with recognizable architecture and a tourist train to the Trai Mat area. It is a good short stop for photos, history and a calm city route.', 'Танымал сәулеті және Чаймат ауданына туристік пойызы бар тарихи вокзал. Фото, тарих және тыныш қалалық маршрут үшін жақсы қысқа аялдама.', 11.94190000, 108.46350000, 'https://www.openstreetmap.org/search?query=Da%20Lat%20Railway%20Station', '50000000-0000-4000-8000-000000000032'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Da_Lat_train_station_36.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Da_Lat_train_station_36.jpg'),
    ('9becd171-75b3-4488-b2bb-a8256d3ef7dc'::uuid, 'da-lat', 'MARKET', 2, 'HOURS', 4.5, ARRAY['vietnam', 'da-lat', 'night-market', 'market', 'street-food', 'evening']::text[], 'Ночной рынок Далата', 'Da Lat Night Market', 'Далат түнгі базары', 'Вечерний рынок в центре Далата с уличной едой, клубникой, одеждой и сувенирами. Это понятная точка для прогулки после дневных водопадов и парков.', 'An evening market in central Da Lat with street food, strawberries, clothes and souvenirs. It is an easy walk after daytime waterfalls and parks.', 'Далат орталығындағы көше тағамдары, құлпынай, киім және кәдесыйлары бар кешкі базар. Күндізгі сарқырамалар мен парктерден кейінгі жеңіл серуенге жақсы.', 11.94430000, 108.43720000, 'https://www.openstreetmap.org/search?query=Da%20Lat%20Night%20Market', '50000000-0000-4000-8000-000000000033'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Da_Lat_night.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Da_Lat_night.jpg'),

    ('92b78b65-7a0e-49a8-9762-473266cd3273'::uuid, 'can-tho', 'OTHER', 1, 'HOURS', 4.5, ARRAY['vietnam', 'can-tho', 'ninh-kieu-wharf', 'mekong', 'river', 'evening']::text[], 'Причал Нинькьеу', 'Ninh Kieu Wharf', 'Нинькьеу айлағы', 'Главная набережная Кантхо на реке Меконга с прогулками, лодками, кафе и вечерними видами. Хорошая стартовая точка для городского и речного маршрута.', 'The main Can Tho riverfront on the Mekong, with walks, boats, cafes and evening views. It is a good starting point for city and river itineraries.', 'Меконг бойындағы серуендер, қайықтар, кафелер және кешкі көріністері бар Кантхоның басты набережнаясы. Қалалық және өзен маршрутына жақсы бастау нүктесі.', 10.03400000, 105.78830000, 'https://www.openstreetmap.org/search?query=Ninh%20Kieu%20Wharf%20Can%20Tho', '50000000-0000-4000-8000-000000000034'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ninh_Kieu_Quay.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Ninh_Kieu_Quay.jpg'),
    ('8079371e-0054-4de3-ba54-b6adcd31ac32'::uuid, 'can-tho', 'OTHER', 3, 'HOURS', 4.5, ARRAY['vietnam', 'can-tho', 'son-islet', 'community-tourism', 'mekong', 'local-life']::text[], 'Остров Сон', 'Son Islet', 'Сон аралы', 'Локальный community-tourism маршрут в Кантхо с рыбными хозяйствами, садами и домашними форматами знакомства с дельтой. Подходит для мягкой альтернативы только плавучему рынку.', 'A local community-tourism route in Can Tho with fish farms, gardens and home-style Delta experiences. It is a gentle alternative to seeing only the floating market.', 'Кантходағы балық шаруашылықтары, бақтары және дельтамен үй форматында танысуы бар жергілікті community-tourism маршруты. Тек қалқымалы базармен шектелмеудің жұмсақ баламасы.', 10.06400000, 105.80100000, 'https://www.openstreetmap.org/search?query=Son%20Islet%20Can%20Tho', '50000000-0000-4000-8000-000000000035'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/C%E1%BB%93n_S%C6%A1n_C%E1%BA%A7n_Th%C6%A1_ng23th4n2023_%28v%E1%BB%B1a_nu%C3%B4i_c%C3%A1%29_%282%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:C%E1%BB%93n_S%C6%A1n_C%E1%BA%A7n_Th%C6%A1_ng23th4n2023_(v%E1%BB%B1a_nu%C3%B4i_c%C3%A1)_(2).jpg'),
    ('eca0e123-5a96-40ee-8798-eb52388c7fdc'::uuid, 'can-tho', 'ARCHITECTURE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'can-tho', 'binh-thuy-ancient-house', 'architecture', 'history', 'heritage']::text[], 'Старинный дом Биньтхюи', 'Binh Thuy Ancient House', 'Биньтхюи көне үйі', 'Исторический дом Кантхо с колониальными и южновьетнамскими деталями, садом и атмосферой старой дельты. Хорошо работает как короткая культурная остановка.', 'A historic Can Tho house with colonial and southern Vietnamese details, a garden and old Delta atmosphere. It works well as a short cultural stop.', 'Отарлық және оңтүстік вьетнамдық детальдары, бағы және ескі дельта атмосферасы бар Кантходағы тарихи үй. Қысқа мәдени аялдама ретінде жақсы.', 10.06450000, 105.73660000, 'https://www.openstreetmap.org/search?query=Binh%20Thuy%20Ancient%20House', '50000000-0000-4000-8000-000000000036'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nha_co_Binh_Thuy_1.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Nha_co_Binh_Thuy_1.jpg'),
    ('1c286d4c-7c97-4ea7-84d1-685adfff457e'::uuid, 'can-tho', 'TEMPLE', 1, 'HOURS', 4.4, ARRAY['vietnam', 'can-tho', 'ong-temple', 'temple', 'culture', 'center']::text[], 'Храм Онг в Кантхо', 'Ong Temple Can Tho', 'Кантхо Онг храмы', 'Китайско-вьетнамский храм рядом с набережной Нинькьеу, известный яркими деталями и благовониями. Удобная культурная остановка в центре Кантхо.', 'A Chinese-Vietnamese temple near Ninh Kieu Wharf, known for vivid details and incense. It is a convenient cultural stop in central Can Tho.', 'Нинькьеу набережнаясы маңындағы жарқын детальдары және хош иісімен белгілі қытай-вьетнам храмы. Кантхо орталығындағы ыңғайлы мәдени аялдама.', 10.03450000, 105.78740000, 'https://www.openstreetmap.org/search?query=Ong%20Temple%20Can%20Tho', '50000000-0000-4000-8000-000000000037'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Le_temple_d%C3%94ng_%28Can_Tho,_Vietnam%29_%286642900621%29.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Le_temple_d%C3%94ng_(Can_Tho,_Vietnam)_(6642900621).jpg'),
    ('3f5cffb0-c452-4cbe-a778-ed70365ed160'::uuid, 'can-tho', 'MUSEUM', 1, 'HOURS', 4.3, ARRAY['vietnam', 'can-tho', 'museum', 'mekong-delta', 'history', 'indoor']::text[], 'Музей Кантхо', 'Can Tho Museum', 'Кантхо музейі', 'Музей о городе, дельте Меконга, истории региона и локальной культуре. Полезен как indoor-точка перед рынками, набережной и речными экскурсиями.', 'A museum about the city, Mekong Delta, regional history and local culture. It is useful as an indoor stop before markets, the riverfront and boat trips.', 'Қала, Меконг дельтасы, аймақ тарихы және жергілікті мәдениет туралы музей. Базарлар, набережная және қайық экскурсиялары алдында indoor аялдама ретінде пайдалы.', 10.03780000, 105.78910000, 'https://www.openstreetmap.org/search?query=Can%20Tho%20Museum', '50000000-0000-4000-8000-000000000038'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Can_Tho_Museum.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Can_Tho_Museum.jpg'),

    ('ce273330-4881-47ed-971e-982bed13a498'::uuid, 'phan-thiet', 'NATURE', 3, 'HOURS', 4.7, ARRAY['vietnam', 'phan-thiet', 'mui-ne', 'white-sand-dunes', 'dunes', 'sunrise']::text[], 'Белые дюны Муйне', 'White Sand Dunes Mui Ne', 'Муйне ақ құм төбелері', 'Главный природный образ Муйне с широкими песчаными ландшафтами, рассветными турами и фотоостановками. Обычно требует раннего выезда и аккуратного отношения к жаре.', 'The main natural image of Mui Ne, with wide sand landscapes, sunrise tours and photo stops. It usually requires an early start and care with heat.', 'Муйне аймағының кең құм ландшафттары, таңғы турлары және фото аялдамалары бар басты табиғи бейнесі. Әдетте ерте шығуды және ыстықты ескеруді талап етеді.', 11.06890000, 108.42700000, 'https://www.openstreetmap.org/search?query=White%20Sand%20Dunes%20Mui%20Ne', '50000000-0000-4000-8000-000000000039'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/White_Dune_-_Mui_Ne.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:White_Dune_-_Mui_Ne.jpg'),
    ('54e204ef-89b1-46a7-a14f-3f6af48ac12c'::uuid, 'phan-thiet', 'NATURE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'phan-thiet', 'mui-ne', 'red-sand-dunes', 'dunes', 'sunset']::text[], 'Красные дюны Муйне', 'Red Sand Dunes Mui Ne', 'Муйне қызыл құм төбелері', 'Более доступные песчаные дюны рядом с Муйне, популярные для заката, короткой остановки и фото. Хорошо дополняют Белые дюны в классическом маршруте.', 'More accessible sand dunes near Mui Ne, popular for sunset, a short stop and photos. They complement the White Sand Dunes in the classic route.', 'Муйне маңындағы қолжетімді құм төбелері: күн батуы, қысқа аялдама және фото үшін танымал. Классикалық маршрутта Ақ дюналарды жақсы толықтырады.', 10.95010000, 108.29500000, 'https://www.openstreetmap.org/search?query=Red%20Sand%20Dunes%20Mui%20Ne', '50000000-0000-4000-8000-000000000040'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sunset_on_the_Sand_dunes..JPG?width=1400', 'https://commons.wikimedia.org/wiki/File:Sunset_on_the_Sand_dunes..JPG'),
    ('ee688ac8-af05-4c03-919b-73716f52611c'::uuid, 'phan-thiet', 'NATURE', 2, 'HOURS', 4.5, ARRAY['vietnam', 'phan-thiet', 'mui-ne', 'fairy-stream', 'canyon', 'walk']::text[], 'Ручей Фейри в Муйне', 'Fairy Stream Mui Ne', 'Муйне Фейри бұлағы', 'Мелкий ручей с красно-белыми песчаными склонами, по которому идут пешком прямо по воде. Легкая и необычная прогулка для маршрута по Муйне.', 'A shallow stream with red and white sandy slopes, walked directly through the water. It is an easy and unusual walk for a Mui Ne route.', 'Қызыл-ақ құмды беткейлері бар, су бойымен жаяу өтетін тайыз бұлақ. Муйне маршруты үшін жеңіл әрі ерекше серуен.', 10.95730000, 108.28090000, 'https://www.openstreetmap.org/search?query=Fairy%20Stream%20Mui%20Ne', '50000000-0000-4000-8000-000000000041'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mui_Ne_Fairy_Stream.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Mui_Ne_Fairy_Stream.jpg'),
    ('552694aa-b64a-484f-99ef-7d3f2dc83ca2'::uuid, 'phan-thiet', 'OTHER', 1, 'HOURS', 4.4, ARRAY['vietnam', 'phan-thiet', 'mui-ne', 'fishing-village', 'boats', 'local-life']::text[], 'Рыбацкая деревня Муйне', 'Mui Ne Fishing Village', 'Муйне балықшылар ауылы', 'Прибрежная деревня с круглыми лодками, утренним рынком и сильной локальной атмосферой. Лучше всего работает на рассвете или как часть маршрута к дюнам.', 'A coastal village with round boats, morning market activity and a strong local atmosphere. It works best at sunrise or as part of a dunes route.', 'Дөңгелек қайықтары, таңғы базар тіршілігі және жергілікті атмосферасы күшті жағалаудағы ауыл. Таңсәріде немесе дюналар маршрутының бөлігі ретінде жақсы.', 10.93860000, 108.28830000, 'https://www.openstreetmap.org/search?query=Mui%20Ne%20Fishing%20Village', '50000000-0000-4000-8000-000000000042'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C5%A9i_N%C3%A9_Fishing_Village.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:M%C5%A9i_N%C3%A9_Fishing_Village.jpg'),
    ('93d14027-cf08-4631-aabd-229908d654f3'::uuid, 'phan-thiet', 'BEACH', 3, 'HOURS', 4.4, ARRAY['vietnam', 'phan-thiet', 'mui-ne-beach', 'beach', 'kite-surfing', 'resort']::text[], 'Пляж Муйне', 'Mui Ne Beach', 'Муйне жағажайы', 'Главный пляжный район Муйне с отелями, кафе, школами кайтсерфинга и длинной береговой линией. Хорош для базового пляжного сценария и отдыха между экскурсиями.', 'The main Mui Ne beach area with hotels, cafes, kitesurf schools and a long shoreline. It suits a core beach scenario and rest between excursions.', 'Қонақүйлері, кафелері, кайтсерфинг мектептері және ұзын жағалауы бар Муйне негізгі жағажай аймағы. Негізгі жағажай сценарийіне және экскурсиялар арасындағы демалысқа сай.', 10.93630000, 108.28340000, 'https://www.openstreetmap.org/search?query=Mui%20Ne%20Beach', '50000000-0000-4000-8000-000000000043'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mui_Ne_beach.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Mui_Ne_beach.jpg'),
    ('151b87d9-027f-4a67-8135-1008c74259d4'::uuid, 'phan-thiet', 'TEMPLE', 1, 'HOURS', 4.5, ARRAY['vietnam', 'phan-thiet', 'po-sah-inu', 'cham-towers', 'temple', 'history']::text[], 'Башни По Сах Ину', 'Po Sah Inu Cham Towers', 'По Сах Ину Чам мұнаралары', 'Чамский храмовый комплекс рядом с Фантхьетом, который добавляет культурный слой к пляжному направлению. Хорош для короткой исторической остановки и видов на побережье.', 'A Cham temple complex near Phan Thiet that adds cultural depth to the beach destination. It is good for a short historical stop and coastal views.', 'Фантхьет маңындағы жағажай бағытына мәдени қабат қосатын Чам храм кешені. Қысқа тарихи аялдамаға және жағалау көріністеріне жақсы.', 10.92890000, 108.10260000, 'https://www.openstreetmap.org/search?query=Po%20Sah%20Inu%20Cham%20Towers', '50000000-0000-4000-8000-000000000044'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Thap_Po_Sah_Inu_temples_complex,_Phu_Hai,_Vietnam_03.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Thap_Po_Sah_Inu_temples_complex,_Phu_Hai,_Vietnam_03.jpg'),
    ('1616f288-edb9-4517-bfec-ae268d32494e'::uuid, 'phan-thiet', 'TEMPLE', 4, 'HOURS', 4.5, ARRAY['vietnam', 'phan-thiet', 'ta-cu-mountain', 'reclining-buddha', 'cable-car', 'temple']::text[], 'Гора Таку', 'Ta Cu Mountain', 'Таку тауы', 'Горный храмовый маршрут с канатной дорогой, лесом и большой статуей лежащего Будды. Подходит как дневная поездка из Фантхьета и Муйне.', 'A mountain temple route with a cable car, forest and a large reclining Buddha statue. It works as a day trip from Phan Thiet and Mui Ne.', 'Аспалы жолы, орманы және үлкен жатқан Будда мүсіні бар тау-храм маршруты. Фантхьет пен Муйне қалаларынан күндік сапар ретінде қолайлы.', 10.80270000, 107.88790000, 'https://www.openstreetmap.org/search?query=Ta%20Cu%20Mountain%20Vietnam', '50000000-0000-4000-8000-000000000045'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%BAi_T%C3%A0_C%C3%BA_Vietnam_03.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:N%C3%BAi_T%C3%A0_C%C3%BA_Vietnam_03.jpg'),
    ('baee7642-c803-4c95-a461-2d8b22f89404'::uuid, 'phan-thiet', 'ARCHITECTURE', 2, 'HOURS', 4.5, ARRAY['vietnam', 'phan-thiet', 'ke-ga-lighthouse', 'lighthouse', 'coast', 'photo']::text[], 'Маяк Кега', 'Ke Ga Lighthouse', 'Кега шамшырағы', 'Исторический маяк на прибрежном островке к югу от Фантхьета, популярный для фото и поездок вдоль моря. Лучше проверять доступ к лодкам и погоду.', 'A historic lighthouse on a coastal islet south of Phan Thiet, popular for photos and seaside drives. Boat access and weather are worth checking.', 'Фантхьеттің оңтүстігіндегі жағалаулық аралшадағы тарихи шамшырақ, фотоға және теңіз бойындағы сапарларға танымал. Қайық қолжетімділігі мен ауа райын тексерген дұрыс.', 10.70350000, 107.99370000, 'https://www.openstreetmap.org/search?query=Ke%20Ga%20Lighthouse', '50000000-0000-4000-8000-000000000046'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ke_Ga_Lighthouse_in_early_morning_of_Phan_Thiet,_Binh_Thuan,_Vietnam.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Ke_Ga_Lighthouse_in_early_morning_of_Phan_Thiet,_Binh_Thuan,_Vietnam.jpg'),
    ('627c04c6-16f7-4a8d-abc9-189a32d7b656'::uuid, 'phan-thiet', 'MARKET', 1, 'HOURS', 4.3, ARRAY['vietnam', 'phan-thiet', 'central-market', 'market', 'seafood', 'local-food']::text[], 'Центральный рынок Фантхьета', 'Phan Thiet Central Market', 'Фантхьет орталық базары', 'Локальный рынок Фантхьета с морепродуктами, фруктами, специями и повседневной городской жизнью. Полезен для гастрономических маршрутов и практичных покупок.', 'A local Phan Thiet market with seafood, fruit, spices and everyday city life. It is useful for food routes and practical shopping.', 'Теңіз өнімдері, жеміс, дәмдеуіштер және күнделікті қала өмірі бар Фантхьет жергілікті базары. Гастро-маршруттар мен практикалық саудаға пайдалы.', 10.92880000, 108.10200000, 'https://www.openstreetmap.org/search?query=Phan%20Thiet%20Central%20Market', '50000000-0000-4000-8000-000000000047'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Phan_Thiet,_Market_-_panoramio.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Phan_Thiet,_Market_-_panoramio.jpg');

INSERT INTO attractions (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    'VN',
    city_id,
    category,
    NULL::numeric,
    NULL::varchar(3),
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    NOW(),
    NOW()
FROM seed_vietnam_priority_attractions
ON CONFLICT (id) DO UPDATE
SET
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    updated_at = NOW(),
    deleted_at = NULL
WHERE attractions.source = 'IMPORT';

INSERT INTO attraction_translations (
    attraction_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    seed.id,
    locale_rows.locale,
    CASE locale_rows.locale
        WHEN 'ru' THEN seed.title_ru
        WHEN 'kk' THEN seed.title_kk
        ELSE seed.title_en
    END,
    CASE locale_rows.locale
        WHEN 'ru' THEN seed.description_ru
        WHEN 'kk' THEN seed.description_kk
        ELSE seed.description_en
    END,
    NOW(),
    NOW()
FROM seed_vietnam_priority_attractions seed
CROSS JOIN (VALUES ('ru'), ('en'), ('kk')) AS locale_rows(locale)
ON CONFLICT (attraction_id, locale) DO UPDATE
SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

WITH seed_locations (
    id,
    latitude,
    longitude,
    location_source_url
) AS (
    SELECT
        id,
        latitude,
        longitude,
        location_source_url
    FROM seed_vietnam_priority_attractions
)
UPDATE attractions
SET
    latitude = seed_locations.latitude,
    longitude = seed_locations.longitude,
    location_source_url = seed_locations.location_source_url,
    updated_at = NOW()
FROM seed_locations
WHERE attractions.id = seed_locations.id
    AND attractions.source = 'IMPORT';

INSERT INTO attraction_media (
    id,
    attraction_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_vietnam_priority_attractions
WHERE EXISTS (
    SELECT 1
    FROM attractions a
    WHERE a.id = seed_vietnam_priority_attractions.id
)
ON CONFLICT (id) DO UPDATE
SET
    attraction_id = EXCLUDED.attraction_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO attraction_city_links (id, attraction_id, kind, country_code, city_id, position, created_at)
SELECT gen_random_uuid(), id, kind, 'VN', city_id, 0, NOW()
FROM seed_vietnam_priority_attractions
CROSS JOIN (VALUES ('ACCESS'), ('DEPARTURE')) AS link(kind)
ON CONFLICT (attraction_id, kind, city_id) DO NOTHING;

DROP TABLE IF EXISTS seed_vietnam_priority_attractions;
