-- Priority Thailand attractions seed.
-- Texts are original Inflap editorial summaries localized for ru, en, kk.
-- Sources audited in May 2026:
-- - Tourism Authority of Thailand, Tripadvisor and Klook for tourist-demand signals.
-- - Official attraction/operator pages where available.
-- - Wikimedia Commons for representative cover media.
-- - OpenStreetMap search URLs for lightweight location verification anchors.
-- Selection policy:
-- - country_code is always TH;
-- - city_id stores the practical tourist hub for filtering and guide departures;
-- - markets and night markets use the MARKET category introduced in migration 019;
-- - ratings are editorial baselines for imported curated content until user reviews take over;
-- - price is left NULL because tickets, tours and opening conditions change by season/operator.

DROP TABLE IF EXISTS seed_thailand_priority_attractions;

CREATE TEMP TABLE seed_thailand_priority_attractions (
    id uuid PRIMARY KEY,
    city_id varchar(64) NOT NULL,
    category varchar(32) NOT NULL,
    duration_value int NOT NULL,
    duration_unit varchar(16) NOT NULL,
    rating numeric(2, 1) NOT NULL,
    tags text[] NOT NULL,
    title_ru varchar(200) NOT NULL,
    title_en varchar(200) NOT NULL,
    title_kk varchar(200) NOT NULL,
    description_ru text NOT NULL,
    description_en text NOT NULL,
    description_kk text NOT NULL,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    location_source_url text NOT NULL,
    media_id uuid NOT NULL,
    media_url text NOT NULL,
    source_url text NOT NULL
);

INSERT INTO seed_thailand_priority_attractions (
    id,
    city_id,
    category,
    duration_value,
    duration_unit,
    rating,
    tags,
    title_ru,
    title_en,
    title_kk,
    description_ru,
    description_en,
    description_kk,
    latitude,
    longitude,
    location_source_url,
    media_id,
    media_url,
    source_url
) VALUES
    ('60000000-0000-4000-8000-000000000001'::uuid, 'bangkok', 'ARCHITECTURE', 3, 'HOURS', 4.8, ARRAY['thailand', 'bangkok', 'grand-palace', 'royal', 'architecture', 'temple']::text[], 'Большой дворец', 'Grand Palace', 'Үлкен сарай', 'Главный дворцово-храмовый комплекс Бангкока с королевскими павильонами, Ват Пхра Кео и плотным туристическим потоком. Это обязательная точка для первого знакомства с историческим центром.', 'Bangkok main royal and temple complex with ceremonial halls, Wat Phra Kaew and heavy visitor demand. It is a core first-route anchor for the historic center.', 'Бангкоктың салтанатты залдары, Ват Пхра Кео және үлкен туристік ағыны бар басты сарай-храм кешені. Тарихи орталықпен алғашқы танысу үшін негізгі нысан.', 13.75000000, 100.49130000, 'https://www.openstreetmap.org/search?query=Grand%20Palace%20Bangkok', '61000000-0000-4000-8000-000000000001'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grand_Palace_Bangkok.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Grand_Palace_Bangkok.jpg'),
    ('60000000-0000-4000-8000-000000000002'::uuid, 'bangkok', 'TEMPLE', 2, 'HOURS', 4.8, ARRAY['thailand', 'bangkok', 'wat-pho', 'temple', 'reclining-buddha', 'old-city']::text[], 'Храм Ват Пхо', 'Wat Pho', 'Ват Пхо ғибадатханасы', 'Один из ключевых храмов старого Бангкока со знаменитым лежащим Буддой, галереями и школой традиционного массажа. Удобно объединяется с Большим дворцом и набережной.', 'One of old Bangkok key temples, known for the Reclining Buddha, galleries and traditional massage heritage. It combines naturally with the Grand Palace and riverfront.', 'Ескі Бангкоктағы Жатқан Буддасымен, галереяларымен және дәстүрлі массаж мұрасымен белгілі негізгі храмдардың бірі. Үлкен сараймен және өзен жағалауымен жақсы үйлеседі.', 13.74650000, 100.49300000, 'https://www.openstreetmap.org/search?query=Wat%20Pho%20Bangkok', '61000000-0000-4000-8000-000000000002'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Reclining%20Buddha%20statue%20of%20Wat%20Pho9.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Reclining_Buddha_statue_of_Wat_Pho9.jpg'),
    ('60000000-0000-4000-8000-000000000003'::uuid, 'bangkok', 'TEMPLE', 2, 'HOURS', 4.7, ARRAY['thailand', 'bangkok', 'wat-arun', 'temple', 'river', 'sunset']::text[], 'Храм Рассвета Ват Арун', 'Wat Arun', 'Ват Арун ғибадатханасы', 'Храм на берегу Чао Прайи с высокой центральной башней, керамическим декором и сильной вечерней фототочкой. Хорош для маршрутов по реке и старому городу.', 'A Chao Phraya riverside temple with a tall central prang, ceramic detail and strong sunset photo value. It is useful for river and old-city itineraries.', 'Чао Прайя жағасындағы биік орталық прангі, керамикалық әшекейі және күн бататын фото нүктесі бар храм. Өзен және ескі қала маршруттарына ыңғайлы.', 13.74370000, 100.48890000, 'https://www.openstreetmap.org/search?query=Wat%20Arun%20Bangkok', '61000000-0000-4000-8000-000000000003'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat%20Arun%20from%20Chao%20Phraya%20River.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Arun_from_Chao_Phraya_River.jpg'),
    ('60000000-0000-4000-8000-000000000004'::uuid, 'bangkok', 'MUSEUM', 2, 'HOURS', 4.5, ARRAY['thailand', 'bangkok', 'national-museum', 'museum', 'history', 'indoor']::text[], 'Национальный музей Бангкока', 'Bangkok National Museum', 'Бангкок ұлттық музейі', 'Крупный музей тайской истории и искусства рядом с историческим центром. Полезен как indoor-остановка для маршрутов о культуре, королевских регалиях и традиционном искусстве.', 'A major Thai history and art museum near the historic center. It is a useful indoor stop for culture, royal regalia and traditional art routes.', 'Тарихи орталық маңындағы тай тарихы мен өнерінің ірі музейі. Мәдениет, корольдік жәдігерлер және дәстүрлі өнер бағыттарына пайдалы indoor аялдама.', 13.75760000, 100.49250000, 'https://www.openstreetmap.org/search?query=Bangkok%20National%20Museum', '61000000-0000-4000-8000-000000000004'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bangkok_National_Museum.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Bangkok_National_Museum.jpg'),
    ('60000000-0000-4000-8000-000000000005'::uuid, 'bangkok', 'MUSEUM', 1, 'HOURS', 4.6, ARRAY['thailand', 'bangkok', 'jim-thompson-house', 'museum', 'silk', 'architecture']::text[], 'Дом-музей Джима Томпсона', 'Jim Thompson House', 'Джим Томпсон үй-музейі', 'Дом-музей с тайской деревянной архитектурой, шелковым наследием и спокойным садом в центре города. Хорошая культурная остановка между шопингом и историческими районами.', 'A house museum with Thai timber architecture, silk heritage and a calm central garden. It works as a cultural stop between shopping areas and historic districts.', 'Тай ағаш сәулеті, жібек мұрасы және орталықтағы тыныш бағы бар үй-музей. Сауда аймақтары мен тарихи аудандар арасындағы мәдени аялдамаға жақсы.', 13.74930000, 100.52840000, 'https://www.openstreetmap.org/search?query=Jim%20Thompson%20House%20Bangkok', '61000000-0000-4000-8000-000000000005'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Main%20House%20of%20Jim%20Thompson%20photo%20Don%20Ramey%20Logan.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Main_House_of_Jim_Thompson_photo_Don_Ramey_Logan.jpg'),
    ('60000000-0000-4000-8000-000000000006'::uuid, 'bangkok', 'PARK', 2, 'HOURS', 4.5, ARRAY['thailand', 'bangkok', 'lumphini-park', 'park', 'city-walk', 'family']::text[], 'Парк Люмпини', 'Lumphini Park', 'Люмпини паркі', 'Большой городской парк с озером, прогулочными дорожками и передышкой от плотного трафика Бангкока. Подходит для семей, утренних прогулок и мягких активностей.', 'A large city park with a lake, walking paths and a break from Bangkok dense traffic. It suits families, morning walks and light activities.', 'Көлі, серуен жолдары және Бангкоктың қарбаласынан демалысы бар үлкен қалалық парк. Отбасыларға, таңғы серуенге және жеңіл белсенділікке сай.', 13.73070000, 100.54180000, 'https://www.openstreetmap.org/search?query=Lumphini%20Park%20Bangkok', '61000000-0000-4000-8000-000000000006'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lumphini_Park_Bangkok.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Lumphini_Park_Bangkok.jpg'),
    ('60000000-0000-4000-8000-000000000007'::uuid, 'bangkok', 'MARKET', 3, 'HOURS', 4.6, ARRAY['thailand', 'bangkok', 'chatuchak', 'weekend-market', 'market', 'shopping']::text[], 'Рынок Чатучак', 'Chatuchak Weekend Market', 'Чатучак демалыс базары', 'Один из крупнейших рынков Бангкока с одеждой, сувенирами, декором, едой и длинными торговыми рядами. Нужен как отдельный сценарий выходного дня, а не короткая остановка.', 'One of Bangkok largest markets, with clothing, souvenirs, decor, food and long shopping lanes. It works as a dedicated weekend scenario rather than a quick stop.', 'Киім, сувенир, декор, тағам және ұзын сауда қатарлары бар Бангкоктағы ең ірі базарлардың бірі. Қысқа аялдама емес, демалыс күнгі жеке сценарий ретінде ыңғайлы.', 13.79960000, 100.55010000, 'https://www.openstreetmap.org/search?query=Chatuchak%20Weekend%20Market%20Bangkok', '61000000-0000-4000-8000-000000000007'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chatuchak_Weekend_Market_Bangkok.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Chatuchak_Weekend_Market_Bangkok.jpg'),
    ('60000000-0000-4000-8000-000000000008'::uuid, 'bangkok', 'SHOPPING', 3, 'HOURS', 4.6, ARRAY['thailand', 'bangkok', 'iconsiam', 'mall', 'riverfront', 'shopping']::text[], 'Торговый центр ICONSIAM', 'ICONSIAM', 'ICONSIAM сауда орталығы', 'Крупный молл на берегу Чао Прайи с магазинами, фуд-зоной, набережной и вечерними видами. Удобен как комфортная точка для шопинга, еды и отдыха после города.', 'A large Chao Phraya riverside mall with shops, food zones, promenade views and evening appeal. It is a comfortable anchor for shopping, food and rest after city routes.', 'Чао Прайя жағасындағы дүкендері, фуд-аймағы, набережнаясы және кешкі көрінісі бар ірі молл. Қала маршрутыннан кейін сауда, тамақ және демалыс үшін ыңғайлы.', 13.72660000, 100.51090000, 'https://www.openstreetmap.org/search?query=ICONSIAM%20Bangkok', '61000000-0000-4000-8000-000000000008'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/ICONSIAM_Bangkok.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:ICONSIAM_Bangkok.jpg'),
    ('60000000-0000-4000-8000-000000000009'::uuid, 'bangkok', 'ENTERTAINMENT', 2, 'HOURS', 4.5, ARRAY['thailand', 'bangkok', 'mahanakhon', 'skywalk', 'viewpoint', 'city']::text[], 'Смотровая площадка Mahanakhon SkyWalk', 'Mahanakhon SkyWalk', 'Mahanakhon SkyWalk алаңы', 'Высотная смотровая площадка с панорамой Бангкока и стеклянным участком пола. Хороша для вечернего маршрута, когда туристам нужен понятный городской wow-эффект.', 'A high-rise viewpoint with Bangkok panoramas and a glass-floor section. It is a clear evening route anchor when travelers want a city wow moment.', 'Бангкок панорамасы және әйнек еден бөлігі бар биік смотровая алаң. Туристерге қаладағы әсерлі сәт керек кешкі маршрутқа жақсы.', 13.72330000, 100.52870000, 'https://www.openstreetmap.org/search?query=Mahanakhon%20SkyWalk%20Bangkok', '61000000-0000-4000-8000-000000000009'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/King_Power_Mahanakhon_Bangkok.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:King_Power_Mahanakhon_Bangkok.jpg'),

    ('60000000-0000-4000-8000-000000000010'::uuid, 'ayutthaya', 'PARK', 4, 'HOURS', 4.8, ARRAY['thailand', 'ayutthaya', 'historical-park', 'unesco', 'temples', 'history']::text[], 'Исторический парк Аюттхая', 'Ayutthaya Historical Park', 'Аюттхая тарихи паркі', 'Обширная зона руин древней столицы с храмами, ступами и веломаршрутами. Это главный культурный day trip из Бангкока и базовая точка для гидов по истории Таиланда.', 'A wide ancient-capital ruins area with temples, stupas and cycling routes. It is the core cultural day trip from Bangkok and a base for Thai history guiding.', 'Ежелгі астананың храмдары, ступалары және веломаршруттары бар үлкен қирандылар аймағы. Бангкоктан мәдени day trip және Таиланд тарихына арналған негізгі бағыт.', 14.35590000, 100.56890000, 'https://www.openstreetmap.org/search?query=Ayutthaya%20Historical%20Park', '61000000-0000-4000-8000-000000000010'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ayutthaya_Historical_Park.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Ayutthaya_Historical_Park.jpg'),
    ('60000000-0000-4000-8000-000000000011'::uuid, 'ayutthaya', 'TEMPLE', 1, 'HOURS', 4.7, ARRAY['thailand', 'ayutthaya', 'wat-mahathat', 'buddha-head', 'temple', 'history']::text[], 'Ват Махатхат в Аюттхае', 'Wat Mahathat Ayutthaya', 'Аюттхая Ват Махатхат', 'Храмовый комплекс с известной головой Будды в корнях дерева и атмосферой древней столицы. Обычно становится одной из самых узнаваемых остановок Аюттхаи.', 'A temple complex known for the Buddha head in tree roots and the ancient-capital atmosphere. It is usually one of Ayutthaya most recognizable stops.', 'Ағаш тамырларындағы Будда басымен және ежелгі астана атмосферасымен белгілі храм кешені. Аюттхаядағы ең танымал аялдамалардың бірі.', 14.35720000, 100.56700000, 'https://www.openstreetmap.org/search?query=Wat%20Mahathat%20Ayutthaya', '61000000-0000-4000-8000-000000000011'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Mahathat_Ayutthaya.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Mahathat_Ayutthaya.jpg'),
    ('60000000-0000-4000-8000-000000000012'::uuid, 'ayutthaya', 'TEMPLE', 1, 'HOURS', 4.7, ARRAY['thailand', 'ayutthaya', 'wat-chaiwatthanaram', 'temple', 'river', 'sunset']::text[], 'Ват Чайваттханарам', 'Wat Chaiwatthanaram', 'Ват Чайваттханарам', 'Живописный храмовый комплекс у реки с симметричной планировкой и сильным вечерним светом. Хорошо завершает день в Аюттхае и подходит для фото-маршрутов.', 'A scenic riverside temple complex with strong symmetry and evening light. It is a good final stop in Ayutthaya and works well for photo routes.', 'Өзен жағасындағы симметриясы және кешкі жарығы әдемі храм кешені. Аюттхаядағы күнді аяқтауға және фото маршруттарға жақсы.', 14.34390000, 100.54180000, 'https://www.openstreetmap.org/search?query=Wat%20Chaiwatthanaram', '61000000-0000-4000-8000-000000000012'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Chaiwatthanaram_Ayutthaya.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Chaiwatthanaram_Ayutthaya.jpg'),
    ('60000000-0000-4000-8000-000000000013'::uuid, 'ayutthaya', 'ARCHITECTURE', 2, 'HOURS', 4.5, ARRAY['thailand', 'ayutthaya', 'bang-pa-in', 'palace', 'royal', 'architecture']::text[], 'Летний дворец Банг Па-Ин', 'Bang Pa-In Royal Palace', 'Банг Па-Ин король сарайы', 'Королевская резиденция с павильонами, садами и европейско-азиатскими архитектурными мотивами. Удобна как спокойная остановка на пути между Бангкоком и Аюттхаей.', 'A royal residence with pavilions, gardens and European-Asian architectural motifs. It is a calm stop between Bangkok and Ayutthaya.', 'Павильондары, бақтары және еуропалық-азиялық сәулет мотивтері бар король резиденциясы. Бангкок пен Аюттхая арасындағы тыныш аялдама.', 14.23270000, 100.57890000, 'https://www.openstreetmap.org/search?query=Bang%20Pa-In%20Royal%20Palace', '61000000-0000-4000-8000-000000000013'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bang_Pa-In_Royal_Palace.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Bang_Pa-In_Royal_Palace.jpg'),
    ('60000000-0000-4000-8000-000000000014'::uuid, 'ayutthaya', 'MARKET', 2, 'HOURS', 4.3, ARRAY['thailand', 'ayutthaya', 'floating-market', 'market', 'food', 'family']::text[], 'Плавучий рынок Аюттхаи', 'Ayothaya Floating Market', 'Аюттхая қалқымалы базары', 'Туристический рынок с едой, лодками, сувенирами и семейным форматом. Хорошо закрывает легкий leisure-сценарий после храмов и исторических руин.', 'A tourist market with food, boats, souvenirs and a family-friendly format. It fills an easy leisure scenario after temples and ruins.', 'Тағамы, қайықтары, сувенирлері және отбасылық форматы бар туристік базар. Храмдар мен қирандылардан кейін жеңіл leisure сценарийін толықтырады.', 14.35140000, 100.59680000, 'https://www.openstreetmap.org/search?query=Ayothaya%20Floating%20Market', '61000000-0000-4000-8000-000000000014'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ayothaya_Floating_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Ayothaya_Floating_Market.jpg'),

    ('60000000-0000-4000-8000-000000000015'::uuid, 'pattaya', 'ARCHITECTURE', 2, 'HOURS', 4.7, ARRAY['thailand', 'pattaya', 'sanctuary-of-truth', 'wooden-temple', 'architecture', 'culture']::text[], 'Храм Истины', 'Sanctuary of Truth', 'Ақиқат ғибадатханасы', 'Монументальное деревянное сооружение у моря с резьбой, мифологическими сюжетами и сильной визуальной ценностью. Это один из самых понятных культурных якорей Паттайи.', 'A monumental seaside wooden structure with carvings, mythology and high visual value. It is one of Pattaya clearest cultural anchors.', 'Теңіз жағасындағы оюлары, мифологиялық сюжеттері және әсерлі көрінісі бар монументалды ағаш ғимарат. Паттайядағы ең түсінікті мәдени нысандардың бірі.', 12.97280000, 100.88900000, 'https://www.openstreetmap.org/search?query=Sanctuary%20of%20Truth%20Pattaya', '61000000-0000-4000-8000-000000000015'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sanctuary%20of%20Truth%20001.JPG?width=1400', 'https://commons.wikimedia.org/wiki/File:Sanctuary_of_Truth_001.JPG'),
    ('60000000-0000-4000-8000-000000000016'::uuid, 'pattaya', 'PARK', 4, 'HOURS', 4.6, ARRAY['thailand', 'pattaya', 'nong-nooch', 'botanical-garden', 'park', 'family']::text[], 'Тропический сад Нонг Нуч', 'Nong Nooch Tropical Botanical Garden', 'Нонг Нуч тропикалық бағы', 'Большой ботанический парк с тематическими садами, семейными шоу и фотозонами. Подходит для полудневных маршрутов из Паттайи, особенно с детьми.', 'A large botanical park with themed gardens, family shows and photo zones. It works for half-day Pattaya routes, especially with children.', 'Тақырыптық бақтары, отбасылық шоулары және фото аймақтары бар үлкен ботаникалық парк. Паттайядан жарты күндік маршруттарға, әсіресе балалармен, сай.', 12.76540000, 100.93200000, 'https://www.openstreetmap.org/search?query=Nong%20Nooch%20Tropical%20Botanical%20Garden', '61000000-0000-4000-8000-000000000016'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nong_Nooch_Tropical_Botanical_Garden.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Nong_Nooch_Tropical_Botanical_Garden.jpg'),
    ('60000000-0000-4000-8000-000000000017'::uuid, 'pattaya', 'BEACH', 2, 'HOURS', 4.2, ARRAY['thailand', 'pattaya', 'pattaya-beach', 'beach', 'city', 'promenade']::text[], 'Пляж Паттайя', 'Pattaya Beach', 'Паттайя жағажайы', 'Центральный городской пляж рядом с отелями, торговыми центрами и вечерней набережной. Это удобная базовая точка для отдыха у моря без дальнего трансфера.', 'The central city beach near hotels, malls and the evening promenade. It is a convenient baseline seaside point without a long transfer.', 'Қонақүйлерге, моллдарға және кешкі набережнаяға жақын орталық қалалық жағажай. Ұзақ трансферсіз теңіз жағасындағы негізгі нүкте.', 12.93670000, 100.88300000, 'https://www.openstreetmap.org/search?query=Pattaya%20Beach', '61000000-0000-4000-8000-000000000017'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pattaya_Beach_Thailand.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Pattaya_Beach_Thailand.jpg'),
    ('60000000-0000-4000-8000-000000000018'::uuid, 'pattaya', 'MARKET', 2, 'HOURS', 4.3, ARRAY['thailand', 'pattaya', 'floating-market', 'market', 'food', 'souvenirs']::text[], 'Плавучий рынок Паттайи', 'Pattaya Floating Market', 'Паттайя қалқымалы базары', 'Туристический рынок с павильонами, едой, сувенирами и лодочными сценами. Хорош для легкой дневной программы и первых покупок в Паттайе.', 'A tourist market with pavilions, food, souvenirs and boat scenes. It is useful for an easy daytime program and first Pattaya shopping.', 'Павильондары, тағамы, сувенирлері және қайық көріністері бар туристік базар. Жеңіл күндізгі бағдарламаға және Паттайядағы алғашқы саудаға ыңғайлы.', 12.86710000, 100.90290000, 'https://www.openstreetmap.org/search?query=Pattaya%20Floating%20Market', '61000000-0000-4000-8000-000000000018'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pattaya_Floating_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Pattaya_Floating_Market.jpg'),
    ('60000000-0000-4000-8000-000000000019'::uuid, 'pattaya', 'SHOPPING', 2, 'HOURS', 4.4, ARRAY['thailand', 'pattaya', 'central-pattaya', 'mall', 'shopping', 'food']::text[], 'Торговый центр Central Pattaya', 'Central Pattaya', 'Central Pattaya сауда орталығы', 'Крупный молл в центре Паттайи с магазинами, фуд-кортом и быстрым доступом к пляжу. Полезен как комфортная точка в жару или дождь.', 'A major central Pattaya mall with shops, food court and quick beach access. It is useful as a comfortable hot-weather or rainy-day stop.', 'Паттайя орталығындағы дүкендері, фудкорты және жағажайға жылдам шығуы бар ірі молл. Ыстықта немесе жаңбырлы күні жайлы аялдама.', 12.93470000, 100.88220000, 'https://www.openstreetmap.org/search?query=Central%20Pattaya', '61000000-0000-4000-8000-000000000019'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Central_Pattaya.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Central_Pattaya.jpg'),
    ('60000000-0000-4000-8000-000000000020'::uuid, 'pattaya', 'OTHER', 1, 'HOURS', 4.4, ARRAY['thailand', 'pattaya', 'khao-chi-chan', 'buddha-mountain', 'photo', 'culture']::text[], 'Гора Будды Кхао Чи Чан', 'Khao Chi Chan', 'Кхао Чи Чан Будда тауы', 'Скала с большим золотым изображением Будды рядом с Паттайей. Это короткая, понятная и фотогеничная остановка рядом с Нонг Нуч и южными пляжами.', 'A cliff with a large golden Buddha image near Pattaya. It is a short, clear and photogenic stop near Nong Nooch and southern beaches.', 'Паттайя маңындағы үлкен алтын Будда бейнесі бар жартас. Нонг Нуч пен оңтүстік жағажайлар жанындағы қысқа, түсінікті және фотогенді аялдама.', 12.76470000, 100.95650000, 'https://www.openstreetmap.org/search?query=Khao%20Chi%20Chan%20Pattaya', '61000000-0000-4000-8000-000000000020'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Khao_Chi_Chan_Buddha_Mountain.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Khao_Chi_Chan_Buddha_Mountain.jpg'),

    ('60000000-0000-4000-8000-000000000021'::uuid, 'phuket', 'TEMPLE', 2, 'HOURS', 4.6, ARRAY['thailand', 'phuket', 'big-buddha', 'temple', 'viewpoint', 'island']::text[], 'Большой Будда Пхукета', 'Phuket Big Buddha', 'Пхукет Үлкен Буддасы', 'Крупная статуя Будды на холме с обзором на юг Пхукета, пляжи и бухты. Это один из самых сильных видовых и культурных якорей острова.', 'A large hilltop Buddha statue overlooking southern Phuket, beaches and bays. It is one of the island strongest scenic and cultural anchors.', 'Пхукеттің оңтүстігіне, жағажайлар мен бухталарға қарайтын төбедегі үлкен Будда мүсіні. Аралдың ең күшті көріністік және мәдени нысандарының бірі.', 7.82760000, 98.31280000, 'https://www.openstreetmap.org/search?query=Phuket%20Big%20Buddha', '61000000-0000-4000-8000-000000000021'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Big%20Buddha.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:The_Big_Buddha.jpg'),
    ('60000000-0000-4000-8000-000000000022'::uuid, 'phuket', 'TEMPLE', 1, 'HOURS', 4.5, ARRAY['thailand', 'phuket', 'wat-chalong', 'temple', 'culture', 'old-town']::text[], 'Храм Ват Чалонг', 'Wat Chalong', 'Ват Чалонг ғибадатханасы', 'Самый известный храм Пхукета с пагодой, церемониальными залами и плотным потоком паломников и туристов. Хорошо соединяется с Большим Буддой.', 'Phuket best-known temple, with a pagoda, ceremonial halls and steady pilgrim and visitor flow. It pairs well with the Big Buddha.', 'Пхукеттің пагодасы, салтанатты залдары және тұрақты келушілері бар ең танымал храмы. Үлкен Буддамен жақсы үйлеседі.', 7.84610000, 98.33890000, 'https://www.openstreetmap.org/search?query=Wat%20Chalong%20Phuket', '61000000-0000-4000-8000-000000000022'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Chalong_Phuket.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Chalong_Phuket.jpg'),
    ('60000000-0000-4000-8000-000000000023'::uuid, 'phuket', 'ARCHITECTURE', 3, 'HOURS', 4.6, ARRAY['thailand', 'phuket', 'old-town', 'architecture', 'street-art', 'city-walk']::text[], 'Старый город Пхукета', 'Phuket Old Town', 'Пхукет ескі қаласы', 'Исторический район с сино-португальскими фасадами, кафе, стрит-артом и вечерними прогулками. Нужен как городская альтернатива пляжному Пхукету.', 'A historic district with Sino-Portuguese facades, cafes, street art and evening walks. It is the city-side alternative to beach Phuket.', 'Сино-португал қасбеттері, кафелері, стрит-арты және кешкі серуені бар тарихи аудан. Жағажайлы Пхукетке қалалық балама.', 7.88400000, 98.38900000, 'https://www.openstreetmap.org/search?query=Phuket%20Old%20Town', '61000000-0000-4000-8000-000000000023'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Phuket_Old_Town.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Phuket_Old_Town.jpg'),
    ('60000000-0000-4000-8000-000000000024'::uuid, 'phuket', 'BEACH', 3, 'HOURS', 4.4, ARRAY['thailand', 'phuket', 'patong-beach', 'beach', 'nightlife', 'central']::text[], 'Пляж Патонг', 'Patong Beach', 'Патонг жағажайы', 'Самый известный и оживленный пляж Пхукета рядом с отелями, ресторанами, водными активностями и ночной жизнью. Подходит тем, кто хочет максимум инфраструктуры.', 'Phuket best-known and busiest beach, near hotels, restaurants, water activities and nightlife. It suits travelers who want maximum infrastructure.', 'Қонақүйлерге, мейрамханаларға, су белсенділігіне және түнгі өмірге жақын Пхукеттің ең танымал әрі белсенді жағажайы. Инфрақұрылым көп керек туристерге сай.', 7.89640000, 98.29580000, 'https://www.openstreetmap.org/search?query=Patong%20Beach%20Phuket', '61000000-0000-4000-8000-000000000024'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Patong_Beach_Phuket.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Patong_Beach_Phuket.jpg'),
    ('60000000-0000-4000-8000-000000000025'::uuid, 'phuket', 'MARKET', 2, 'HOURS', 4.4, ARRAY['thailand', 'phuket', 'naka-market', 'weekend-market', 'market', 'food']::text[], 'Рынок Нака на Пхукете', 'Naka Weekend Market', 'Пхукет Нака демалыс базары', 'Крупный вечерний рынок выходного дня с уличной едой, одеждой и сувенирами. Хорош для гастрономического сценария и практичных покупок после пляжа.', 'A large weekend evening market with street food, clothing and souvenirs. It works for food scenarios and practical shopping after beach time.', 'Стрит-фуды, киімі және сувенирлері бар үлкен демалыс кешкі базары. Жағажайдан кейінгі гастро сценарийге және практикалық саудаға жақсы.', 7.88840000, 98.36690000, 'https://www.openstreetmap.org/search?query=Naka%20Weekend%20Market%20Phuket', '61000000-0000-4000-8000-000000000025'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Phuket_Weekend_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Phuket_Weekend_Market.jpg'),
    ('60000000-0000-4000-8000-000000000026'::uuid, 'phuket', 'SHOPPING', 2, 'HOURS', 4.4, ARRAY['thailand', 'phuket', 'central-phuket', 'mall', 'shopping', 'food']::text[], 'Торговый центр Central Phuket', 'Central Phuket', 'Central Phuket сауда орталығы', 'Главный крупный молл острова с магазинами, ресторанами, супермаркетом и indoor-сценарием для жары или дождя. Удобен как сервисная точка маршрута.', 'A main island mall with shops, restaurants, supermarket and indoor value for hot or rainy days. It is a practical service stop in Phuket routes.', 'Дүкендері, мейрамханалары, супермаркеті және ыстық не жаңбырлы күнге indoor сценарийі бар аралдың негізгі моллы. Пхукет маршруттарындағы практикалық аялдама.', 7.89170000, 98.36890000, 'https://www.openstreetmap.org/search?query=Central%20Phuket', '61000000-0000-4000-8000-000000000026'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Central_Phuket.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Central_Phuket.jpg'),

    ('60000000-0000-4000-8000-000000000027'::uuid, 'krabi', 'BEACH', 4, 'HOURS', 4.8, ARRAY['thailand', 'krabi', 'railay-beach', 'beach', 'limestone', 'climbing']::text[], 'Пляж Рейли', 'Railay Beach', 'Рейли жағажайы', 'Полуостровной пляж Краби с известняковыми скалами, лодочным доступом и сильной фотоценностью. Это один из главных природно-пляжных якорей региона.', 'A Krabi peninsula beach with limestone cliffs, boat access and strong photo value. It is one of the region core nature-and-beach anchors.', 'Әктас жартастары, қайықпен жету және әсерлі фото көріністері бар Краби түбегіндегі жағажай. Аймақтың басты табиғат-ж жағажай нысандарының бірі.', 8.01000000, 98.83990000, 'https://www.openstreetmap.org/search?query=Railay%20Beach%20Krabi', '61000000-0000-4000-8000-000000000027'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Railay%20Beach%202.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Railay_Beach_2.jpg'),
    ('60000000-0000-4000-8000-000000000028'::uuid, 'krabi', 'BEACH', 3, 'HOURS', 4.7, ARRAY['thailand', 'krabi', 'phra-nang', 'cave-beach', 'beach', 'limestone']::text[], 'Пляж Пхра Нанг Кейв', 'Phra Nang Cave Beach', 'Пхра Нанг үңгір жағажайы', 'Красивый пляж рядом с Рейли, пещерами и известняковыми стенами. Хорош для лодочных маршрутов, фото и отдыха у воды без сложного треккинга.', 'A beautiful beach near Railay, caves and limestone walls. It suits boat routes, photos and water time without difficult trekking.', 'Рейли, үңгірлер және әктас қабырғалары жанындағы әдемі жағажай. Қайық маршрутына, фотоға және қиын треккингсіз су жағасындағы демалысқа сай.', 8.00550000, 98.83790000, 'https://www.openstreetmap.org/search?query=Phra%20Nang%20Cave%20Beach', '61000000-0000-4000-8000-000000000028'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Phra_Nang_Cave_Beach.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Phra_Nang_Cave_Beach.jpg'),
    ('60000000-0000-4000-8000-000000000029'::uuid, 'krabi', 'TEMPLE', 3, 'HOURS', 4.6, ARRAY['thailand', 'krabi', 'tiger-cave-temple', 'temple', 'stairs', 'viewpoint']::text[], 'Храм Тигровой пещеры', 'Tiger Cave Temple', 'Жолбарыс үңгірі храмы', 'Храмовый комплекс с длинным подъемом к обзорной площадке над Краби. Требует физической готовности, но дает сильный видовой результат.', 'A temple complex with a long climb to a viewpoint above Krabi. It requires physical readiness but rewards with strong views.', 'Краби үстіндегі смотровая алаңға ұзақ көтерілетін храм кешені. Дайындық қажет, бірақ көрінісі өте әсерлі.', 8.12630000, 98.92480000, 'https://www.openstreetmap.org/search?query=Tiger%20Cave%20Temple%20Krabi', '61000000-0000-4000-8000-000000000029'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tiger_Cave_Temple_Krabi.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Tiger_Cave_Temple_Krabi.jpg'),
    ('60000000-0000-4000-8000-000000000030'::uuid, 'krabi', 'NATURE', 2, 'HOURS', 4.5, ARRAY['thailand', 'krabi', 'emerald-pool', 'nature', 'swimming', 'forest']::text[], 'Изумрудный бассейн Краби', 'Emerald Pool', 'Краби Изумруд бассейні', 'Природный бассейн с прозрачной водой в лесной зоне Краби. Хорош для дневных маршрутов, где туристам нужен легкий природный формат с купанием.', 'A natural clear-water pool in a Krabi forest area. It fits daytime routes where travelers want an easy nature-and-swimming format.', 'Крабидің орман аймағындағы мөлдір суы бар табиғи бассейн. Туристерге жеңіл табиғат және шомылу форматы керек күндізгі бағыттарға сай.', 7.93040000, 99.26890000, 'https://www.openstreetmap.org/search?query=Emerald%20Pool%20Krabi', '61000000-0000-4000-8000-000000000030'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Emerald_Pool_Krabi.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Emerald_Pool_Krabi.jpg'),
    ('60000000-0000-4000-8000-000000000031'::uuid, 'krabi', 'NATURE', 5, 'HOURS', 4.7, ARRAY['thailand', 'krabi', 'hong-islands', 'islands', 'boat', 'snorkeling']::text[], 'Острова Хонг', 'Hong Islands', 'Хонг аралдары', 'Группа островов Краби с лагунами, пляжами и лодочными турами. Это сильный вариант для морского дня, снорклинга и фото на воде.', 'A Krabi island group with lagoons, beaches and boat tours. It is a strong option for a sea day, snorkeling and water photos.', 'Лагуналары, жағажайлары және қайық турлары бар Краби аралдары тобы. Теңіз күніне, снорклингке және судағы фотоға жақсы нұсқа.', 8.08000000, 98.68000000, 'https://www.openstreetmap.org/search?query=Hong%20Islands%20Krabi', '61000000-0000-4000-8000-000000000031'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hong_Island_Krabi.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Hong_Island_Krabi.jpg'),
    ('60000000-0000-4000-8000-000000000032'::uuid, 'krabi', 'MARKET', 2, 'HOURS', 4.4, ARRAY['thailand', 'krabi', 'walking-street', 'night-market', 'market', 'food']::text[], 'Ночной рынок Krabi Walking Street', 'Krabi Walking Street', 'Краби Walking Street түнгі базары', 'Вечерний рынок в городе Краби с едой, сувенирами и локальной атмосферой. Хорош для простой вечерней программы после пляжей и островов.', 'An evening market in Krabi Town with food, souvenirs and local atmosphere. It is a simple evening program after beaches and islands.', 'Краби қаласындағы тағамы, сувенирі және жергілікті атмосферасы бар кешкі базар. Жағажайлар мен аралдардан кейінгі жеңіл кешкі бағдарлама.', 8.06470000, 98.91690000, 'https://www.openstreetmap.org/search?query=Krabi%20Walking%20Street', '61000000-0000-4000-8000-000000000032'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Krabi_Walking_Street.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Krabi_Walking_Street.jpg'),

    ('60000000-0000-4000-8000-000000000033'::uuid, 'phang-nga', 'NATURE', 5, 'HOURS', 4.7, ARRAY['thailand', 'phang-nga', 'james-bond-island', 'island', 'boat', 'limestone']::text[], 'Остров Джеймса Бонда', 'James Bond Island', 'Джеймс Бонд аралы', 'Известняковый остров в заливе Пхангнга, популярный в лодочных турах из Пхукета и Краби. Хорош как узнаваемая морская точка для массового спроса.', 'A limestone island in Phang Nga Bay, popular on boat tours from Phuket and Krabi. It is a recognizable sea-route anchor for mainstream demand.', 'Пхангнга шығанағындағы Пхукет пен Крабиден қайық турларына танымал әктас арал. Жаппай сұранысқа түсінікті теңіз нүктесі.', 8.27580000, 98.50150000, 'https://www.openstreetmap.org/search?query=James%20Bond%20Island%20Thailand', '61000000-0000-4000-8000-000000000033'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/James_Bond_Island_Thailand.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:James_Bond_Island_Thailand.jpg'),
    ('60000000-0000-4000-8000-000000000034'::uuid, 'phang-nga', 'NATURE', 1, 'HOURS', 4.7, ARRAY['thailand', 'phang-nga', 'samet-nangshe', 'viewpoint', 'sunrise', 'bay']::text[], 'Смотровая площадка Самет Нангше', 'Samet Nangshe Viewpoint', 'Самет Нангше көрініс алаңы', 'Панорамная площадка над заливом Пхангнга, особенно сильная на рассвете. Подходит для фото-маршрутов и коротких остановок по пути к лодочным турам.', 'A panoramic viewpoint above Phang Nga Bay, especially strong at sunrise. It suits photo routes and short stops before boat tours.', 'Пхангнга шығанағы үстіндегі, әсіресе таңсәріде әдемі панорамалық алаң. Фото маршруттарға және қайық туры алдындағы қысқа аялдамаға сай.', 8.23940000, 98.44960000, 'https://www.openstreetmap.org/search?query=Samet%20Nangshe%20Viewpoint', '61000000-0000-4000-8000-000000000034'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Samet_Nangshe_Viewpoint.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Samet_Nangshe_Viewpoint.jpg'),
    ('60000000-0000-4000-8000-000000000035'::uuid, 'phang-nga', 'PARK', 4, 'HOURS', 4.5, ARRAY['thailand', 'phang-nga', 'khao-lak-lam-ru', 'national-park', 'nature', 'hiking']::text[], 'Национальный парк Кхао Лак-Лам Ру', 'Khao Lak-Lam Ru National Park', 'Кхао Лак-Лам Ру ұлттық паркі', 'Национальный парк с тропами, лесом и морскими видами в районе Кхао Лак. Хорош для туристов, которым нужен природный формат за пределами пляжа.', 'A national park with trails, forest and sea views around Khao Lak. It is useful for travelers who want nature beyond the beach.', 'Кхао Лак аймағындағы соқпақтары, орманы және теңіз көріністері бар ұлттық парк. Жағажайдан тыс табиғат керек туристерге пайдалы.', 8.62650000, 98.23900000, 'https://www.openstreetmap.org/search?query=Khao%20Lak-Lam%20Ru%20National%20Park', '61000000-0000-4000-8000-000000000035'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Khao_Lak-Lam_Ru_National_Park.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Khao_Lak-Lam_Ru_National_Park.jpg'),
    ('60000000-0000-4000-8000-000000000036'::uuid, 'phang-nga', 'TEMPLE', 1, 'HOURS', 4.4, ARRAY['thailand', 'phang-nga', 'wat-suwan-khuha', 'cave-temple', 'buddha', 'culture']::text[], 'Пещерный храм Ват Суван Куха', 'Wat Suwan Khuha', 'Ват Суван Куха үңгір храмы', 'Пещерный храм с лежащим Буддой и карстовым окружением. Это компактная культурная остановка в маршрутах по Пхангнга.', 'A cave temple with a reclining Buddha and karst surroundings. It is a compact cultural stop in Phang Nga routes.', 'Жатқан Буддасы және карст ортасы бар үңгір храмы. Пхангнга маршруттарындағы ықшам мәдени аялдама.', 8.44260000, 98.53060000, 'https://www.openstreetmap.org/search?query=Wat%20Suwan%20Khuha', '61000000-0000-4000-8000-000000000036'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Suwan_Khuha.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Suwan_Khuha.jpg'),
    ('60000000-0000-4000-8000-000000000037'::uuid, 'phang-nga', 'MARKET', 2, 'HOURS', 4.3, ARRAY['thailand', 'phang-nga', 'bang-niang-market', 'night-market', 'market', 'khao-lak']::text[], 'Рынок Банг Нианг', 'Bang Niang Market', 'Банг Нианг базары', 'Популярный вечерний рынок Кхао Лака с едой, фруктами, одеждой и сувенирами. Хорош для спокойного вечернего сценария после пляжа или экскурсий.', 'A popular Khao Lak evening market with food, fruit, clothing and souvenirs. It works for an easy evening scenario after beach time or tours.', 'Тағам, жеміс, киім және сувенирлері бар Кхао Лактың танымал кешкі базары. Жағажай немесе экскурсиядан кейінгі тыныш кешкі сценарийге сай.', 8.66610000, 98.25250000, 'https://www.openstreetmap.org/search?query=Bang%20Niang%20Market%20Khao%20Lak', '61000000-0000-4000-8000-000000000037'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bang_Niang_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Bang_Niang_Market.jpg'),

    ('60000000-0000-4000-8000-000000000038'::uuid, 'chiang-mai', 'TEMPLE', 3, 'HOURS', 4.8, ARRAY['thailand', 'chiang-mai', 'doi-suthep', 'temple', 'mountain', 'viewpoint']::text[], 'Храм Ват Пхра Тхат Дой Сутхеп', 'Wat Phra That Doi Suthep', 'Ват Пхра Тхат Дой Сутхеп', 'Главный горный храм Чиангмая с золотой ступой, лестницей и видом на город. Это обязательный культурный якорь северного Таиланда.', 'Chiang Mai main mountain temple, with a golden stupa, stairway and city views. It is an essential cultural anchor of northern Thailand.', 'Алтын ступасы, баспалдағы және қала көрінісі бар Чиангмайдың басты тау храмы. Солтүстік Таиландтың міндетті мәдени нысаны.', 18.80490000, 98.92160000, 'https://www.openstreetmap.org/search?query=Wat%20Phra%20That%20Doi%20Suthep', '61000000-0000-4000-8000-000000000038'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Phra_That_Doi_Suthep_-_Chiang_Mai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Phra_That_Doi_Suthep_-_Chiang_Mai.jpg'),
    ('60000000-0000-4000-8000-000000000039'::uuid, 'chiang-mai', 'TEMPLE', 1, 'HOURS', 4.6, ARRAY['thailand', 'chiang-mai', 'wat-chedi-luang', 'temple', 'old-city', 'history']::text[], 'Храм Ват Чеди Луанг', 'Wat Chedi Luang', 'Ват Чеди Луанг', 'Исторический храм в старом городе Чиангмая с массивной древней чеди. Хорош для пеших маршрутов по храмам, рынкам и стенам старого города.', 'A historic temple in Chiang Mai Old City with a massive ancient chedi. It fits walking routes around temples, markets and old city walls.', 'Чиангмай ескі қаласындағы үлкен көне чедиі бар тарихи храм. Храмдар, базарлар және ескі қала қабырғалары бойынша жаяу маршруттарға сай.', 18.78690000, 98.98650000, 'https://www.openstreetmap.org/search?query=Wat%20Chedi%20Luang%20Chiang%20Mai', '61000000-0000-4000-8000-000000000039'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Chedi_Luang_Chiang_Mai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Chedi_Luang_Chiang_Mai.jpg'),
    ('60000000-0000-4000-8000-000000000040'::uuid, 'chiang-mai', 'MUSEUM', 1, 'HOURS', 4.4, ARRAY['thailand', 'chiang-mai', 'city-arts-cultural-centre', 'museum', 'history', 'indoor']::text[], 'Центр искусств и культуры Чиангмая', 'Chiang Mai City Arts & Cultural Centre', 'Чиангмай өнер және мәдениет орталығы', 'Музей в старом городе о местной истории, культуре Ланна и городской идентичности. Хорошая indoor-точка перед храмами и рынками.', 'An Old City museum about local history, Lanna culture and city identity. It is a useful indoor stop before temples and markets.', 'Ескі қаладағы жергілікті тарих, Ланна мәдениеті және қала бірегейлігі туралы музей. Храмдар мен базарлар алдындағы indoor аялдама.', 18.79040000, 98.98790000, 'https://www.openstreetmap.org/search?query=Chiang%20Mai%20City%20Arts%20Cultural%20Centre', '61000000-0000-4000-8000-000000000040'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chiang_Mai_City_Arts_and_Cultural_Centre.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Chiang_Mai_City_Arts_and_Cultural_Centre.jpg'),
    ('60000000-0000-4000-8000-000000000041'::uuid, 'chiang-mai', 'PARK', 8, 'HOURS', 4.7, ARRAY['thailand', 'chiang-mai', 'doi-inthanon', 'national-park', 'mountain', 'waterfalls']::text[], 'Национальный парк Дой Интханон', 'Doi Inthanon National Park', 'Дой Интханон ұлттық паркі', 'Горный национальный парк с самой высокой точкой Таиланда, водопадами, пагодами и прохладным климатом. Лучше как полноценная дневная поездка из Чиангмая.', 'A mountain national park with Thailand highest point, waterfalls, pagodas and cooler climate. It works best as a full day trip from Chiang Mai.', 'Таиландтың ең биік нүктесі, сарқырамалары, пагодалары және салқындау климаты бар тау ұлттық паркі. Чиангмайдан толық күндік сапар ретінде жақсы.', 18.58810000, 98.48670000, 'https://www.openstreetmap.org/search?query=Doi%20Inthanon%20National%20Park', '61000000-0000-4000-8000-000000000041'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Doi_Inthanon_National_Park.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Doi_Inthanon_National_Park.jpg'),
    ('60000000-0000-4000-8000-000000000042'::uuid, 'chiang-mai', 'PARK', 2, 'HOURS', 4.4, ARRAY['thailand', 'chiang-mai', 'royal-park-rajapruek', 'park', 'garden', 'family']::text[], 'Королевский парк Раджапруек', 'Royal Park Rajapruek', 'Раджапруек король паркі', 'Большой садово-парковый комплекс с павильонами, цветочными зонами и семейными прогулками. Хорош как спокойная дневная остановка рядом с городом.', 'A large garden and park complex with pavilions, flower areas and family walks. It is a calm daytime stop near the city.', 'Павильондары, гүл аймақтары және отбасылық серуендері бар үлкен бақ-парк кешені. Қала маңындағы тыныш күндізгі аялдама.', 18.74860000, 98.92360000, 'https://www.openstreetmap.org/search?query=Royal%20Park%20Rajapruek', '61000000-0000-4000-8000-000000000042'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Royal_Park_Rajapruek.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Royal_Park_Rajapruek.jpg'),
    ('60000000-0000-4000-8000-000000000043'::uuid, 'chiang-mai', 'MARKET', 3, 'HOURS', 4.6, ARRAY['thailand', 'chiang-mai', 'sunday-walking-street', 'night-market', 'market', 'crafts']::text[], 'Воскресный рынок Чиангмая', 'Sunday Walking Street', 'Чиангмай жексенбілік базары', 'Популярный воскресный рынок старого города с ремеслами, стрит-фудом и вечерней прогулкой. Это один из главных urban-сценариев Чиангмая.', 'A popular Old City Sunday market with crafts, street food and evening strolling. It is one of Chiang Mai main urban scenarios.', 'Ескі қаладағы қолөнер, стрит-фуд және кешкі серуені бар танымал жексенбілік базар. Чиангмайдың басты қалалық сценарийлерінің бірі.', 18.78880000, 98.98690000, 'https://www.openstreetmap.org/search?query=Sunday%20Walking%20Street%20Chiang%20Mai', '61000000-0000-4000-8000-000000000043'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chiang_Mai_Sunday_Walking_Street.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Chiang_Mai_Sunday_Walking_Street.jpg'),
    ('60000000-0000-4000-8000-000000000044'::uuid, 'chiang-mai', 'MARKET', 2, 'HOURS', 4.4, ARRAY['thailand', 'chiang-mai', 'warorot-market', 'market', 'food', 'local']::text[], 'Рынок Варорот', 'Warorot Market', 'Варорот базары', 'Классический городской рынок Чиангмая с едой, специями, текстилем и повседневной локальной жизнью. Полезен для гастро-маршрутов и практичных покупок.', 'A classic Chiang Mai city market with food, spices, textiles and everyday local life. It is useful for food routes and practical shopping.', 'Тағам, дәмдеуіш, тоқыма және күнделікті жергілікті өмірі бар Чиангмайдың классикалық қалалық базары. Гастро маршруттар мен практикалық саудаға пайдалы.', 18.78830000, 99.00080000, 'https://www.openstreetmap.org/search?query=Warorot%20Market%20Chiang%20Mai', '61000000-0000-4000-8000-000000000044'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Warorot_Market_Chiang_Mai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Warorot_Market_Chiang_Mai.jpg'),

    ('60000000-0000-4000-8000-000000000045'::uuid, 'chiang-rai', 'TEMPLE', 2, 'HOURS', 4.8, ARRAY['thailand', 'chiang-rai', 'wat-rong-khun', 'white-temple', 'temple', 'art']::text[], 'Белый храм Ват Ронг Кхун', 'Wat Rong Khun', 'Ват Ронг Кхун ақ храмы', 'Современный белый храмовый комплекс с яркой художественной символикой. Это главный туристический якорь Чианграя и сильная фото-точка.', 'A modern white temple complex with vivid artistic symbolism. It is Chiang Rai main visitor anchor and a strong photo stop.', 'Жарқын көркем символикасы бар заманауи ақ храм кешені. Чианграйдың басты туристік нысаны және әсерлі фото нүктесі.', 19.82420000, 99.76310000, 'https://www.openstreetmap.org/search?query=Wat%20Rong%20Khun%20Chiang%20Rai', '61000000-0000-4000-8000-000000000045'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Rong_Khun_-_Chiang_Rai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Rong_Khun_-_Chiang_Rai.jpg'),
    ('60000000-0000-4000-8000-000000000046'::uuid, 'chiang-rai', 'TEMPLE', 1, 'HOURS', 4.7, ARRAY['thailand', 'chiang-rai', 'blue-temple', 'temple', 'art', 'culture']::text[], 'Синий храм Ват Ронг Суа Тен', 'Wat Rong Suea Ten', 'Ват Ронг Суа Тен көк храмы', 'Яркий синий храм с современным декором и выразительными интерьерами. Хорош как компактная культурная остановка в Чианграе.', 'A vivid blue temple with modern decor and expressive interiors. It is a compact cultural stop in Chiang Rai.', 'Заманауи декоры және әсерлі интерьерлері бар көк храм. Чианграйдағы ықшам мәдени аялдама.', 19.92720000, 99.84610000, 'https://www.openstreetmap.org/search?query=Wat%20Rong%20Suea%20Ten', '61000000-0000-4000-8000-000000000046'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat_Rong_Suea_Ten_Chiang_Rai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Rong_Suea_Ten_Chiang_Rai.jpg'),
    ('60000000-0000-4000-8000-000000000047'::uuid, 'chiang-rai', 'MUSEUM', 2, 'HOURS', 4.6, ARRAY['thailand', 'chiang-rai', 'baan-dam', 'black-house', 'museum', 'art']::text[], 'Музей Баан Дам', 'Baan Dam Museum', 'Баан Дам музейі', 'Арт-комплекс Черный дом с деревянными павильонами, коллекциями и необычной атмосферой. Добавляет Чианграю современный художественный слой.', 'The Black House art complex with timber pavilions, collections and unusual atmosphere. It adds a contemporary art layer to Chiang Rai.', 'Ағаш павильондары, коллекциялары және ерекше атмосферасы бар Қара үй арт-кешені. Чианграйға заманауи өнер қабатын қосады.', 19.99210000, 99.86080000, 'https://www.openstreetmap.org/search?query=Baan%20Dam%20Museum', '61000000-0000-4000-8000-000000000047'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baan_Dam_Museum_Chiang_Rai.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Baan_Dam_Museum_Chiang_Rai.jpg'),
    ('60000000-0000-4000-8000-000000000048'::uuid, 'chiang-rai', 'OTHER', 3, 'HOURS', 4.4, ARRAY['thailand', 'chiang-rai', 'golden-triangle', 'mekong', 'border', 'viewpoint']::text[], 'Золотой треугольник', 'Golden Triangle', 'Алтын үшбұрыш', 'Пограничная зона у Меконга, где сходятся Таиланд, Лаос и Мьянма. Подходит для маршрутов о географии, истории региона и видах на реку.', 'A Mekong border area where Thailand, Laos and Myanmar meet. It suits routes about geography, regional history and river views.', 'Таиланд, Лаос және Мьянма түйісетін Меконг бойындағы шекара аймағы. География, аймақ тарихы және өзен көріністері туралы маршруттарға сай.', 20.35220000, 100.08170000, 'https://www.openstreetmap.org/search?query=Golden%20Triangle%20Thailand', '61000000-0000-4000-8000-000000000048'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Golden_Triangle_Thailand.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Golden_Triangle_Thailand.jpg'),
    ('60000000-0000-4000-8000-000000000049'::uuid, 'chiang-rai', 'MARKET', 2, 'HOURS', 4.4, ARRAY['thailand', 'chiang-rai', 'night-bazaar', 'night-market', 'market', 'food']::text[], 'Ночной базар Чианграя', 'Chiang Rai Night Bazaar', 'Чианграй түнгі базары', 'Вечерний рынок в центре Чианграя с едой, сувенирами, сценой и спокойным городским ритмом. Хорош для завершения дня после храмов.', 'A central Chiang Rai evening market with food, souvenirs, a stage and an easy city rhythm. It works well after temple routes.', 'Тағамы, сувенирлері, сахнасы және тыныш қала ырғағы бар Чианграй орталығындағы кешкі базар. Храм маршрутынан кейін жақсы.', 19.90560000, 99.83280000, 'https://www.openstreetmap.org/search?query=Chiang%20Rai%20Night%20Bazaar', '61000000-0000-4000-8000-000000000049'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chiang_Rai_Night_Bazaar.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Chiang_Rai_Night_Bazaar.jpg'),
    ('60000000-0000-4000-8000-000000000050'::uuid, 'pai', 'NATURE', 2, 'HOURS', 4.6, ARRAY['thailand', 'pai', 'pai-canyon', 'canyon', 'sunset', 'nature']::text[], 'Каньон Пай', 'Pai Canyon', 'Пай каньоны', 'Природная смотровая зона рядом с Паем, популярная на закате и для коротких прогулок по гребням. Требует аккуратности на узких участках.', 'A natural viewpoint area near Pai, popular at sunset and for short ridge walks. Narrow sections require care.', 'Пай маңындағы күн батуы мен қысқа жота серуендеріне танымал табиғи смотровая аймақ. Тар жерлерде сақтық қажет.', 19.33180000, 98.45200000, 'https://www.openstreetmap.org/search?query=Pai%20Canyon', '61000000-0000-4000-8000-000000000050'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pai_canyon_1.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Pai_canyon_1.jpg'),

    ('60000000-0000-4000-8000-000000000051'::uuid, 'koh-samui', 'TEMPLE', 1, 'HOURS', 4.5, ARRAY['thailand', 'koh-samui', 'big-buddha-temple', 'temple', 'island', 'view']::text[], 'Храм Большого Будды на Самуи', 'Big Buddha Temple', 'Самуи Үлкен Будда храмы', 'Один из самых узнаваемых храмов Самуи с большой статуей Будды у моря и легким доступом из туристических районов. Хорош как короткая культурная остановка.', 'One of Koh Samui most recognizable temples, with a large seaside Buddha statue and easy access from resort areas. It is a good short cultural stop.', 'Теңіз жанындағы үлкен Будда мүсіні және туристік аймақтардан оңай жетуі бар Самуидің ең танымал храмдарының бірі. Қысқа мәдени аялдамаға жақсы.', 9.57070000, 100.06020000, 'https://www.openstreetmap.org/search?query=Big%20Buddha%20Temple%20Koh%20Samui', '61000000-0000-4000-8000-000000000051'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koh%20Samui%2C%20Big%20Buddha%2001.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Koh_Samui,_Big_Buddha_01.jpg'),
    ('60000000-0000-4000-8000-000000000052'::uuid, 'koh-samui', 'TEMPLE', 1, 'HOURS', 4.5, ARRAY['thailand', 'koh-samui', 'wat-plai-laem', 'temple', 'island', 'culture']::text[], 'Храм Ват Плай Лаем', 'Wat Plai Laem', 'Ват Плай Лаем ғибадатханасы', 'Яркий храмовый комплекс Самуи с озером, статуями и удобной прогулочной зоной. Хорошо дополняет храм Большого Будды в коротком маршруте.', 'A vivid Koh Samui temple complex with a lake, statues and easy walking space. It pairs well with the Big Buddha Temple in a short route.', 'Көлі, мүсіндері және ыңғайлы серуен аймағы бар Самуидің жарқын храм кешені. Қысқа маршрутта Үлкен Будда храмын жақсы толықтырады.', 9.57170000, 100.06270000, 'https://www.openstreetmap.org/search?query=Wat%20Plai%20Laem', '61000000-0000-4000-8000-000000000052'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wat%20Plai%20Laem%2003.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Wat_Plai_Laem_03.jpg'),
    ('60000000-0000-4000-8000-000000000053'::uuid, 'koh-samui', 'BEACH', 3, 'HOURS', 4.4, ARRAY['thailand', 'koh-samui', 'chaweng-beach', 'beach', 'resort', 'nightlife']::text[], 'Пляж Чавенг', 'Chaweng Beach', 'Чавенг жағажайы', 'Самый известный пляж Самуи с длинной береговой линией, отелями, кафе и вечерней инфраструктурой. Подходит туристам, которым нужен активный островной центр.', 'Koh Samui best-known beach, with a long shoreline, hotels, cafes and evening infrastructure. It suits travelers who want an active island center.', 'Ұзын жағалауы, қонақүйлері, кафелері және кешкі инфрақұрылымы бар Самуидің ең танымал жағажайы. Белсенді арал орталығын қалайтын туристерге сай.', 9.53020000, 100.06480000, 'https://www.openstreetmap.org/search?query=Chaweng%20Beach%20Koh%20Samui', '61000000-0000-4000-8000-000000000053'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chaweng_Beach_Koh_Samui.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Chaweng_Beach_Koh_Samui.jpg'),
    ('60000000-0000-4000-8000-000000000054'::uuid, 'koh-tao', 'BEACH', 5, 'HOURS', 4.8, ARRAY['thailand', 'koh-tao', 'koh-nang-yuan', 'beach', 'snorkeling', 'viewpoint']::text[], 'Остров Ко Нанг Юан', 'Koh Nang Yuan', 'Ко Нанг Юан аралы', 'Три маленьких острова рядом с Ко Тао, соединенные песчаной косой, со снорклингом и известной смотровой площадкой. Это ключевой морской day trip региона.', 'Three small islands near Koh Tao, linked by a sandbar, with snorkeling and a famous viewpoint. It is a key sea day trip in the region.', 'Ко Тао маңындағы құм мойнағымен қосылған, снорклинг және әйгілі смотроваясы бар үш шағын арал. Аймақтағы негізгі теңіз day trip.', 10.11850000, 99.81240000, 'https://www.openstreetmap.org/search?query=Koh%20Nang%20Yuan', '61000000-0000-4000-8000-000000000054'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Nang%20Yuan%20from%20Viewpoint.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Ko_Nang_Yuan_from_Viewpoint.jpg'),
    ('60000000-0000-4000-8000-000000000055'::uuid, 'hua-hin', 'MARKET', 2, 'HOURS', 4.4, ARRAY['thailand', 'hua-hin', 'night-market', 'market', 'seafood', 'shopping']::text[], 'Ночной рынок Хуахина', 'Hua Hin Night Market', 'Хуахин түнгі базары', 'Центральный вечерний рынок Хуахина с морепродуктами, уличной едой, сувенирами и спокойным курортным ритмом. Хорош для ежедневного вечернего сценария.', 'A central Hua Hin evening market with seafood, street food, souvenirs and a relaxed resort rhythm. It works as an everyday evening scenario.', 'Теңіз өнімдері, стрит-фуд, сувенирлер және тыныш курорттық ырғағы бар Хуахиннің орталық кешкі базары. Күнделікті кешкі сценарийге жақсы.', 12.57170000, 99.95540000, 'https://www.openstreetmap.org/search?query=Hua%20Hin%20Night%20Market', '61000000-0000-4000-8000-000000000055'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hua_Hin_Night_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Hua_Hin_Night_Market.jpg'),
    ('60000000-0000-4000-8000-000000000056'::uuid, 'koh-phangan', 'MARKET', 2, 'HOURS', 4.3, ARRAY['thailand', 'koh-phangan', 'thong-sala-night-market', 'night-market', 'market', 'food']::text[], 'Ночной рынок Тонг Сала', 'Thong Sala Night Market', 'Тонг Сала түнгі базары', 'Популярный островной вечерний рынок на Пангане с тайской едой, фруктами и непринужденной атмосферой. Хорош для мягкого вечернего сценария без клубного формата.', 'A popular Koh Phangan evening market with Thai food, fruit and an easy island atmosphere. It is useful for a relaxed evening scenario outside club formats.', 'Тай тағамы, жемісі және жеңіл арал атмосферасы бар Панганның танымал кешкі базары. Клубтық форматсыз тыныш кешкі сценарийге пайдалы.', 9.71180000, 99.98870000, 'https://www.openstreetmap.org/search?query=Thong%20Sala%20Night%20Market%20Koh%20Phangan', '61000000-0000-4000-8000-000000000056'::uuid, 'https://commons.wikimedia.org/wiki/Special:FilePath/Thong_Sala_Night_Market.jpg?width=1400', 'https://commons.wikimedia.org/wiki/File:Thong_Sala_Night_Market.jpg');

INSERT INTO attractions (
    id,
    author_user_id,
    default_locale,
    country_code,
    city_id,
    category,
    price_amount,
    price_currency,
    duration_value,
    duration_unit,
    rating,
    review_count,
    spots,
    source,
    status,
    tags,
    created_at,
    updated_at
)
SELECT
    id,
    '21c40900-2090-43ca-b7f8-4bb962b2d275'::uuid,
    'ru',
    'TH',
    city_id,
    category,
    NULL::numeric,
    NULL::varchar(3),
    duration_value,
    duration_unit,
    rating,
    0,
    NULL::int,
    'IMPORT',
    'PUBLISHED',
    tags,
    NOW(),
    NOW()
FROM seed_thailand_priority_attractions
ON CONFLICT (id) DO UPDATE
SET
    default_locale = EXCLUDED.default_locale,
    country_code = EXCLUDED.country_code,
    city_id = EXCLUDED.city_id,
    category = EXCLUDED.category,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    spots = EXCLUDED.spots,
    source = EXCLUDED.source,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    updated_at = NOW(),
    deleted_at = NULL
WHERE attractions.source = 'IMPORT';

INSERT INTO attraction_translations (
    attraction_id,
    locale,
    title,
    description,
    created_at,
    updated_at
)
SELECT
    seed.id,
    locale_rows.locale,
    CASE locale_rows.locale
        WHEN 'ru' THEN seed.title_ru
        WHEN 'kk' THEN seed.title_kk
        ELSE seed.title_en
    END,
    CASE locale_rows.locale
        WHEN 'ru' THEN seed.description_ru
        WHEN 'kk' THEN seed.description_kk
        ELSE seed.description_en
    END,
    NOW(),
    NOW()
FROM seed_thailand_priority_attractions seed
CROSS JOIN (VALUES ('ru'), ('en'), ('kk')) AS locale_rows(locale)
ON CONFLICT (attraction_id, locale) DO UPDATE
SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = NOW();

WITH seed_locations (
    id,
    latitude,
    longitude,
    location_source_url
) AS (
    SELECT
        id,
        latitude,
        longitude,
        location_source_url
    FROM seed_thailand_priority_attractions
)
UPDATE attractions
SET
    latitude = seed_locations.latitude,
    longitude = seed_locations.longitude,
    location_source_url = seed_locations.location_source_url,
    updated_at = NOW()
FROM seed_locations
WHERE attractions.id = seed_locations.id
    AND attractions.source = 'IMPORT';

INSERT INTO attraction_media (
    id,
    attraction_id,
    file_id,
    external_url,
    source_url,
    credit,
    license,
    media_type,
    position,
    created_at
)
SELECT
    media_id,
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    media_url,
    source_url,
    'Wikimedia Commons contributors',
    'See Wikimedia Commons source page',
    'PHOTO',
    0,
    NOW()
FROM seed_thailand_priority_attractions
WHERE EXISTS (
    SELECT 1
    FROM attractions a
    WHERE a.id = seed_thailand_priority_attractions.id
)
ON CONFLICT (id) DO UPDATE
SET
    attraction_id = EXCLUDED.attraction_id,
    file_id = EXCLUDED.file_id,
    external_url = EXCLUDED.external_url,
    source_url = EXCLUDED.source_url,
    credit = EXCLUDED.credit,
    license = EXCLUDED.license,
    media_type = EXCLUDED.media_type,
    position = EXCLUDED.position;

INSERT INTO attraction_city_links (id, attraction_id, kind, country_code, city_id, position, created_at)
SELECT gen_random_uuid(), id, kind, 'TH', city_id, 0, NOW()
FROM seed_thailand_priority_attractions
CROSS JOIN (VALUES ('ACCESS'), ('DEPARTURE')) AS link(kind)
ON CONFLICT (attraction_id, kind, city_id) DO NOTHING;

DROP TABLE IF EXISTS seed_thailand_priority_attractions;
