#!/usr/bin/env bash
set -euo pipefail

BASE="${BASE:-http://127.0.0.1:8080/api/v1}"
TMP_DIR="${TMP_DIR:-/private/tmp/inflap_activity_suite_$$}"
mkdir -p "$TMP_DIR"
RESULTS="$TMP_DIR/results.tsv"
: > "$RESULTS"

psql_activity() {
  docker exec activity-postgres psql -q -U activity_service -d activity_service_db -c "$1" >/dev/null 2>&1 || true
}

reset_qa_rate_limit_window() {
  psql_activity "update activities set created_at = now() - interval '48 hours' where title like 'QA %' and created_at > now() - interval '24 hours';"
}

cleanup_previous_qa_state() {
  psql_activity "update activity_participants p set status = 'CANCELLED', cancelled_at = coalesce(cancelled_at, now()), updated_at = now() from activities a where p.activity_id = a.id and a.title like 'QA %' and p.status in ('INVITED','REQUESTED','APPROVED','WAITLISTED','PENDING_PAYMENT','CONFIRMED','CHECKED_IN');"
  psql_activity "update activities set status = 'CANCELLED', cancellation_reason = coalesce(cancellation_reason, 'QA cleanup before activity flow suite'), cancelled_at = coalesce(cancelled_at, now()), updated_at = now(), created_at = now() - interval '48 hours' where title like 'QA %';"
  reset_qa_rate_limit_window
}

req() {
  local method="$1"
  local path="$2"
  local token="${3:-}"
  local data="${4:-}"
  local body="$TMP_DIR/body.json"
  local code
  : > "$body"

  if [[ -n "$data" ]]; then
    if [[ -n "$token" ]]; then
      code=$(curl -s -o "$body" -w "%{http_code}" -X "$method" "$BASE$path" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $token" \
        -d "$data" || printf "000")
    else
      code=$(curl -s -o "$body" -w "%{http_code}" -X "$method" "$BASE$path" \
        -H "Content-Type: application/json" \
        -d "$data" || printf "000")
    fi
  else
    if [[ -n "$token" ]]; then
      code=$(curl -s -o "$body" -w "%{http_code}" -X "$method" "$BASE$path" \
        -H "Authorization: Bearer $token" || printf "000")
    else
      code=$(curl -s -o "$body" -w "%{http_code}" -X "$method" "$BASE$path" || printf "000")
    fi
  fi

  printf "%s\n" "$code" > "$TMP_DIR/last_code"
  cp "$body" "$TMP_DIR/last_body.json"
}

body_excerpt() {
  tr "\n" " " < "$TMP_DIR/last_body.json" | cut -c1-220
}

record() {
  local id="$1"
  local result="$2"
  local actual="$3"
  printf "%s\t%s\t%s\n" "$id" "$result" "$actual" >> "$RESULTS"
}

expect_code() {
  local id="$1"
  local expected="$2"
  local actual_code
  actual_code=$(cat "$TMP_DIR/last_code")
  if [[ "$actual_code" == "$expected" ]]; then
    record "$id" "PASS" "HTTP $actual_code"
  else
    record "$id" "FAIL" "Expected HTTP $expected, got $actual_code; body=$(body_excerpt)"
  fi
}

expect_code_any() {
  local id="$1"
  local expected_csv="$2"
  local actual_code
  actual_code=$(cat "$TMP_DIR/last_code")
  if [[ ",$expected_csv," == *",$actual_code,"* ]]; then
    record "$id" "PASS" "HTTP $actual_code"
  else
    record "$id" "FAIL" "Expected one of [$expected_csv], got $actual_code; body=$(body_excerpt)"
  fi
}

auth() {
  local phone="$1"
  local token
  req POST "/auth/phone/send-code" "" "{\"phone\":\"$phone\"}"
  req POST "/auth/phone/verify" "" "{\"phone\":\"$phone\",\"code\":\"000000\"}"
  token=$(jq -r ".access_token // .accessToken // empty" "$TMP_DIR/last_body.json")
  if [[ -z "$token" ]]; then
    echo "AUTH_FAILED for $phone" >&2
    cat "$TMP_DIR/last_body.json" >&2
    exit 1
  fi
  printf "%s" "$token"
}

uri() {
  jq -nr --arg value "$1" '$value | @uri'
}

activity_payload() {
  local title="$1"
  local start="$2"
  local end="$3"
  local category="${4:-food-drinks}"
  local subcategory="${5:-coffee-meetup}"
  local format="${6:-OFFLINE}"
  local visibility="${7:-PUBLIC}"
  local price_type="${8:-FREE}"
  local max_participants="10"
  local extra="{}"

  if [[ $# -ge 9 ]]; then
    max_participants="$9"
  fi
  if [[ $# -ge 10 ]]; then
    extra="${10}"
  fi

  if ! printf "%s" "$extra" | jq -e . >/dev/null 2>&1; then
    echo "Invalid extra JSON for activity payload: $extra" >&2
    extra="{}"
  fi

  jq -n \
    --arg title "$title" \
    --arg description "Autogenerated QA activity for flow coverage." \
    --arg format "$format" \
    --arg visibility "$visibility" \
    --arg category "$category" \
    --arg subcategory "$subcategory" \
    --arg start "$start" \
    --arg end "$end" \
    --arg priceType "$price_type" \
    --arg country "KZ" \
    --arg city "Алматы" \
    --arg address "QA street 1" \
    --arg map "https://maps.google.com/?q=43.238949,76.889709" \
    --arg maxParticipants "$max_participants" \
    --arg extra "$extra" \
    '{
      title: $title,
      description: $description,
      format: $format,
      visibility: $visibility,
      categorySlug: $category,
      subcategorySlug: $subcategory,
      tags: ["qa", "activity-flow"],
      languageCode: "ru",
      timezone: "Asia/Almaty",
      startAt: $start,
      endAt: $end,
      capacityType: "LIMITED",
      minParticipants: 2,
      maxParticipants: ($maxParticipants | tonumber),
      priceType: $priceType,
      requiresProfileCompletion: false,
      requiresAttendanceConfirmation: false,
      allowsParticipantInvites: false,
      countryCode: $country,
      cityName: $city,
      addressText: $address,
      latitude: 43.238949,
      longitude: 76.889709,
      mapUrl: $map,
      authorCountryCode: $country,
      authorCityName: $city
    } * ($extra | fromjson)'
}

create_activity() {
  local title="$1"
  local start="$2"
  local end="$3"
  local token="$4"
  local category="${5:-food-drinks}"
  local subcategory="${6:-coffee-meetup}"
  local format="${7:-OFFLINE}"
  local visibility="${8:-PUBLIC}"
  local price_type="${9:-FREE}"
  local max_participants="10"
  local extra="{}"
  local payload

  if [[ $# -ge 10 ]]; then
    max_participants="${10}"
  fi
  if [[ $# -ge 11 ]]; then
    extra="${11}"
  fi
  payload=$(activity_payload "$title" "$start" "$end" "$category" "$subcategory" "$format" "$visibility" "$price_type" "$max_participants" "$extra")
  req POST "/me/activities" "$token" "$payload"
  local id
  id=$(jq -r ".id // empty" "$TMP_DIR/last_body.json")
  if [[ -n "$id" ]]; then
    reset_qa_rate_limit_window
  fi
  printf "%s\n" "$id"
}

if [[ "${QA_DB_CLEANUP:-1}" == "1" ]]; then
  cleanup_previous_qa_state
fi

HOST_PHONE="${HOST_PHONE:-+77051698779}"
PARTICIPANT_PHONE="${PARTICIPANT_PHONE:-+77051471066}"

HOST_TOKEN=$(auth "$HOST_PHONE")
PARTICIPANT_TOKEN=$(auth "$PARTICIPANT_PHONE")

START1="2026-06-22T09:00:00Z"
END1="2026-06-22T11:00:00Z"
START2="2026-06-23T09:00:00Z"
END2="2026-06-23T11:00:00Z"
START3="2026-06-24T09:00:00Z"
END3="2026-06-24T11:00:00Z"
START4="2026-06-25T09:00:00Z"
END4="2026-06-25T11:00:00Z"
START5="2026-06-26T09:00:00Z"
END5="2026-06-26T11:00:00Z"

req GET "/activity-categories"
code=$(cat "$TMP_DIR/last_code")
category_count=$(jq ".items | length" "$TMP_DIR/last_body.json" 2>/dev/null || echo 0)
if [[ "$code" == "200" && "$category_count" -gt 0 ]]; then
  record ACT-001 PASS "HTTP 200; categories=$category_count"
else
  record ACT-001 FAIL "HTTP $code; categories=$category_count"
fi

req GET "/activities?limit=5"
expect_code ACT-002 200

req GET "/activities?limit=1&offset=0"
code=$(cat "$TMP_DIR/last_code")
items_count=$(jq ".items | length" "$TMP_DIR/last_body.json" 2>/dev/null || echo 99)
if [[ "$code" == "200" && "$items_count" -le 1 ]]; then
  record ACT-003 PASS "HTTP 200; first page items=$items_count"
else
  record ACT-003 FAIL "HTTP $code; first page items=$items_count"
fi

req GET "/activities?limit=999"
expect_code ACT-008 200

req GET "/activities/not-a-uuid" "$HOST_TOKEN"
expect_code ACT-009 400

missing_id="00000000-0000-4000-8000-000000000001"
req GET "/activities/$missing_id" "$HOST_TOKEN"
expect_code ACT-010 404

free_id=$(create_activity "QA free flow $(date +%s)" "$START1" "$END1" "$HOST_TOKEN")
code=$(cat "$TMP_DIR/last_code")
if [[ "$code" == "201" && -n "$free_id" ]]; then
  record ACT-011 PASS "HTTP 201; id=$free_id"
else
  record ACT-011 FAIL "HTTP $code; body=$(body_excerpt)"
fi

paid_extra='{"priceAmount":5000,"currency":"KZT"}'
paid_id=$(create_activity "QA paid flow $(date +%s)" "$START2" "$END2" "$HOST_TOKEN" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "PAID" "2" "$paid_extra")
code=$(cat "$TMP_DIR/last_code")
if [[ "$code" == "201" && -n "$paid_id" ]]; then
  record ACT-012 PASS "HTTP 201; id=$paid_id"
else
  record ACT-012 FAIL "HTTP $code; body=$(body_excerpt)"
fi

private_extra='{"visibilityPassword":"Secret123!"}'
private_id=$(create_activity "QA private flow $(date +%s)" "$START3" "$END3" "$HOST_TOKEN" "food-drinks" "coffee-meetup" "OFFLINE" "PRIVATE" "FREE" "10" "$private_extra")
code=$(cat "$TMP_DIR/last_code")
if [[ "$code" == "201" && -n "$private_id" ]]; then
  record ACT-013 PASS "HTTP 201; id=$private_id"
else
  record ACT-013 FAIL "HTTP $code; body=$(body_excerpt)"
fi

hybrid_extra='{"meetingUrl":"https://meet.example.com/qa-flow"}'
hybrid_id=$(create_activity "QA hybrid flow $(date +%s)" "$START4" "$END4" "$HOST_TOKEN" "food-drinks" "coffee-meetup" "HYBRID" "PUBLIC" "FREE" "10" "$hybrid_extra")
code=$(cat "$TMP_DIR/last_code")
if [[ "$code" == "201" && -n "$hybrid_id" ]]; then
  record ACT-020 PASS "HTTP 201; id=$hybrid_id"
else
  record ACT-020 FAIL "HTTP $code; body=$(body_excerpt)"
fi

req GET "/activities?q=$(uri "QA free flow")"
expect_code ACT-004 200

req GET "/activities?categorySlug=food-drinks"
expect_code ACT-005 200

req GET "/activities?cityName=$(uri "Алматы")"
expect_code ACT-006 200

req GET "/activities?status=ENROLLMENT_OPEN"
expect_code ACT-007 200

req GET "/activities/$free_id" "$HOST_TOKEN"
expect_code ACT-038 200

req GET "/activities/$free_id/participants"
code=$(cat "$TMP_DIR/last_code")
participants_count=$(jq ".items | length" "$TMP_DIR/last_body.json" 2>/dev/null || echo 0)
if [[ "$code" == "200" && "$participants_count" -ge 1 ]]; then
  record ACT-039 PASS "HTTP 200; participants=$participants_count"
else
  record ACT-039 FAIL "HTTP $code; participants=$participants_count"
fi

payload=$(activity_payload "QA private no password" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PRIVATE" "FREE" "10" "{}")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-014 400

payload=$(activity_payload "QA private non ascii" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PRIVATE" "FREE" "10" '{"visibilityPassword":"пароль"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-015 400

create_activity "QA invalid category" "$START4" "$END4" "$HOST_TOKEN" "unknown-category" "coffee-meetup" >/dev/null
expect_code ACT-016 400

create_activity "QA invalid subcat" "$START4" "$END4" "$HOST_TOKEN" "food-drinks" "karaoke" >/dev/null
expect_code ACT-017 400

payload=$(activity_payload "QA online with offline" "$START4" "$END4" "food-drinks" "coffee-meetup" "ONLINE" "PUBLIC" "FREE" "10" "{}")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-018 400

payload=$(activity_payload "QA offline with meeting" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"meetingUrl":"https://meet.example.com/bad"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-019 400

payload=$(activity_payload "QA lat only" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"longitude":null}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-021 400

payload=$(activity_payload "QA invalid coords" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"latitude":999}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-022 400

soon_start=$(date -u -v+10M +"%Y-%m-%dT%H:%M:%SZ")
soon_end=$(date -u -v+130M +"%Y-%m-%dT%H:%M:%SZ")
payload=$(activity_payload "QA too soon" "$soon_start" "$soon_end" "food-drinks" "coffee-meetup")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-023 400

payload=$(activity_payload "QA too far" "2027-06-01T09:00:00Z" "2027-06-01T11:00:00Z" "food-drinks" "coffee-meetup")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-024 400

payload=$(activity_payload "QA bad time" "$END4" "$START4" "food-drinks" "coffee-meetup")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-025 400

payload=$(activity_payload "QA too long" "$START4" "2026-07-28T09:00:00Z" "food-drinks" "coffee-meetup")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-026 400

payload=$(activity_payload "QA min one" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"minParticipants":1}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-027 400

payload=$(activity_payload "QA max over" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "101" "{}")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-028 400

payload=$(activity_payload "QA max below min" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "3" '{"minParticipants":5}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-029 400

payload=$(activity_payload "QA paid no amount" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "PAID" "10" '{"currency":"KZT"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-030 400

payload=$(activity_payload "QA paid negative" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "PAID" "10" '{"priceAmount":-1,"currency":"KZT"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-031 400

payload=$(activity_payload "QA deposit" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "DEPOSIT" "10" '{"priceAmount":1000,"currency":"KZT"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-032 400

payload=$(activity_payload "QA bad currency" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "PAID" "10" '{"priceAmount":1000,"currency":"XXX"}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-033 400

long_title=$(printf "A%.0s" {1..260})
payload=$(activity_payload "$long_title" "$START4" "$END4" "food-drinks" "coffee-meetup")
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-034 400

payload=$(activity_payload "" "$START4" "$END4" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"description":""}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code ACT-035 400

payload=$(activity_payload "QA weird tags" "$START5" "$END5" "food-drinks" "coffee-meetup" "OFFLINE" "PUBLIC" "FREE" "10" '{"tags":["","Food","food"]}')
req POST "/me/activities" "$HOST_TOKEN" "$payload"
expect_code_any ACT-036 "201,400"

payload=$(activity_payload "QA unauth" "$START5" "$END5")
req POST "/me/activities" "" "$payload"
expect_code ACT-037 401

req POST "/me/activities/$free_id/join" "$PARTICIPANT_TOKEN"
expect_code_any ACT-040 "200,201"

req POST "/me/activities/$paid_id/join" "$PARTICIPANT_TOKEN"
code=$(cat "$TMP_DIR/last_code")
participant_status=$(jq -r ".status // empty" "$TMP_DIR/last_body.json" 2>/dev/null)
payment_tx=$(jq -r ".paymentTransactionId // empty" "$TMP_DIR/last_body.json" 2>/dev/null)
if [[ ",200,201," == *",$code,"* && "$participant_status" == "CONFIRMED" && -n "$payment_tx" ]]; then
  record ACT-041 PASS "HTTP $code; status=$participant_status; tx=$payment_tx"
else
  record ACT-041 FAIL "HTTP $code; status=$participant_status; tx=$payment_tx; body=$(body_excerpt)"
fi

req GET "/activities/$paid_id" "$HOST_TOKEN"
code=$(cat "$TMP_DIR/last_code")
activity_status=$(jq -r ".status // empty" "$TMP_DIR/last_body.json" 2>/dev/null)
if [[ "$code" == "200" && "$activity_status" == "FULL" ]]; then
  record ACT-042 PASS "HTTP 200; status=FULL"
else
  record ACT-042 FAIL "HTTP $code; status=$activity_status"
fi

req POST "/me/activities/$free_id/join" "$PARTICIPANT_TOKEN"
expect_code_any ACT-043 "409"

req POST "/me/activities/$free_id/join" "$HOST_TOKEN"
expect_code_any ACT-044 "409"

req POST "/me/activities/$private_id/join" "$PARTICIPANT_TOKEN"
expect_code_any ACT-045 "400,403"

req POST "/me/activities/$private_id/join" "$PARTICIPANT_TOKEN" '{"password":"Wrong123!"}'
expect_code_any ACT-046 "400,403"

req POST "/me/activities/$private_id/join" "$PARTICIPANT_TOKEN" '{"password":"Secret123!"}'
expect_code_any ACT-047 "200,201,409"

req POST "/me/activities/$paid_id/join" "$HOST_TOKEN"
expect_code_any ACT-048 "409"

overlap_id=$(create_activity "QA overlap flow $(date +%s)" "$START1" "$END1" "$HOST_TOKEN" "culture-art" "museum-gallery")
req POST "/me/activities/$overlap_id/join" "$PARTICIPANT_TOKEN"
expect_code_any ACT-049 "409"

leave_id=$(create_activity "QA leave flow $(date +%s)" "$START5" "$END5" "$HOST_TOKEN" "sports-wellness" "running")
req POST "/me/activities/$leave_id/join" "$PARTICIPANT_TOKEN"
req POST "/me/activities/$leave_id/leave" "$PARTICIPANT_TOKEN" '{"reason":"QA leave"}'
expect_code_any ACT-050 "200,204"

req POST "/me/activities/$leave_id/leave" "$PARTICIPANT_TOKEN" '{"reason":"QA leave again"}'
expect_code_any ACT-051 "409"

not_joined_id=$(create_activity "QA not joined leave $(date +%s)" "$START5" "$END5" "$HOST_TOKEN" "games-entertainment" "board-games")
req POST "/me/activities/$not_joined_id/leave" "$PARTICIPANT_TOKEN" '{"reason":"not joined"}'
expect_code_any ACT-052 "404"

req PATCH "/me/activities/$free_id" "$PARTICIPANT_TOKEN" '{"title":"Participant should not edit"}'
expect_code_any ACT-055 "403"

update_id=$(create_activity "QA update flow $(date +%s)" "$START5" "$END5" "$HOST_TOKEN" "family-kids" "family-walk")
req PATCH "/me/activities/$update_id" "$HOST_TOKEN" '{"title":"QA updated title"}'
expect_code_any ACT-056 "200"

req PATCH "/me/activities/$free_id" "$HOST_TOKEN" '{"priceType":"PAID","priceAmount":1000,"currency":"KZT"}'
expect_code_any ACT-057 "400,403,409"

req POST "/me/activities/$free_id/publish" "$HOST_TOKEN"
expect_code_any ACT-059 "409"

duplicate_payload='{"startAt":"2026-06-27T09:00:00Z","endAt":"2026-06-27T11:00:00Z","registrationDeadline":"2026-06-27T08:00:00Z"}'
req POST "/me/activities/$update_id/duplicate" "$HOST_TOKEN" "$duplicate_payload"
expect_code_any ACT-060 "200,201"

req POST "/me/activities/$update_id/duplicate" "$PARTICIPANT_TOKEN" "$duplicate_payload"
expect_code_any ACT-061 "403"

cancel_id=$(create_activity "QA cancel flow $(date +%s)" "$START5" "$END5" "$HOST_TOKEN" "other" "community-event")
req POST "/me/activities/$cancel_id/cancel" "$HOST_TOKEN" '{}'
expect_code ACT-062 400

req POST "/me/activities/$cancel_id/cancel" "$HOST_TOKEN" '{"reason":"QA cancellation reason"}'
expect_code ACT-063 200

req POST "/me/activities/$cancel_id/cancel" "$HOST_TOKEN" '{"reason":"QA cancellation again"}'
expect_code_any ACT-064 "409"

req POST "/me/activities/$update_id/complete" "$HOST_TOKEN" '{"reason":"QA complete too early"}'
expect_code_any ACT-065 "409"

req POST "/me/activities/$update_id/complete" "$HOST_TOKEN" '{}'
expect_code_any ACT-066 "400,409"

req POST "/me/activities/$update_id/extend" "$HOST_TOKEN" '{"minutes":30}'
expect_code_any ACT-067 "400,409"

req POST "/me/activities/$update_id/extend" "$HOST_TOKEN" '{"minutes":15}'
expect_code_any ACT-068 "400,409"

req POST "/me/activities/$update_id/participants/invite-friends" "$PARTICIPANT_TOKEN" '{"userIds":["00000000-0000-4000-8000-000000000002"]}'
expect_code_any ACT-069 "403,404,409"

req GET "/me/activities/$update_id/attendance-qr" "$HOST_TOKEN"
expect_code_any ACT-072 "200,403,409"

req GET "/me/activities/$update_id/attendance-qr" "$PARTICIPANT_TOKEN"
expect_code_any ACT-073 "403,404"

req POST "/me/attendance/sync" "$PARTICIPANT_TOKEN" '{"items":[]}'
expect_code ACT-074 400

req POST "/me/attendance/sync" "$PARTICIPANT_TOKEN" '{"items":[{"scanId":"00000000-0000-4000-8000-000000000003","qrToken":"fake-token","installationId":"qa-installation","scannedAtDevice":"2026-06-03T04:00:00Z"}]}'
expect_code ACT-075 200

cat "$RESULTS"
