-- UUID values are generated by saved-service; this migration requires no extensions.
CREATE TABLE saved_content_projections (
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    source_service TEXT NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 0,
    projection_revision BIGINT NOT NULL DEFAULT 0,
    visibility_revision BIGINT NOT NULL DEFAULT 0,
    visibility_status TEXT NOT NULL DEFAULT 'UNKNOWN',
    visibility_validated_at TIMESTAMPTZ,
    source_default_locale TEXT,
    title_en TEXT,
    title_ru TEXT,
    title_kk TEXT,
    subtitle_en TEXT,
    subtitle_ru TEXT,
    subtitle_kk TEXT,
    city_en TEXT,
    city_ru TEXT,
    city_kk TEXT,
    country_en TEXT,
    country_ru TEXT,
    country_kk TEXT,
    display_location_en TEXT,
    display_location_ru TEXT,
    display_location_kk TEXT,
    search_document_version BIGINT NOT NULL DEFAULT 0,
    normalized_search_document_en TEXT,
    normalized_search_document_ru TEXT,
    normalized_search_document_kk TEXT,
    media_reference TEXT,
    media_reference_revision BIGINT,
    media_valid_until TIMESTAMPTZ,
    rating_value NUMERIC(7, 4),
    rating_count BIGINT,
    rating_scale_max NUMERIC(7, 4),
    price_summary JSONB,
    availability_summary JSONB,
    summary_as_of TIMESTAMPTZ,
    summary_valid_until TIMESTAMPTZ,
    canonical_detail_route TEXT,
    shell_expires_at TIMESTAMPTZ,
    ever_referenced BOOLEAN NOT NULL DEFAULT FALSE,
    gc_candidate_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT saved_content_projections_pkey
        PRIMARY KEY (entity_type, entity_id),
    CONSTRAINT saved_content_projections_entity_type_check
        CHECK (entity_type IN ('ATTRACTION', 'ACTIVITY', 'EXCURSION', 'GUIDE')),
    CONSTRAINT saved_content_projections_entity_id_check
        CHECK (
            entity_id <> ''
            AND octet_length(entity_id) <= 512
            AND entity_id !~ '^[[:space:]]'
            AND entity_id !~ '[[:space:]]$'
        ),
    CONSTRAINT saved_content_projections_source_service_check
        CHECK (
            octet_length(source_service) BETWEEN 1 AND 64
            AND source_service ~ '^[a-z][a-z0-9-]*$'
        ),
    CONSTRAINT saved_content_projections_revisions_check
        CHECK (
            source_revision >= 0
            AND projection_revision >= 0
            AND visibility_revision >= 0
            AND search_document_version >= 0
        ),
    CONSTRAINT saved_content_projections_visibility_status_check
        CHECK (
            visibility_status IN (
                'UNKNOWN',
                'PUBLIC',
                'PRIVATE',
                'UNAVAILABLE',
                'DELETED',
                'RESTRICTED'
            )
        ),
    CONSTRAINT saved_content_projections_private_type_check
        CHECK (visibility_status <> 'PRIVATE' OR entity_type = 'ACTIVITY'),
    CONSTRAINT saved_content_projections_visibility_validation_check
        CHECK (visibility_status = 'UNKNOWN' OR visibility_validated_at IS NOT NULL),
    CONSTRAINT saved_content_projections_locale_check
        CHECK (source_default_locale IS NULL OR source_default_locale IN ('EN', 'RU', 'KK')),
    CONSTRAINT saved_content_projections_title_bounds_check
        CHECK (
            (title_en IS NULL OR (btrim(title_en) <> '' AND octet_length(title_en) <= 1024))
            AND (title_ru IS NULL OR (btrim(title_ru) <> '' AND octet_length(title_ru) <= 1024))
            AND (title_kk IS NULL OR (btrim(title_kk) <> '' AND octet_length(title_kk) <= 1024))
        ),
    CONSTRAINT saved_content_projections_subtitle_bounds_check
        CHECK (
            (subtitle_en IS NULL OR (btrim(subtitle_en) <> '' AND octet_length(subtitle_en) <= 2048))
            AND (subtitle_ru IS NULL OR (btrim(subtitle_ru) <> '' AND octet_length(subtitle_ru) <= 2048))
            AND (subtitle_kk IS NULL OR (btrim(subtitle_kk) <> '' AND octet_length(subtitle_kk) <= 2048))
        ),
    CONSTRAINT saved_content_projections_location_bounds_check
        CHECK (
            (city_en IS NULL OR (btrim(city_en) <> '' AND octet_length(city_en) <= 256))
            AND (city_ru IS NULL OR (btrim(city_ru) <> '' AND octet_length(city_ru) <= 256))
            AND (city_kk IS NULL OR (btrim(city_kk) <> '' AND octet_length(city_kk) <= 256))
            AND (country_en IS NULL OR (btrim(country_en) <> '' AND octet_length(country_en) <= 256))
            AND (country_ru IS NULL OR (btrim(country_ru) <> '' AND octet_length(country_ru) <= 256))
            AND (country_kk IS NULL OR (btrim(country_kk) <> '' AND octet_length(country_kk) <= 256))
            AND (
                display_location_en IS NULL
                OR (btrim(display_location_en) <> '' AND octet_length(display_location_en) <= 1024)
            )
            AND (
                display_location_ru IS NULL
                OR (btrim(display_location_ru) <> '' AND octet_length(display_location_ru) <= 1024)
            )
            AND (
                display_location_kk IS NULL
                OR (btrim(display_location_kk) <> '' AND octet_length(display_location_kk) <= 1024)
            )
        ),
    CONSTRAINT saved_content_projections_search_bounds_check
        CHECK (
            (
                normalized_search_document_en IS NULL
                OR (
                    btrim(normalized_search_document_en) <> ''
                    AND octet_length(normalized_search_document_en) <= 32768
                )
            )
            AND (
                normalized_search_document_ru IS NULL
                OR (
                    btrim(normalized_search_document_ru) <> ''
                    AND octet_length(normalized_search_document_ru) <= 32768
                )
            )
            AND (
                normalized_search_document_kk IS NULL
                OR (
                    btrim(normalized_search_document_kk) <> ''
                    AND octet_length(normalized_search_document_kk) <= 32768
                )
            )
        ),
    CONSTRAINT saved_content_projections_reference_bounds_check
        CHECK (
            (
                (
                    media_reference IS NULL
                    AND media_reference_revision IS NULL
                    AND media_valid_until IS NULL
                )
                OR (
                    media_reference IS NOT NULL
                    AND media_reference_revision IS NOT NULL
                    AND btrim(media_reference) <> ''
                    AND octet_length(media_reference) <= 2048
                    AND media_reference_revision > 0
                    AND media_valid_until IS NOT NULL
                    AND isfinite(media_valid_until)
                    AND visibility_validated_at IS NOT NULL
                    AND media_valid_until > visibility_validated_at
                    AND media_valid_until <= visibility_validated_at + INTERVAL '15 minutes'
                )
            )
            AND (
                canonical_detail_route IS NULL
                OR (
                    btrim(canonical_detail_route) <> ''
                    AND octet_length(canonical_detail_route) <= 2048
                )
            )
        ),
    CONSTRAINT saved_content_projections_rating_check
        CHECK (
            (
                rating_value IS NULL
                AND rating_count IS NULL
                AND rating_scale_max IS NULL
            )
            OR (
                rating_value IS NOT NULL
                AND rating_count IS NOT NULL
                AND rating_count >= 0
                AND rating_scale_max IS NOT NULL
                AND rating_scale_max > 0
                AND rating_scale_max <= 100
                AND rating_value BETWEEN 0 AND rating_scale_max
            )
        ),
    CONSTRAINT saved_content_projections_summary_shape_check
        CHECK (
            (
                price_summary IS NULL
                OR (
                    jsonb_typeof(price_summary) = 'object'
                    AND octet_length(price_summary::TEXT) <= 16384
                )
            )
            AND (
                availability_summary IS NULL
                OR (
                    jsonb_typeof(availability_summary) = 'object'
                    AND octet_length(availability_summary::TEXT) <= 16384
                )
            )
        ),
    CONSTRAINT saved_content_projections_summary_time_check
        CHECK (
            (
                rating_value IS NULL
                AND price_summary IS NULL
                AND availability_summary IS NULL
                AND summary_as_of IS NULL
                AND summary_valid_until IS NULL
            )
            OR (
                (
                    rating_value IS NOT NULL
                    OR price_summary IS NOT NULL
                    OR availability_summary IS NOT NULL
                )
                AND summary_as_of IS NOT NULL
                AND (
                    (
                        price_summary IS NULL
                        AND availability_summary IS NULL
                        AND (
                            summary_valid_until IS NULL
                            OR summary_valid_until > summary_as_of
                        )
                    )
                    OR (
                        (price_summary IS NOT NULL OR availability_summary IS NOT NULL)
                        AND summary_valid_until IS NOT NULL
                        AND summary_valid_until > summary_as_of
                    )
                )
            )
        ),
    CONSTRAINT saved_content_projections_public_title_check
        CHECK (
            visibility_status <> 'PUBLIC'
            OR (
                source_default_locale IS NOT NULL
                AND (
                    (source_default_locale = 'EN' AND title_en IS NOT NULL)
                    OR (source_default_locale = 'RU' AND title_ru IS NOT NULL)
                    OR (source_default_locale = 'KK' AND title_kk IS NOT NULL)
                )
            )
        ),
    CONSTRAINT saved_content_projections_non_public_payload_check
        CHECK (
            visibility_status = 'PUBLIC'
            OR (
                source_default_locale IS NULL
                AND title_en IS NULL
                AND title_ru IS NULL
                AND title_kk IS NULL
                AND subtitle_en IS NULL
                AND subtitle_ru IS NULL
                AND subtitle_kk IS NULL
                AND city_en IS NULL
                AND city_ru IS NULL
                AND city_kk IS NULL
                AND country_en IS NULL
                AND country_ru IS NULL
                AND country_kk IS NULL
                AND display_location_en IS NULL
                AND display_location_ru IS NULL
                AND display_location_kk IS NULL
                AND normalized_search_document_en IS NULL
                AND normalized_search_document_ru IS NULL
                AND normalized_search_document_kk IS NULL
                AND media_reference IS NULL
                AND media_reference_revision IS NULL
                AND media_valid_until IS NULL
                AND rating_value IS NULL
                AND rating_count IS NULL
                AND rating_scale_max IS NULL
                AND price_summary IS NULL
                AND availability_summary IS NULL
                AND summary_as_of IS NULL
                AND summary_valid_until IS NULL
                AND canonical_detail_route IS NULL
            )
        ),
    CONSTRAINT saved_content_projections_ephemeral_lifecycle_check
        CHECK (
            (ever_referenced AND shell_expires_at IS NULL)
            OR (NOT ever_referenced AND shell_expires_at IS NOT NULL)
        ),
    CONSTRAINT saved_content_projections_gc_candidate_check
        CHECK (gc_candidate_at IS NULL OR ever_referenced),
    CONSTRAINT saved_content_projections_timestamps_check
        CHECK (
            isfinite(created_at)
            AND isfinite(updated_at)
            AND updated_at >= created_at
            AND (
                visibility_validated_at IS NULL
                OR isfinite(visibility_validated_at)
            )
            AND (summary_as_of IS NULL OR isfinite(summary_as_of))
            AND (summary_valid_until IS NULL OR isfinite(summary_valid_until))
            AND (media_valid_until IS NULL OR isfinite(media_valid_until))
            AND (
                shell_expires_at IS NULL
                OR (
                    isfinite(shell_expires_at)
                    AND shell_expires_at > created_at
                    AND shell_expires_at <= created_at + INTERVAL '1 hour'
                )
            )
            AND (
                gc_candidate_at IS NULL
                OR (isfinite(gc_candidate_at) AND gc_candidate_at >= created_at)
            )
        )
);

-- The application chooses shell_expires_at after the linked operation deadline;
-- the row-local hard cap above prevents an ephemeral shell from becoming durable.

CREATE INDEX idx_saved_content_projections_ephemeral_expiry
    ON saved_content_projections (shell_expires_at, entity_type, entity_id)
    WHERE ever_referenced = FALSE AND shell_expires_at IS NOT NULL;

CREATE INDEX idx_saved_content_projections_visibility_validation
    ON saved_content_projections (visibility_validated_at, entity_type, entity_id)
    WHERE visibility_status <> 'UNKNOWN';

CREATE INDEX idx_saved_content_projections_gc_candidate
    ON saved_content_projections (gc_candidate_at, entity_type, entity_id)
    WHERE ever_referenced = TRUE AND gc_candidate_at IS NOT NULL;

CREATE TABLE saved_items (
    id UUID PRIMARY KEY,
    owner_user_id UUID NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    relationship_state TEXT NOT NULL DEFAULT 'ACTIVE',
    state_generation UUID NOT NULL,
    relationship_attribution_id UUID NOT NULL,
    relationship_version BIGINT NOT NULL DEFAULT 1,
    dependent_membership_version BIGINT NOT NULL DEFAULT 0,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at TIMESTAMPTZ,
    purge_eligible_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT saved_items_owner_target_key
        UNIQUE (owner_user_id, entity_type, entity_id),
    CONSTRAINT saved_items_owner_id_key
        UNIQUE (owner_user_id, id),
    -- Projection GC must retain the parent until ACTIVE relationships and REMOVED
    -- tombstones have both been purged; relationship integrity wins over early GC.
    CONSTRAINT saved_items_projection_fkey
        FOREIGN KEY (entity_type, entity_id)
        REFERENCES saved_content_projections (entity_type, entity_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT saved_items_entity_type_check
        CHECK (entity_type IN ('ATTRACTION', 'ACTIVITY', 'EXCURSION', 'GUIDE')),
    CONSTRAINT saved_items_entity_id_check
        CHECK (
            entity_id <> ''
            AND octet_length(entity_id) <= 512
            AND entity_id !~ '^[[:space:]]'
            AND entity_id !~ '[[:space:]]$'
        ),
    CONSTRAINT saved_items_relationship_state_check
        CHECK (relationship_state IN ('ACTIVE', 'REMOVED')),
    CONSTRAINT saved_items_versions_check
        CHECK (relationship_version > 0 AND dependent_membership_version >= 0),
    CONSTRAINT saved_items_lifecycle_check
        CHECK (
            (
                relationship_state = 'ACTIVE'
                AND removed_at IS NULL
                AND purge_eligible_at IS NULL
            )
            OR (
                relationship_state = 'REMOVED'
                AND removed_at IS NOT NULL
                AND removed_at >= saved_at
                AND purge_eligible_at IS NOT NULL
                AND isfinite(removed_at)
                AND isfinite(purge_eligible_at)
                AND purge_eligible_at = removed_at + INTERVAL '14 days'
            )
        ),
    CONSTRAINT saved_items_timestamps_check
        CHECK (
            isfinite(created_at)
            AND isfinite(saved_at)
            AND isfinite(updated_at)
            AND saved_at >= created_at
            AND updated_at >= saved_at
        )
);

CREATE INDEX idx_saved_items_owner_state_saved
    ON saved_items (owner_user_id, relationship_state, saved_at DESC, id DESC);

CREATE INDEX idx_saved_items_owner_type_state_saved
    ON saved_items (
        owner_user_id,
        entity_type,
        relationship_state,
        saved_at DESC,
        id DESC
    );

CREATE INDEX idx_saved_items_active_target
    ON saved_items (entity_type, entity_id, owner_user_id)
    WHERE relationship_state = 'ACTIVE';

CREATE INDEX idx_saved_items_removed_purge
    ON saved_items (purge_eligible_at, owner_user_id, id)
    WHERE relationship_state = 'REMOVED';

CREATE TABLE saved_user_usage (
    owner_user_id UUID PRIMARY KEY,
    active_saved_items_count BIGINT NOT NULL DEFAULT 0,
    usage_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT saved_user_usage_values_check
        CHECK (active_saved_items_count >= 0 AND usage_version >= 0),
    CONSTRAINT saved_user_usage_timestamps_check
        CHECK (updated_at >= created_at)
);

CREATE TABLE saved_operations (
    subject TEXT NOT NULL,
    session_generation UUID NOT NULL,
    operation_id UUID NOT NULL,
    operation_kind TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    semantic_request_hmac BYTEA NOT NULL,
    request_hmac_key_version INTEGER NOT NULL,
    first_seen_source_surface TEXT NOT NULL,
    accepted_platform_access_policy_revision BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    commit_deadline TIMESTAMPTZ NOT NULL,
    outcome_code TEXT,
    outcome_retryable BOOLEAN,
    refresh_scope TEXT NOT NULL DEFAULT 'NONE',
    observed_relationship_version BIGINT,
    applied_relationship_generation UUID,
    applied_relationship_version BIGINT,
    applied_user_usage_version BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    retention_expires_at TIMESTAMPTZ,

    CONSTRAINT saved_operations_pkey
        PRIMARY KEY (subject, session_generation, operation_id),
    CONSTRAINT saved_operations_idempotency_key
        UNIQUE (subject, session_generation, idempotency_key),
    CONSTRAINT saved_operations_subject_check
        CHECK (btrim(subject) <> '' AND octet_length(subject) <= 255),
    CONSTRAINT saved_operations_kind_check
        CHECK (operation_kind IN ('SAVE_TARGET', 'UNSAVE_TARGET')),
    CONSTRAINT saved_operations_idempotency_key_check
        CHECK (
            octet_length(idempotency_key) BETWEEN 22 AND 128
            AND idempotency_key ~ '^[A-Za-z0-9_-]{22,128}$'
        ),
    CONSTRAINT saved_operations_hmac_check
        CHECK (octet_length(semantic_request_hmac) = 32 AND request_hmac_key_version > 0),
    CONSTRAINT saved_operations_source_surface_check
        CHECK (
            first_seen_source_surface IN (
                'UNKNOWN',
                'CARD',
                'DETAIL',
                'SAVED_ALL',
                'SAVED_COLLECTION'
            )
        ),
    CONSTRAINT saved_operations_policy_revision_check
        CHECK (accepted_platform_access_policy_revision > 0),
    CONSTRAINT saved_operations_status_check
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT saved_operations_refresh_scope_check
        CHECK (refresh_scope IN ('SAVED_ITEMS', 'COLLECTIONS', 'BOTH', 'NONE')),
    CONSTRAINT saved_operations_outcome_code_check
        CHECK (
            (status = 'PENDING' AND outcome_code IS NULL)
            OR (
                status = 'SUCCEEDED'
                AND outcome_code IN ('APPLIED', 'NO_OP')
            )
            OR (
                status = 'REJECTED'
                AND outcome_code IN (
                    'SAVED_TARGET_TYPE_UNSUPPORTED',
                    'SAVED_TARGET_UNAVAILABLE',
                    'SAVED_DEPENDENCY_UNAVAILABLE',
                    'SAVED_MUTATION_STALE',
                    'SAVED_MUTATION_REPLAY_MISMATCH',
                    'SAVED_ITEM_LIMIT_REACHED',
                    'SAVED_RATE_LIMITED',
                    'SAVED_TEMPORARILY_UNAVAILABLE',
                    'PLATFORM_PERSONAL_DATA_LOCKED'
                )
            )
            OR (status = 'EXPIRED' AND outcome_code = 'EXPIRED')
        ),
    CONSTRAINT saved_operations_versions_check
        CHECK (
            (observed_relationship_version IS NULL OR observed_relationship_version >= 0)
            AND (applied_relationship_version IS NULL OR applied_relationship_version > 0)
            AND (applied_user_usage_version IS NULL OR applied_user_usage_version >= 0)
            AND (
                (applied_relationship_generation IS NULL AND applied_relationship_version IS NULL)
                OR (
                    applied_relationship_generation IS NOT NULL
                    AND applied_relationship_version IS NOT NULL
                )
            )
        ),
    CONSTRAINT saved_operations_deadline_check
        CHECK (
            isfinite(created_at)
            AND isfinite(commit_deadline)
            AND commit_deadline > created_at
            AND commit_deadline <= created_at + INTERVAL '15 seconds'
        ),
    CONSTRAINT saved_operations_applied_versions_status_check
        CHECK (
            status = 'SUCCEEDED'
            OR (
                applied_relationship_version IS NULL
                AND applied_relationship_generation IS NULL
                AND applied_user_usage_version IS NULL
            )
        ),
    CONSTRAINT saved_operations_status_lifecycle_check
        CHECK (
            (
                status = 'PENDING'
                AND outcome_code IS NULL
                AND outcome_retryable IS NULL
                AND refresh_scope = 'NONE'
                AND observed_relationship_version IS NULL
                AND applied_relationship_version IS NULL
                AND applied_user_usage_version IS NULL
                AND completed_at IS NULL
                AND retention_expires_at IS NULL
            )
            OR (
                status IN ('SUCCEEDED', 'REJECTED', 'EXPIRED')
                AND outcome_code IS NOT NULL
                AND outcome_retryable IS NOT NULL
                AND (status <> 'SUCCEEDED' OR outcome_retryable = FALSE)
                AND (status <> 'EXPIRED' OR outcome_retryable = FALSE)
                AND completed_at IS NOT NULL
                AND isfinite(completed_at)
                AND completed_at >= created_at
                AND retention_expires_at IS NOT NULL
                AND isfinite(retention_expires_at)
                AND retention_expires_at = completed_at + INTERVAL '14 days'
            )
        ),
    CONSTRAINT saved_operations_terminal_deadline_check
        CHECK (
            status = 'PENDING'
            OR (status IN ('SUCCEEDED', 'REJECTED') AND completed_at <= commit_deadline)
            OR (status = 'EXPIRED' AND completed_at >= commit_deadline)
        )
);

CREATE INDEX idx_saved_operations_pending_deadline
    ON saved_operations (
        commit_deadline,
        subject,
        session_generation,
        operation_id
    )
    WHERE status = 'PENDING';

CREATE INDEX idx_saved_operations_subject_pending
    ON saved_operations (subject, created_at, operation_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_saved_operations_retention_expiry
    ON saved_operations (
        retention_expires_at,
        subject,
        session_generation,
        operation_id
    )
    WHERE status IN ('SUCCEEDED', 'REJECTED', 'EXPIRED');

CREATE TABLE saved_outbox (
    id UUID PRIMARY KEY,
    owner_user_id UUID NOT NULL,
    saved_item_id UUID NOT NULL,
    event_schema_version INTEGER NOT NULL DEFAULT 1,
    event_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    relationship_state TEXT NOT NULL,
    state_generation UUID NOT NULL,
    relationship_attribution_id UUID NOT NULL,
    relationship_version BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    dead_at TIMESTAMPTZ,
    last_error_code TEXT,
    retention_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Retention and subject-purge workers must delete outbox rows before their
    -- saved_items parent. RESTRICT makes that ordering explicit and tenant-safe.
    CONSTRAINT saved_outbox_saved_item_fkey
        FOREIGN KEY (owner_user_id, saved_item_id)
        REFERENCES saved_items (owner_user_id, id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT saved_outbox_event_key
        UNIQUE (
            owner_user_id,
            saved_item_id,
            state_generation,
            relationship_version,
            event_type
        ),
    CONSTRAINT saved_outbox_event_schema_version_check
        CHECK (event_schema_version > 0),
    CONSTRAINT saved_outbox_event_type_check
        CHECK (event_type IN ('SAVED_ITEM_ACTIVATED', 'SAVED_ITEM_REMOVED')),
    CONSTRAINT saved_outbox_entity_type_check
        CHECK (entity_type IN ('ATTRACTION', 'ACTIVITY', 'EXCURSION', 'GUIDE')),
    CONSTRAINT saved_outbox_entity_id_check
        CHECK (
            entity_id <> ''
            AND octet_length(entity_id) <= 512
            AND entity_id !~ '^[[:space:]]'
            AND entity_id !~ '[[:space:]]$'
        ),
    CONSTRAINT saved_outbox_relationship_state_check
        CHECK (relationship_state IN ('ACTIVE', 'REMOVED')),
    CONSTRAINT saved_outbox_event_state_check
        CHECK (
            (event_type = 'SAVED_ITEM_ACTIVATED' AND relationship_state = 'ACTIVE')
            OR (event_type = 'SAVED_ITEM_REMOVED' AND relationship_state = 'REMOVED')
        ),
    CONSTRAINT saved_outbox_relationship_version_check
        CHECK (relationship_version > 0),
    CONSTRAINT saved_outbox_status_check
        CHECK (status IN ('PENDING', 'DELIVERED', 'DEAD')),
    CONSTRAINT saved_outbox_attempt_count_check
        CHECK (attempt_count >= 0),
    CONSTRAINT saved_outbox_last_error_code_check
        CHECK (
            last_error_code IS NULL
            OR (
                octet_length(last_error_code) BETWEEN 1 AND 128
                AND last_error_code ~ '^[A-Z][A-Z0-9_]*$'
            )
        ),
    CONSTRAINT saved_outbox_status_lifecycle_check
        CHECK (
            (
                status = 'PENDING'
                AND delivered_at IS NULL
                AND dead_at IS NULL
                AND retention_expires_at IS NULL
            )
            OR (
                status = 'DELIVERED'
                AND delivered_at IS NOT NULL
                AND dead_at IS NULL
                AND locked_at IS NULL
                AND retention_expires_at IS NOT NULL
                AND retention_expires_at > delivered_at
            )
            OR (
                status = 'DEAD'
                AND delivered_at IS NULL
                AND dead_at IS NOT NULL
                AND locked_at IS NULL
                AND retention_expires_at IS NOT NULL
                AND retention_expires_at > dead_at
            )
        ),
    CONSTRAINT saved_outbox_timestamps_check
        CHECK (
            updated_at >= created_at
            AND next_attempt_at >= created_at
            AND (locked_at IS NULL OR locked_at >= created_at)
            AND (delivered_at IS NULL OR delivered_at >= created_at)
            AND (dead_at IS NULL OR dead_at >= created_at)
        )
);

CREATE INDEX idx_saved_outbox_due
    ON saved_outbox (next_attempt_at, created_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_saved_outbox_terminal_retention
    ON saved_outbox (retention_expires_at, owner_user_id, id)
    WHERE status IN ('DELIVERED', 'DEAD');

-- The inbox row and its projection decision are committed in one transaction.
-- Only bounded envelope identity and the terminal decision are retained; event
-- and card payloads are never persisted here.
CREATE TABLE saved_inbox_dedup (
    source_service TEXT NOT NULL,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    processing_state TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    retention_expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '14 days'),

    CONSTRAINT saved_inbox_dedup_pkey
        PRIMARY KEY (source_service, event_id),
    CONSTRAINT saved_inbox_dedup_source_service_check
        CHECK (
            octet_length(source_service) BETWEEN 1 AND 64
            AND source_service ~ '^[a-z][a-z0-9-]*$'
        ),
    CONSTRAINT saved_inbox_dedup_event_id_check
        CHECK (
            octet_length(event_id) BETWEEN 1 AND 128
            AND event_id !~ '^[[:space:]]'
            AND event_id !~ '[[:space:]]$'
        ),
    CONSTRAINT saved_inbox_dedup_event_type_check
        CHECK (
            event_type IN (
                'content.published',
                'content.updated',
                'content.unavailable',
                'content.visibility_changed',
                'content.deleted'
            )
        ),
    CONSTRAINT saved_inbox_dedup_processing_state_check
        CHECK (
            processing_state IN (
                'APPLIED',
                'IGNORED_UNKNOWN_TARGET',
                'IGNORED_STALE_REVISION'
            )
        ),
    CONSTRAINT saved_inbox_dedup_retention_check
        CHECK (
            isfinite(processed_at)
            AND isfinite(retention_expires_at)
            AND retention_expires_at = processed_at + INTERVAL '14 days'
        )
);

CREATE INDEX idx_saved_inbox_dedup_retention
    ON saved_inbox_dedup (retention_expires_at, source_service, event_id);

-- This ledger intentionally has no FK to subject-owned data, so it survives the
-- deletion it coordinates. A worker advances monotonically in bounded batches:
-- OUTBOX -> SAVED_ITEMS -> OPERATIONS -> USER_USAGE -> COMPLETED. It stores no
-- account-deletion request or Saved content payload.
CREATE TABLE saved_subject_purge_operations (
    operation_id UUID PRIMARY KEY,
    subject TEXT NOT NULL,
    owner_user_id UUID NOT NULL,
    phase TEXT NOT NULL DEFAULT 'OUTBOX',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ DEFAULT now(),
    last_error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    retention_expires_at TIMESTAMPTZ,

    CONSTRAINT saved_subject_purge_operations_subject_key
        UNIQUE (subject),
    CONSTRAINT saved_subject_purge_operations_owner_key
        UNIQUE (owner_user_id),
    CONSTRAINT saved_subject_purge_operations_subject_check
        CHECK (
            octet_length(subject) BETWEEN 1 AND 255
            AND subject !~ '^[[:space:]]'
            AND subject !~ '[[:space:]]$'
        ),
    CONSTRAINT saved_subject_purge_operations_phase_check
        CHECK (
            phase IN (
                'OUTBOX',
                'SAVED_ITEMS',
                'OPERATIONS',
                'USER_USAGE',
                'COMPLETED'
            )
        ),
    CONSTRAINT saved_subject_purge_operations_attempt_count_check
        CHECK (attempt_count >= 0),
    CONSTRAINT saved_subject_purge_operations_last_error_code_check
        CHECK (
            last_error_code IS NULL
            OR (
                octet_length(last_error_code) BETWEEN 1 AND 128
                AND last_error_code ~ '^[A-Z][A-Z0-9_]*$'
            )
        ),
    CONSTRAINT saved_subject_purge_operations_lifecycle_check
        CHECK (
            (
                phase <> 'COMPLETED'
                AND next_attempt_at IS NOT NULL
                AND completed_at IS NULL
                AND retention_expires_at IS NULL
            )
            OR (
                phase = 'COMPLETED'
                AND next_attempt_at IS NULL
                AND last_error_code IS NULL
                AND completed_at IS NOT NULL
                AND isfinite(completed_at)
                AND completed_at >= created_at
                AND retention_expires_at IS NOT NULL
                AND isfinite(retention_expires_at)
                AND retention_expires_at = completed_at + INTERVAL '14 days'
            )
        ),
    CONSTRAINT saved_subject_purge_operations_timestamps_check
        CHECK (
            isfinite(created_at)
            AND isfinite(updated_at)
            AND updated_at >= created_at
            AND (
                next_attempt_at IS NULL
                OR (isfinite(next_attempt_at) AND next_attempt_at >= created_at)
            )
        )
);

CREATE INDEX idx_saved_subject_purge_operations_work
    ON saved_subject_purge_operations (next_attempt_at, created_at, operation_id)
    WHERE phase <> 'COMPLETED';

CREATE INDEX idx_saved_subject_purge_operations_retention
    ON saved_subject_purge_operations (retention_expires_at, operation_id)
    WHERE phase = 'COMPLETED';
