package app

import "errors"

var (
	ErrInvalidActorUserID                     = errors.New("invalid actor user id")
	ErrInvalidExcursionID                     = errors.New("invalid excursion id")
	ErrExcursionNotFound                      = errors.New("excursion not found")
	ErrExcursionAccessDenied                  = errors.New("excursion access denied")
	ErrGuideNotAllowed                        = errors.New("guide is not allowed to manage excursions")
	ErrExcursionAttractionRequired            = errors.New("excursion must be based on an attraction")
	ErrCombinedExcursionRouteRequiresTwoStops = errors.New("combined excursion route requires at least two attraction stops")
	ErrCombinedExcursionRouteTooManyStops     = errors.New("combined excursion route supports at most five attraction stops")
	ErrCombinedExcursionRouteDuplicateStop    = errors.New("combined excursion route contains duplicate attraction stops")
	ErrInvalidExcursionIncludedItem           = errors.New("invalid excursion included item")
	ErrExcursionOfferNotFound                 = errors.New("excursion offer not found")
	ErrExcursionOfferNotBookable              = errors.New("excursion offer is not available for booking")
	ErrExcursionNotPublished                  = errors.New("excursion offer is not published")
	ErrExcursionTranslationFailed             = errors.New("failed to translate excursion content")
	ErrExcursionBookingNotFound               = errors.New("excursion booking not found")
	ErrExcursionBookingNotEditable            = errors.New("excursion booking cannot be edited")
	ErrExcursionBookingNotReviewable          = errors.New("excursion booking is not ready for review")
	ErrExcursionBookingIdempotencyConflict    = errors.New("excursion booking idempotency conflict")
	ErrExcursionScheduleConflict              = errors.New("excursion schedule conflict")
	ErrExcursionScheduleStartTooSoon          = errors.New("excursion schedule slot must start at least 3 hours from now")
	ErrExcursionScheduleUnavailable           = errors.New("excursion schedule slot is unavailable")
	ErrExcursionAttendanceAccessDenied        = errors.New("excursion attendance access denied")
	ErrExcursionAttendanceQRUnavailable       = errors.New("excursion attendance qr is unavailable for this slot")
	ErrExcursionAttendanceQRInvalid           = errors.New("excursion attendance qr is invalid")
	ErrExcursionAttendanceQRVersionInvalid    = errors.New("excursion attendance qr version is not supported")
	ErrExcursionAttendanceQRExpired           = errors.New("excursion attendance qr is no longer usable")
	ErrExcursionAttendanceAlreadyCheckedIn    = errors.New("excursion booking already checked in")
	ErrExcursionAttendanceBookingInvalid      = errors.New("excursion booking is not eligible for attendance check-in")

	ErrExcursionCoverFileNotFound   = errors.New("excursion cover file not found")
	ErrExcursionCoverFileNotReady   = errors.New("excursion cover file is not ready")
	ErrExcursionCoverFileNotAllowed = errors.New("excursion cover file is not allowed")
	ErrFraudRejected                = errors.New("excursion action rejected by fraud policy")
	ErrTrustPolicyRejected          = errors.New("excursion action rejected by trust policy")
)
